export const localeConfig: Record<string, { label: string; flag: string; name: string }> = {
  en: { label: "EN", flag: "🇺🇸", name: "English" },
  he: { label: "עב", flag: "🇮🇱", name: "עברית" },
  ru: { label: "RU", flag: "🇷🇺", name: "Русский" },
  es: { label: "ES", flag: "🇪🇸", name: "Español" },
  pt: { label: "PT", flag: "🇧🇷", name: "Português" },
  fr: { label: "FR", flag: "🇫🇷", name: "Français" },
  zh: { label: "中文", flag: "🇨🇳", name: "中文" },
  de: { label: "DE", flag: "🇩🇪", name: "Deutsch" },
  fa: { label: "فا", flag: "🇮🇷", name: "فارسی" },
  ar: { label: "عر", flag: "🇸🇦", name: "العربية" },
  hi: { label: "हि", flag: "🇮🇳", name: "हिन्दी" },
  id: { label: "ID", flag: "🇮🇩", name: "Bahasa" },
  tr: { label: "TR", flag: "🇹🇷", name: "Türkçe" },
  vi: { label: "VI", flag: "🇻🇳", name: "Tiếng Việt" },
  th: { label: "ไท", flag: "🇹🇭", name: "ไทย" },
  ms: { label: "MS", flag: "🇲🇾", name: "Bahasa Melayu" },
  ko: { label: "한", flag: "🇰🇷", name: "Korean" },
  ja: { label: "日", flag: "🇯🇵", name: "日本語" },
  tl: { label: "TL", flag: "🇵🇭", name: "Filipino" },
  ur: { label: "اُر", flag: "🇵🇰", name: "اردو" },
  sw: { label: "SW", flag: "🇰🇪", name: "Kiswahili" },
  az: { label: "AZ", flag: "🇦🇿", name: "Azərbaycan" },
  pl: { label: "PL", flag: "🇵🇱", name: "Polski" },
  uk: { label: "УК", flag: "🇺🇦", name: "Українська" },
};
