import {
  BatteryIcon,
  BoltIcon,
  GiftIcon,
  LockIcon,
  NoSymbolIcon,
  PlayStoreIcon,
  ServerIcon,
  ShieldIcon,
} from "@/components/icons/platform";
import type { PlatformLandingConfig } from "@/components/landing/platform-landing-config";

export const androidPlatform: PlatformLandingConfig = {
  slug: "vpn-for-android",
  namespace: "vpnForAndroid",
  operatingSystem: "Android",
  trackPlatform: "android",
  downloadUrl: "https://play.google.com/store/apps/details?id=org.dopplervpn.android",
  downloadVariant: "android-play",
  ogImageAlt: "Doppler VPN for Android",
  ratingChip: { storeKey: "googlePlay" },
  heroCtaIcon: PlayStoreIcon,
  heroCtaKey: "hero.cta",
  heroGapClass: "gap-12 lg:gap-20",
  heroVisual: {
    kind: "image",
    src: "/images/android-hero.avif",
    alt: "Doppler VPN running on Android — secure VPN connection screen",
    width: 1354,
    height: 909,
    roundedClass: "rounded-[2rem]",
  },
  features: [
    { key: "vlessEncryption", featured: true, icon: LockIcon },
    { key: "noRegistration", icon: NoSymbolIcon },
    { key: "oneTapConnect", icon: BoltIcon },
    { key: "bypassCensorship", featured: true, icon: ShieldIcon },
    { key: "noLogs", icon: ShieldIcon },
    { key: "globalServers", icon: ServerIcon },
    { key: "freeTrial", featured: true, icon: GiftIcon },
    { key: "batteryEfficient", featured: true, icon: BatteryIcon },
  ],
  stepKeys: ["step1", "step2", "step3", "step4"],
  faqKeys: ["q1", "q2", "q3", "q4", "q5", "q6"],
  related: [
    { href: "/no-registration-vpn", title: "noRegistration", desc: "noRegistrationDesc" },
    { href: "/vless-vpn", title: "vless", desc: "vlessDesc" },
    { href: "/vpn-for-ios", title: "ios", desc: "iosDesc" },
    { href: "/vpn-for-macos", title: "macos", desc: "macosDesc" },
    { href: "/vpn-for-windows", title: "windows", desc: "windowsDesc" },
    { href: "/vless-vpn-android", title: "vlessAndroid", desc: "vlessAndroidDesc" },
  ],
  ctaDownloadKey: "cta.downloadAndroid",
};
