import type { ChartCopy } from "./en";

/** Arabic chart copy. Keys and their order match ./en.ts. */
export const ar: ChartCopy = {
  "figure.sourceLabel": "المصدر",

  "journey.title": "اتصال واحد، من طرف إلى طرف",
  "journey.link1": "مشفّر",
  "journey.link2": "يُفَك غلافه",
  "journey.link3": "عنوان العقدة",
  "journey.lane1.title": "1 · جهازك",
  "journey.lane1.node1.label": "تطبيق Doppler",
  "journey.lane1.node1.detail": "معرّف حساب عشوائي، بلا بريد إلكتروني",
  "journey.lane1.node2.label": "DNS وأسماء المواقع",
  "journey.lane1.node2.detail": "تُرسل داخل النفق، لا إلى مزود الإنترنت",
  "journey.lane1.watcher.who": "صاحب شبكة Wi-Fi، مزود الإنترنت",
  "journey.lane1.watcher.sees": "جلسة TLS 1.3 واحدة إلى ما يبدو موقعاً شائعاً",
  "journey.lane2.title": "2 · نفق VLESS-Reality",
  "journey.lane2.node1.label": "مصافحة TLS 1.3",
  "journey.lane2.node1.detail": "مستعارة من موقع حقيقي",
  "journey.lane2.node2.label": "عمليات السبر",
  "journey.lane2.node2.detail": "تُحوَّل إلى ذلك الموقع الحقيقي",
  "journey.lane2.watcher.who": "أنظمة DPI لدى الرقابة",
  "journey.lane2.watcher.sees": "HTTPS عادي؛ والسبر يجد موقعاً أصلياً",
  "journey.lane3.title": "3 · عقدة Doppler الحافة",
  "journey.lane3.node1.label": "تبديل العنوان",
  "journey.lane3.node1.detail": "عنوانك يصبح عنوان العقدة",
  "journey.lane3.node2.label": "محلّل DNS",
  "journey.lane3.node2.detail": "الاستعلامات لا تُسجَّل أبداً",
  "journey.lane3.node3.label": "سجلات حركة البيانات",
  "journey.lane3.node3.detail": "لا يُحفظ منها شيء",
  "journey.lane4.title": "4 · الإنترنت المفتوح",
  "journey.lane4.node1.label": "الموقع الذي طلبته",
  "journey.lane4.node1.detail": "اختبر ما يراه عبر /tools",
  "journey.lane4.watcher.who": "الموقع",
  "journey.lane4.watcher.sees": "عنوان العقدة، وبصمة متصفحك أنت",

  "schema-device.title": "ما الذي يغادر جهازك حين يتصل Doppler",
  "schema-device.link1": "1 · تسجيل الدخول",
  "schema-device.link2": "2 · الاتصال",
  "schema-device.lane1.title": "جهازك",
  "schema-device.lane1.node1.label": "تطبيق Doppler",
  "schema-device.lane1.node1.detail": "ينشئ معرّف VPN-XXXX-XXXX-XXXX عشوائياً عند أول تشغيل",
  "schema-device.lane1.node2.label": "بلا نموذج تسجيل",
  "schema-device.lane1.node2.detail": "بلا بريد إلكتروني أو هاتف أو كلمة مرور",
  "schema-device.lane1.watcher.who": "صاحب شبكة Wi-Fi، مزود الإنترنت",
  "schema-device.lane1.watcher.sees": "طلب HTTPS إلى واجهتنا البرمجية، ثم جلسة TLS واحدة",
  "schema-device.lane2.title": "واجهة Doppler البرمجية",
  "schema-device.lane2.node1.label": "سجل المصادقة",
  "schema-device.lane2.node1.detail": "عنوان IP، معرّف الحساب، معرّف الجهاز، الوقت. يُحفظ حتى 90 يوماً",
  "schema-device.lane2.node2.label": "إعدادات الخوادم",
  "schema-device.lane2.node2.detail": "تُسلَّم عبر واجهة برمجية موثَّقة",
  "schema-device.lane3.title": "النفق",
  "schema-device.lane3.node1.label": "يُفتح VLESS-Reality",
  "schema-device.lane3.node1.detail": "DNS وأسماء المواقع تسافر الآن داخله",
  "schema-device.lane3.watcher.who": "صاحب شبكة Wi-Fi، مزود الإنترنت",
  "schema-device.lane3.watcher.sees": "لا نطاقات، ولا أسماء مواقع، ولا صفحات",

  "fingerprint-uniqueness.title": "نسبة المتصفحات ذات البصمة الفريدة",
  "fingerprint-uniqueness.note": "أخذ Panopticlick عينة من نحو 470,000 متصفح عام 2010. وأخذ AmIUnique عينة من 118,934 متصفحاً عام 2016.",
  "fingerprint-uniqueness.bar1": "Panopticlick، كل المتصفحات (2010)",
  "fingerprint-uniqueness.bar2": "Panopticlick، مع Flash أو Java (2010)",
  "fingerprint-uniqueness.bar3": "AmIUnique (2016)",

  "dbir-2026.title": "ما الذي يظهر في اختراقات البيانات (نسبة الاختراقات المؤكدة)",
  "dbir-2026.note": "أكثر من 22,000 اختراق مؤكد في 145 دولة. والفئات متداخلة، لذا لا يبلغ مجموعها 100%.",
  "dbir-2026.bar1": "تدخّل عنصر بشري",
  "dbir-2026.bar2": "برمجيات الفدية",
  "dbir-2026.bar3": "تدخّل طرف ثالث",
  "dbir-2026.bar4": "الدخول عبر ثغرة برمجية",
  "dbir-2026.bar5": "بيانات اعتماد ضمن البيانات المأخوذة",

  "schema-reality.title": "إلى أين يذهب اتصال Reality، وماذا يرى كل طرف",
  "schema-reality.link1": "TLS 1.3",
  "schema-reality.link2": "فحص الرمز",
  "schema-reality.lane1.title": "العميل",
  "schema-reality.lane1.node1.label": "تطبيق Doppler",
  "schema-reality.lane1.node1.detail": "المصافحة تذكر موقعاً حقيقياً وتحمل رمز x25519 مخفياً",
  "schema-reality.lane1.node2.label": "أي أحد آخر",
  "schema-reality.lane1.node2.detail": "سبر الرقابة، أو ماسح، أو متصفح",
  "schema-reality.lane2.title": "الشبكة",
  "schema-reality.lane2.node1.label": "صندوق DPI",
  "schema-reality.lane2.node1.detail": "GFW أو TSPU أو مرشّح لدى مزود الإنترنت",
  "schema-reality.lane2.watcher.who": "الرقابة",
  "schema-reality.lane2.watcher.sees": "زيارة TLS 1.3 عادية لموقع شائع",
  "schema-reality.lane3.title": "خادم Reality",
  "schema-reality.lane3.node1.label": "رمز صالح",
  "schema-reality.lane3.node1.detail": "يُفتح النفق وتتدفق حركة VLESS إلى عقدة الحافة",
  "schema-reality.lane3.node2.label": "بلا رمز",
  "schema-reality.lane3.node2.detail": "يُمرَّر إلى الموقع الحقيقي وشهادته الأصلية",

  "detection-rates.title": "كم مرة أمسك الباحثون بحركة البيانات المموّهة",
  "detection-rates.note": "ثلاث دراسات على شبكات حقيقية. كل رقم هو الحد الأدنى الذي أوردته الدراسة، فالمعدلات الحقيقية عنده أو أعلى منه.",
  "detection-rates.bar1": "تدفقات OpenVPN التي جرى تمييزها",
  "detection-rates.bar2": "إعدادات VPN \"المموّهة\" التي أُمسك بها (34 من 41)",
  "detection-rates.bar3": "وكلاء مموّهون أُمسك بهم عبر أنماط TLS داخل TLS",

  "protocol-timeline.title": "عشرون عاماً من القط والفأر",
  "protocol-timeline.e1.year": "2002",
  "protocol-timeline.e1.title": "انطلاق Tor",
  "protocol-timeline.e1.body": "التوجيه البصلي يُفتح للعامة. حركة بياناته سهلة التمييز، وهو ما يفرض لاحقاً ابتكار \"وسائط نقل قابلة للتركيب\" مموّهة.",
  "protocol-timeline.e2.year": "2012",
  "protocol-timeline.e2.title": "Shadowsocks",
  "protocol-timeline.e2.body": "وكيل خفيف تبدو حركة بياناته بايتات عشوائية. ينتشر بسرعة في الصين.",
  "protocol-timeline.e3.year": "2015",
  "protocol-timeline.e3.title": "V2Ray وVMess، وعملية إزالة",
  "protocol-timeline.e3.body": "يبدأ Project V في سبتمبر. وفي أغسطس كان مؤلف Shadowsocks قد حذف الشيفرة بعد زيارة من الشرطة.",
  "protocol-timeline.e4.year": "2019",
  "protocol-timeline.e4.title": "توثيق السبر النشط",
  "protocol-timeline.e4.body": "يسجّل الباحثون أكثر من 51,000 عملية سبر من عناوين IP صينية تختبر خوادم يُشتبه أنها Shadowsocks.",
  "protocol-timeline.e5.year": "يوليو 2020",
  "protocol-timeline.e5.title": "اقتراح VLESS",
  "protocol-timeline.e5.body": "بروتوكول مجرّد بلا تشفير خاص به، وُضع ليركب داخل TLS.",
  "protocol-timeline.e6.year": "نوفمبر 2020",
  "protocol-timeline.e6.title": "Xray-core",
  "protocol-timeline.e6.body": "مشروع XTLS ينفصل عن V2Ray ويصبح الموطن الرئيسي لـ VLESS.",
  "protocol-timeline.e7.year": "نوفمبر 2021",
  "protocol-timeline.e7.title": "الصين تحجب حركة البيانات \"المشفّرة بالكامل\"",
  "protocol-timeline.e7.body": "الاتصالات التي تبدو عشوائية نحو عناوين IP لمراكز البيانات تبدأ بالقطع باحتمال 26% لكل اتصال.",
  "protocol-timeline.e8.year": "أكتوبر 2022",
  "protocol-timeline.e8.title": "XTLS Vision",
  "protocol-timeline.e8.body": "يتوقف عن تشفير حركة الويب المشفّرة أصلاً مرة ثانية، ويخفي الأحجام الفاضحة لـ TLS المتداخل داخل TLS.",
  "protocol-timeline.e9.year": "مارس 2023",
  "protocol-timeline.e9.title": "إطلاق REALITY",
  "protocol-timeline.e9.body": "Xray-core 1.8.0. لا حاجة إلى نطاق أو شهادة: الخادم يستعير مصافحة TLS لموقع حقيقي.",
  "protocol-timeline.e10.year": "أغسطس 2023",
  "protocol-timeline.e10.title": "روسيا ترشّح WireGuard وOpenVPN",
  "protocol-timeline.e10.body": "مستخدمون لدى كبار مشغّلي الهاتف المحمول يبلّغون عن قطع البروتوكولين خلال ثوانٍ.",
  "protocol-timeline.e11.year": "نوفمبر 2025",
  "protocol-timeline.e11.title": "الجولة التالية",
  "protocol-timeline.e11.body": "تقارير عن قطع بعض مزودي الإنترنت المنزلي في روسيا لاتصالات Reality. والمشغّلون يردّون بمنافذ ووسائط نقل جديدة.",

  "schema-edge.title": "داخل عقدة Doppler الحافة",
  "schema-edge.link1": "يُفَك غلافه",
  "schema-edge.link2": "عنوان العقدة",
  "schema-edge.lane1.title": "النفق",
  "schema-edge.lane1.node1.label": "تدفق VLESS-Reality",
  "schema-edge.lane1.node1.detail": "يصل مشفّراً من جهازك",
  "schema-edge.lane2.title": "عقدة الحافة",
  "schema-edge.lane2.node1.label": "ترجمة العناوين",
  "schema-edge.lane2.node1.detail": "عنوانك يُستبدل بعنوان العقدة",
  "schema-edge.lane2.node2.label": "محلّل DNS",
  "schema-edge.lane2.node2.detail": "يجيب عن الاستعلامات داخل النفق",
  "schema-edge.lane2.node3.label": "غير مدوَّن",
  "schema-edge.lane2.node3.detail": "المواقع، استعلامات DNS، النطاق الترددي، أوقات الجلسات",
  "schema-edge.lane3.title": "الإنترنت المفتوح",
  "schema-edge.lane3.node1.label": "الموقع",
  "schema-edge.lane3.node1.detail": "يستقبل الطلب من العقدة",
  "schema-edge.lane3.watcher.who": "الموقع",
  "schema-edge.lane3.watcher.sees": "عنوان العقدة، لا عنوانك. وبصمة متصفحك تصل إليه رغم ذلك",

  "latency-distance.title": "زمن الذهاب والإياب مقابل المسافة بين المدن",
  "latency-distance.note": "النقاط: متوسط زمن الذهاب والإياب المقيس بين أزواج المدن (WonderNetwork، 24 سبتمبر 2026)، مرسوماً عند مسافة الدائرة العظمى التقريبية. الخط المتقطع: الحد الفيزيائي الأدنى، نحو 1 ms لكل 100 km في الألياف.",
  "latency-distance.xLabel": "المسافة (km)",
  "latency-distance.yLabel": "الذهاب والإياب (ms)",
  "latency-distance.reference": "الضوء في الألياف",
  "latency-distance.point1": "لندن إلى فرانكفورت، 17 ms",
  "latency-distance.point2": "لندن إلى نيويورك، 70 ms",
  "latency-distance.point3": "فرانكفورت إلى سنغافورة، 157 ms",
  "latency-distance.point4": "لندن إلى سيدني، 266 ms",
};
