/**
 * Every word that appears inside a /how-it-works chart, flat and one per line.
 *
 * The numbers, URLs and source citations stay in ../registry.tsx: a figure must
 * never drift from the study it came from just because someone edited a label.
 * This file holds only the prose, so a translator edits one file per locale and
 * cannot touch the data.
 *
 * `en` is the source of truth. `ChartCopyKey` is derived from it, so a locale
 * file that misses or misspells a key fails `npm run typecheck` rather than
 * quietly rendering English inside a translated article.
 */
export const en = {
  /** The figcaption prefix on every chart. Source labels themselves stay English. */
  "figure.sourceLabel": "Source",

  /* ── The hub's whole-journey schema ──────────────────────────────────── */
  "journey.title": "One connection, end to end",
  "journey.link1": "encrypted",
  "journey.link2": "unwrapped",
  "journey.link3": "node's IP",
  "journey.lane1.title": "1 · Your device",
  "journey.lane1.node1.label": "Doppler app",
  "journey.lane1.node1.detail": "Random account ID, no email",
  "journey.lane1.node2.label": "DNS and site names",
  "journey.lane1.node2.detail": "Sent into the tunnel, not to your ISP",
  "journey.lane1.watcher.who": "Wi-Fi owner, ISP",
  "journey.lane1.watcher.sees": "One TLS 1.3 session to what looks like a popular website",
  "journey.lane2.title": "2 · VLESS-Reality tunnel",
  "journey.lane2.node1.label": "TLS 1.3 handshake",
  "journey.lane2.node1.detail": "Borrowed from a real website",
  "journey.lane2.node2.label": "Probes",
  "journey.lane2.node2.detail": "Forwarded to that real website",
  "journey.lane2.watcher.who": "Censor's DPI",
  "journey.lane2.watcher.sees": "Ordinary HTTPS; a probe finds a genuine site",
  "journey.lane3.title": "3 · Doppler edge node",
  "journey.lane3.node1.label": "Address swap",
  "journey.lane3.node1.detail": "Your IP becomes the node's",
  "journey.lane3.node2.label": "DNS resolver",
  "journey.lane3.node2.detail": "Queries never logged",
  "journey.lane3.node3.label": "Traffic logs",
  "journey.lane3.node3.detail": "None kept",
  "journey.lane4.title": "4 · Open internet",
  "journey.lane4.node1.label": "The site you asked for",
  "journey.lane4.node1.detail": "Test what it sees at /tools",
  "journey.lane4.watcher.who": "The website",
  "journey.lane4.watcher.sees": "The node's IP, and your browser's own fingerprint",

  /* ── Step 1: your device ─────────────────────────────────────────────── */
  "schema-device.title": "What leaves your device when Doppler connects",
  "schema-device.link1": "1 · sign in",
  "schema-device.link2": "2 · connect",
  "schema-device.lane1.title": "Your device",
  "schema-device.lane1.node1.label": "Doppler app",
  "schema-device.lane1.node1.detail": "Makes a random VPN-XXXX-XXXX-XXXX ID on first launch",
  "schema-device.lane1.node2.label": "No sign-up form",
  "schema-device.lane1.node2.detail": "No email, phone or password",
  "schema-device.lane1.watcher.who": "Wi-Fi owner, ISP",
  "schema-device.lane1.watcher.sees": "An HTTPS call to our API, then one TLS session",
  "schema-device.lane2.title": "Doppler API",
  "schema-device.lane2.node1.label": "Sign-in record",
  "schema-device.lane2.node1.detail": "IP, account ID, device ID, time. Kept up to 90 days",
  "schema-device.lane2.node2.label": "Server settings",
  "schema-device.lane2.node2.detail": "Delivered over an authenticated API",
  "schema-device.lane3.title": "Tunnel",
  "schema-device.lane3.node1.label": "VLESS-Reality opens",
  "schema-device.lane3.node1.detail": "DNS and site names now travel inside it",
  "schema-device.lane3.watcher.who": "Wi-Fi owner, ISP",
  "schema-device.lane3.watcher.sees": "No domains, no site names, no pages",

  "fingerprint-uniqueness.title": "Share of browsers with a unique fingerprint",
  "fingerprint-uniqueness.note": "Panopticlick sampled about 470,000 browsers in 2010. AmIUnique sampled 118,934 in 2016.",
  "fingerprint-uniqueness.bar1": "Panopticlick, all browsers (2010)",
  "fingerprint-uniqueness.bar2": "Panopticlick, with Flash or Java (2010)",
  "fingerprint-uniqueness.bar3": "AmIUnique (2016)",

  "dbir-2026.title": "What shows up in data breaches (share of confirmed breaches)",
  "dbir-2026.note": "Over 22,000 confirmed breaches across 145 countries. Categories overlap, so they do not add up to 100%.",
  "dbir-2026.bar1": "A human element involved",
  "dbir-2026.bar2": "Ransomware",
  "dbir-2026.bar3": "A third party involved",
  "dbir-2026.bar4": "Entry through a software vulnerability",
  "dbir-2026.bar5": "Credentials among the data taken",

  /* ── Step 2: the VLESS-Reality tunnel ────────────────────────────────── */
  "schema-reality.title": "Where a Reality connection goes, and what each party sees",
  "schema-reality.link1": "TLS 1.3",
  "schema-reality.link2": "token check",
  "schema-reality.lane1.title": "Client",
  "schema-reality.lane1.node1.label": "Doppler app",
  "schema-reality.lane1.node1.detail": "Handshake names a real site and carries a hidden x25519 token",
  "schema-reality.lane1.node2.label": "Anyone else",
  "schema-reality.lane1.node2.detail": "Censor's probe, scanner, browser",
  "schema-reality.lane2.title": "The network",
  "schema-reality.lane2.node1.label": "DPI box",
  "schema-reality.lane2.node1.detail": "GFW, TSPU or an ISP filter",
  "schema-reality.lane2.watcher.who": "Censor",
  "schema-reality.lane2.watcher.sees": "A normal TLS 1.3 visit to a popular website",
  "schema-reality.lane3.title": "Reality server",
  "schema-reality.lane3.node1.label": "Valid token",
  "schema-reality.lane3.node1.detail": "Tunnel opens, VLESS traffic flows to the edge node",
  "schema-reality.lane3.node2.label": "No token",
  "schema-reality.lane3.node2.detail": "Passed through to the real site and its genuine certificate",

  "detection-rates.title": "How often researchers caught disguised traffic",
  "detection-rates.note": "Three studies on real networks. Each figure is the study's reported floor, so the true rates are at or above these.",
  "detection-rates.bar1": "OpenVPN flows identified",
  "detection-rates.bar2": "\"Obfuscated\" VPN setups caught (34 of 41)",
  "detection-rates.bar3": "Obfuscated proxies caught by TLS-in-TLS patterns",

  "protocol-timeline.title": "Twenty years of cat and mouse",
  "protocol-timeline.e1.year": "2002",
  "protocol-timeline.e1.title": "Tor goes live",
  "protocol-timeline.e1.body": "Onion routing opens to the public. Its traffic is easy to recognise, which later forces the creation of disguised \"pluggable transports\".",
  "protocol-timeline.e2.year": "2012",
  "protocol-timeline.e2.title": "Shadowsocks",
  "protocol-timeline.e2.body": "A lightweight proxy whose traffic looks like random bytes. It spreads fast in China.",
  "protocol-timeline.e3.year": "2015",
  "protocol-timeline.e3.title": "V2Ray and VMess, and a takedown",
  "protocol-timeline.e3.body": "Project V starts in September. In August the Shadowsocks author had deleted the code after a visit from the police.",
  "protocol-timeline.e4.year": "2019",
  "protocol-timeline.e4.title": "Active probing gets documented",
  "protocol-timeline.e4.body": "Researchers log over 51,000 probes from Chinese IPs testing suspected Shadowsocks servers.",
  "protocol-timeline.e5.year": "Jul 2020",
  "protocol-timeline.e5.title": "VLESS proposed",
  "protocol-timeline.e5.body": "A stripped-down protocol with no encryption of its own, meant to ride inside TLS.",
  "protocol-timeline.e6.year": "Nov 2020",
  "protocol-timeline.e6.title": "Xray-core",
  "protocol-timeline.e6.body": "The XTLS project forks from V2Ray and becomes VLESS's main home.",
  "protocol-timeline.e7.year": "Nov 2021",
  "protocol-timeline.e7.title": "China blocks \"fully encrypted\" traffic",
  "protocol-timeline.e7.body": "Random-looking connections to data-centre IPs start getting cut with a 26% chance each.",
  "protocol-timeline.e8.year": "Oct 2022",
  "protocol-timeline.e8.title": "XTLS Vision",
  "protocol-timeline.e8.body": "Stops encrypting already encrypted web traffic twice, and hides the telltale sizes of TLS nested in TLS.",
  "protocol-timeline.e9.year": "Mar 2023",
  "protocol-timeline.e9.title": "REALITY ships",
  "protocol-timeline.e9.body": "Xray-core 1.8.0. No domain or certificate needed: the server borrows a real website's TLS handshake.",
  "protocol-timeline.e10.year": "Aug 2023",
  "protocol-timeline.e10.title": "Russia filters WireGuard and OpenVPN",
  "protocol-timeline.e10.body": "Users on major mobile carriers report both protocols cut within seconds.",
  "protocol-timeline.e11.year": "Nov 2025",
  "protocol-timeline.e11.title": "The next round",
  "protocol-timeline.e11.body": "Some Russian home ISPs are reported to cut Reality connections. Operators answer with new ports and transports.",

  /* ── Step 3: the edge node ───────────────────────────────────────────── */
  "schema-edge.title": "Inside a Doppler edge node",
  "schema-edge.link1": "unwrapped",
  "schema-edge.link2": "node's IP",
  "schema-edge.lane1.title": "Tunnel",
  "schema-edge.lane1.node1.label": "VLESS-Reality stream",
  "schema-edge.lane1.node1.detail": "Arrives encrypted from your device",
  "schema-edge.lane2.title": "Edge node",
  "schema-edge.lane2.node1.label": "Address translation",
  "schema-edge.lane2.node1.detail": "Your IP is swapped for the node's",
  "schema-edge.lane2.node2.label": "DNS resolver",
  "schema-edge.lane2.node2.detail": "Answers lookups inside the tunnel",
  "schema-edge.lane2.node3.label": "Not written down",
  "schema-edge.lane2.node3.detail": "Sites, DNS queries, bandwidth, session times",
  "schema-edge.lane3.title": "Open internet",
  "schema-edge.lane3.node1.label": "Website",
  "schema-edge.lane3.node1.detail": "Receives the request from the node",
  "schema-edge.lane3.watcher.who": "The website",
  "schema-edge.lane3.watcher.sees": "The node's IP, not yours. Your browser fingerprint still reaches it",

  "latency-distance.title": "Round-trip time vs distance between cities",
  "latency-distance.note": "Dots: measured average RTT between city pairs (WonderNetwork, 24 September 2026), plotted at the approximate great-circle distance. Dashed line: the physical floor of about 1 ms per 100 km in fibre.",
  "latency-distance.xLabel": "Distance (km)",
  "latency-distance.yLabel": "Round trip (ms)",
  "latency-distance.reference": "Light in fibre",
  "latency-distance.point1": "London to Frankfurt, 17 ms",
  "latency-distance.point2": "London to New York, 70 ms",
  "latency-distance.point3": "Frankfurt to Singapore, 157 ms",
  "latency-distance.point4": "London to Sydney, 266 ms",
} as const;

export type ChartCopyKey = keyof typeof en;
export type ChartCopy = Record<ChartCopyKey, string>;
