import type { ChartCopy } from "./en";

/** Persian chart copy. Keys and their order match ./en.ts. */
export const fa: ChartCopy = {
  "figure.sourceLabel": "منبع",

  "journey.title": "یک اتصال، از ابتدا تا انتها",
  "journey.link1": "رمزنگاری‌شده",
  "journey.link2": "باز می‌شود",
  "journey.link3": "IP نود",
  "journey.lane1.title": "1 · دستگاه شما",
  "journey.lane1.node1.label": "اپلیکیشن Doppler",
  "journey.lane1.node1.detail": "شناسه‌ی حساب تصادفی، بدون ایمیل",
  "journey.lane1.node2.label": "DNS و نام سایت‌ها",
  "journey.lane1.node2.detail": "به داخل تونل می‌روند، نه به ISP شما",
  "journey.lane1.watcher.who": "صاحب وای‌فای، ISP",
  "journey.lane1.watcher.sees": "یک نشست TLS 1.3 به چیزی که شبیه یک سایت پرطرفدار است",
  "journey.lane2.title": "2 · تونل VLESS-Reality",
  "journey.lane2.node1.label": "دست‌دهی TLS 1.3",
  "journey.lane2.node1.detail": "از یک وب‌سایت واقعی قرض گرفته شده",
  "journey.lane2.node2.label": "کاوش‌ها",
  "journey.lane2.node2.detail": "به همان وب‌سایت واقعی هدایت می‌شوند",
  "journey.lane2.watcher.who": "DPI سانسورچی",
  "journey.lane2.watcher.sees": "HTTPS معمولی؛ کاوش به یک سایت اصیل می‌رسد",
  "journey.lane3.title": "3 · نود لبه‌ی Doppler",
  "journey.lane3.node1.label": "تعویض نشانی",
  "journey.lane3.node1.detail": "IP شما به IP نود تبدیل می‌شود",
  "journey.lane3.node2.label": "حل‌کننده‌ی DNS",
  "journey.lane3.node2.detail": "کوئری‌ها هرگز ثبت نمی‌شوند",
  "journey.lane3.node3.label": "لاگ ترافیک",
  "journey.lane3.node3.detail": "هیچ نگه داشته نمی‌شود",
  "journey.lane4.title": "4 · اینترنت باز",
  "journey.lane4.node1.label": "سایتی که خواسته‌اید",
  "journey.lane4.node1.detail": "آنچه می‌بیند را در /tools بیازمایید",
  "journey.lane4.watcher.who": "وب‌سایت",
  "journey.lane4.watcher.sees": "IP نود، و اثر انگشت خود مرورگر شما",

  "schema-device.title": "وقتی Doppler وصل می‌شود چه چیزی از دستگاه شما بیرون می‌رود",
  "schema-device.link1": "1 · ورود",
  "schema-device.link2": "2 · اتصال",
  "schema-device.lane1.title": "دستگاه شما",
  "schema-device.lane1.node1.label": "اپلیکیشن Doppler",
  "schema-device.lane1.node1.detail": "در اولین اجرا یک شناسه‌ی تصادفی VPN-XXXX-XXXX-XXXX می‌سازد",
  "schema-device.lane1.node2.label": "بدون فرم ثبت‌نام",
  "schema-device.lane1.node2.detail": "بدون ایمیل، تلفن یا گذرواژه",
  "schema-device.lane1.watcher.who": "صاحب وای‌فای، ISP",
  "schema-device.lane1.watcher.sees": "یک تماس HTTPS با API ما، بعد یک نشست TLS",
  "schema-device.lane2.title": "API‏ Doppler",
  "schema-device.lane2.node1.label": "رکورد احراز هویت",
  "schema-device.lane2.node1.detail": "IP، شناسه‌ی حساب، شناسه‌ی دستگاه، زمان. تا 90 روز نگه داشته می‌شود",
  "schema-device.lane2.node2.label": "تنظیمات سرور",
  "schema-device.lane2.node2.detail": "از طریق یک API احرازهویت‌شده تحویل می‌شود",
  "schema-device.lane3.title": "تونل",
  "schema-device.lane3.node1.label": "VLESS-Reality باز می‌شود",
  "schema-device.lane3.node1.detail": "DNS و نام سایت‌ها از حالا داخل آن سفر می‌کنند",
  "schema-device.lane3.watcher.who": "صاحب وای‌فای، ISP",
  "schema-device.lane3.watcher.sees": "نه دامنه‌ای، نه نام سایتی، نه صفحه‌ای",

  "fingerprint-uniqueness.title": "سهم مرورگرهایی که اثر انگشت یکتا دارند",
  "fingerprint-uniqueness.note": "Panopticlick در 2010 حدود 470,000 مرورگر را نمونه‌گیری کرد. AmIUnique در 2016 روی 118,934 مرورگر.",
  "fingerprint-uniqueness.bar1": "Panopticlick، همه‌ی مرورگرها (2010)",
  "fingerprint-uniqueness.bar2": "Panopticlick، با Flash یا Java (2010)",
  "fingerprint-uniqueness.bar3": "AmIUnique (2016)",

  "dbir-2026.title": "در نشت داده‌ها چه چیزی پیدا می‌شود (سهم از نشت‌های تأییدشده)",
  "dbir-2026.note": "بیش از 22,000 نشت تأییدشده در 145 کشور. دسته‌ها همپوشانی دارند، پس جمعشان 100% نمی‌شود.",
  "dbir-2026.bar1": "دخالت یک عامل انسانی",
  "dbir-2026.bar2": "باج‌افزار",
  "dbir-2026.bar3": "دخالت یک طرف ثالث",
  "dbir-2026.bar4": "ورود از راه یک آسیب‌پذیری نرم‌افزاری",
  "dbir-2026.bar5": "اطلاعات ورود میان داده‌های برده‌شده",

  "schema-reality.title": "یک اتصال Reality کجا می‌رود، و هر طرف چه می‌بیند",
  "schema-reality.link1": "TLS 1.3",
  "schema-reality.link2": "بررسی نشانه",
  "schema-reality.lane1.title": "کلاینت",
  "schema-reality.lane1.node1.label": "اپلیکیشن Doppler",
  "schema-reality.lane1.node1.detail": "دست‌دهی نام یک سایت واقعی را می‌برد و یک نشانه‌ی پنهان x25519 حمل می‌کند",
  "schema-reality.lane1.node2.label": "هر کس دیگری",
  "schema-reality.lane1.node2.detail": "کاوش سانسورچی، اسکنر، مرورگر",
  "schema-reality.lane2.title": "شبکه",
  "schema-reality.lane2.node1.label": "جعبه‌ی DPI",
  "schema-reality.lane2.node1.detail": "GFW، TSPU یا یک فیلتر ISP",
  "schema-reality.lane2.watcher.who": "سانسورچی",
  "schema-reality.lane2.watcher.sees": "یک بازدید معمولی TLS 1.3 از یک وب‌سایت پرطرفدار",
  "schema-reality.lane3.title": "سرور Reality",
  "schema-reality.lane3.node1.label": "نشانه‌ی معتبر",
  "schema-reality.lane3.node1.detail": "تونل باز می‌شود، ترافیک VLESS به نود لبه جاری می‌شود",
  "schema-reality.lane3.node2.label": "بدون نشانه",
  "schema-reality.lane3.node2.detail": "به سایت واقعی و گواهی اصیلش عبور داده می‌شود",

  "detection-rates.title": "پژوهشگران هر چند وقت ترافیک استتارشده را گرفتند",
  "detection-rates.note": "سه پژوهش روی شبکه‌های واقعی. هر عدد، کف گزارش‌شده‌ی همان پژوهش است، پس نرخ‌های واقعی برابر یا بالاتر از این‌هاست.",
  "detection-rates.bar1": "جریان‌های OpenVPN شناسایی‌شده",
  "detection-rates.bar2": "پیکربندی‌های VPN «مبهم‌سازی‌شده» که گرفته شدند (34 از 41)",
  "detection-rates.bar3": "پروکسی‌های مبهم‌سازی‌شده که با الگوی TLS در TLS گرفته شدند",

  "protocol-timeline.title": "بیست سال بازی موش و گربه",
  "protocol-timeline.e1.year": "2002",
  "protocol-timeline.e1.title": "Tor راه می‌افتد",
  "protocol-timeline.e1.body": "مسیریابی پیازی در دسترس عموم قرار می‌گیرد. ترافیکش به‌راحتی قابل تشخیص است، و همین بعدها ساخت «ترانسپورت‌های افزودنی» استتارشده را ناگزیر می‌کند.",
  "protocol-timeline.e2.year": "2012",
  "protocol-timeline.e2.title": "Shadowsocks",
  "protocol-timeline.e2.body": "یک پروکسی سبک که ترافیکش شبیه بایت‌های تصادفی است. در چین به‌سرعت گسترش می‌یابد.",
  "protocol-timeline.e3.year": "2015",
  "protocol-timeline.e3.title": "V2Ray و VMess، و یک حذف اجباری",
  "protocol-timeline.e3.body": "پروژه‌ی V در سپتامبر آغاز می‌شود. در اوت، نویسنده‌ی Shadowsocks پس از سر زدن پلیس کد را پاک کرده بود.",
  "protocol-timeline.e4.year": "2019",
  "protocol-timeline.e4.title": "کاوش فعال مستند می‌شود",
  "protocol-timeline.e4.body": "پژوهشگران بیش از 51,000 کاوش از IPهای چینی را ثبت می‌کنند که سرورهای مظنون به Shadowsocks را می‌آزمایند.",
  "protocol-timeline.e5.year": "ژوئیه 2020",
  "protocol-timeline.e5.title": "VLESS پیشنهاد می‌شود",
  "protocol-timeline.e5.body": "پروتکلی لاغرشده بدون رمزنگاری از خودش، ساخته شده تا داخل TLS سوار شود.",
  "protocol-timeline.e6.year": "نوامبر 2020",
  "protocol-timeline.e6.title": "Xray-core",
  "protocol-timeline.e6.body": "پروژه‌ی XTLS از V2Ray جدا می‌شود و به خانه‌ی اصلی VLESS بدل می‌گردد.",
  "protocol-timeline.e7.year": "نوامبر 2021",
  "protocol-timeline.e7.title": "چین ترافیک «کاملاً رمزنگاری‌شده» را مسدود می‌کند",
  "protocol-timeline.e7.body": "اتصال‌هایی که تصادفی به نظر می‌رسند و به IPهای مرکز داده می‌روند، هر کدام با احتمال 26% قطع می‌شوند.",
  "protocol-timeline.e8.year": "اکتبر 2022",
  "protocol-timeline.e8.title": "XTLS Vision",
  "protocol-timeline.e8.body": "از رمزنگاری دوباره‌ی ترافیک وبی که از قبل رمزنگاری شده دست می‌کشد، و اندازه‌های افشاگر TLS تودرتو در TLS را پنهان می‌کند.",
  "protocol-timeline.e9.year": "مارس 2023",
  "protocol-timeline.e9.title": "REALITY عرضه می‌شود",
  "protocol-timeline.e9.body": "Xray-core 1.8.0. نه دامنه‌ای لازم است نه گواهی: سرور دست‌دهی TLS یک وب‌سایت واقعی را قرض می‌گیرد.",
  "protocol-timeline.e10.year": "اوت 2023",
  "protocol-timeline.e10.title": "روسیه WireGuard و OpenVPN را فیلتر می‌کند",
  "protocol-timeline.e10.body": "کاربران اپراتورهای بزرگ تلفن همراه گزارش می‌دهند هر دو پروتکل ظرف چند ثانیه قطع می‌شوند.",
  "protocol-timeline.e11.year": "نوامبر 2025",
  "protocol-timeline.e11.title": "دور بعدی",
  "protocol-timeline.e11.body": "گزارش می‌شود که برخی ISPهای خانگی روسیه اتصال‌های Reality را قطع می‌کنند. گردانندگان با درگاه‌ها و ترانسپورت‌های تازه پاسخ می‌دهند.",

  "schema-edge.title": "داخل یک نود لبه‌ی Doppler",
  "schema-edge.link1": "باز می‌شود",
  "schema-edge.link2": "IP نود",
  "schema-edge.lane1.title": "تونل",
  "schema-edge.lane1.node1.label": "جریان VLESS-Reality",
  "schema-edge.lane1.node1.detail": "رمزنگاری‌شده از دستگاه شما می‌رسد",
  "schema-edge.lane2.title": "نود لبه",
  "schema-edge.lane2.node1.label": "ترجمه‌ی نشانی",
  "schema-edge.lane2.node1.detail": "IP شما با IP نود عوض می‌شود",
  "schema-edge.lane2.node2.label": "حل‌کننده‌ی DNS",
  "schema-edge.lane2.node2.detail": "به درخواست‌ها داخل تونل پاسخ می‌دهد",
  "schema-edge.lane2.node3.label": "نوشته نمی‌شود",
  "schema-edge.lane2.node3.detail": "سایت‌ها، کوئری‌های DNS، پهنای باند، مدت نشست",
  "schema-edge.lane3.title": "اینترنت باز",
  "schema-edge.lane3.node1.label": "وب‌سایت",
  "schema-edge.lane3.node1.detail": "درخواست را از نود دریافت می‌کند",
  "schema-edge.lane3.watcher.who": "وب‌سایت",
  "schema-edge.lane3.watcher.sees": "IP نود را، نه IP شما را. اثر انگشت مرورگرتان همچنان به آن می‌رسد",

  "latency-distance.title": "زمان رفت‌وبرگشت در برابر فاصله‌ی میان شهرها",
  "latency-distance.note": "نقطه‌ها: میانگین RTT اندازه‌گیری‌شده میان جفت‌شهرها (WonderNetwork، 24 سپتامبر 2026)، رسم‌شده روی فاصله‌ی تقریبی دایره‌ی بزرگ. خط‌چین: کف فیزیکی حدود 1 میلی‌ثانیه به ازای هر 100 کیلومتر در فیبر.",
  "latency-distance.xLabel": "فاصله (km)",
  "latency-distance.yLabel": "رفت‌وبرگشت (ms)",
  "latency-distance.reference": "نور در فیبر",
  "latency-distance.point1": "لندن تا فرانکفورت، 17 ms",
  "latency-distance.point2": "لندن تا نیویورک، 70 ms",
  "latency-distance.point3": "فرانکفورت تا سنگاپور، 157 ms",
  "latency-distance.point4": "لندن تا سیدنی، 266 ms",
};
