import type { ChartCopy } from "./en";

/** Russian chart copy. Keys and their order match ./en.ts. */
export const ru: ChartCopy = {
  "figure.sourceLabel": "Источник",

  /* ── Схема всего пути на странице-хабе ───────────────────────────────── */
  "journey.title": "Одно соединение от начала до конца",
  "journey.link1": "зашифровано",
  "journey.link2": "распаковано",
  "journey.link3": "IP узла",
  "journey.lane1.title": "1 · Ваше устройство",
  "journey.lane1.node1.label": "Приложение Doppler",
  "journey.lane1.node1.detail": "Случайный идентификатор аккаунта, без почты",
  "journey.lane1.node2.label": "DNS и имена сайтов",
  "journey.lane1.node2.detail": "Уходят в туннель, а не к провайдеру",
  "journey.lane1.watcher.who": "Владелец Wi-Fi, провайдер",
  "journey.lane1.watcher.sees": "Одна сессия TLS 1.3 к чему-то похожему на популярный сайт",
  "journey.lane2.title": "2 · Туннель VLESS-Reality",
  "journey.lane2.node1.label": "Рукопожатие TLS 1.3",
  "journey.lane2.node1.detail": "Позаимствовано у реального сайта",
  "journey.lane2.node2.label": "Зондирование",
  "journey.lane2.node2.detail": "Переадресуется на этот реальный сайт",
  "journey.lane2.watcher.who": "DPI цензора",
  "journey.lane2.watcher.sees": "Обычный HTTPS; зонд находит настоящий сайт",
  "journey.lane3.title": "3 · Выходной узел Doppler",
  "journey.lane3.node1.label": "Подмена адреса",
  "journey.lane3.node1.detail": "Ваш IP становится IP узла",
  "journey.lane3.node2.label": "DNS-резолвер",
  "journey.lane3.node2.detail": "Запросы не журналируются",
  "journey.lane3.node3.label": "Журналы трафика",
  "journey.lane3.node3.detail": "Не ведутся",
  "journey.lane4.title": "4 · Открытый интернет",
  "journey.lane4.node1.label": "Сайт, который вы запросили",
  "journey.lane4.node1.detail": "Что он видит, проверьте на /tools",
  "journey.lane4.watcher.who": "Сайт",
  "journey.lane4.watcher.sees": "IP узла и собственный отпечаток вашего браузера",

  /* ── Шаг 1: ваше устройство ──────────────────────────────────────────── */
  "schema-device.title": "Что уходит с вашего устройства, когда Doppler подключается",
  "schema-device.link1": "1 · вход",
  "schema-device.link2": "2 · подключение",
  "schema-device.lane1.title": "Ваше устройство",
  "schema-device.lane1.node1.label": "Приложение Doppler",
  "schema-device.lane1.node1.detail": "При первом запуске создаёт случайный ID вида VPN-XXXX-XXXX-XXXX",
  "schema-device.lane1.node2.label": "Никакой формы регистрации",
  "schema-device.lane1.node2.detail": "Ни почты, ни телефона, ни пароля",
  "schema-device.lane1.watcher.who": "Владелец Wi-Fi, провайдер",
  "schema-device.lane1.watcher.sees": "HTTPS-обращение к нашему API, затем одна TLS-сессия",
  "schema-device.lane2.title": "API Doppler",
  "schema-device.lane2.node1.label": "Запись аутентификации",
  "schema-device.lane2.node1.detail": "IP, ID аккаунта, ID устройства, время. Хранится до 90 дней",
  "schema-device.lane2.node2.label": "Настройки серверов",
  "schema-device.lane2.node2.detail": "Передаются через аутентифицированный API",
  "schema-device.lane3.title": "Туннель",
  "schema-device.lane3.node1.label": "VLESS-Reality открывается",
  "schema-device.lane3.node1.detail": "DNS и имена сайтов теперь идут внутри него",
  "schema-device.lane3.watcher.who": "Владелец Wi-Fi, провайдер",
  "schema-device.lane3.watcher.sees": "Ни доменов, ни имён сайтов, ни страниц",

  "fingerprint-uniqueness.title": "Доля браузеров с уникальным отпечатком",
  "fingerprint-uniqueness.note": "Panopticlick собрал около 470 000 браузеров в 2010 году. AmIUnique собрал 118 934 в 2016 году.",
  "fingerprint-uniqueness.bar1": "Panopticlick, все браузеры (2010)",
  "fingerprint-uniqueness.bar2": "Panopticlick, с Flash или Java (2010)",
  "fingerprint-uniqueness.bar3": "AmIUnique (2016)",

  "dbir-2026.title": "Что встречается в утечках данных (доля подтверждённых утечек)",
  "dbir-2026.note": "Более 22 000 подтверждённых утечек в 145 странах. Категории пересекаются, поэтому в сумме они не дают 100%.",
  "dbir-2026.bar1": "Замешан человеческий фактор",
  "dbir-2026.bar2": "Программы-вымогатели",
  "dbir-2026.bar3": "Замешана третья сторона",
  "dbir-2026.bar4": "Проникновение через уязвимость в ПО",
  "dbir-2026.bar5": "Среди похищенного есть учётные данные",

  /* ── Шаг 2: туннель VLESS-Reality ────────────────────────────────────── */
  "schema-reality.title": "Куда идёт соединение Reality и что видит каждая сторона",
  "schema-reality.link1": "TLS 1.3",
  "schema-reality.link2": "проверка токена",
  "schema-reality.lane1.title": "Клиент",
  "schema-reality.lane1.node1.label": "Приложение Doppler",
  "schema-reality.lane1.node1.detail": "Рукопожатие называет реальный сайт и несёт скрытый токен x25519",
  "schema-reality.lane1.node2.label": "Все остальные",
  "schema-reality.lane1.node2.detail": "Зонд цензора, сканер, браузер",
  "schema-reality.lane2.title": "Сеть",
  "schema-reality.lane2.node1.label": "DPI-оборудование",
  "schema-reality.lane2.node1.detail": "GFW, ТСПУ или фильтр провайдера",
  "schema-reality.lane2.watcher.who": "Цензор",
  "schema-reality.lane2.watcher.sees": "Обычный заход по TLS 1.3 на популярный сайт",
  "schema-reality.lane3.title": "Сервер Reality",
  "schema-reality.lane3.node1.label": "Токен верный",
  "schema-reality.lane3.node1.detail": "Туннель открывается, трафик VLESS идёт на выходной узел",
  "schema-reality.lane3.node2.label": "Токена нет",
  "schema-reality.lane3.node2.detail": "Переадресация на реальный сайт с его подлинным сертификатом",

  "detection-rates.title": "Как часто исследователи ловили замаскированный трафик",
  "detection-rates.note": "Три исследования в реальных сетях. Каждая цифра это заявленная в исследовании нижняя граница, так что настоящие показатели не ниже.",
  "detection-rates.bar1": "Опознано потоков OpenVPN",
  "detection-rates.bar2": "Поймано «обфусцированных» VPN-конфигураций (34 из 41)",
  "detection-rates.bar3": "Поймано обфусцированных прокси по рисунку TLS в TLS",

  "protocol-timeline.title": "Двадцать лет игры в кошки-мышки",
  "protocol-timeline.e1.year": "2002",
  "protocol-timeline.e1.title": "Tor выходит в свет",
  "protocol-timeline.e1.body": "Луковая маршрутизация становится общедоступной. Её трафик легко распознать, и позже это вынуждает создать маскирующие «подключаемые транспорты».",
  "protocol-timeline.e2.year": "2012",
  "protocol-timeline.e2.title": "Shadowsocks",
  "protocol-timeline.e2.body": "Лёгкий прокси, трафик которого выглядит как случайные байты. В Китае он расходится быстро.",
  "protocol-timeline.e3.year": "2015",
  "protocol-timeline.e3.title": "V2Ray и VMess, и удаление кода",
  "protocol-timeline.e3.body": "Project V стартует в сентябре. В августе автор Shadowsocks удалил код после визита полиции.",
  "protocol-timeline.e4.year": "2019",
  "protocol-timeline.e4.title": "Активное зондирование задокументировано",
  "protocol-timeline.e4.body": "Исследователи фиксируют более 51 000 зондирований с китайских IP, проверяющих подозреваемые серверы Shadowsocks.",
  "protocol-timeline.e5.year": "Июль 2020",
  "protocol-timeline.e5.title": "Предложен VLESS",
  "protocol-timeline.e5.body": "Урезанный протокол без собственного шифрования, рассчитанный на работу внутри TLS.",
  "protocol-timeline.e6.year": "Ноябрь 2020",
  "protocol-timeline.e6.title": "Xray-core",
  "protocol-timeline.e6.body": "Проект XTLS отделяется от V2Ray и становится главным домом VLESS.",
  "protocol-timeline.e7.year": "Ноябрь 2021",
  "protocol-timeline.e7.title": "Китай блокирует «полностью зашифрованный» трафик",
  "protocol-timeline.e7.body": "Похожие на случайные соединения к IP дата-центров начинают обрывать с вероятностью 26% каждое.",
  "protocol-timeline.e8.year": "Октябрь 2022",
  "protocol-timeline.e8.title": "XTLS Vision",
  "protocol-timeline.e8.body": "Перестаёт шифровать второй раз уже зашифрованный веб-трафик и прячет выдающие размеры TLS, вложенного в TLS.",
  "protocol-timeline.e9.year": "Март 2023",
  "protocol-timeline.e9.title": "Выходит REALITY",
  "protocol-timeline.e9.body": "Xray-core 1.8.0. Ни домена, ни сертификата не нужно: сервер заимствует TLS-рукопожатие реального сайта.",
  "protocol-timeline.e10.year": "Август 2023",
  "protocol-timeline.e10.title": "Россия фильтрует WireGuard и OpenVPN",
  "protocol-timeline.e10.body": "Пользователи крупных мобильных операторов сообщают, что оба протокола обрывают за считаные секунды.",
  "protocol-timeline.e11.year": "Ноябрь 2025",
  "protocol-timeline.e11.title": "Следующий раунд",
  "protocol-timeline.e11.body": "Сообщается, что часть российских домашних провайдеров обрывает соединения Reality. Операторы отвечают новыми портами и транспортами.",

  /* ── Шаг 3: выходной узел ────────────────────────────────────────────── */
  "schema-edge.title": "Внутри выходного узла Doppler",
  "schema-edge.link1": "распаковано",
  "schema-edge.link2": "IP узла",
  "schema-edge.lane1.title": "Туннель",
  "schema-edge.lane1.node1.label": "Поток VLESS-Reality",
  "schema-edge.lane1.node1.detail": "Приходит зашифрованным с вашего устройства",
  "schema-edge.lane2.title": "Выходной узел",
  "schema-edge.lane2.node1.label": "Трансляция адресов",
  "schema-edge.lane2.node1.detail": "Ваш IP подменяется на IP узла",
  "schema-edge.lane2.node2.label": "DNS-резолвер",
  "schema-edge.lane2.node2.detail": "Отвечает на запросы внутри туннеля",
  "schema-edge.lane2.node3.label": "Не записывается",
  "schema-edge.lane2.node3.detail": "Сайты, DNS-запросы, объём трафика, время сессий",
  "schema-edge.lane3.title": "Открытый интернет",
  "schema-edge.lane3.node1.label": "Сайт",
  "schema-edge.lane3.node1.detail": "Получает запрос от узла",
  "schema-edge.lane3.watcher.who": "Сайт",
  "schema-edge.lane3.watcher.sees": "IP узла, а не ваш. Отпечаток вашего браузера до него всё равно доходит",

  "latency-distance.title": "Время отклика и расстояние между городами",
  "latency-distance.note": "Точки: измеренное среднее время отклика между парами городов (WonderNetwork, 24 сентября 2026 года), отложенное по приблизительному расстоянию по дуге большого круга. Пунктир: физический предел около 1 мс на 100 км в оптоволокне.",
  "latency-distance.xLabel": "Расстояние (км)",
  "latency-distance.yLabel": "Отклик в обе стороны (мс)",
  "latency-distance.reference": "Свет в оптоволокне",
  "latency-distance.point1": "Лондон и Франкфурт, 17 мс",
  "latency-distance.point2": "Лондон и Нью-Йорк, 70 мс",
  "latency-distance.point3": "Франкфурт и Сингапур, 157 мс",
  "latency-distance.point4": "Лондон и Сидней, 266 мс",
};
