import type { ChartCopy } from "./en";

/** Turkish chart copy. Keys and their order match ./en.ts. */
export const tr: ChartCopy = {
  "figure.sourceLabel": "Kaynak",

  /* ── The hub's whole-journey schema ──────────────────────────────────── */
  "journey.title": "Tek bir bağlantı, uçtan uca",
  "journey.link1": "şifreli",
  "journey.link2": "açılıyor",
  "journey.link3": "düğümün IP'si",
  "journey.lane1.title": "1 · Cihazınız",
  "journey.lane1.node1.label": "Doppler uygulaması",
  "journey.lane1.node1.detail": "Rastgele hesap kimliği, e-posta yok",
  "journey.lane1.node2.label": "DNS ve site adları",
  "journey.lane1.node2.detail": "Sağlayıcınıza değil, tünele gönderiliyor",
  "journey.lane1.watcher.who": "Wi-Fi sahibi, sağlayıcı",
  "journey.lane1.watcher.sees": "Popüler görünen bir siteye tek bir TLS 1.3 oturumu",
  "journey.lane2.title": "2 · VLESS-Reality tüneli",
  "journey.lane2.node1.label": "TLS 1.3 el sıkışması",
  "journey.lane2.node1.detail": "Gerçek bir siteden ödünç alınmış",
  "journey.lane2.node2.label": "Sondalar",
  "journey.lane2.node2.detail": "O gerçek siteye yönlendiriliyor",
  "journey.lane2.watcher.who": "Sansürcünün DPI'sı",
  "journey.lane2.watcher.sees": "Sıradan HTTPS; sonda gerçek bir site buluyor",
  "journey.lane3.title": "3 · Doppler uç düğümü",
  "journey.lane3.node1.label": "Adres değişimi",
  "journey.lane3.node1.detail": "IP'niz düğümünki oluyor",
  "journey.lane3.node2.label": "DNS çözücü",
  "journey.lane3.node2.detail": "Sorgular hiç kaydedilmiyor",
  "journey.lane3.node3.label": "Trafik kayıtları",
  "journey.lane3.node3.detail": "Hiç tutulmuyor",
  "journey.lane4.title": "4 · Açık internet",
  "journey.lane4.node1.label": "İstediğiniz site",
  "journey.lane4.node1.detail": "Ne gördüğünü /tools sayfasında test edin",
  "journey.lane4.watcher.who": "Web sitesi",
  "journey.lane4.watcher.sees": "Düğümün IP'si ve tarayıcınızın kendi parmak izi",

  /* ── Step 1: your device ─────────────────────────────────────────────── */
  "schema-device.title": "Doppler bağlandığında cihazınızdan ne çıkıyor",
  "schema-device.link1": "1 · oturum aç",
  "schema-device.link2": "2 · bağlan",
  "schema-device.lane1.title": "Cihazınız",
  "schema-device.lane1.node1.label": "Doppler uygulaması",
  "schema-device.lane1.node1.detail": "İlk açılışta rastgele bir VPN-XXXX-XXXX-XXXX kimliği üretiyor",
  "schema-device.lane1.node2.label": "Kayıt formu yok",
  "schema-device.lane1.node2.detail": "E-posta, telefon veya parola yok",
  "schema-device.lane1.watcher.who": "Wi-Fi sahibi, sağlayıcı",
  "schema-device.lane1.watcher.sees": "API'mize bir HTTPS çağrısı, sonra tek bir TLS oturumu",
  "schema-device.lane2.title": "Doppler API",
  "schema-device.lane2.node1.label": "Oturum açma kaydı",
  "schema-device.lane2.node1.detail": "IP, hesap kimliği, cihaz kimliği, zaman. 90 güne kadar tutuluyor",
  "schema-device.lane2.node2.label": "Sunucu ayarları",
  "schema-device.lane2.node2.detail": "Kimlik doğrulamalı bir API üzerinden iletiliyor",
  "schema-device.lane3.title": "Tünel",
  "schema-device.lane3.node1.label": "VLESS-Reality açılıyor",
  "schema-device.lane3.node1.detail": "DNS ve site adları artık içinden geçiyor",
  "schema-device.lane3.watcher.who": "Wi-Fi sahibi, sağlayıcı",
  "schema-device.lane3.watcher.sees": "Alan adı yok, site adı yok, sayfa yok",

  "fingerprint-uniqueness.title": "Benzersiz parmak izine sahip tarayıcıların oranı",
  "fingerprint-uniqueness.note": "Panopticlick 2010'da yaklaşık 470,000 tarayıcı örnekledi. AmIUnique 2016'da 118,934 tarayıcı örnekledi.",
  "fingerprint-uniqueness.bar1": "Panopticlick, tüm tarayıcılar (2010)",
  "fingerprint-uniqueness.bar2": "Panopticlick, Flash veya Java ile (2010)",
  "fingerprint-uniqueness.bar3": "AmIUnique (2016)",

  "dbir-2026.title": "Veri ihlallerinde ne çıkıyor (doğrulanmış ihlallerdeki pay)",
  "dbir-2026.note": "145 ülkede 22,000'den fazla doğrulanmış ihlal. Kategoriler örtüştüğü için toplamları 100% etmiyor.",
  "dbir-2026.bar1": "İşin içinde insan unsuru var",
  "dbir-2026.bar2": "Fidye yazılımı",
  "dbir-2026.bar3": "İşin içinde üçüncü taraf var",
  "dbir-2026.bar4": "Yazılım açığından giriş",
  "dbir-2026.bar5": "Çalınan veriler arasında kimlik bilgileri",

  /* ── Step 2: the VLESS-Reality tunnel ────────────────────────────────── */
  "schema-reality.title": "Bir Reality bağlantısı nereye gidiyor ve her taraf ne görüyor",
  "schema-reality.link1": "TLS 1.3",
  "schema-reality.link2": "belirteç kontrolü",
  "schema-reality.lane1.title": "İstemci",
  "schema-reality.lane1.node1.label": "Doppler uygulaması",
  "schema-reality.lane1.node1.detail": "El sıkışma gerçek bir siteyi adlandırıyor ve gizli bir x25519 belirteci taşıyor",
  "schema-reality.lane1.node2.label": "Başka herkes",
  "schema-reality.lane1.node2.detail": "Sansürcünün sondası, tarayıcı robotu, web tarayıcısı",
  "schema-reality.lane2.title": "Ağ",
  "schema-reality.lane2.node1.label": "DPI kutusu",
  "schema-reality.lane2.node1.detail": "GFW, TSPU veya bir sağlayıcı filtresi",
  "schema-reality.lane2.watcher.who": "Sansürcü",
  "schema-reality.lane2.watcher.sees": "Popüler bir web sitesine normal bir TLS 1.3 ziyareti",
  "schema-reality.lane3.title": "Reality sunucusu",
  "schema-reality.lane3.node1.label": "Geçerli belirteç",
  "schema-reality.lane3.node1.detail": "Tünel açılıyor, VLESS trafiği uç düğüme akıyor",
  "schema-reality.lane3.node2.label": "Belirteç yok",
  "schema-reality.lane3.node2.detail": "Gerçek siteye ve onun hakiki sertifikasına aktarılıyor",

  "detection-rates.title": "Araştırmacılar gizlenmiş trafiği ne sıklıkta yakaladı",
  "detection-rates.note": "Gerçek ağlarda üç çalışma. Her rakam çalışmanın bildirdiği alt sınır, yani gerçek oranlar bunlara eşit veya bunlardan yüksek.",
  "detection-rates.bar1": "Tespit edilen OpenVPN akışları",
  "detection-rates.bar2": "Yakalanan \"gizlenmiş\" VPN kurulumları (41'de 34)",
  "detection-rates.bar3": "TLS içinde TLS desenleriyle yakalanan gizlenmiş proxy'ler",

  "protocol-timeline.title": "Yirmi yıllık kedi fare oyunu",
  "protocol-timeline.e1.year": "2002",
  "protocol-timeline.e1.title": "Tor yayına giriyor",
  "protocol-timeline.e1.body": "Soğan yönlendirme herkese açılıyor. Trafiğini tanımak kolay; bu da ilerleyen yıllarda gizlenmiş \"takılabilir taşıyıcıların\" icadını zorunlu kılıyor.",
  "protocol-timeline.e2.year": "2012",
  "protocol-timeline.e2.title": "Shadowsocks",
  "protocol-timeline.e2.body": "Trafiği rastgele baytlara benzeyen hafif bir proxy. Çin'de hızla yayılıyor.",
  "protocol-timeline.e3.year": "2015",
  "protocol-timeline.e3.title": "V2Ray ile VMess, ve bir kapatma",
  "protocol-timeline.e3.body": "Project V eylülde başlıyor. Ağustosta Shadowsocks'un yazarı, polisin ziyaretinin ardından kodu silmişti.",
  "protocol-timeline.e4.year": "2019",
  "protocol-timeline.e4.title": "Aktif sondalama belgeleniyor",
  "protocol-timeline.e4.body": "Araştırmacılar, şüpheli Shadowsocks sunucularını yoklayan Çin IP'lerinden 51,000'den fazla sonda kaydediyor.",
  "protocol-timeline.e5.year": "Tem 2020",
  "protocol-timeline.e5.title": "VLESS öneriliyor",
  "protocol-timeline.e5.body": "Kendi şifrelemesi olmayan, TLS'in içinde taşınmak üzere düşünülmüş sadeleştirilmiş bir protokol.",
  "protocol-timeline.e6.year": "Kas 2020",
  "protocol-timeline.e6.title": "Xray-core",
  "protocol-timeline.e6.body": "XTLS projesi V2Ray'den ayrılıyor ve VLESS'in ana yuvası oluyor.",
  "protocol-timeline.e7.year": "Kas 2021",
  "protocol-timeline.e7.title": "Çin \"tamamen şifreli\" trafiği engelliyor",
  "protocol-timeline.e7.body": "Veri merkezi IP'lerine giden rastgele görünümlü bağlantılar, her biri 26% olasılıkla kesilmeye başlıyor.",
  "protocol-timeline.e8.year": "Eki 2022",
  "protocol-timeline.e8.title": "XTLS Vision",
  "protocol-timeline.e8.body": "Zaten şifreli olan web trafiğini ikinci kez şifrelemeyi bırakıyor ve TLS içine yerleşmiş TLS'in ele veren boyutlarını gizliyor.",
  "protocol-timeline.e9.year": "Mar 2023",
  "protocol-timeline.e9.title": "REALITY yayımlanıyor",
  "protocol-timeline.e9.body": "Xray-core 1.8.0. Alan adı veya sertifika gerekmiyor: sunucu gerçek bir web sitesinin TLS el sıkışmasını ödünç alıyor.",
  "protocol-timeline.e10.year": "Ağu 2023",
  "protocol-timeline.e10.title": "Rusya WireGuard ve OpenVPN'i filtreliyor",
  "protocol-timeline.e10.body": "Büyük mobil operatörlerdeki kullanıcılar iki protokolün de saniyeler içinde kesildiğini bildiriyor.",
  "protocol-timeline.e11.year": "Kas 2025",
  "protocol-timeline.e11.title": "Bir sonraki raunt",
  "protocol-timeline.e11.body": "Rusya'daki bazı ev internet sağlayıcılarının Reality bağlantılarını kestiği bildiriliyor. İşletenler yeni portlar ve taşıma katmanlarıyla karşılık veriyor.",

  /* ── Step 3: the edge node ───────────────────────────────────────────── */
  "schema-edge.title": "Bir Doppler uç düğümünün içi",
  "schema-edge.link1": "açılıyor",
  "schema-edge.link2": "düğümün IP'si",
  "schema-edge.lane1.title": "Tünel",
  "schema-edge.lane1.node1.label": "VLESS-Reality akışı",
  "schema-edge.lane1.node1.detail": "Cihazınızdan şifreli olarak geliyor",
  "schema-edge.lane2.title": "Uç düğüm",
  "schema-edge.lane2.node1.label": "Adres çevirisi",
  "schema-edge.lane2.node1.detail": "IP'niz düğümünkiyle değiştiriliyor",
  "schema-edge.lane2.node2.label": "DNS çözücü",
  "schema-edge.lane2.node2.detail": "Sorguları tünelin içinde yanıtlıyor",
  "schema-edge.lane2.node3.label": "Yazıya dökülmüyor",
  "schema-edge.lane2.node3.detail": "Siteler, DNS sorguları, bant genişliği, oturum süreleri",
  "schema-edge.lane3.title": "Açık internet",
  "schema-edge.lane3.node1.label": "Web sitesi",
  "schema-edge.lane3.node1.detail": "İsteği düğümden alıyor",
  "schema-edge.lane3.watcher.who": "Web sitesi",
  "schema-edge.lane3.watcher.sees": "Sizinkini değil, düğümün IP'sini. Tarayıcı parmak iziniz yine de ona ulaşıyor",

  "latency-distance.title": "Şehirler arası mesafeye karşı gidiş dönüş süresi",
  "latency-distance.note": "Noktalar: şehir çiftleri arasında ölçülen ortalama gidiş dönüş süresi (WonderNetwork, 24 Eylül 2026), yaklaşık büyük çember mesafesine göre yerleştirildi. Kesikli çizgi: fiberde 100 km başına yaklaşık 1 ms olan fiziksel alt sınır.",
  "latency-distance.xLabel": "Mesafe (km)",
  "latency-distance.yLabel": "Gidiş dönüş (ms)",
  "latency-distance.reference": "Fiberde ışık",
  "latency-distance.point1": "Londra'dan Frankfurt'a, 17 ms",
  "latency-distance.point2": "Londra'dan New York'a, 70 ms",
  "latency-distance.point3": "Frankfurt'tan Singapur'a, 157 ms",
  "latency-distance.point4": "Londra'dan Sydney'e, 266 ms",
};
