import type { ChartCopy } from "./en";

/** Simplified Chinese chart copy. Keys and their order match ./en.ts. */
export const zh: ChartCopy = {
  "figure.sourceLabel": "来源",

  "journey.title": "一条连接，从头到尾",
  "journey.link1": "加密",
  "journey.link2": "拆封",
  "journey.link3": "节点 IP",
  "journey.lane1.title": "1 · 你的设备",
  "journey.lane1.node1.label": "Doppler 应用",
  "journey.lane1.node1.detail": "随机账户 ID，不要邮箱",
  "journey.lane1.node2.label": "DNS 与网站名",
  "journey.lane1.node2.detail": "送进隧道，不给运营商",
  "journey.lane1.watcher.who": "Wi-Fi 主人、运营商",
  "journey.lane1.watcher.sees": "一次 TLS 1.3 会话，看着像在访问热门网站",
  "journey.lane2.title": "2 · VLESS-Reality 隧道",
  "journey.lane2.node1.label": "TLS 1.3 握手",
  "journey.lane2.node1.detail": "借自一个真实网站",
  "journey.lane2.node2.label": "探测",
  "journey.lane2.node2.detail": "被转发到那个真实网站",
  "journey.lane2.watcher.who": "审查方的 DPI",
  "journey.lane2.watcher.sees": "普通 HTTPS；探测只找到真实网站",
  "journey.lane3.title": "3 · Doppler 边缘节点",
  "journey.lane3.node1.label": "地址替换",
  "journey.lane3.node1.detail": "你的 IP 变成节点的 IP",
  "journey.lane3.node2.label": "DNS 解析",
  "journey.lane3.node2.detail": "查询从不记录",
  "journey.lane3.node3.label": "流量日志",
  "journey.lane3.node3.detail": "一条不留",
  "journey.lane4.title": "4 · 开放互联网",
  "journey.lane4.node1.label": "你要访问的网站",
  "journey.lane4.node1.detail": "到 /tools 测测它看到什么",
  "journey.lane4.watcher.who": "网站",
  "journey.lane4.watcher.sees": "节点的 IP，以及你浏览器自己的指纹",

  "schema-device.title": "连接 Doppler 时，什么会离开你的设备",
  "schema-device.link1": "1 · 认证",
  "schema-device.link2": "2 · 连接",
  "schema-device.lane1.title": "你的设备",
  "schema-device.lane1.node1.label": "Doppler 应用",
  "schema-device.lane1.node1.detail": "首次启动生成随机的 VPN-XXXX-XXXX-XXXX ID",
  "schema-device.lane1.node2.label": "没有注册表单",
  "schema-device.lane1.node2.detail": "不要邮箱、手机号或密码",
  "schema-device.lane1.watcher.who": "Wi-Fi 主人、运营商",
  "schema-device.lane1.watcher.sees": "一次到我们 API 的 HTTPS 请求，然后一次 TLS 会话",
  "schema-device.lane2.title": "Doppler API",
  "schema-device.lane2.node1.label": "认证记录",
  "schema-device.lane2.node1.detail": "IP、账户 ID、设备 ID、时间。最长保留 90 天",
  "schema-device.lane2.node2.label": "服务器配置",
  "schema-device.lane2.node2.detail": "经认证的 API 下发",
  "schema-device.lane3.title": "隧道",
  "schema-device.lane3.node1.label": "VLESS-Reality 打开",
  "schema-device.lane3.node1.detail": "DNS 与网站名从此走在里面",
  "schema-device.lane3.watcher.who": "Wi-Fi 主人、运营商",
  "schema-device.lane3.watcher.sees": "看不到域名，看不到网站名，也看不到页面",

  "fingerprint-uniqueness.title": "指纹独一无二的浏览器占比",
  "fingerprint-uniqueness.note": "Panopticlick 在 2010 年采样约 470,000 个浏览器。AmIUnique 在 2016 年采样 118,934 个。",
  "fingerprint-uniqueness.bar1": "Panopticlick，全部浏览器（2010）",
  "fingerprint-uniqueness.bar2": "Panopticlick，装有 Flash 或 Java（2010）",
  "fingerprint-uniqueness.bar3": "AmIUnique（2016）",

  "dbir-2026.title": "数据泄露里都有什么（占已确认泄露的比例）",
  "dbir-2026.note": "覆盖 145 个国家的 22,000 多起已确认泄露。各类别有重叠，因此总和不为 100%。",
  "dbir-2026.bar1": "有人为因素参与",
  "dbir-2026.bar2": "勒索软件",
  "dbir-2026.bar3": "有第三方牵涉其中",
  "dbir-2026.bar4": "从软件漏洞入侵",
  "dbir-2026.bar5": "被窃数据中含登录凭据",

  "schema-reality.title": "一条 Reality 连接去了哪里，各方分别看到什么",
  "schema-reality.link1": "TLS 1.3",
  "schema-reality.link2": "凭证校验",
  "schema-reality.lane1.title": "客户端",
  "schema-reality.lane1.node1.label": "Doppler 应用",
  "schema-reality.lane1.node1.detail": "握手写着真实网站名，并携带隐藏的 x25519 凭证",
  "schema-reality.lane1.node2.label": "其他任何人",
  "schema-reality.lane1.node2.detail": "审查方探测、扫描器、浏览器",
  "schema-reality.lane2.title": "网络",
  "schema-reality.lane2.node1.label": "DPI 设备",
  "schema-reality.lane2.node1.detail": "GFW、TSPU 或运营商的过滤器",
  "schema-reality.lane2.watcher.who": "审查方",
  "schema-reality.lane2.watcher.sees": "一次访问热门网站的普通 TLS 1.3",
  "schema-reality.lane3.title": "Reality 服务器",
  "schema-reality.lane3.node1.label": "凭证有效",
  "schema-reality.lane3.node1.detail": "隧道打开，VLESS 流量流向边缘节点",
  "schema-reality.lane3.node2.label": "没有凭证",
  "schema-reality.lane3.node2.detail": "转发到真实网站，看到它真实的证书",

  "detection-rates.title": "研究者抓住伪装流量的比例",
  "detection-rates.note": "三项在真实网络上完成的研究。每个数字都是研究给出的下限，真实比例只会更高。",
  "detection-rates.bar1": "被识别出的 OpenVPN 连接",
  "detection-rates.bar2": "被抓住的“混淆”VPN 方案（41 种里的 34 种）",
  "detection-rates.bar3": "被 TLS 套 TLS 特征抓住的混淆代理",

  "protocol-timeline.title": "二十年的猫鼠游戏",
  "protocol-timeline.e1.year": "2002",
  "protocol-timeline.e1.title": "Tor 上线",
  "protocol-timeline.e1.body": "洋葱路由向公众开放。它的流量很容易认出来，这后来逼出了伪装用的“可插拔传输”。",
  "protocol-timeline.e2.year": "2012",
  "protocol-timeline.e2.title": "Shadowsocks",
  "protocol-timeline.e2.body": "一个轻量级代理，流量看上去像随机字节。它在中国迅速流行。",
  "protocol-timeline.e3.year": "2015",
  "protocol-timeline.e3.title": "V2Ray 与 VMess，以及一次删库",
  "protocol-timeline.e3.body": "Project V 在 9 月启动。8 月，Shadowsocks 作者在警方上门后删除了代码。",
  "protocol-timeline.e4.year": "2019",
  "protocol-timeline.e4.title": "主动探测被记录在案",
  "protocol-timeline.e4.body": "研究人员记录到来自中国 IP 的 51,000 多次探测，用来试探疑似 Shadowsocks 的服务器。",
  "protocol-timeline.e5.year": "2020年7月",
  "protocol-timeline.e5.title": "VLESS 提出",
  "protocol-timeline.e5.body": "一个极简协议，自身不做加密，设计上就是要跑在 TLS 里面。",
  "protocol-timeline.e6.year": "2020年11月",
  "protocol-timeline.e6.title": "Xray-core",
  "protocol-timeline.e6.body": "XTLS 项目从 V2Ray 分叉，成为 VLESS 的主要落脚处。",
  "protocol-timeline.e7.year": "2021年11月",
  "protocol-timeline.e7.title": "中国封锁“全加密”流量",
  "protocol-timeline.e7.body": "指向数据中心 IP 的随机样连接，开始以每次 26% 的概率被切断。",
  "protocol-timeline.e8.year": "2022年10月",
  "protocol-timeline.e8.title": "XTLS Vision",
  "protocol-timeline.e8.body": "不再对已加密的网页流量做二次加密，并隐藏 TLS 套 TLS 的长度特征。",
  "protocol-timeline.e9.year": "2023年3月",
  "protocol-timeline.e9.title": "REALITY 发布",
  "protocol-timeline.e9.body": "Xray-core 1.8.0。无需域名和证书：服务器借用真实网站的 TLS 握手。",
  "protocol-timeline.e10.year": "2023年8月",
  "protocol-timeline.e10.title": "俄罗斯过滤 WireGuard 和 OpenVPN",
  "protocol-timeline.e10.body": "主要移动运营商的用户报告，两种协议都在几秒之内被切断。",
  "protocol-timeline.e11.year": "2025年11月",
  "protocol-timeline.e11.title": "新的一轮",
  "protocol-timeline.e11.body": "有报告称俄罗斯部分家庭宽带运营商开始切断 Reality 连接。运营方以新端口和新传输方式应对。",

  "schema-edge.title": "Doppler 边缘节点内部",
  "schema-edge.link1": "拆封",
  "schema-edge.link2": "节点 IP",
  "schema-edge.lane1.title": "隧道",
  "schema-edge.lane1.node1.label": "VLESS-Reality 流",
  "schema-edge.lane1.node1.detail": "从你的设备加密抵达",
  "schema-edge.lane2.title": "边缘节点",
  "schema-edge.lane2.node1.label": "地址转换",
  "schema-edge.lane2.node1.detail": "你的 IP 被换成节点的 IP",
  "schema-edge.lane2.node2.label": "DNS 解析",
  "schema-edge.lane2.node2.detail": "在隧道内部回答查询",
  "schema-edge.lane2.node3.label": "不写下来的东西",
  "schema-edge.lane2.node3.detail": "网站、DNS 查询、流量用量、会话时长",
  "schema-edge.lane3.title": "开放互联网",
  "schema-edge.lane3.node1.label": "网站",
  "schema-edge.lane3.node1.detail": "从节点收到请求",
  "schema-edge.lane3.watcher.who": "网站",
  "schema-edge.lane3.watcher.sees": "节点的 IP，不是你的。你的浏览器指纹仍会到达它",

  "latency-distance.title": "城市之间的往返时延与距离",
  "latency-distance.note": "圆点：城市对之间的实测平均往返时延（WonderNetwork，2026 年 9 月 24 日），按大圆距离的近似值绘制。虚线：光纤中每 100 km 约 1 ms 的物理下限。",
  "latency-distance.xLabel": "距离（km）",
  "latency-distance.yLabel": "往返（ms）",
  "latency-distance.reference": "光纤中的光",
  "latency-distance.point1": "伦敦至法兰克福，17 ms",
  "latency-distance.point2": "伦敦至纽约，70 ms",
  "latency-distance.point3": "法兰克福至新加坡，157 ms",
  "latency-distance.point4": "伦敦至悉尼，266 ms",
};
