#!/usr/bin/env python3
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from pack_rows import L, save

save("tr", L({
"u": "Son güncelleme: 28 Eylül 2026",
"rt": "İadeler",
"ri": "Bu politika, SIMNETIQ LTD (şirket numarası 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom tarafından satılan Doppler VPN satın alımlarını kapsar. Web sitesi erişimi tek seferlik bir ödemedir. App Store ve Google Play planları, mağazada iptal edilene kadar yenilenir.",
"ai": "Apple iade talimatları", "ar": "Apple'a sorun bildir", "gi": "Google Play iade politikası",
"e1t": "1. AB/AEA iptali (14 gün)",
"e1": "Avrupa Birliği veya AEA'da tüketicisi iseniz, gerekçe göstermeden 14 gün içinde iptal edebilirsiniz. 14 gün bitmeden support@simnetiq.com adresine yazın. Ödediğiniz tutarı iade ederiz ve ödeme işlemcisi ücretini düşmeyiz. Kullanılmış hizmet için kesinti otomatik değildir. App Store veya Google Play satın alımları ilgili mağazadan talep edilir.",
"e2t": "2. Birleşik Krallık iptali (14 gün)",
"e2": "Birleşik Krallık'ta tüketicisi iseniz, Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 kapsamında 14 günlük iptal hakkınız vardır. support@simnetiq.com adresine açık bir bildirim gönderin. Ödediğiniz tutarı iade ederiz ve işlemci ücretini düşmeyiz. Kullanılmış hizmet için kesinti otomatik değildir ve tek bir bağlantı tek başına ret gerekçesi değildir.",
"e3t": "3. 30 günlük iyi niyet iadesi",
"e3": "AB/AEA ve Birleşik Krallık dışındaki müşteriler için yayımlanan iyi niyet iadesi, ilk satın alımdan itibaren 30 gündür ve müşteri başına bir kezdir. Yasa aksini gerektirmediği sürece promosyonlu veya indirimli satın alımlar hariçtir. İade verildiğinde ödenen tutar içindir. Account ID ve sipariş referansınızla support@simnetiq.com adresine yazın.",
"e4t": "4. Web sitesi kart ödemeleri",
"e4": "Web sitesindeki kart ödemeleri, bu sayfadaki Apple Pay ve Google Pay dahil, Revolut tarafından işlenir. Bunlar App Store veya Google Play satın alımı değildir. Account ID ve sipariş referansınızla support@simnetiq.com adresine yazın. Kart numarasını göndermeyin. Bu politika işlemci ücretini düşmez. Kredinin ne zaman görüneceğine bankanız karar verir.",
"e5t": "5. Kripto ödemeleri (OxaPay)",
"e5": "Web sitesindeki kripto ödemeleri OxaPay tarafından işlenir. Account ID, fatura referansı, coin ve ağ bilginizle support@simnetiq.com adresine yazın. Gönderen adresi tahmin etmeyiz. Kullanılacak cüzdan adresini siz verin. İade göndermeden önce varlık, ağ ve tutarı onaylarız. Bu politika ağ ücretlerini veya fiyat değişimini kesinti olarak tutmaz.",
"e6t": "6. App Store",
"e6": "App Store iadelerine Apple karar verir. Onay veya gün sayısı vaat etmeyiz. Aşağıdaki bağlantıları kullanın. Account ID bulma yardımı için: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Google Play iadelerine Google karar verir. Uygunluk ürüne, ödemenin ne kadar önce yapıldığına, ülkeye ve nedene bağlıdır. Yayımlanmış bir süreyi genel ret haline getirmeyiz ve onay vaat etmeyiz. Aşağıdaki bağlantıyı kullanın.",
"e8t": "8. Yenilemeler",
"e8": "Web sitesi satın alımı seçtiğiniz dönemi kapsar. Otomatik yenilenmez ve iade edilecek bir yenileme ücreti yoktur. App Store veya Google Play planı, dönem bitmeden en az 24 saat önce mağazada iptal edilene kadar yenilenir. İstenmeyen bir yenileme alındıysa 14 gün içinde bize yazın; mağazaya başvurmanıza yardımcı oluruz. Kararı mağaza verir.",
"e9t": "9. İstisnalar",
"e9": "İyi niyet iadesi, talep gecikmişse, hesap Koşulları ihlali nedeniyle kapatılmışsa, aynı müşteri yeniden talep ediyorsa veya satın alım promosyonlu ya da indirimliyse reddedilebilir. Bunlar yasal hakları kaldırmaz. Ödeme işlemcisi ücreti, iadeyi reddetme veya azaltma gerekçesi değildir.",
"e10t": "10. Nasıl talep edilir",
"e10": "Account ID, ödeme yerini (web kartı, kripto, App Store veya Google Play), sipariş veya fatura referansını ve tarihi gönderin. Neden isteğe bağlıdır. E-posta: support@simnetiq.com. Kart numarası, cüzdan seed'i veya özel anahtar göndermeyin. Web sitesi taleplerini 2 iş günü içinde onaylamayı hedefleriz.",
"e11t": "11. İletişim",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-posta: support@simnetiq.com. AB tüketicileri Avrupa Komisyonu ODR platformunu da kullanabilir: https://ec.europa.eu/consumers/odr.",
"at": "Account ID ve kurtarma",
"ai2": "Doppler hesabı anonim bir Account ID'dir. E-posta girişi değildir ve uygulama dili yaşadığınız ülke değildir.",
"w1t": "Account ID nedir",
"w1": "ID, VPN-XXXX-XXXX-XXXX biçimindedir. Uygulama ilk açılışta oluşturur. Site ödeme sırasında da oluşturabilir. Profil veya Ayarlar altında Hesap bölümündedir. Her cihazda aynı ID'yi kullanın ve gizli tutun. Destek kart numarası istemez.",
"w2t": "Kaybederseniz",
"w2": "E-posta bağladıysanız Destek'i açıp Hesabı geri yükle'yi seçin. ID'yi o e-postaya göndeririz. Hiçbir şey bağlamadıysanız destek talebi açın. Yapıştırılan bir ID tek başına hesabın size ait olduğunu kanıtlamaz.",
"w3t": "Dil ikamet değildir",
"w3": "Rusça veya başka herhangi bir dil, hangi ülkede yaşadığınızı veya bir yaptırım kuralının sizi kapsayıp kapsamadığını göstermez.",
"w4t": "Hesap silme",
"w4": "Uygulamada veya hesap silme sayfasında hesabı silmek tüm Doppler hesabını siler. Yalnızca bir destek iletişimini silmez. Ücretli erişimin önce bitmesi veya iptal edilmesi gerekir. Yalnızca destek iletişimini kaldırmak için ayrı bir genel sayfa yoktur.",
"bt": "Web sitesi erişimi ve mağaza abonelikleri",
"bi": "Ödemeyi nerede yaptığınız, erişimin yenilenip yenilenmeyeceğini ve kimin iade edebileceğini belirler.",
"b1t": "Tek seferlik web sitesi erişimi",
"b1": "Site, seçtiğiniz dönem için bir kez ücret alır: bir ay, 6 ay veya bir yıl. Otomatik yenilenmez ve sonraki bir ücret için kart saklamaz. Kart ödemeleri Revolut, kripto OxaPay üzerinden yapılır. Windows uygulaması ve Android APK siteden satın alınır.",
"b2t": "Sitede Apple Pay ve Google Pay",
"b2": "Sitedeki Apple Pay ve Google Pay, kart ödeme sayfasındaki cüzdanlardır. App Store veya Google Play aboneliği değildir.",
"b3t": "App Store ve Google Play",
"b3": "Bu mağazalar otomatik yenilenen abonelik satar. Yeni mağaza müşterileri 3 günlük deneme alır. Yenilemeden en az 24 saat önce mağazada iptal edin. Bir mağaza aboneliği Pro'yu aynı anda bir Account ID'ye bağlar.",
"b4t": "Ne satmıyoruz",
"b4": "Telegram Stars satın alımı, Microsoft Store satın alımı veya bakiye yükleme yoktur. Windows uygulaması doğrudan yükleyicidir.",
"ct": "Geri yükle, iptal et veya iade et",
"ci": "Geri yükleme, iptal ve iade farklı işlemlerdir.",
"c1t": "Geri yükleme",
"c1": "Geri yükleme, zaten ödediğiniz erişimi bir Account ID'ye koyar. App Store veya Google Play uygulamasında Profil, Abonelik, ardından Satın Alımları Geri Yükle'yi açın. Farklı bir Account ID'de geri yüklemek Pro'yu o hesaba taşır. Site satın alımı, ödemede kullanılan Account ID ile giriş yapıldığında görünür. Görünmezse uygulamayı yeniden başlatın. APK'de Satın Alımları Geri Yükle düğmesi yoktur.",
"c2t": "İptal",
"c2": "İptal, sonraki mağaza yenilemesini durdurur. Tek başına para iade etmez. iPhone'da: Ayarlar, adınız, Abonelikler, Doppler VPN, İptal. Android'de: Play Store, profil, Ödemeler ve abonelikler, Abonelikler, İptal. Site satın alımı yenilenmez, bu yüzden iptal edilecek bir şey yoktur.",
"c3t": "İade",
"c3": "İade, paranın geri istenmesidir. İade Politikası web kartı, kripto, App Store ve Google Play adımlarını açıklar. Kart numarası göndermeyin.",
"gt": "Rehberler", "g1": "Account ID ve kurtarma", "g2": "Web sitesi erişimi ve mağaza abonelikleri", "g3": "Geri yükle, iptal et veya iade et", "g4": "İadeler",
"faq": "AB/AEA ve Birleşik Krallık müşterilerinin 14 günlük iptal hakkı vardır. Diğer müşteriler için yayımlanan iyi niyet iadesi yalnızca ilk satın alımda 30 gündür; promosyon ve indirimler hariçtir. App Store iadelerini Apple, Google Play iadelerini Google yönetir. Web kartı veya kripto için Account ID ve sipariş referansınızı destekle paylaşın. Kart numarası göndermeyin.",
"home": "AB/AEA ve Birleşik Krallık müşterilerinin 14 günlük iptal hakkı vardır. Diğer müşteriler için yayımlanan iyi niyet iadesi yalnızca ilk satın alımda 30 gündür; promosyon ve indirimler hariçtir. Web kartı ve kripto: Account ID ile support@simnetiq.com adresine yazın. Kart numarası göndermeyin. App Store ve Google Play iadeleri mağazadan talep edilir. Bu sitedeki İade Politikasına bakın.",
"guar": "AB/AEA ve Birleşik Krallık müşterilerinin 14 günlük iptal hakkı vardır. Diğer müşteriler için yayımlanan iyi niyet iadesi yalnızca ilk satın alımda 30 gündür; promosyon ve indirimler hariçtir. Web ödeme tek seferliktir ve otomatik yenilenmez. App Store ve Google Play planları iptal edilene kadar yenilenir.",
"foot": "Kart (Revolut) veya kripto (OxaPay) ile güvenli ödeme. Web ödeme tek seferliktir ve otomatik yenilenmez.",
"sub": "Kart (Revolut) veya kripto (OxaPay) ile tek seferlik ödeme. Otomatik yenileme yok. AB/AEA ve Birleşik Krallık müşterilerinin 14 günlük iptal hakkı vardır. Başka yerlerde yayımlanan iyi niyet iadesi yalnızca ilk satın alımda 30 gündür.",
"eb": "AB/AEA ve Birleşik Krallık'ta 14 günlük iptal hakkı. Diğer müşteriler için ilk satın alımda 30 günlük iyi niyet iadesi.",
"er": "Doppler VPN size uymuyorsa bu e-postayı yanıtlayın veya sipariş numarası ve Account ID ile {email} adresine yazın. Kart numarası göndermeyin. Web sitesi iadesi ödediğiniz tutar içindir.",
"pt": "Destek iletişimi ve hesap silme",
"pc": "Kurtarma veya destek için e-posta ya da Telegram bağlamak hesap silmek değildir. Hesap silme sayfası Doppler hesabını siler. Yalnızca bir destek iletişimini kaldırmaz. Ödeme kayıtları yasa gerektirdiğinde saklanabilir. Yalnızca destek iletişimini kaldırmak için ayrı bir genel sayfa yoktur.",
}))

save("id", L({
"u": "Terakhir diperbarui: 28 September 2026",
"rt": "Pengembalian dana",
"ri": "Kebijakan ini mencakup pembelian Doppler VPN dari SIMNETIQ LTD (nomor perusahaan 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Akses situs web adalah pembayaran satu kali. Paket App Store dan Google Play diperpanjang sampai Anda membatalkannya di toko.",
"ai": "Petunjuk pengembalian dana Apple", "ar": "Laporkan masalah ke Apple", "gi": "Kebijakan pengembalian dana Google Play",
"e1t": "1. Pembatalan UE/EEA (14 hari)",
"e1": "Jika Anda konsumen di Uni Eropa atau EEA, Anda dapat membatalkan dalam 14 hari tanpa memberi alasan. Email support@simnetiq.com sebelum 14 hari berakhir. Kami mengembalikan jumlah yang Anda bayar dan tidak memotong biaya prosesor pembayaran. Potongan untuk layanan yang sudah digunakan tidak otomatis. Pembelian App Store atau Google Play diajukan di toko tersebut.",
"e2t": "2. Pembatalan Inggris (14 hari)",
"e2": "Jika Anda konsumen di United Kingdom, Anda punya hak pembatalan 14 hari berdasarkan Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Kirim pernyataan jelas ke support@simnetiq.com. Kami mengembalikan jumlah yang Anda bayar dan tidak memotong biaya prosesor. Potongan untuk layanan yang sudah digunakan tidak otomatis, dan satu koneksi saja bukan alasan penolakan.",
"e3t": "3. Pengembalian dana goodwill 30 hari",
"e3": "Untuk pelanggan di luar UE/EEA dan UK, pengembalian dana goodwill yang dipublikasikan adalah 30 hari sejak pembelian pertama, sekali per pelanggan. Pembelian promo atau diskon dikecualikan kecuali hukum mengharuskan sebaliknya. Jika diberikan, pengembalian adalah untuk jumlah yang dibayar. Email support@simnetiq.com dengan Account ID dan referensi pesanan.",
"e4t": "4. Pembayaran kartu di situs",
"e4": "Pembayaran kartu di situs, termasuk Apple Pay dan Google Pay di halaman itu, diproses oleh Revolut. Itu bukan pembelian App Store atau Google Play. Email support@simnetiq.com dengan Account ID dan referensi pesanan. Jangan kirim nomor kartu. Kebijakan ini tidak memotong biaya prosesor. Bank Anda memutuskan kapan kredit muncul.",
"e5t": "5. Pembayaran kripto (OxaPay)",
"e5": "Pembayaran kripto di situs diproses oleh OxaPay. Email support@simnetiq.com dengan Account ID, referensi invoice, koin, dan jaringan. Kami tidak menebak alamat pengirim. Berikan alamat dompet. Kami mengonfirmasi aset, jaringan, dan jumlah sebelum mengirim pengembalian. Kebijakan ini tidak menahan biaya jaringan atau perubahan harga.",
"e6t": "6. App Store",
"e6": "Apple yang memutuskan pengembalian dana App Store. Kami tidak menjanjikan persetujuan atau jumlah hari. Gunakan tautan di bawah. Bantuan Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Google yang memutuskan pengembalian dana Google Play. Kelayakan bergantung pada produk, berapa lama sejak pembayaran, negara, dan alasan. Kami tidak mengubah satu jendela waktu yang dipublikasikan menjadi penolakan umum, dan tidak menjanjikan persetujuan. Gunakan tautan di bawah.",
"e8t": "8. Perpanjangan",
"e8": "Pembelian di situs mencakup periode yang Anda pilih. Tidak diperpanjang otomatis, dan tidak ada biaya perpanjangan untuk dikembalikan. Paket App Store atau Google Play diperpanjang sampai Anda membatalkannya di toko, setidaknya 24 jam sebelum periode berakhir. Jika toko menagih perpanjangan yang tidak diinginkan, hubungi kami dalam 14 hari dan kami bantu mengajukan ke toko. Toko yang memutuskan.",
"e9t": "9. Pengecualian",
"e9": "Pengembalian goodwill dapat ditolak jika permintaan terlambat, akun ditutup karena melanggar Ketentuan, pelanggan yang sama meminta lagi, atau pembelian bersifat promo atau diskon. Ini tidak menghapus hak hukum. Biaya prosesor pembayaran bukan alasan menolak atau mengurangi pengembalian.",
"e10t": "10. Cara mengajukan",
"e10": "Kirim Account ID, tempat Anda membayar (kartu situs, kripto, App Store, atau Google Play), referensi pesanan atau invoice, dan tanggal. Alasan bersifat opsional. Email: support@simnetiq.com. Jangan kirim nomor kartu, seed dompet, atau kunci privat. Kami berusaha mengakui permintaan situs dalam 2 hari kerja.",
"e11t": "11. Kontak",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Email: support@simnetiq.com. Konsumen UE juga dapat memakai platform ODR Komisi Eropa: https://ec.europa.eu/consumers/odr.",
"at": "Account ID dan pemulihan",
"ai2": "Akun Doppler adalah Account ID anonim. Bukan login email, dan bahasa aplikasi bukan negara tempat Anda tinggal.",
"w1t": "Apa itu Account ID",
"w1": "ID berbentuk VPN-XXXX-XXXX-XXXX. Aplikasi membuatnya saat pertama dibuka. Situs juga dapat membuatnya saat checkout. Ada di Profil atau Pengaturan, lalu Akun. Gunakan ID yang sama di setiap perangkat dan jaga kerahasiaannya. Dukungan tidak meminta nomor kartu.",
"w2t": "Jika Anda kehilangannya",
"w2": "Jika Anda menautkan email, buka Dukungan dan pilih Pulihkan akun. Kami mengirim ID ke email itu. Jika tidak menautkan apa pun, buka permintaan dukungan. Menempelkan ID saja tidak membuktikan bahwa akun itu milik Anda.",
"w3t": "Bahasa bukan tempat tinggal",
"w3": "Bahasa Rusia, atau bahasa lain apa pun, tidak memberi tahu kami negara tempat Anda tinggal atau apakah aturan sanksi berlaku untuk Anda.",
"w4t": "Menghapus akun",
"w4": "Menghapus akun di aplikasi atau di halaman hapus-akun menghapus seluruh akun Doppler. Itu tidak hanya menghapus kontak dukungan. Akses berbayar harus berakhir atau dibatalkan terlebih dahulu. Belum ada halaman publik terpisah untuk hanya menghapus kontak dukungan.",
"bt": "Akses situs dan langganan toko",
"bi": "Tempat Anda membayar menentukan apakah akses diperpanjang dan siapa yang dapat mengembalikan dana.",
"b1t": "Akses situs satu kali",
"b1": "Situs menagih sekali untuk periode yang Anda pilih: sebulan, 6 bulan, atau setahun. Tidak diperpanjang otomatis dan tidak menyimpan kartu untuk tagihan nanti. Kartu lewat Revolut, kripto lewat OxaPay. Aplikasi Windows dan APK Android dibeli di situs.",
"b2t": "Apple Pay dan Google Pay di situs",
"b2": "Apple Pay dan Google Pay di situs adalah dompet pada checkout kartu. Bukan langganan App Store atau Google Play.",
"b3t": "App Store dan Google Play",
"b3": "Toko tersebut menjual langganan yang diperpanjang otomatis. Pelanggan toko baru mendapat uji coba 3 hari. Batalkan di toko setidaknya 24 jam sebelum perpanjangan. Satu langganan toko menempelkan Pro ke satu Account ID pada satu waktu.",
"b4t": "Apa yang tidak kami jual",
"b4": "Tidak ada pembelian Telegram Stars, pembelian Microsoft Store, atau isi ulang saldo. Aplikasi Windows adalah penginstal langsung.",
"ct": "Pulihkan, batalkan, atau kembalikan dana",
"ci": "Pulihkan, batalkan, dan pengembalian dana adalah tindakan berbeda.",
"c1t": "Pulihkan",
"c1": "Pulihkan menempatkan akses yang sudah dibayar ke Account ID. Di aplikasi App Store atau Google Play, buka Profil, Langganan, lalu Pulihkan Pembelian. Memulihkan di Account ID lain memindahkan Pro ke akun itu. Pembelian situs muncul saat aplikasi masuk dengan Account ID yang dipakai di checkout. Mulai ulang aplikasi jika belum muncul. APK tidak punya tombol Pulihkan Pembelian.",
"c2t": "Batalkan",
"c2": "Membatalkan menghentikan perpanjangan toko berikutnya. Itu sendiri tidak mengembalikan uang. Di iPhone: Pengaturan, nama Anda, Langganan, Doppler VPN, Batalkan. Di Android: Play Store, profil, Pembayaran dan langganan, Langganan, Batalkan. Pembelian situs tidak diperpanjang, jadi tidak ada yang perlu dibatalkan.",
"c3t": "Pengembalian dana",
"c3": "Pengembalian dana meminta uang kembali. Kebijakan Pengembalian Dana menjelaskan langkah untuk kartu situs, kripto, App Store, dan Google Play. Jangan kirim nomor kartu.",
"gt": "Panduan", "g1": "Account ID dan pemulihan", "g2": "Akses situs dan langganan toko", "g3": "Pulihkan, batalkan, atau kembalikan dana", "g4": "Pengembalian dana",
"faq": "Pelanggan UE/EEA dan UK punya hak pembatalan 14 hari. Untuk pelanggan lain, pengembalian goodwill yang dipublikasikan adalah 30 hari hanya pada pembelian pertama; promo dan diskon dikecualikan. Pengembalian App Store lewat Apple, Google Play lewat Google. Untuk kartu atau kripto situs, hubungi dukungan dengan Account ID dan referensi pesanan. Jangan kirim nomor kartu.",
"home": "Pelanggan UE/EEA dan UK punya hak pembatalan 14 hari. Untuk pelanggan lain, pengembalian goodwill yang dipublikasikan adalah 30 hari hanya pada pembelian pertama; promo dan diskon dikecualikan. Kartu dan kripto situs: email support@simnetiq.com dengan Account ID. Jangan kirim nomor kartu. Pengembalian App Store dan Google Play diajukan di toko. Lihat Kebijakan Pengembalian Dana di situs ini.",
"guar": "Pelanggan UE/EEA dan UK punya hak pembatalan 14 hari. Untuk pelanggan lain, pengembalian goodwill yang dipublikasikan adalah 30 hari hanya pada pembelian pertama; promo dan diskon dikecualikan. Checkout web adalah pembayaran satu kali dan tidak diperpanjang otomatis. Paket App Store dan Google Play diperpanjang sampai dibatalkan.",
"foot": "Pembayaran aman dengan kartu (Revolut) atau kripto (OxaPay). Checkout web adalah pembayaran satu kali dan tidak diperpanjang otomatis.",
"sub": "Pembayaran satu kali dengan kartu (Revolut) atau kripto (OxaPay). Tanpa perpanjangan otomatis. Pelanggan UE/EEA dan UK punya hak pembatalan 14 hari. Di tempat lain, pengembalian goodwill yang dipublikasikan adalah 30 hari hanya pada pembelian pertama.",
"eb": "Hak pembatalan 14 hari di UE/EEA dan UK. Pengembalian goodwill 30 hari pada pembelian pertama untuk pelanggan lain.",
"er": "Jika Doppler VPN tidak cocok untuk Anda, balas email ini atau hubungi {email} dengan ID pesanan dan Account ID. Jangan kirim nomor kartu. Pengembalian situs adalah untuk jumlah yang Anda bayar.",
"pt": "Kontak dukungan dan penghapusan akun",
"pc": "Menautkan email atau Telegram untuk pemulihan atau dukungan bukan sama dengan menghapus akun. Halaman hapus-akun menghapus akun Doppler. Itu tidak hanya menghapus kontak dukungan. Catatan pembayaran dapat disimpan jika hukum mengharuskannya. Tidak ada halaman publik terpisah untuk hanya menghapus kontak dukungan.",
}))

save("vi", L({
"u": "Cập nhật lần cuối: 28 tháng 9 năm 2026",
"rt": "Hoàn tiền",
"ri": "Chính sách này áp dụng cho các giao dịch mua Doppler VPN từ SIMNETIQ LTD (số công ty 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Truy cập qua trang web là thanh toán một lần. Gói App Store và Google Play gia hạn cho đến khi bạn hủy trong cửa hàng.",
"ai": "Hướng dẫn hoàn tiền của Apple", "ar": "Báo cáo sự cố với Apple", "gi": "Chính sách hoàn tiền Google Play",
"e1t": "1. Hủy trong EU/EEA (14 ngày)",
"e1": "Nếu bạn là người tiêu dùng tại Liên minh Châu Âu hoặc EEA, bạn có thể hủy trong 14 ngày mà không cần nêu lý do. Gửi email tới support@simnetiq.com trước khi hết 14 ngày. Chúng tôi hoàn số tiền bạn đã trả và không trừ phí bộ xử lý thanh toán. Khoản trừ cho dịch vụ đã dùng không tự động. Mua từ App Store hoặc Google Play thì yêu cầu tại cửa hàng đó.",
"e2t": "2. Hủy tại Vương quốc Anh (14 ngày)",
"e2": "Nếu bạn là người tiêu dùng tại United Kingdom, bạn có quyền hủy 14 ngày theo Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Gửi tuyên bố rõ ràng tới support@simnetiq.com. Chúng tôi hoàn số tiền đã trả và không trừ phí bộ xử lý. Khoản trừ cho dịch vụ đã dùng không tự động, và một lần kết nối không tự nó là lý do từ chối.",
"e3t": "3. Hoàn tiền thiện chí 30 ngày",
"e3": "Với khách hàng ngoài EU/EEA và UK, hoàn tiền thiện chí đã công bố là 30 ngày kể từ lần mua đầu tiên, một lần mỗi khách hàng. Mua khuyến mãi hoặc giảm giá bị loại trừ trừ khi luật yêu cầu khác. Khi được chấp thuận, hoàn cho số tiền đã trả. Gửi email support@simnetiq.com kèm Account ID và mã đơn hàng.",
"e4t": "4. Thanh toán thẻ trên trang web",
"e4": "Thanh toán thẻ trên trang web, gồm Apple Pay và Google Pay trên trang đó, được Revolut xử lý. Đó không phải mua App Store hoặc Google Play. Gửi email support@simnetiq.com kèm Account ID và mã đơn. Không gửi số thẻ. Chính sách này không trừ phí bộ xử lý. Ngân hàng của bạn quyết định khi nào khoản ghi có xuất hiện.",
"e5t": "5. Thanh toán crypto (OxaPay)",
"e5": "Thanh toán crypto trên trang web do OxaPay xử lý. Gửi email support@simnetiq.com kèm Account ID, mã hóa đơn, coin và mạng. Chúng tôi không đoán địa chỉ gửi. Bạn cung cấp địa chỉ ví. Chúng tôi xác nhận tài sản, mạng và số tiền trước khi gửi hoàn. Chính sách này không giữ phí mạng hoặc thay đổi giá.",
"e6t": "6. App Store",
"e6": "Apple quyết định hoàn tiền App Store. Chúng tôi không hứa phê duyệt hay số ngày. Dùng các liên kết bên dưới. Hỗ trợ tìm Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Google quyết định hoàn tiền Google Play. Điều kiện phụ thuộc sản phẩm, thời gian sau thanh toán, quốc gia và lý do. Chúng tôi không biến một khung thời gian đã công bố thành từ chối chung và không hứa phê duyệt. Dùng liên kết bên dưới.",
"e8t": "8. Gia hạn",
"e8": "Mua trên trang web bao gồm khoảng thời gian bạn chọn. Không tự gia hạn và không có phí gia hạn để hoàn. Gói App Store hoặc Google Play gia hạn cho đến khi bạn hủy trong cửa hàng, ít nhất 24 giờ trước khi kỳ kết thúc. Nếu cửa hàng tính phí gia hạn không mong muốn, liên hệ chúng tôi trong 14 ngày để được hỗ trợ yêu cầu cửa hàng. Cửa hàng quyết định.",
"e9t": "9. Ngoại lệ",
"e9": "Hoàn thiện chí có thể bị từ chối nếu yêu cầu muộn, tài khoản bị đóng vì vi phạm Điều khoản, cùng khách hàng yêu cầu lại, hoặc mua khuyến mãi/giảm giá. Điều này không loại bỏ quyền theo luật. Phí bộ xử lý thanh toán không phải lý do từ chối hoặc giảm hoàn tiền.",
"e10t": "10. Cách yêu cầu",
"e10": "Gửi Account ID, nơi bạn thanh toán (thẻ web, crypto, App Store hoặc Google Play), mã đơn hoặc hóa đơn và ngày. Lý do là tùy chọn. Email: support@simnetiq.com. Không gửi số thẻ, seed ví hoặc khóa riêng. Chúng tôi nhằm xác nhận yêu cầu từ web trong 2 ngày làm việc.",
"e11t": "11. Liên hệ",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Email: support@simnetiq.com. Người tiêu dùng EU cũng có thể dùng nền tảng ODR của Ủy ban Châu Âu: https://ec.europa.eu/consumers/odr.",
"at": "Account ID và khôi phục",
"ai2": "Tài khoản Doppler là Account ID ẩn danh. Không phải đăng nhập email, và ngôn ngữ ứng dụng không phải quốc gia bạn sống.",
"w1t": "Account ID là gì",
"w1": "ID dạng VPN-XXXX-XXXX-XXXX. Ứng dụng tạo khi mở lần đầu. Trang web cũng có thể tạo khi thanh toán. Tìm trong Hồ sơ hoặc Cài đặt, rồi Tài khoản. Dùng cùng ID trên mọi thiết bị và giữ riêng tư. Hỗ trợ không hỏi số thẻ.",
"w2t": "Nếu bạn mất nó",
"w2": "Nếu đã liên kết email, mở Hỗ trợ và chọn Khôi phục tài khoản. Chúng tôi gửi ID tới email đó. Nếu không liên kết gì, mở yêu cầu hỗ trợ. Dán ID không tự chứng minh bạn sở hữu tài khoản.",
"w3t": "Ngôn ngữ không phải nơi cư trú",
"w3": "Tiếng Nga hay bất kỳ ngôn ngữ nào khác không cho biết bạn sống ở nước nào hoặc liệu quy tắc trừng phạt có áp dụng với bạn.",
"w4t": "Xóa tài khoản",
"w4": "Xóa tài khoản trong ứng dụng hoặc trên trang xóa tài khoản sẽ xóa toàn bộ tài khoản Doppler. Không chỉ xóa liên hệ hỗ trợ. Quyền truy cập trả phí phải hết hạn hoặc được hủy trước. Chưa có trang công khai riêng để chỉ xóa liên hệ hỗ trợ.",
"bt": "Truy cập web và đăng ký cửa hàng",
"bi": "Nơi bạn thanh toán quyết định quyền truy cập có gia hạn và ai có thể hoàn tiền.",
"b1t": "Truy cập web một lần",
"b1": "Trang web tính phí một lần cho kỳ bạn chọn: một tháng, 6 tháng hoặc một năm. Không tự gia hạn và không lưu thẻ cho lần tính sau. Thẻ qua Revolut, crypto qua OxaPay. Ứng dụng Windows và APK Android mua trên trang web.",
"b2t": "Apple Pay và Google Pay trên trang web",
"b2": "Apple Pay và Google Pay trên trang web là ví trên trang thanh toán thẻ. Không phải đăng ký App Store hoặc Google Play.",
"b3t": "App Store và Google Play",
"b3": "Các cửa hàng đó bán đăng ký tự gia hạn. Khách hàng cửa hàng mới có 3 ngày dùng thử. Hủy trong cửa hàng ít nhất 24 giờ trước khi gia hạn. Một đăng ký cửa hàng gắn Pro với một Account ID tại một thời điểm.",
"b4t": "Những gì chúng tôi không bán",
"b4": "Không có mua Telegram Stars, mua Microsoft Store hay nạp số dư. Ứng dụng Windows là trình cài đặt trực tiếp.",
"ct": "Khôi phục, hủy hoặc hoàn tiền",
"ci": "Khôi phục, hủy và hoàn tiền là các thao tác khác nhau.",
"c1t": "Khôi phục",
"c1": "Khôi phục đặt quyền truy cập bạn đã trả lên một Account ID. Trong ứng dụng App Store hoặc Google Play, mở Hồ sơ, Đăng ký, rồi Khôi phục giao dịch mua. Khôi phục trên Account ID khác chuyển Pro sang tài khoản đó. Mua web hiện khi ứng dụng đăng nhập bằng Account ID dùng lúc thanh toán. Khởi động lại ứng dụng nếu chưa thấy. APK không có nút Khôi phục giao dịch mua.",
"c2t": "Hủy",
"c2": "Hủy dừng lần gia hạn cửa hàng tiếp theo. Bản thân việc hủy không trả lại tiền. Trên iPhone: Cài đặt, tên bạn, Đăng ký, Doppler VPN, Hủy. Trên Android: Play Store, hồ sơ, Thanh toán và đăng ký, Đăng ký, Hủy. Mua web không gia hạn nên không có gì để hủy.",
"c3t": "Hoàn tiền",
"c3": "Hoàn tiền là yêu cầu nhận lại tiền. Chính sách Hoàn tiền mô tả các bước cho thẻ web, crypto, App Store và Google Play. Không gửi số thẻ.",
"gt": "Hướng dẫn", "g1": "Account ID và khôi phục", "g2": "Truy cập web và đăng ký cửa hàng", "g3": "Khôi phục, hủy hoặc hoàn tiền", "g4": "Hoàn tiền",
"faq": "Khách hàng EU/EEA và UK có quyền hủy 14 ngày. Với khách khác, hoàn thiện chí đã công bố là 30 ngày chỉ cho lần mua đầu; khuyến mãi và giảm giá bị loại trừ. Hoàn App Store do Apple, Google Play do Google. Với thẻ hoặc crypto web, liên hệ hỗ trợ kèm Account ID và mã đơn. Không gửi số thẻ.",
"home": "Khách hàng EU/EEA và UK có quyền hủy 14 ngày. Với khách khác, hoàn thiện chí đã công bố là 30 ngày chỉ cho lần mua đầu; khuyến mãi và giảm giá bị loại trừ. Thẻ và crypto web: gửi email support@simnetiq.com kèm Account ID. Không gửi số thẻ. Hoàn App Store và Google Play yêu cầu tại cửa hàng. Xem Chính sách Hoàn tiền trên trang này.",
"guar": "Khách hàng EU/EEA và UK có quyền hủy 14 ngày. Với khách khác, hoàn thiện chí đã công bố là 30 ngày chỉ cho lần mua đầu; khuyến mãi và giảm giá bị loại trừ. Thanh toán web là một lần và không tự gia hạn. Gói App Store và Google Play gia hạn cho đến khi hủy.",
"foot": "Thanh toán an toàn bằng thẻ (Revolut) hoặc crypto (OxaPay). Thanh toán web là một lần và không tự gia hạn.",
"sub": "Thanh toán một lần bằng thẻ (Revolut) hoặc crypto (OxaPay). Không tự gia hạn. Khách hàng EU/EEA và UK có quyền hủy 14 ngày. Ở nơi khác, hoàn thiện chí đã công bố là 30 ngày chỉ cho lần mua đầu.",
"eb": "Quyền hủy 14 ngày tại EU/EEA và UK. Hoàn thiện chí 30 ngày cho lần mua đầu với khách hàng khác.",
"er": "Nếu Doppler VPN không phù hợp với bạn, trả lời email này hoặc liên hệ {email} kèm mã đơn và Account ID. Không gửi số thẻ. Hoàn tiền web là cho số tiền bạn đã trả.",
"pt": "Liên hệ hỗ trợ và xóa tài khoản",
"pc": "Liên kết email hoặc Telegram để khôi phục hoặc hỗ trợ không phải là xóa tài khoản. Trang xóa tài khoản xóa tài khoản Doppler. Không chỉ xóa liên hệ hỗ trợ. Hồ sơ thanh toán có thể được lưu khi luật yêu cầu. Không có trang công khai riêng để chỉ xóa liên hệ hỗ trợ.",
}))


save("ms", L({
"u": "Kemas kini terakhir: 28 September 2026",
"rt": "Bayaran balik",
"ri": "Dasar ini meliputi pembelian Doppler VPN daripada SIMNETIQ LTD (nombor syarikat 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Akses laman web ialah bayaran sekali. Pelan App Store dan Google Play diperbaharui sehingga anda batalkan di kedai.",
"ai": "Arahan bayaran balik Apple", "ar": "Laporkan masalah kepada Apple", "gi": "Dasar bayaran balik Google Play",
"e1t": "1. Pembatalan EU/EEA (14 hari)",
"e1": "Jika anda pengguna di Kesatuan Eropah atau EEA, anda boleh membatalkan dalam 14 hari tanpa memberi sebab. E-mel support@simnetiq.com sebelum 14 hari tamat. Kami pulangkan jumlah yang anda bayar dan tidak potong yuran pemproses pembayaran. Potongan untuk perkhidmatan yang sudah digunakan tidak automatik. Pembelian App Store atau Google Play diminta di kedai tersebut.",
"e2t": "2. Pembatalan UK (14 hari)",
"e2": "Jika anda pengguna di United Kingdom, anda mempunyai hak pembatalan 14 hari di bawah Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Hantar kenyataan jelas ke support@simnetiq.com. Kami pulangkan jumlah yang dibayar dan tidak potong yuran pemproses. Potongan untuk perkhidmatan yang sudah digunakan tidak automatik, dan satu sambungan sahaja bukan sebab penolakan.",
"e3t": "3. Bayaran balik niat baik 30 hari",
"e3": "Bagi pelanggan di luar EU/EEA dan UK, bayaran balik niat baik yang diterbitkan ialah 30 hari dari pembelian pertama, sekali setiap pelanggan. Pembelian promosi atau diskaun dikecualikan kecuali undang-undang memerlukan sebaliknya. Jika diberikan, ia adalah untuk jumlah yang dibayar. E-mel support@simnetiq.com dengan Account ID dan rujukan pesanan.",
"e4t": "4. Bayaran kad di laman web",
"e4": "Bayaran kad di laman web, termasuk Apple Pay dan Google Pay pada halaman itu, diproses oleh Revolut. Ia bukan pembelian App Store atau Google Play. E-mel support@simnetiq.com dengan Account ID dan rujukan pesanan. Jangan hantar nombor kad. Dasar ini tidak potong yuran pemproses. Bank anda menentukan bila kredit muncul.",
"e5t": "5. Bayaran kripto (OxaPay)",
"e5": "Bayaran kripto di laman web diproses oleh OxaPay. E-mel support@simnetiq.com dengan Account ID, rujukan invois, koin dan rangkaian. Kami tidak meneka alamat penghantar. Berikan alamat dompet. Kami sahkan aset, rangkaian dan jumlah sebelum menghantar bayaran balik. Dasar ini tidak menahan yuran rangkaian atau perubahan harga.",
"e6t": "6. App Store",
"e6": "Apple memutuskan bayaran balik App Store. Kami tidak menjanjikan kelulusan atau bilangan hari. Gunakan pautan di bawah. Bantuan Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Google memutuskan bayaran balik Google Play. Kelayakan bergantung pada produk, berapa lama sejak bayaran, negara dan sebab. Kami tidak menjadikan satu tingkap masa yang diterbitkan sebagai penolakan umum, dan tidak menjanjikan kelulusan. Gunakan pautan di bawah.",
"e8t": "8. Pembaharuan",
"e8": "Pembelian laman web meliputi tempoh yang anda pilih. Ia tidak diperbaharui automatik, dan tiada caj pembaharuan untuk dipulangkan. Pelan App Store atau Google Play diperbaharui sehingga anda batalkan di kedai, sekurang-kurangnya 24 jam sebelum tempoh tamat. Jika kedai mengecaj pembaharuan yang tidak diingini, hubungi kami dalam 14 hari dan kami bantu anda meminta kedai. Kedai yang memutuskan.",
"e9t": "9. Pengecualian",
"e9": "Bayaran balik niat baik boleh ditolak jika permintaan lewat, akaun ditutup kerana melanggar Terma, pelanggan yang sama meminta lagi, atau pembelian bersifat promosi atau diskaun. Ini tidak menghilangkan hak statutori. Yuran pemproses pembayaran bukan sebab untuk menolak atau mengurangkan bayaran balik.",
"e10t": "10. Cara meminta",
"e10": "Hantar Account ID, tempat anda bayar (kad laman, kripto, App Store atau Google Play), rujukan pesanan atau invois, dan tarikh. Sebab adalah pilihan. E-mel: support@simnetiq.com. Jangan hantar nombor kad, seed dompet atau kunci peribadi. Kami bertujuan mengakui permintaan laman dalam 2 hari perniagaan.",
"e11t": "11. Hubungi",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mel: support@simnetiq.com. Pengguna EU juga boleh menggunakan platform ODR Suruhanjaya Eropah: https://ec.europa.eu/consumers/odr.",
"at": "Account ID dan pemulihan",
"ai2": "Akaun Doppler ialah Account ID tanpa nama. Ia bukan log masuk e-mel, dan bahasa aplikasi bukan negara tempat anda tinggal.",
"w1t": "Apakah Account ID",
"w1": "ID berbentuk VPN-XXXX-XXXX-XXXX. Aplikasi menciptanya pada pelancaran pertama. Laman juga boleh menciptanya semasa pembayaran. Cari di Profil atau Tetapan, kemudian Akaun. Gunakan ID yang sama pada setiap peranti dan rahsiakannya. Sokongan tidak meminta nombor kad.",
"w2t": "Jika anda kehilangannya",
"w2": "Jika anda pautkan e-mel, buka Sokongan dan pilih Pulihkan akaun. Kami hantar ID ke e-mel itu. Jika tiada yang dipautkan, buka permintaan sokongan. Menampal ID sahaja tidak membuktikan anda memiliki akaun.",
"w3t": "Bahasa bukan kediaman",
"w3": "Bahasa Rusia, atau mana-mana bahasa lain, tidak memberitahu kami negara tempat anda tinggal atau sama ada peraturan sekatan terpakai kepada anda.",
"w4t": "Memadam akaun",
"w4": "Padam akaun dalam aplikasi atau di halaman padam-akaun memadamkan keseluruhan akaun Doppler. Ia tidak hanya memadam hubungan sokongan. Akses berbayar mesti tamat atau dibatalkan dahulu. Tiada halaman awam berasingan lagi untuk hanya membuang hubungan sokongan.",
"bt": "Akses laman dan langganan kedai",
"bi": "Tempat anda bayar menentukan sama ada akses diperbaharui dan siapa yang boleh memulangkan wang.",
"b1t": "Akses laman sekali",
"b1": "Laman mengecaj sekali untuk tempoh yang anda pilih: sebulan, 6 bulan atau setahun. Tidak diperbaharui automatik dan tidak menyimpan kad untuk caj kemudian. Kad melalui Revolut, kripto melalui OxaPay. Aplikasi Windows dan APK Android dibeli di laman.",
"b2t": "Apple Pay dan Google Pay di laman",
"b2": "Apple Pay dan Google Pay di laman ialah dompet pada semakan keluar kad. Ia bukan langganan App Store atau Google Play.",
"b3t": "App Store dan Google Play",
"b3": "Kedai tersebut menjual langganan yang diperbaharui automatik. Pelanggan kedai baharu mendapat percubaan 3 hari. Batalkan di kedai sekurang-kurangnya 24 jam sebelum pembaharuan. Satu langganan kedai melekatkan Pro kepada satu Account ID pada satu masa.",
"b4t": "Apa yang kami tidak jual",
"b4": "Tiada pembelian Telegram Stars, pembelian Microsoft Store atau tambah nilai baki. Aplikasi Windows ialah pemasang terus.",
"ct": "Pulihkan, batalkan atau bayar balik",
"ci": "Pulihkan, batalkan dan bayaran balik ialah tindakan berbeza.",
"c1t": "Pulihkan",
"c1": "Pulihkan meletakkan akses yang sudah dibayar pada Account ID. Dalam aplikasi App Store atau Google Play, buka Profil, Langganan, kemudian Pulihkan Pembelian. Memulihkan pada Account ID lain memindahkan Pro ke akaun itu. Pembelian laman muncul apabila aplikasi dilog masuk dengan Account ID yang digunakan semasa pembayaran. Mulakan semula aplikasi jika belum muncul. APK tiada butang Pulihkan Pembelian.",
"c2t": "Batalkan",
"c2": "Membatalkan menghentikan pembaharuan kedai seterusnya. Ia sendiri tidak memulangkan wang. Pada iPhone: Tetapan, nama anda, Langganan, Doppler VPN, Batalkan. Pada Android: Play Store, profil, Pembayaran dan langganan, Langganan, Batalkan. Pembelian laman tidak diperbaharui, jadi tiada apa untuk dibatalkan.",
"c3t": "Bayaran balik",
"c3": "Bayaran balik meminta wang dikembalikan. Dasar Bayaran Balik menerangkan langkah untuk kad laman, kripto, App Store dan Google Play. Jangan hantar nombor kad.",
"gt": "Panduan", "g1": "Account ID dan pemulihan", "g2": "Akses laman dan langganan kedai", "g3": "Pulihkan, batalkan atau bayar balik", "g4": "Bayaran balik",
"faq": "Pelanggan EU/EEA dan UK mempunyai hak pembatalan 14 hari. Untuk pelanggan lain, bayaran balik niat baik yang diterbitkan ialah 30 hari pada pembelian pertama sahaja; promosi dan diskaun dikecualikan. Bayaran balik App Store melalui Apple, Google Play melalui Google. Untuk kad atau kripto laman, hubungi sokongan dengan Account ID dan rujukan pesanan. Jangan hantar nombor kad.",
"home": "Pelanggan EU/EEA dan UK mempunyai hak pembatalan 14 hari. Untuk pelanggan lain, bayaran balik niat baik yang diterbitkan ialah 30 hari pada pembelian pertama sahaja; promosi dan diskaun dikecualikan. Kad dan kripto laman: e-mel support@simnetiq.com dengan Account ID. Jangan hantar nombor kad. Bayaran balik App Store dan Google Play diminta di kedai. Lihat Dasar Bayaran Balik di laman ini.",
"guar": "Pelanggan EU/EEA dan UK mempunyai hak pembatalan 14 hari. Untuk pelanggan lain, bayaran balik niat baik yang diterbitkan ialah 30 hari pada pembelian pertama sahaja; promosi dan diskaun dikecualikan. Semakan keluar web ialah bayaran sekali dan tidak diperbaharui automatik. Pelan App Store dan Google Play diperbaharui sehingga dibatalkan.",
"foot": "Bayaran selamat dengan kad (Revolut) atau kripto (OxaPay). Semakan keluar web ialah bayaran sekali dan tidak diperbaharui automatik.",
"sub": "Bayaran sekali dengan kad (Revolut) atau kripto (OxaPay). Tiada pembaharuan automatik. Pelanggan EU/EEA dan UK mempunyai hak pembatalan 14 hari. Di tempat lain, bayaran balik niat baik yang diterbitkan ialah 30 hari pada pembelian pertama sahaja.",
"eb": "Hak pembatalan 14 hari di EU/EEA dan UK. Bayaran balik niat baik 30 hari pada pembelian pertama untuk pelanggan lain.",
"er": "Jika Doppler VPN tidak sesuai untuk anda, balas e-mel ini atau hubungi {email} dengan ID pesanan dan Account ID. Jangan hantar nombor kad. Bayaran balik laman adalah untuk jumlah yang anda bayar.",
"pt": "Hubungan sokongan dan pemadaman akaun",
"pc": "Memautkan e-mel atau Telegram untuk pemulihan atau sokongan bukan sama dengan memadam akaun. Halaman padam-akaun memadam akaun Doppler. Ia tidak hanya membuang hubungan sokongan. Rekod pembayaran boleh disimpan jika undang-undang menghendakinya. Tiada halaman awam berasingan untuk hanya membuang hubungan sokongan.",
}))

save("bn", L({
"u": "সর্বশেষ আপডেট: ২৮ সেপ্টেম্বর ২০২৬",
"rt": "ফেরত",
"ri": "এই নীতি SIMNETIQ LTD (কোম্পানি নম্বর 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom থেকে Doppler VPN কেনার ক্ষেত্রে প্রযোজ্য। ওয়েবসাইট অ্যাক্সেস এককালীন পেমেন্ট। App Store ও Google Play প্ল্যান স্টোরে বাতিল না করা পর্যন্ত নবায়ন হয়।",
"ai": "Apple-এর ফেরত নির্দেশনা", "ar": "Apple-কে সমস্যা জানান", "gi": "Google Play ফেরত নীতি",
"e1t": "১. ইইউ/ইইএ বাতিলকরণ (১৪ দিন)",
"e1": "আপনি যদি ইউরোপীয় ইউনিয়ন বা ইইএ-র ভোক্তা হন, কারণ না দিয়ে ১৪ দিনের মধ্যে বাতিল করতে পারেন। ১৪ দিন শেষ হওয়ার আগে support@simnetiq.com-এ ইমেইল করুন। আমরা আপনার দেওয়া টাকা ফেরত দিই এবং পেমেন্ট প্রসেসর ফি কাটি না। ইতিমধ্যে ব্যবহৃত সেবার জন্য কর্তন স্বয়ংক্রিয় নয়। App Store বা Google Play কেনা সেই স্টোর থেকে অনুরোধ করতে হয়।",
"e2t": "২. যুক্তরাজ্য বাতিলকরণ (১৪ দিন)",
"e2": "আপনি যদি United Kingdom-এর ভোক্তা হন, Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 অনুযায়ী ১৪ দিনের বাতিল অধিকার আছে। support@simnetiq.com-এ স্পষ্ট বিবৃতি পাঠান। আমরা দেওয়া টাকা ফেরত দিই এবং প্রসেসর ফি কাটি না। ব্যবহৃত সেবার জন্য কর্তন স্বয়ংক্রিয় নয়, এবং একবার সংযোগ নিজে থেকে প্রত্যাখ্যানের কারণ নয়।",
"e3t": "৩. ৩০ দিনের সদিচ্ছা ফেরত",
"e3": "ইইউ/ইইএ ও যুক্তরাজ্যের বাইরের গ্রাহকদের জন্য প্রকাশিত সদিচ্ছা ফেরত প্রথম কেনা থেকে ৩০ দিন, প্রতি গ্রাহকে একবার। আইন অন্যথা না চাইলে প্রচারমূলক বা ছাড়যুক্ত কেনা বাদ। ফেরত দিলে তা দেওয়া টাকার জন্য। Account ID ও অর্ডার রেফারেন্সসহ support@simnetiq.com-এ ইমেইল করুন।",
"e4t": "৪. ওয়েবসাইট কার্ড পেমেন্ট",
"e4": "ওয়েবসাইটের কার্ড পেমেন্ট, সেই পৃষ্ঠার Apple Pay ও Google Payসহ, Revolut প্রক্রিয়া করে। এগুলো App Store বা Google Play কেনা নয়। Account ID ও অর্ডার রেফারেন্সসহ support@simnetiq.com-এ ইমেইল করুন। কার্ড নম্বর পাঠাবেন না। এই নীতি প্রসেসর ফি কাটে না। ক্রেডিট কখন দেখা যাবে তা ব্যাংক ঠিক করে।",
"e5t": "৫. ক্রিপ্টো পেমেন্ট (OxaPay)",
"e5": "ওয়েবসাইটের ক্রিপ্টো পেমেন্ট OxaPay প্রক্রিয়া করে। Account ID, ইনভয়েস রেফারেন্স, কয়েন ও নেটওয়ার্কসহ support@simnetiq.com-এ ইমেইল করুন। আমরা প্রেরকের ঠিকানা অনুমান করি না। ওয়ালেট ঠিকানা দিন। ফেরত পাঠানোর আগে সম্পদ, নেটওয়ার্ক ও পরিমাণ নিশ্চিত করি। এই নীতি নেটওয়ার্ক ফি বা দামের পরিবর্তন রাখে না।",
"e6t": "৬. App Store",
"e6": "App Store ফেরত Apple সিদ্ধান্ত নেয়। আমরা অনুমোদন বা দিনসংখ্যা প্রতিশ্রুতি দিই না। নিচের লিংক ব্যবহার করুন। Account ID সাহায্য: support@simnetiq.com।",
"e7t": "৭. Google Play",
"e7": "Google Play ফেরত Google সিদ্ধান্ত নেয়। যোগ্যতা পণ্য, পেমেন্টের পর কত সময়, দেশ ও কারণের উপর নির্ভর করে। আমরা একটি প্রকাশিত সময়সীমাকে সাধারণ প্রত্যাখ্যান বানাই না এবং অনুমোদন প্রতিশ্রুতি দিই না। নিচের লিংক ব্যবহার করুন।",
"e8t": "৮. নবায়ন",
"e8": "ওয়েবসাইট কেনা আপনার বেছে নেওয়া সময়কাল কভার করে। এটি স্বয়ংক্রিয় নবায়ন হয় না, এবং ফেরত দেওয়ার মতো নবায়ন চার্জ নেই। App Store বা Google Play প্ল্যান স্টোরে বাতিল না করা পর্যন্ত নবায়ন হয়, মেয়াদ শেষের অন্তত ২৪ ঘণ্টা আগে। স্টোর অনাকাঙ্ক্ষিত নবায়ন চার্জ করলে ১৪ দিনের মধ্যে আমাদের জানান; স্টোরে আবেদনে সাহায্য করব। সিদ্ধান্ত স্টোরের।",
"e9t": "৯. বাদ",
"e9": "সদিচ্ছা ফেরত প্রত্যাখ্যান হতে পারে যদি অনুরোধ দেরি হয়, শর্ত ভঙ্গে অ্যাকাউন্ট বন্ধ হয়, একই গ্রাহক আবার চায়, বা কেনা প্রচারমূলক/ছাড়যুক্ত হয়। এগুলো আইনগত অধিকার কেড়ে নেয় না। পেমেন্ট প্রসেসর ফি ফেরত প্রত্যাখ্যান বা কমানোর কারণ নয়।",
"e10t": "১০. কীভাবে অনুরোধ করবেন",
"e10": "Account ID, কোথায় পেমেন্ট করেছেন (ওয়েব কার্ড, ক্রিপ্টো, App Store বা Google Play), অর্ডার বা ইনভয়েস রেফারেন্স ও তারিখ পাঠান। কারণ ঐচ্ছিক। ইমেইল: support@simnetiq.com। কার্ড নম্বর, ওয়ালেট সিড বা প্রাইভেট কী পাঠাবেন না। ওয়েবসাইট অনুরোধ ২ কর্মদিবসের মধ্যে স্বীকার করার লক্ষ্য রাখি।",
"e11t": "১১. যোগাযোগ",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom। ইমেইল: support@simnetiq.com। ইইউ ভোক্তারা ইউরোপীয় কমিশনের ODR প্ল্যাটফর্মও ব্যবহার করতে পারেন: https://ec.europa.eu/consumers/odr।",
"at": "Account ID ও পুনরুদ্ধার",
"ai2": "Doppler অ্যাকাউন্ট একটি বেনামি Account ID। এটি ইমেইল লগইন নয়, এবং অ্যাপের ভাষা আপনার বাসদেশ নয়।",
"w1t": "Account ID কী",
"w1": "ID দেখতে VPN-XXXX-XXXX-XXXX। অ্যাপ প্রথম চালুতে তৈরি করে। সাইট চেকআউটেও তৈরি করতে পারে। প্রোফাইল বা সেটিংস, তারপর অ্যাকাউন্টে পাবেন। প্রতিটি ডিভাইসে একই ID ব্যবহার করুন এবং গোপন রাখুন। সাপোর্ট কার্ড নম্বর চায় না।",
"w2t": "হারিয়ে গেলে",
"w2": "ইমেইল লিঙ্ক করে থাকলে সাপোর্ট খুলে অ্যাকাউন্ট পুনরুদ্ধার বেছে নিন। সেই ইমেইলে ID পাঠাই। কিছু লিঙ্ক না থাকলে সাপোর্ট অনুরোধ খুলুন। শুধু ID পেস্ট করলে অ্যাকাউন্ট আপনার প্রমাণ হয় না।",
"w3t": "ভাষা বাসস্থান নয়",
"w3": "রাশিয়ান বা অন্য কোনো ভাষা বলে না আপনি কোন দেশে থাকেন বা নিষেধাজ্ঞার নিয়ম আপনার ক্ষেত্রে প্রযোজ্য কিনা।",
"w4t": "অ্যাকাউন্ট মুছে ফেলা",
"w4": "অ্যাপে বা অ্যাকাউন্ট-মুছুন পৃষ্ঠায় অ্যাকাউন্ট মুছলে পুরো Doppler অ্যাকাউন্ট মুছে যায়। শুধু সাপোর্ট যোগাযোগ মুছে না। প্রথমে পেইড অ্যাক্সেস শেষ বা বাতিল হতে হবে। শুধু সাপোর্ট যোগাযোগ সরাতে আলাদা পাবলিক পৃষ্ঠা নেই।",
"bt": "ওয়েবসাইট অ্যাক্সেস ও স্টোর সাবস্ক্রিপশন",
"bi": "আপনি কোথায় পেমেন্ট করেছেন তা বলে অ্যাক্সেস নবায়ন হবে কিনা এবং কে ফেরত দিতে পারে।",
"b1t": "এককালীন ওয়েবসাইট অ্যাক্সেস",
"b1": "সাইট আপনার বেছে নেওয়া সময়ের জন্য একবার চার্জ করে: এক মাস, ৬ মাস বা এক বছর। স্বয়ংক্রিয় নবায়ন হয় না এবং পরের চার্জের জন্য কার্ড রাখে না। কার্ড Revolut, ক্রিপ্টো OxaPay দিয়ে। Windows অ্যাপ ও Android APK সাইটে কেনা যায়।",
"b2t": "সাইটে Apple Pay ও Google Pay",
"b2": "সাইটের Apple Pay ও Google Pay কার্ড চেকআউটের ওয়ালেট। App Store বা Google Play সাবস্ক্রিপশন নয়।",
"b3t": "App Store ও Google Play",
"b3": "এই স্টোরগুলো স্বয়ংক্রিয় নবায়ন সাবস্ক্রিপশন বিক্রি করে। নতুন স্টোর গ্রাহকরা ৩ দিনের ট্রায়াল পান। নবায়নের অন্তত ২৪ ঘণ্টা আগে স্টোরে বাতিল করুন। একটি স্টোর সাবস্ক্রিপশন একসময়ে এক Account ID-তে Pro যুক্ত করে।",
"b4t": "আমরা কী বিক্রি করি না",
"b4": "Telegram Stars কেনা, Microsoft Store কেনা বা ব্যালেন্স টপ-আপ নেই। Windows অ্যাপ সরাসরি ইনস্টলার।",
"ct": "পুনরুদ্ধার, বাতিল বা ফেরত",
"ci": "পুনরুদ্ধার, বাতিল ও ফেরত আলাদা কাজ।",
"c1t": "পুনরুদ্ধার",
"c1": "পুনরুদ্ধার ইতিমধ্যে কেনা অ্যাক্সেস একটি Account ID-তে বসায়। App Store বা Google Play অ্যাপে প্রোফাইল, সাবস্ক্রিপশন, তারপর কেনাকাটা পুনরুদ্ধার খুলুন। অন্য Account ID-তে পুনরুদ্ধার করলে Pro সেই অ্যাকাউন্টে যায়। ওয়েব কেনা দেখা যায় যখন অ্যাপ চেকআউটের Account ID দিয়ে সাইন ইন থাকে। না দেখালে অ্যাপ পুনরায় চালু করুন। APK-তে কেনাকাটা পুনরুদ্ধার বোতাম নেই।",
"c2t": "বাতিল",
"c2": "বাতিল পরের স্টোর নবায়ন থামায়। নিজে থেকে টাকা ফেরত দেয় না। iPhone-এ: সেটিংস, আপনার নাম, সাবস্ক্রিপশন, Doppler VPN, বাতিল। Android-এ: Play Store, প্রোফাইল, পেমেন্ট ও সাবস্ক্রিপশন, সাবস্ক্রিপশন, বাতিল। ওয়েব কেনা নবায়ন হয় না, তাই বাতিল করার কিছু নেই।",
"c3t": "ফেরত",
"c3": "ফেরত মানে টাকা ফেরত চাওয়া। ফেরত নীতিতে ওয়েব কার্ড, ক্রিপ্টো, App Store ও Google Play-এর ধাপ আছে। কার্ড নম্বর পাঠাবেন না।",
"gt": "গাইড", "g1": "Account ID ও পুনরুদ্ধার", "g2": "ওয়েবসাইট অ্যাক্সেস ও স্টোর সাবস্ক্রিপশন", "g3": "পুনরুদ্ধার, বাতিল বা ফেরত", "g4": "ফেরত",
"faq": "ইইউ/ইইএ ও যুক্তরাজ্যের গ্রাহকদের ১৪ দিনের বাতিল অধিকার আছে। অন্যদের জন্য প্রকাশিত সদিচ্ছা ফেরত শুধু প্রথম কেনায় ৩০ দিন; প্রচার ও ছাড় বাদ। App Store ফেরত Apple, Google Play Google। ওয়েব কার্ড বা ক্রিপ্টোর জন্য Account ID ও অর্ডার রেফারেন্সসহ সাপোর্টে যোগাযোগ করুন। কার্ড নম্বর পাঠাবেন না।",
"home": "ইইউ/ইইএ ও যুক্তরাজ্যের গ্রাহকদের ১৪ দিনের বাতিল অধিকার আছে। অন্যদের জন্য প্রকাশিত সদিচ্ছা ফেরত শুধু প্রথম কেনায় ৩০ দিন; প্রচার ও ছাড় বাদ। ওয়েব কার্ড ও ক্রিপ্টো: Account IDসহ support@simnetiq.com-এ ইমেইল করুন। কার্ড নম্বর পাঠাবেন না। App Store ও Google Play ফেরত স্টোর থেকে অনুরোধ করতে হয়। এই সাইটের ফেরত নীতি দেখুন।",
"guar": "ইইউ/ইইএ ও যুক্তরাজ্যের গ্রাহকদের ১৪ দিনের বাতিল অধিকার আছে। অন্যদের জন্য প্রকাশিত সদিচ্ছা ফেরত শুধু প্রথম কেনায় ৩০ দিন; প্রচার ও ছাড় বাদ। ওয়েব চেকআউট এককালীন এবং স্বয়ংক্রিয় নবায়ন হয় না। App Store ও Google Play প্ল্যান বাতিল না করা পর্যন্ত নবায়ন হয়।",
"foot": "কার্ড (Revolut) বা ক্রিপ্টো (OxaPay) দিয়ে নিরাপদ পেমেন্ট। ওয়েব চেকআউট এককালীন এবং স্বয়ংক্রিয় নবায়ন হয় না।",
"sub": "কার্ড (Revolut) বা ক্রিপ্টো (OxaPay) দিয়ে এককালীন পেমেন্ট। স্বয়ংক্রিয় নবায়ন নেই। ইইউ/ইইএ ও যুক্তরাজ্যের গ্রাহকদের ১৪ দিনের বাতিল অধিকার আছে। অন্যত্র প্রকাশিত সদিচ্ছা ফেরত শুধু প্রথম কেনায় ৩০ দিন।",
"eb": "ইইউ/ইইএ ও যুক্তরাজ্যে ১৪ দিনের বাতিল অধিকার। অন্য গ্রাহকদের জন্য প্রথম কেনায় ৩০ দিনের সদিচ্ছা ফেরত।",
"er": "Doppler VPN আপনার জন্য কাজ না করলে এই ইমেইলের উত্তর দিন বা অর্ডার ID ও Account IDসহ {email}-এ যোগাযোগ করুন। কার্ড নম্বর পাঠাবেন না। ওয়েবসাইট ফেরত আপনার দেওয়া টাকার জন্য।",
"pt": "সাপোর্ট যোগাযোগ ও অ্যাকাউন্ট মুছে ফেলা",
"pc": "পুনরুদ্ধার বা সাপোর্টের জন্য ইমেইল বা Telegram লিঙ্ক করা অ্যাকাউন্ট মুছার সমান নয়। অ্যাকাউন্ট-মুছুন পৃষ্ঠা Doppler অ্যাকাউন্ট মুছে। শুধু সাপোর্ট যোগাযোগ সরায় না। আইন চাইলে পেমেন্ট রেকর্ড রাখা হতে পারে। শুধু সাপোর্ট যোগাযোগ সরাতে আলাদা পাবলিক পৃষ্ঠা নেই।",
}))

save("ur", L({
"u": "آخری اپ ڈیٹ: 28 ستمبر 2026",
"rt": "رقم کی واپسی",
"ri": "یہ پالیسی SIMNETIQ LTD (کمپنی نمبر 16861177)، 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom سے Doppler VPN خریداریوں پر لاگو ہوتی ہے۔ ویب سائٹ رسائی ایک بار کی ادائیگی ہے۔ App Store اور Google Play پلان اسٹور میں منسوخ ہونے تک تجدید ہوتے رہتے ہیں۔",
"ai": "Apple کی رقم واپسی ہدایات", "ar": "Apple کو مسئلہ رپورٹ کریں", "gi": "Google Play رقم واپسی پالیسی",
"e1t": "1. EU/EEA منسوخی (14 دن)",
"e1": "اگر آپ یورپی یونین یا EEA میں صارف ہیں تو بغیر وجہ بتائے 14 دن میں منسوخ کر سکتے ہیں۔ 14 دن ختم ہونے سے پہلے support@simnetiq.com پر ای میل کریں۔ ہم ادا کی گئی رقم واپس کرتے ہیں اور ادائیگی پروسیسر فیس نہیں کاٹتے۔ استعمال شدہ سروس کی کٹوتی خود بخود نہیں۔ App Store یا Google Play خریداری اسی اسٹور سے مانگی جاتی ہے۔",
"e2t": "2. برطانیہ منسوخی (14 دن)",
"e2": "اگر آپ United Kingdom میں صارف ہیں تو Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 کے تحت 14 دن کی منسوخی کا حق ہے۔ support@simnetiq.com پر واضح بیان بھیجیں۔ ہم ادا کی گئی رقم واپس کرتے ہیں اور پروسیسر فیس نہیں کاٹتے۔ استعمال شدہ سروس کی کٹوتی خود بخود نہیں، اور ایک کنکشن خود بخود انکار کی وجہ نہیں۔",
"e3t": "3. 30 دن کی خیرسگالی واپسی",
"e3": "EU/EEA اور UK سے باہر گاہکوں کے لیے شائع شدہ خیرسگالی واپسی پہلی خریداری سے 30 دن ہے، فی گاہک ایک بار۔ قانون ورنہ نہ کہے تو پرومو یا رعایتی خریداریاں خارج ہیں۔ منظوری پر ادا شدہ رقم واپس ہوتی ہے۔ Account ID اور آرڈر حوالہ کے ساتھ support@simnetiq.com پر ای میل کریں۔",
"e4t": "4. ویب سائٹ کارڈ ادائیگیاں",
"e4": "ویب سائٹ پر کارڈ ادائیگیاں، بشمول اس صفحے پر Apple Pay اور Google Pay، Revolut سنبھالتا ہے۔ یہ App Store یا Google Play خریداری نہیں۔ Account ID اور آرڈر حوالہ کے ساتھ support@simnetiq.com پر ای میل کریں۔ کارڈ نمبر نہ بھیجیں۔ یہ پالیسی پروسیسر فیس نہیں کاٹتی۔ کریڈٹ کب دکھے گا بینک طے کرتا ہے۔",
"e5t": "5. کرپٹو ادائیگیاں (OxaPay)",
"e5": "ویب سائٹ پر کرپٹو ادائیگیاں OxaPay سنبھالتا ہے۔ Account ID، انوائس حوالہ، کوائن اور نیٹ ورک کے ساتھ support@simnetiq.com پر ای میل کریں۔ ہم بھیجنے والے پتے کا اندازہ نہیں لگاتے۔ والیٹ ایڈریس بتائیں۔ واپسی بھیجنے سے پہلے اثاثہ، نیٹ ورک اور رقم کی تصدیق کرتے ہیں۔ یہ پالیسی نیٹ ورک فیس یا قیمت کی تبدیلی نہیں رکھتی۔",
"e6t": "6. App Store",
"e6": "App Store واپسی کا فیصلہ Apple کرتا ہے۔ ہم منظوری یا دنوں کی تعداد کا وعدہ نہیں کرتے۔ نیچے لنکس استعمال کریں۔ Account ID مدد: support@simnetiq.com۔",
"e7t": "7. Google Play",
"e7": "Google Play واپسی کا فیصلہ Google کرتا ہے۔ اہلیت پروڈکٹ، ادائیگی کے بعد کتنا وقت، ملک اور وجہ پر منحصر ہے۔ ہم ایک شائع شدہ وقت کو عمومی انکار نہیں بناتے اور منظوری کا وعدہ نہیں کرتے۔ نیچے لنک استعمال کریں۔",
"e8t": "8. تجدیدیں",
"e8": "ویب سائٹ خریداری آپ کے منتخب دورانیے کا احاطہ کرتی ہے۔ خود کار تجدید نہیں ہوتی، اور واپس کرنے کے لیے کوئی تجدید چارج نہیں۔ App Store یا Google Play پلان اسٹور میں منسوخ ہونے تک تجدید ہوتا ہے، مدت ختم ہونے سے کم از کم 24 گھنٹے پہلے۔ اگر اسٹور نے ناپسندیدہ تجدید لی تو 14 دن میں ہم سے رابطہ کریں؛ اسٹور سے درخواست میں مدد کریں گے۔ فیصلہ اسٹور کا ہے۔",
"e9t": "9. استثنائات",
"e9": "خیرسگالی واپسی مسترد ہو سکتی ہے اگر درخواست دیر سے ہو، شرائط توڑنے پر اکاؤنٹ بند ہو، وہی گاہک دوبارہ مانگے، یا خریداری پرومو/رعایتی ہو۔ یہ قانونی حقوق ختم نہیں کرتے۔ ادائیگی پروسیسر فیس واپسی مسترد یا کم کرنے کی وجہ نہیں۔",
"e10t": "10. درخواست کیسے کریں",
"e10": "Account ID، ادائیگی کی جگہ (ویب کارڈ، کرپٹو، App Store یا Google Play)، آرڈر یا انوائس حوالہ اور تاریخ بھیجیں۔ وجہ اختیاری ہے۔ ای میل: support@simnetiq.com۔ کارڈ نمبر، والیٹ سیڈ یا پرائیویٹ کلید نہ بھیجیں۔ ویب سائٹ درخواست کو 2 کاروباری دنوں میں تسلیم کرنے کا ہدف ہے۔",
"e11t": "11. رابطہ",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom۔ ای میل: support@simnetiq.com۔ EU صارفین یورپی کمیشن کا ODR پلیٹ فارم بھی استعمال کر سکتے ہیں: https://ec.europa.eu/consumers/odr۔",
"at": "Account ID اور بازیابی",
"ai2": "Doppler اکاؤنٹ ایک گمنام Account ID ہے۔ یہ ای میل لاگ اِن نہیں، اور ایپ کی زبان آپ کے رہائشی ملک نہیں۔",
"w1t": "Account ID کیا ہے",
"w1": "ID شکل VPN-XXXX-XXXX-XXXX ہے۔ ایپ پہلی بار چلنے پر بناتی ہے۔ سائٹ چیک آؤٹ پر بھی بنا سکتی ہے۔ پروفائل یا سیٹنگز، پھر اکاؤنٹ میں ملیں۔ ہر ڈیوائس پر ایک ہی ID استعمال کریں اور خفیہ رکھیں۔ سپورٹ کارڈ نمبر نہیں مانگتا۔",
"w2t": "اگر کھو جائے",
"w2": "اگر ای میل منسلک کی ہے تو سپورٹ کھول کر اکاؤنٹ بحال کریں۔ ہم وہ ID اس ای میل پر بھیجتے ہیں۔ کچھ منسلک نہ ہو تو سپورٹ درخواست کھولیں۔ صرف ID چسپاں کرنا ملکیت ثابت نہیں کرتا۔",
"w3t": "زبان رہائش نہیں",
"w3": "روسی یا کوئی اور زبان نہیں بتاتی کہ آپ کس ملک میں رہتے ہیں یا پابندی کا قاعدہ آپ پر لاگو ہے یا نہیں۔",
"w4t": "اکاؤنٹ حذف کرنا",
"w4": "ایپ یا حذف-اکاؤنٹ صفحے پر اکاؤنٹ حذف کرنا پورا Doppler اکاؤنٹ مٹاتا ہے۔ صرف سپورٹ رابطہ نہیں ہٹاتا۔ ادا شدہ رسائی پہلے ختم یا منسوخ ہونی چاہیے۔ صرف سپورٹ رابطہ ہٹانے کا الگ عوامی صفحہ نہیں۔",
"bt": "ویب سائٹ رسائی اور اسٹور سبسکرپشنز",
"bi": "آپ نے کہاں ادائیگی کی اس سے طے ہوتا ہے کہ رسائی تجدید ہوگی اور کون رقم واپس کر سکتا ہے۔",
"b1t": "ایک بار کی ویب سائٹ رسائی",
"b1": "سائٹ آپ کے منتخب دورانیے کے لیے ایک بار چارج کرتی ہے: ایک مہینہ، 6 مہینے یا ایک سال۔ خود کار تجدید نہیں اور بعد کے چارج کے لیے کارڈ نہیں رکھتی۔ کارڈ Revolut، کرپٹو OxaPay سے۔ Windows ایپ اور Android APK سائٹ سے خریدے جاتے ہیں۔",
"b2t": "سائٹ پر Apple Pay اور Google Pay",
"b2": "سائٹ پر Apple Pay اور Google Pay کارڈ چیک آؤٹ کے والیٹ ہیں۔ App Store یا Google Play سبسکرپشن نہیں۔",
"b3t": "App Store اور Google Play",
"b3": "یہ اسٹور خود کار تجدید سبسکرپشن بیچتے ہیں۔ نئے اسٹور گاہکوں کو 3 دن کا ٹرائل ملتا ہے۔ تجدید سے کم از کم 24 گھنٹے پہلے اسٹور میں منسوخ کریں۔ ایک اسٹور سبسکرپشن ایک وقت میں ایک Account ID سے Pro جوڑتی ہے۔",
"b4t": "ہم کیا نہیں بیچتے",
"b4": "Telegram Stars خریداری، Microsoft Store خریداری یا بیلنس ٹاپ اپ نہیں۔ Windows ایپ براہِ راست انسٹالر ہے۔",
"ct": "بحال کریں، منسوخ کریں یا واپسی",
"ci": "بحالی، منسوخی اور واپسی مختلف کام ہیں۔",
"c1t": "بحال کریں",
"c1": "بحالی پہلے ادا شدہ رسائی کو Account ID پر رکھتی ہے۔ App Store یا Google Play ایپ میں پروفائل، سبسکرپشن، پھر خریداریاں بحال کریں کھولیں۔ دوسرے Account ID پر بحالی Pro وہاں منتقل کرتی ہے۔ ویب خریداری تب دکھتی ہے جب ایپ چیک آؤٹ والے Account ID سے سائن اِن ہو۔ نہ دکھے تو ایپ دوبارہ چلائیں۔ APK میں خریداریاں بحال کریں بٹن نہیں۔",
"c2t": "منسوخ کریں",
"c2": "منسوخی اگلی اسٹور تجدید روکتی ہے۔ خود بخود رقم واپس نہیں کرتی۔ iPhone پر: سیٹنگز، آپ کا نام، سبسکرپشنز، Doppler VPN، منسوخ۔ Android پر: Play Store، پروفائل، ادائیگیاں اور سبسکرپشنز، سبسکرپشنز، منسوخ۔ ویب خریداری تجدید نہیں ہوتی، لہٰذا منسوخ کرنے کو کچھ نہیں۔",
"c3t": "رقم کی واپسی",
"c3": "واپسی رقم واپس مانگنا ہے۔ رقم واپسی پالیسی میں ویب کارڈ، کرپٹو، App Store اور Google Play کے مراحل ہیں۔ کارڈ نمبر نہ بھیجیں۔",
"gt": "رہنمائی", "g1": "Account ID اور بازیابی", "g2": "ویب سائٹ رسائی اور اسٹور سبسکرپشنز", "g3": "بحال کریں، منسوخ کریں یا واپسی", "g4": "رقم کی واپسی",
"faq": "EU/EEA اور UK گاہکوں کو 14 دن کی منسوخی کا حق ہے۔ دیگر گاہکوں کے لیے شائع شدہ خیرسگالی واپسی صرف پہلی خریداری پر 30 دن ہے؛ پرومو اور رعایتیں خارج ہیں۔ App Store واپسی Apple، Google Play Google۔ ویب کارڈ یا کرپٹو کے لیے Account ID اور آرڈر حوالہ کے ساتھ سپورٹ سے رابطہ کریں۔ کارڈ نمبر نہ بھیجیں۔",
"home": "EU/EEA اور UK گاہکوں کو 14 دن کی منسوخی کا حق ہے۔ دیگر گاہکوں کے لیے شائع شدہ خیرسگالی واپسی صرف پہلی خریداری پر 30 دن ہے؛ پرومو اور رعایتیں خارج ہیں۔ ویب کارڈ اور کرپٹو: Account ID کے ساتھ support@simnetiq.com پر ای میل کریں۔ کارڈ نمبر نہ بھیجیں۔ App Store اور Google Play واپسی اسٹور سے مانگی جاتی ہے۔ اس سائٹ پر رقم واپسی پالیسی دیکھیں۔",
"guar": "EU/EEA اور UK گاہکوں کو 14 دن کی منسوخی کا حق ہے۔ دیگر گاہکوں کے لیے شائع شدہ خیرسگالی واپسی صرف پہلی خریداری پر 30 دن ہے؛ پرومو اور رعایتیں خارج ہیں۔ ویب چیک آؤٹ ایک بار کی ادائیگی ہے اور خود کار تجدید نہیں ہوتی۔ App Store اور Google Play پلان منسوخ ہونے تک تجدید ہوتے ہیں۔",
"foot": "کارڈ (Revolut) یا کرپٹو (OxaPay) سے محفوظ ادائیگی۔ ویب چیک آؤٹ ایک بار کی ادائیگی ہے اور خود کار تجدید نہیں ہوتی۔",
"sub": "کارڈ (Revolut) یا کرپٹو (OxaPay) سے ایک بار کی ادائیگی۔ خود کار تجدید نہیں۔ EU/EEA اور UK گاہکوں کو 14 دن کی منسوخی کا حق ہے۔ کہیں اور شائع شدہ خیرسگالی واپسی صرف پہلی خریداری پر 30 دن ہے۔",
"eb": "EU/EEA اور UK میں 14 دن کی منسوخی کا حق۔ دیگر گاہکوں کے لیے پہلی خریداری پر 30 دن کی خیرسگالی واپسی۔",
"er": "اگر Doppler VPN آپ کے لیے کام نہ کرے تو اس ای میل کا جواب دیں یا آرڈر ID اور Account ID کے ساتھ {email} سے رابطہ کریں۔ کارڈ نمبر نہ بھیجیں۔ ویب سائٹ واپسی آپ کی ادا شدہ رقم کے لیے ہے۔",
"pt": "سپورٹ رابطہ اور اکاؤنٹ حذف",
"pc": "بازیابی یا سپورٹ کے لیے ای میل یا Telegram منسلک کرنا اکاؤنٹ حذف کرنے کے برابر نہیں۔ حذف-اکاؤنٹ صفحہ Doppler اکاؤنٹ مٹاتا ہے۔ صرف سپورٹ رابطہ نہیں ہٹاتا۔ قانون کے مطابق ادائیگی ریکارڈ رکھے جا سکتے ہیں۔ صرف سپورٹ رابطہ ہٹانے کا الگ عوامی صفحہ نہیں۔",
}))

save("sw", L({
"u": "Ilisasishwa mwisho: 28 Septemba 2026",
"rt": "Marejesho",
"ri": "Sera hii inashughulikia ununuzi wa Doppler VPN kutoka SIMNETIQ LTD (nambari ya kampuni 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Ufikiaji wa tovuti ni malipo ya mara moja. Mipango ya App Store na Google Play inasasishwa hadi uifute kwenye duka.",
"ai": "Maagizo ya marejesho ya Apple", "ar": "Ripoti tatizo kwa Apple", "gi": "Sera ya marejesho ya Google Play",
"e1t": "1. Kufuta EU/EEA (siku 14)",
"e1": "Ikiwa wewe ni mlaji katika Umoja wa Ulaya au EEA, unaweza kufuta ndani ya siku 14 bila kutoa sababu. Tuma barua pepe support@simnetiq.com kabla ya siku 14 kuisha. Tunarejesha kiasi ulicholipa na hatupunguzi ada ya mchakato wa malipo. Punguzo kwa huduma iliyotumika si automatiki. Ununuzi wa App Store au Google Play unaombwa kwenye duka hilo.",
"e2t": "2. Kufuta Uingereza (siku 14)",
"e2": "Ikiwa wewe ni mlaji nchini United Kingdom, una haki ya kufuta siku 14 chini ya Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Tuma taarifa wazi kwa support@simnetiq.com. Tunarejesha kiasi ulicholipa na hatupunguzi ada ya mchakato. Punguzo kwa huduma iliyotumika si automatiki, na muunganisho mmoja peke yake si sababu ya kukataa.",
"e3t": "3. Marejesho ya nia njema siku 30",
"e3": "Kwa wateja nje ya EU/EEA na UK, marejesho ya nia njema yaliyochapishwa ni siku 30 kutoka ununuzi wa kwanza, mara moja kwa kila mteja. Ununuzi wa promo au punguzo haujumuishwi isipokuwa sheria inahitaji vinginevyo. Ikiruhusiwa, ni kwa kiasi kilicholipwa. Tuma barua pepe support@simnetiq.com na Account ID na rejeleo la agizo.",
"e4t": "4. Malipo ya kadi kwenye tovuti",
"e4": "Malipo ya kadi kwenye tovuti, ikiwa ni pamoja na Apple Pay na Google Pay kwenye ukurasa huo, yanachakatwa na Revolut. Si ununuzi wa App Store au Google Play. Tuma barua pepe support@simnetiq.com na Account ID na rejeleo la agizo. Usitume nambari ya kadi. Sera hii haipunguzi ada ya mchakato. Benki yako inaamua wakati salio linaonekana.",
"e5t": "5. Malipo ya crypto (OxaPay)",
"e5": "Malipo ya crypto kwenye tovuti yanachakatwa na OxaPay. Tuma barua pepe support@simnetiq.com na Account ID, rejeleo la ankara, sarafu, na mtandao. Hatutakisia anwani ya mtumaji. Toa anwani ya pochi. Tunathibitisha mali, mtandao, na kiasi kabla ya kutuma marejesho. Sera hii haihifadhi ada za mtandao au mabadiliko ya bei.",
"e6t": "6. App Store",
"e6": "Apple inaamua marejesho ya App Store. Hatuahidi idhini wala idadi ya siku. Tumia viungo vilivyo hapa chini. Msaada wa Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Google inaamua marejesho ya Google Play. Ustahili hutegemea bidhaa, muda tangu ulipolipa, nchi, na sababu. Hatugeuzi dirisha moja la muda lililochapishwa kuwa kukataa kwa ujumla, wala hatuahidi idhini. Tumia kiungo kilicho hapa chini.",
"e8t": "8. Sasisho",
"e8": "Ununuzi wa tovuti unashughulikia kipindi ulichochagua. Hausasishwi automatiki, na hakuna ada ya sasisho ya kurejesha. Mpango wa App Store au Google Play unasasishwa hadi uifute kwenye duka, angalau saa 24 kabla ya kipindi kuisha. Ikiwa duka lilitozwa sasisho usilotaka, wasiliana nasi ndani ya siku 14 na tutakusaidia kuuliza duka. Duka linaamua.",
"e9t": "9. Vighairi",
"e9": "Marejesho ya nia njema yanaweza kukataliwa ikiwa ombi limechelewa, akaunti ilifungwa kwa kuvunja Masharti, mteja yule yule anaomba tena, au ununuzi ulikuwa wa promo au punguzo. Hii haiondoi haki za kisheria. Ada ya mchakato wa malipo si sababu ya kukataa au kupunguza marejesho.",
"e10t": "10. Jinsi ya kuuliza",
"e10": "Tuma Account ID, mahali ulipolipa (kadi ya tovuti, crypto, App Store, au Google Play), rejeleo la agizo au ankara, na tarehe. Sababu ni hiari. Barua pepe: support@simnetiq.com. Usitume nambari ya kadi, mbegu ya pochi, au ufunguo wa faragha. Tunalenga kuthibitisha ombi la tovuti ndani ya siku 2 za biashara.",
"e11t": "11. Wasiliana",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Barua pepe: support@simnetiq.com. Walaji wa EU wanaweza pia kutumia jukwaa la ODR la Tume ya Ulaya: https://ec.europa.eu/consumers/odr.",
"at": "Account ID na urejeshaji",
"ai2": "Akaunti ya Doppler ni Account ID isiyojulikana. Si kuingia kwa barua pepe, na lugha ya programu si nchi unayoishi.",
"w1t": "Account ID ni nini",
"w1": "ID inaonekana kama VPN-XXXX-XXXX-XXXX. Programu inaunda wakati wa kuzindua mara ya kwanza. Tovuti pia inaweza kuunda wakati wa malipo. Ipate chini ya Wasifu au Mipangilio, kisha Akaunti. Tumia ID ile ile kwenye kila kifaa na uiweke siri. Msaada haombi nambari ya kadi.",
"w2t": "Ukipoteza",
"w2": "Ukiunganisha barua pepe, fungua Msaada na chagua Rejesha akaunti. Tunatuma ID kwa barua pepe hiyo. Ikiwa hukuunganisha chochote, fungua ombi la msaada. Kubandika ID pekee hakuthibitishi kuwa akaunti ni yako.",
"w3t": "Lugha si makazi",
"w3": "Kirusi, au lugha nyingine yoyote, haituambii nchi unayoishi au kama kanuni ya vikwazo inakutumikia.",
"w4t": "Kufuta akaunti",
"w4": "Kufuta akaunti katika programu au kwenye ukurasa wa kufuta-akaunti huondoa akaunti nzima ya Doppler. Haiondoi tu anwani ya msaada. Ufikiaji uliolipwa lazima uishe au ughairiwe kwanza. Hakuna ukurasa tofauti wa umma wa kuondoa tu anwani ya msaada.",
"bt": "Ufikiaji wa tovuti na usajili wa duka",
"bi": "Mahali ulipolipa huamua kama ufikiaji unasasishwa na nani anaweza kurejesha pesa.",
"b1t": "Ufikiaji wa tovuti wa mara moja",
"b1": "Tovuti inatoza mara moja kwa kipindi unachochagua: mwezi, miezi 6, au mwaka. Haisasishwi automatiki na haihifadhi kadi kwa tozo ya baadaye. Kadi hutumia Revolut. Crypto hutumia OxaPay. Programu ya Windows na APK ya Android hununuliwa kwenye tovuti.",
"b2t": "Apple Pay na Google Pay kwenye tovuti",
"b2": "Apple Pay na Google Pay kwenye tovuti ni pochi kwenye malipo ya kadi. Si usajili wa App Store au Google Play.",
"b3t": "App Store na Google Play",
"b3": "Maduka hayo yanauza usajili unaosasishwa automatiki. Wateja wapya wa duka hupata jaribio la siku 3. Ghairi kwenye duka angalau saa 24 kabla ya sasisho. Usajili mmoja wa duka unaambatanisha Pro kwa Account ID moja kwa wakati mmoja.",
"b4t": "Tunachokiuza sio",
"b4": "Hakuna ununuzi wa Telegram Stars, ununuzi wa Microsoft Store, wala kuongeza salio. Programu ya Windows ni kisakinishi moja kwa moja.",
"ct": "Rejesha, ghairi, au rejelea",
"ci": "Kurejesha, kughairi, na kurejesha pesa ni vitendo tofauti.",
"c1t": "Rejesha",
"c1": "Kurejesha huweka ufikiaji uliolipa tayari kwenye Account ID. Katika programu ya App Store au Google Play, fungua Wasifu, Usajili, kisha Rejesha Ununuzi. Kurejesha kwenye Account ID tofauti huhamisha Pro kwenda akaunti hiyo. Ununuzi wa tovuti unaonekana programu ikiwa imeingia kwa Account ID iliyotumika wakati wa malipo. Anzisha upya programu ikiwa bado haionekani. APK haina kitufe cha Rejesha Ununuzi.",
"c2t": "Ghairi",
"c2": "Kughairi husimamisha sasisho linalofuata la duka. Yenyewe hairudishi pesa. Kwenye iPhone: Mipangilio, jina lako, Usajili, Doppler VPN, Ghairi. Kwenye Android: Play Store, wasifu, Malipo na usajili, Usajili, Ghairi. Ununuzi wa tovuti hausasishwi, kwa hiyo hakuna cha kughairi.",
"c3t": "Marejesho",
"c3": "Marejesho yanaomba pesa zirudishwe. Sera ya Marejesho ina hatua za kadi ya tovuti, crypto, App Store, na Google Play. Usitume nambari ya kadi.",
"gt": "Mwongozo", "g1": "Account ID na urejeshaji", "g2": "Ufikiaji wa tovuti na usajili wa duka", "g3": "Rejesha, ghairi, au rejelea", "g4": "Marejesho",
"faq": "Wateja wa EU/EEA na UK wana haki ya kufuta siku 14. Kwa wateja wengine, marejesho ya nia njema yaliyochapishwa ni siku 30 kwenye ununuzi wa kwanza tu; promo na punguzo hazijumuishwi. Marejesho ya App Store yanapitia Apple, Google Play yanapitia Google. Kwa kadi au crypto ya tovuti, wasiliana na msaada na Account ID na rejeleo la agizo. Usitume nambari ya kadi.",
"home": "Wateja wa EU/EEA na UK wana haki ya kufuta siku 14. Kwa wateja wengine, marejesho ya nia njema yaliyochapishwa ni siku 30 kwenye ununuzi wa kwanza tu; promo na punguzo hazijumuishwi. Kadi na crypto ya tovuti: tuma barua pepe support@simnetiq.com na Account ID. Usitume nambari ya kadi. Marejesho ya App Store na Google Play yanaombwa kwenye duka. Angalia Sera ya Marejesho kwenye tovuti hii.",
"guar": "Wateja wa EU/EEA na UK wana haki ya kufuta siku 14. Kwa wateja wengine, marejesho ya nia njema yaliyochapishwa ni siku 30 kwenye ununuzi wa kwanza tu; promo na punguzo hazijumuishwi. Malipo ya wavuti ni mara moja na hayasasishwi automatiki. Mipango ya App Store na Google Play inasasishwa hadi ifutwe.",
"foot": "Malipo salama kwa kadi (Revolut) au crypto (OxaPay). Malipo ya wavuti ni mara moja na hayasasishwi automatiki.",
"sub": "Malipo ya mara moja kwa kadi (Revolut) au crypto (OxaPay). Hakuna sasisho automatiki. Wateja wa EU/EEA na UK wana haki ya kufuta siku 14. Mahali pengine, marejesho ya nia njema yaliyochapishwa ni siku 30 kwenye ununuzi wa kwanza tu.",
"eb": "Haki ya kufuta siku 14 katika EU/EEA na UK. Marejesho ya nia njema siku 30 kwenye ununuzi wa kwanza kwa wateja wengine.",
"er": "Ikiwa Doppler VPN haikufai, jibu barua pepe hii au wasiliana na {email} na ID ya agizo na Account ID. Usitume nambari ya kadi. Marejesho ya tovuti ni kwa kiasi ulicholipa.",
"pt": "Anwani ya msaada na kufuta akaunti",
"pc": "Kuunganisha barua pepe au Telegram kwa urejeshaji au msaada si sawa na kufuta akaunti. Ukurasa wa kufuta-akaunti unafuta akaunti ya Doppler. Haiondoi tu anwani ya msaada. Rekodi za malipo zinaweza kuhifadhiwa pale sheria inapohitaji. Hakuna ukurasa tofauti wa umma wa kuondoa tu anwani ya msaada.",
}))

save("az", L({
"u": "Son yenilənmə: 28 sentyabr 2026",
"rt": "Geri ödənişlər",
"ri": "Bu siyasət SIMNETIQ LTD (şirkət nömrəsi 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom tərəfindən satılan Doppler VPN alışlarını əhatə edir. Veb sayt girişi birdəfəlik ödənişdir. App Store və Google Play planları mağazada ləğv edilənə qədər yenilənir.",
"ai": "Apple geri ödəniş təlimatları", "ar": "Apple-a problem bildirin", "gi": "Google Play geri ödəniş siyasəti",
"e1t": "1. Aİ/AEA ləğvi (14 gün)",
"e1": "Avropa İttifaqı və ya AEA-da istehlakçı olsanız, səbəb göstərmədən 14 gün ərzində ləğv edə bilərsiniz. 14 gün bitməzdən əvvəl support@simnetiq.com ünvanına yazın. Ödədiyiniz məbləği qaytarırıq və ödəniş prosessoru haqqını çıxmırıq. İstifadə olunmuş xidmət üçün tutulma avtomatik deyil. App Store və ya Google Play alışları həmin mağazadan tələb olunur.",
"e2t": "2. Birləşmiş Krallıq ləğvi (14 gün)",
"e2": "United Kingdom-da istehlakçı olsanız, Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 əsasında 14 günlük ləğv hüququnuz var. support@simnetiq.com ünvanına aydın bəyanat göndərin. Ödədiyiniz məbləği qaytarırıq və prosessor haqqını çıxmırıq. İstifadə olunmuş xidmət üçün tutulma avtomatik deyil və bir bağlantı öz-özlüyündə imtina səbəbi deyil.",
"e3t": "3. 30 günlük xoşniyyət geri ödənişi",
"e3": "Aİ/AEA və UK xaricindəki müştərilər üçün dərc olunmuş xoşniyyət geri ödənişi ilk alışdan 30 gündür, müştəri başına bir dəfə. Qanun başqa tələb etmədikcə promo və ya endirimli alışlar istisna edilir. Verildikdə ödənilmiş məbləğ üçündür. Account ID və sifariş istinadı ilə support@simnetiq.com ünvanına yazın.",
"e4t": "4. Veb sayt kart ödənişləri",
"e4": "Veb saytdakı kart ödənişləri, o cümlədən həmin səhifədəki Apple Pay və Google Pay, Revolut tərəfindən emal olunur. Bunlar App Store və ya Google Play alışı deyil. Account ID və sifariş istinadı ilə support@simnetiq.com ünvanına yazın. Kart nömrəsini göndərməyin. Bu siyasət prosessor haqqını çıxmır. Kreditin nə vaxt görünəcəyinə bankınız qərar verir.",
"e5t": "5. Kripto ödənişləri (OxaPay)",
"e5": "Veb saytdakı kripto ödənişləri OxaPay tərəfindən emal olunur. Account ID, faktura istinadı, coin və şəbəkə ilə support@simnetiq.com ünvanına yazın. Göndərən ünvanı təxmin etmirik. Cüzdan ünvanını siz verin. Geri ödəniş göndərməzdən əvvəl aktiv, şəbəkə və məbləği təsdiqləyirik. Bu siyasət şəbəkə haqlarını və ya qiymət dəyişikliyini saxlamır.",
"e6t": "6. App Store",
"e6": "App Store geri ödənişlərinə Apple qərar verir. Təsdiq və ya gün sayı vəd etmirik. Aşağıdakı keçidlərdən istifadə edin. Account ID köməyi: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Google Play geri ödənişlərinə Google qərar verir. Uyğunluq məhsuldan, ödənişdən sonra keçən vaxtdan, ölkədən və səbəbdən asılıdır. Dərc olunmuş bir müddəti ümumi imtinaya çevirmirik və təsdiq vəd etmirik. Aşağıdakı keçiddən istifadə edin.",
"e8t": "8. Yeniləmələr",
"e8": "Veb sayt alışı seçdiyiniz dövrü əhatə edir. Avtomatik yenilənmir və geri ödəniləcək yeniləmə haqqı yoxdur. App Store və ya Google Play planı dövr bitməzdən ən azı 24 saat əvvəl mağazada ləğv edilənə qədər yenilənir. İstənməyən yeniləmə tutularsa, 14 gün ərzində bizə yazın; mağazaya müraciətdə kömək edəcəyik. Qərarı mağaza verir.",
"e9t": "9. İstisnalar",
"e9": "Xoşniyyət geri ödənişi tələb geciksə, hesab Şərtləri pozduğu üçün bağlanıbsa, eyni müştəri yenidən istəyirsə və ya alış promo/endirimli olubsa rədd edilə bilər. Bunlar qanuni hüquqları ləğv etmir. Ödəniş prosessoru haqqı geri ödənişi rədd etmək və ya azaltmaq üçün səbəb deyil.",
"e10t": "10. Necə tələb etmək",
"e10": "Account ID, harada ödədiyinizi (veb kart, kripto, App Store və ya Google Play), sifariş və ya faktura istinadını və tarixi göndərin. Səbəb istəyə bağlıdır. E-poçt: support@simnetiq.com. Kart nömrəsi, cüzdan seed və ya şəxsi açar göndərməyin. Veb sayt tələbini 2 iş günü ərzində təsdiqləməyi hədəfləyirik.",
"e11t": "11. Əlaqə",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-poçt: support@simnetiq.com. Aİ istehlakçıları Avropa Komissiyasının ODR platformasından da istifadə edə bilər: https://ec.europa.eu/consumers/odr.",
"at": "Account ID və bərpa",
"ai2": "Doppler hesabı anonim Account ID-dir. E-poçt girişi deyil və tətbiq dili yaşadığınız ölkə deyil.",
"w1t": "Account ID nədir",
"w1": "ID VPN-XXXX-XXXX-XXXX formasındadır. Tətbiq ilk açılışda yaradır. Sayt ödəniş zamanı da yarada bilər. Profil və ya Parametrlər altında Hesab bölməsindədir. Hər cihazda eyni ID-ni istifadə edin və gizli saxlayın. Dəstək kart nömrəsi istəmir.",
"w2t": "İtkirsinizsə",
"w2": "E-poçt bağlayıbsınızsa, Dəstəyi açıb Hesabı bərpa et seçin. ID-ni həmin e-poçta göndəririk. Heç nə bağlanmayıbsa, dəstək sorğusu açın. Yapışdırılmış ID təkbaşına hesabın sizə aid olduğunu sübut etmir.",
"w3t": "Dil yaşayış yeri deyil",
"w3": "Rus dili və ya hər hansı digər dil hansı ölkədə yaşadığınızı və ya sanksiya qaydasının sizə aid olub-olmadığını göstərmir.",
"w4t": "Hesabın silinməsi",
"w4": "Tətbiqdə və ya hesab-sil səhifəsində hesabı silmək bütün Doppler hesabını silir. Yalnız dəstək əlaqəsini silmir. Ödənişli giriş əvvəlcə bitməli və ya ləğv edilməlidir. Yalnız dəstək əlaqəsini silmək üçün ayrıca ictimai səhifə yoxdur.",
"bt": "Veb sayt girişi və mağaza abunəlikləri",
"bi": "Harada ödədiyiniz girişin yenilənib-yenilənməyəcəyini və kimin geri ödəyə biləcəyini müəyyən edir.",
"b1t": "Birdəfəlik veb sayt girişi",
"b1": "Sayt seçdiyiniz dövr üçün bir dəfə ödəniş alır: bir ay, 6 ay və ya bir il. Avtomatik yenilənmir və sonrakı ödəniş üçün kart saxlamır. Kart Revolut, kripto OxaPay vasitəsilədir. Windows tətbiqi və Android APK saytdan alınır.",
"b2t": "Saytda Apple Pay və Google Pay",
"b2": "Saytdakı Apple Pay və Google Pay kart ödəniş səhifəsindəki cüzdanlardır. App Store və ya Google Play abunəliyi deyil.",
"b3t": "App Store və Google Play",
"b3": "Bu mağazalar avtomatik yenilənən abunəlik satır. Yeni mağaza müştəriləri 3 günlük sınaq alır. Yeniləmədən ən azı 24 saat əvvəl mağazada ləğv edin. Bir mağaza abunəliyi Pro-nu eyni anda bir Account ID-yə bağlayır.",
"b4t": "Nə satmırıq",
"b4": "Telegram Stars alışı, Microsoft Store alışı və ya balans artırımı yoxdur. Windows tətbiqi birbaşa quraşdırıcıdır.",
"ct": "Bərpa et, ləğv et və ya geri ödə",
"ci": "Bərpa, ləğv və geri ödəniş fərqli əməliyyatlardır.",
"c1t": "Bərpa",
"c1": "Bərpa artıq ödədiyiniz girişi Account ID-yə qoyur. App Store və ya Google Play tətbiqində Profil, Abunəlik, sonra Alışları bərpa et açın. Başqa Account ID-də bərpa Pro-nu həmin hesaba köçürür. Veb alışı ödənişdə istifadə olunan Account ID ilə daxil olanda görünür. Görünməsə tətbiqi yenidən başladın. APK-də Alışları bərpa et düyməsi yoxdur.",
"c2t": "Ləğv",
"c2": "Ləğv növbəti mağaza yeniləməsini dayandırır. Öz-özlüyündə pul qaytarmır. iPhone-da: Parametrlər, adınız, Abunəliklər, Doppler VPN, Ləğv et. Android-də: Play Store, profil, Ödənişlər və abunəliklər, Abunəliklər, Ləğv et. Veb alışı yenilənmir, ona görə ləğv ediləcək bir şey yoxdur.",
"c3t": "Geri ödəniş",
"c3": "Geri ödəniş pulun geri istənməsidir. Geri ödəniş Siyasəti veb kart, kripto, App Store və Google Play addımlarını izah edir. Kart nömrəsi göndərməyin.",
"gt": "Bələdçilər", "g1": "Account ID və bərpa", "g2": "Veb sayt girişi və mağaza abunəlikləri", "g3": "Bərpa et, ləğv et və ya geri ödə", "g4": "Geri ödənişlər",
"faq": "Aİ/AEA və UK müştərilərinin 14 günlük ləğv hüququ var. Digərləri üçün dərc olunmuş xoşniyyət geri ödənişi yalnız ilk alışda 30 gündür; promo və endirimlər istisna edilir. App Store geri ödənişlərini Apple, Google Play-i Google idarə edir. Veb kart və ya kripto üçün Account ID və sifariş istinadı ilə dəstəyə müraciət edin. Kart nömrəsi göndərməyin.",
"home": "Aİ/AEA və UK müştərilərinin 14 günlük ləğv hüququ var. Digərləri üçün dərc olunmuş xoşniyyət geri ödənişi yalnız ilk alışda 30 gündür; promo və endirimlər istisna edilir. Veb kart və kripto: Account ID ilə support@simnetiq.com ünvanına yazın. Kart nömrəsi göndərməyin. App Store və Google Play geri ödənişləri mağazadan tələb olunur. Bu saytdakı Geri ödəniş Siyasətinə baxın.",
"guar": "Aİ/AEA və UK müştərilərinin 14 günlük ləğv hüququ var. Digərləri üçün dərc olunmuş xoşniyyət geri ödənişi yalnız ilk alışda 30 gündür; promo və endirimlər istisna edilir. Veb ödəniş birdəfəlikdir və avtomatik yenilənmir. App Store və Google Play planları ləğv edilənə qədər yenilənir.",
"foot": "Kart (Revolut) və ya kripto (OxaPay) ilə təhlükəsiz ödəniş. Veb ödəniş birdəfəlikdir və avtomatik yenilənmir.",
"sub": "Kart (Revolut) və ya kripto (OxaPay) ilə birdəfəlik ödəniş. Avtomatik yenilənmə yoxdur. Aİ/AEA və UK müştərilərinin 14 günlük ləğv hüququ var. Başqa yerdə dərc olunmuş xoşniyyət geri ödənişi yalnız ilk alışda 30 gündür.",
"eb": "Aİ/AEA və UK-də 14 günlük ləğv hüququ. Digər müştərilər üçün ilk alışda 30 günlük xoşniyyət geri ödənişi.",
"er": "Doppler VPN sizə uyğun gəlmirsə, bu e-poçta cavab verin və ya sifariş ID və Account ID ilə {email} ünvanına yazın. Kart nömrəsi göndərməyin. Veb sayt geri ödənişi ödədiyiniz məbləğ üçündür.",
"pt": "Dəstək əlaqəsi və hesabın silinməsi",
"pc": "Bərpa və ya dəstək üçün e-poçt və ya Telegram bağlamaq hesabı silmək deyil. Hesab-sil səhifəsi Doppler hesabını silir. Yalnız dəstək əlaqəsini silmir. Qanun tələb etdikdə ödəniş qeydləri saxlanıla bilər. Yalnız dəstək əlaqəsini silmək üçün ayrıca ictimai səhifə yoxdur.",
}))

save("tl", L({
"u": "Huling na-update: 28 Setyembre 2026",
"rt": "Mga refund",
"ri": "Sinasaklaw ng patakarang ito ang mga pagbili ng Doppler VPN mula sa SIMNETIQ LTD (numero ng kumpanya 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Ang access sa website ay isang beses na bayad. Ang mga plano sa App Store at Google Play ay nagre-renew hanggang kanselahin mo ang mga ito sa store.",
"ai": "Mga tagubilin sa refund ng Apple", "ar": "Mag-ulat ng problema sa Apple", "gi": "Patakaran sa refund ng Google Play",
"e1t": "1. Pagkansela sa EU/EEA (14 araw)",
"e1": "Kung ikaw ay consumer sa European Union o EEA, maaari kang magkansela sa loob ng 14 araw nang hindi nagbibigay ng dahilan. Mag-email sa support@simnetiq.com bago matapos ang 14 araw. Ibinabalik namin ang halagang binayaran mo at hindi namin binabawas ang bayad ng payment processor. Ang bawas para sa serbisyong nagamit na ay hindi awtomatiko. Ang mga pagbili sa App Store o Google Play ay hinihiling sa store na iyon.",
"e2t": "2. Pagkansela sa UK (14 araw)",
"e2": "Kung ikaw ay consumer sa United Kingdom, mayroon kang 14-araw na karapatan sa pagkansela sa ilalim ng Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Magpadala ng malinaw na pahayag sa support@simnetiq.com. Ibinabalik namin ang halagang binayaran at hindi namin binabawas ang processor fee. Ang bawas para sa serbisyong nagamit na ay hindi awtomatiko, at ang isang koneksyon ay hindi sa sarili nitong dahilan ng pagtanggi.",
"e3t": "3. 30-araw na goodwill refund",
"e3": "Para sa mga customer sa labas ng EU/EEA at UK, ang nai-publish na goodwill refund ay 30 araw mula sa unang pagbili, isang beses bawat customer. Hindi kasama ang promo o may-discount na pagbili maliban kung kinakailangan ng batas. Kapag ibinigay, ito ay para sa halagang binayaran. Mag-email sa support@simnetiq.com kasama ang Account ID at order reference.",
"e4t": "4. Mga bayad sa card sa website",
"e4": "Ang mga bayad sa card sa website, kasama ang Apple Pay at Google Pay sa pahinang iyon, ay pinoproseso ng Revolut. Hindi ito pagbili sa App Store o Google Play. Mag-email sa support@simnetiq.com kasama ang Account ID at order reference. Huwag ipadala ang card number. Hindi binabawas ng patakarang ito ang processor fee. Ang bangko mo ang nagdedesisyon kung kailan lalabas ang credit.",
"e5t": "5. Mga bayad sa crypto (OxaPay)",
"e5": "Ang mga bayad sa crypto sa website ay pinoproseso ng OxaPay. Mag-email sa support@simnetiq.com kasama ang Account ID, invoice reference, coin, at network. Hindi namin hulaan ang sending address. Ibigay ang wallet address. Kinukumpirma namin ang asset, network, at amount bago magpadala ng refund. Hindi pinapanatili ng patakarang ito ang network fees o pagbabago sa presyo.",
"e6t": "6. App Store",
"e6": "Si Apple ang nagdedesisyon sa mga refund sa App Store. Hindi kami nangangako ng approval o bilang ng araw. Gamitin ang mga link sa ibaba. Tulong sa Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Si Google ang nagdedesisyon sa mga refund sa Google Play. Depende ang eligibility sa produkto, kung gaano katagal mula nang magbayad, bansa, at dahilan. Hindi namin ginagawang pangkalahatang pagtanggi ang isang nai-publish na time window, at hindi kami nangangako ng approval. Gamitin ang link sa ibaba.",
"e8t": "8. Mga renewal",
"e8": "Sinasaklaw ng pagbili sa website ang panahong pinili mo. Hindi ito auto-renew, at walang renewal charge na ire-refund. Ang plano sa App Store o Google Play ay nagre-renew hanggang kanselahin mo ito sa store, hindi bababa sa 24 oras bago matapos ang period. Kung may siningil ang store na ayaw mong renewal, makipag-ugnayan sa amin sa loob ng 14 araw at tutulungan kang humingi sa store. Ang store ang magdedesisyon.",
"e9t": "9. Mga exclusion",
"e9": "Maaaring tanggihan ang goodwill refund kung huli ang request, isinara ang account dahil sa paglabag sa Terms, muling humiling ang parehong customer, o promo/discounted ang pagbili. Hindi nito inaalis ang statutory rights. Ang payment processor fee ay hindi dahilan para tumanggi o bawasan ang refund.",
"e10t": "10. Paano humiling",
"e10": "Ipadala ang Account ID, kung saan ka nagbayad (website card, crypto, App Store, o Google Play), ang order o invoice reference, at ang petsa. Opsiyonal ang dahilan. Email: support@simnetiq.com. Huwag magpadala ng card number, wallet seed, o private key. Layunin naming kilalanin ang website request sa loob ng 2 business days.",
"e11t": "11. Makipag-ugnayan",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Email: support@simnetiq.com. Maaari ring gamitin ng mga consumer sa EU ang ODR platform ng European Commission: https://ec.europa.eu/consumers/odr.",
"at": "Account ID at pagbawi",
"ai2": "Ang Doppler account ay isang anonymous na Account ID. Hindi ito email login, at ang wika ng app ay hindi ang bansang tinitirhan mo.",
"w1t": "Ano ang Account ID",
"w1": "Mukhang VPN-XXXX-XXXX-XXXX ang ID. Ginagawa ito ng app sa unang pagbukas. Maaari rin itong gawin ng website sa checkout. Hanapin sa Profile o Settings, pagkatapos Account. Gamitin ang parehong ID sa bawat device at panatilihing pribado. Hindi hihilingin ng support ang numero ng card.",
"w2t": "Kung mawala ito",
"w2": "Kung nag-link ka ng email, buksan ang Support at piliin ang Ibalik ang account. Ipinapadala namin ang ID sa email na iyon. Kung walang naka-link, magbukas ng kahilingan sa support. Ang pag-paste ng ID ay hindi sa sarili nitong nagpapatunay na sa iyo ang account.",
"w3t": "Ang wika ay hindi tirahan",
"w3": "Ang Ruso, o anumang ibang wika, ay hindi nagsasabi kung aling bansa ka nakatira o kung nalalapat sa iyo ang isang sanctions rule.",
"w4t": "Pagtanggal ng account",
"w4": "Ang Tanggalin ang account, sa app o sa pahina ng pagtanggal ng account, ay tinatanggal ang buong Doppler account. Hindi nito tinatanggal lang ang contact sa support. Dapat munang matapos o makansela ang bayad na access. Walang hiwalay na pampublikong pahina para tanggalin lang ang contact sa support.",
"bt": "Access sa website at mga subscription sa store",
"bi": "Kung saan ka nagbayad ang nagtatakda kung magre-renew ang access at kung sino ang makakapag-refund.",
"b1t": "Isang beses na access sa website",
"b1": "Sinisingil ng website nang isang beses ang panahong pipiliin mo: isang buwan, 6 na buwan, o isang taon. Hindi ito auto-renew at hindi nagtatago ng card para sa susunod na singil. Card sa pamamagitan ng Revolut, crypto sa pamamagitan ng OxaPay. Binibili ang Windows app at Android APK sa website.",
"b2t": "Apple Pay at Google Pay sa website",
"b2": "Ang Apple Pay at Google Pay sa website ay mga wallet sa card checkout. Hindi ito App Store o Google Play subscription.",
"b3t": "App Store at Google Play",
"b3": "Nagbebenta ang mga store na iyon ng auto-renewing subscription. May 3-araw na trial ang mga bagong customer ng store. Kanselahin sa store nang hindi bababa sa 24 oras bago ang renewal. Isang store subscription ang nag-a-attach ng Pro sa isang Account ID nang paisa-isa.",
"b4t": "Ano ang hindi namin ibinebenta",
"b4": "Walang pagbili ng Telegram Stars, pagbili sa Microsoft Store, o balance top-up. Ang Windows app ay direct installer.",
"ct": "Ibalik, kanselahin, o i-refund",
"ci": "Magkaiba ang pagbalik, pagkansela, at refund.",
"c1t": "Ibalik",
"c1": "Inilalagay ng pagbalik ang access na nabayaran mo na sa isang Account ID. Sa App Store o Google Play app, buksan ang Profile, Subscription, pagkatapos Ibalik ang Mga Binili. Ang pagbalik sa ibang Account ID ay inililipat ang Pro doon. Lumabas ang binili sa website kapag naka-sign in ang app sa Account ID na ginamit sa checkout. I-restart ang app kung hindi pa ito lumalabas. Walang pindutang Ibalik ang Mga Binili ang APK.",
"c2t": "Kanselahin",
"c2": "Hinahinto ng pagkansela ang susunod na pag-renew sa store. Hindi nito sa sarili nitong ibinabalik ang pera. Sa iPhone: Settings, pangalan mo, Subscriptions, Doppler VPN, Cancel. Sa Android: Play Store, profile, Payments and subscriptions, Subscriptions, Cancel. Hindi nagre-renew ang binili sa website, kaya walang ikakansela.",
"c3t": "Refund",
"c3": "Ang refund ay paghingi na ibalik ang pera. May mga hakbang ang Patakaran sa Refund para sa card sa website, crypto, App Store, at Google Play. Huwag magpadala ng card number.",
"gt": "Mga gabay", "g1": "Account ID at pagbawi", "g2": "Access sa website at mga subscription sa tindahan", "g3": "Ibalik, kanselahin, o i-refund", "g4": "Mga refund",
"faq": "May 14-araw na karapatan sa pagkansela ang mga customer sa EU/EEA at UK. Para sa iba, ang nai-publish na goodwill refund ay 30 araw sa unang pagbili lang; hindi kasama ang promo at discount. App Store refunds sa Apple, Google Play sa Google. Para sa website card o crypto, makipag-ugnayan sa support kasama ang Account ID at order reference. Huwag magpadala ng card number.",
"home": "May 14-araw na karapatan sa pagkansela ang mga customer sa EU/EEA at UK. Para sa iba, ang nai-publish na goodwill refund ay 30 araw sa unang pagbili lang; hindi kasama ang promo at discount. Website card at crypto: mag-email sa support@simnetiq.com kasama ang Account ID. Huwag magpadala ng card number. Ang App Store at Google Play refunds ay hinihiling sa store. Tingnan ang Patakaran sa Refund sa website na ito.",
"guar": "May 14-araw na karapatan sa pagkansela ang mga customer sa EU/EEA at UK. Para sa iba, ang nai-publish na goodwill refund ay 30 araw sa unang pagbili lang; hindi kasama ang promo at discount. Ang web checkout ay isang beses na bayad at hindi auto-renew. Ang App Store at Google Play plans ay nagre-renew hanggang kanselahin.",
"foot": "Ligtas na bayad sa pamamagitan ng card (Revolut) o crypto (OxaPay). Ang web checkout ay isang beses na bayad at hindi awtomatikong nagre-renew.",
"sub": "Isang beses na bayad sa pamamagitan ng card (Revolut) o crypto (OxaPay). Walang auto-renewal. May 14-araw na karapatan sa pagkansela ang mga customer sa EU/EEA at UK. Sa ibang lugar, ang nai-publish na goodwill refund ay 30 araw sa unang pagbili lang.",
"eb": "14-araw na karapatan sa pagkansela sa EU/EEA at UK. 30-araw na goodwill refund sa unang pagbili para sa ibang customer.",
"er": "Kung hindi angkop sa iyo ang Doppler VPN, sagutin ang email na ito o makipag-ugnayan sa {email} kasama ang order ID at Account ID. Huwag magpadala ng card number. Ang website refund ay para sa halagang binayaran mo.",
"pt": "Contact sa support at pagtanggal ng account",
"pc": "Ang pag-link ng email o Telegram para sa pagbawi o support ay hindi pagtanggal ng account. Tinatanggal ng pahina ng pagtanggal ng account ang Doppler account. Hindi nito tinatanggal lang ang contact sa support. Maaaring panatilihin ang mga talaan ng bayad kung kinakailangan ng batas. Walang hiwalay na pampublikong pahina para tanggalin lang ang contact sa support.",
}))

print("ok", "tr id vi ms bn ur sw az tl")
