#!/usr/bin/env python3
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from pack_rows import L, save

save("pl", L({
"u": "Ostatnia aktualizacja: 28 września 2026",
"rt": "Zwroty",
"ri": "Ta polityka obejmuje zakupy Doppler VPN od SIMNETIQ LTD (numer 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Dostęp na stronie to jednorazowa płatność. Plany App Store i Google Play odnawiają się, dopóki nie anulujesz ich w sklepie.",
"ai": "Instrukcja zwrotu Apple", "ar": "Zgłoś problem do Apple", "gi": "Zasady zwrotów Google Play",
"e1t": "1. Odstąpienie w UE/EOG (14 dni)",
"e1": "Jeśli jesteś konsumentem w Unii Europejskiej lub EOG, możesz odstąpić w ciągu 14 dni bez podawania powodu. Napisz na support@simnetiq.com przed końcem 14 dni. Zwracamy zapłaconą kwotę i nie potrącamy opłaty operatora płatności. Potrącenie za już świadczoną usługę nie jest automatyczne. Zakupy w App Store lub Google Play zgłasza się w tym sklepie.",
"e2t": "2. Odstąpienie w Wielkiej Brytanii (14 dni)",
"e2": "Jeśli jesteś konsumentem w Wielkiej Brytanii, masz 14 dni na odstąpienie na podstawie Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Wyślij jasne oświadczenie na support@simnetiq.com. Zwracamy zapłaconą kwotę i nie potrącamy opłaty operatora. Potrącenie za już świadczoną usługę nie jest automatyczne, a jedno połączenie samo w sobie nie jest powodem odmowy.",
"e3t": "3. Zwrot gestu dobrej woli w ciągu 30 dni",
"e3": "Dla klientów spoza UE, EOG i Wielkiej Brytanii opublikowany gest dobrej woli to 30 dni od pierwszego zakupu, raz na klienta. Zakupy promocyjne lub ze zniżką są wyłączone, chyba że prawo stanowi inaczej. Jeśli zwrot zostanie przyznany, dotyczy zapłaconej kwoty. Napisz na support@simnetiq.com i podaj Account ID oraz numer zamówienia.",
"e4t": "4. Płatność kartą na stronie",
"e4": "Płatności kartą na stronie, w tym Apple Pay i Google Pay na tej stronie, obsługuje Revolut. To nie są zakupy w App Store ani Google Play. Napisz na support@simnetiq.com, podaj Account ID i numer zamówienia. Nie wysyłaj numeru karty. Ta polityka nie potrąca opłaty operatora. Bank decyduje, kiedy pojawi się uznanie.",
"e5t": "5. Płatność krypto (OxaPay)",
"e5": "Płatności krypto na stronie obsługuje OxaPay. Napisz na support@simnetiq.com i podaj Account ID, numer faktury, monetę i sieć. Nie zgadujemy adresu nadawcy. Podaj adres portfela. Przed wysłaniem potwierdzamy aktywo, sieć i kwotę. Ta polityka nie zatrzymuje opłat sieci ani zmiany ceny.",
"e6t": "6. App Store",
"e6": "O zwrocie w App Store decyduje Apple. Nie obiecujemy akceptacji ani liczby dni. Linki są poniżej. Pomoc z Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "O zwrocie w Google Play decyduje Google. Zależy to od produktu, czasu od płatności, kraju i powodu. Nie zamieniamy jednego opublikowanego terminu w ogólną odmowę i nie obiecujemy akceptacji. Link jest poniżej.",
"e8t": "8. Odnowienia",
"e8": "Zakup na stronie obejmuje wybrany okres. Nie odnawia się sam i nie ma opłaty za odnowienie do zwrotu. Plan App Store lub Google Play odnawia się, dopóki nie anulujesz go w sklepie, co najmniej 24 godziny przed końcem okresu. Jeśli sklep pobrał niechciane odnowienie, napisz do nas w ciągu 14 dni, a pomożemy złożyć wniosek w sklepie. Decyduje sklep.",
"e9t": "9. Wyłączenia",
"e9": "Zwrot gestu dobrej woli może zostać odmówiony, jeśli wniosek jest spóźniony, konto zamknięto za złamanie Warunków, ten sam klient prosi ponownie albo zakup był promocyjny lub ze zniżką. To nie odbiera prawa ustawowego. Opłata operatora płatności nie jest powodem odmowy ani obniżenia zwrotu.",
"e10t": "10. Jak złożyć wniosek",
"e10": "Podaj Account ID, sposób płatności (karta na stronie, krypto, App Store lub Google Play), numer zamówienia lub faktury i datę. Powód jest opcjonalny. E-mail: support@simnetiq.com. Nie wysyłaj numeru karty, frazy seed ani klucza prywatnego. Wniosek ze strony staramy się potwierdzić w 2 dni robocze.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.com. Konsumenci z UE mogą też skorzystać z platformy ODR Komisji Europejskiej: https://ec.europa.eu/consumers/odr.",
"at": "Account ID i odzyskiwanie",
"ai2": "Konto Doppler to anonimowy Account ID. To nie jest logowanie e-mailem, a język aplikacji nie jest krajem, w którym mieszkasz.",
"w1t": "Czym jest Account ID",
"w1": "ID ma postać VPN-XXXX-XXXX-XXXX. Aplikacja tworzy je przy pierwszym uruchomieniu. Strona może je utworzyć przy płatności. Jest w Profilu lub Ustawieniach, w sekcji Konto. Używaj tego samego ID na każdym urządzeniu i trzymaj je w tajemnicy. Pomoc nie prosi o numer karty.",
"w2t": "Jeśli je zgubisz",
"w2": "Jeśli powiązałeś e-mail, otwórz Pomoc i wybierz przywrócenie konta. Wyślemy ID na ten e-mail. Jeśli nic nie jest powiązane, złóż zgłoszenie. Wklejony ID sam nie dowodzi, że konto jest twoje.",
"w3t": "Język to nie miejsce zamieszkania",
"w3": "Rosyjski ani żaden inny język nie mówi, w jakim kraju mieszkasz ani czy dotyczy cię zasada sankcyjna.",
"w4t": "Usuwanie konta",
"w4": "Usunięcie konta w aplikacji lub na stronie usuwania usuwa całe konto Doppler. Nie usuwa samego kontaktu pomocy. Płatny dostęp musi najpierw wygasnąć albo zostać anulowany. Nie ma jeszcze osobnej publicznej strony do usunięcia tylko kontaktu pomocy.",
"bt": "Dostęp na stronie i subskrypcje sklepów",
"bi": "Miejsce płatności decyduje, czy dostęp się odnawia i kto może zwrócić pieniądze.",
"b1t": "Jednorazowy dostęp na stronie",
"b1": "Strona pobiera raz opłatę za wybrany okres: miesiąc, 6 miesięcy albo rok. Nie ma automatycznego odnowienia ani zapisanej karty na kolejną płatność. Karta idzie przez Revolut, krypto przez OxaPay. Aplikację Windows i APK Androida kupuje się na stronie.",
"b2t": "Apple Pay i Google Pay na stronie",
"b2": "Apple Pay i Google Pay na stronie to portfele przy płatności kartą. To nie są subskrypcje App Store ani Google Play.",
"b3t": "App Store i Google Play",
"b3": "Te sklepy sprzedają subskrypcje z automatycznym odnowieniem. Nowi klienci sklepu mają 3 dni próbne. Anuluj w sklepie co najmniej 24 godziny przed odnowieniem. Jedna subskrypcja sklepu przypisuje Pro do jednego Account ID.",
"b4t": "Czego nie sprzedajemy",
"b4": "Nie ma zakupu za Telegram Stars, zakupu w Microsoft Store ani doładowania salda. Aplikacja Windows to bezpośredni instalator.",
"ct": "Przywróć, anuluj albo zwróć",
"ci": "Przywrócenie, anulowanie i zwrot to różne czynności.",
"c1t": "Przywrócenie",
"c1": "Przywrócenie umieszcza już opłacony dostęp na Account ID. W aplikacji z App Store lub Google Play otwórz Profil, Subskrypcję, a potem Przywróć zakupy. Przywrócenie na innym Account ID przenosi tam Pro. Zakup ze strony widać, gdy aplikacja jest zalogowana tym Account ID, którego użyto przy płatności. Uruchom aplikację ponownie, jeśli go nie widać. APK nie ma przycisku przywracania.",
"c2t": "Anulowanie",
"c2": "Anulowanie zatrzymuje kolejne odnowienie w sklepie. Samo w sobie nie zwraca pieniędzy. Na iPhonie: Ustawienia, twoje imię, Subskrypcje, Doppler VPN, Anuluj. Na Androidzie: Sklep Play, profil, Płatności i subskrypcje, Subskrypcje, Anuluj. Zakup na stronie się nie odnawia, więc nie ma czego anulować.",
"c3t": "Zwrot",
"c3": "Zwrot to prośba o pieniądze z powrotem. Polityka zwrotów opisuje kroki dla karty na stronie, krypto, App Store i Google Play. Nie wysyłaj numeru karty.",
"gt": "Poradniki", "g1": "Account ID i odzyskiwanie", "g2": "Dostęp na stronie i subskrypcje sklepów", "g3": "Przywróć, anuluj albo zwróć", "g4": "Zwroty",
"faq": "Klienci z UE, EOG i Wielkiej Brytanii mają 14 dni na odstąpienie. Dla pozostałych opublikowany zwrot gestu dobrej woli to 30 dni i tylko pierwszy zakup; promocje i zniżki są wyłączone. Zwroty App Store obsługuje Apple, a Google Play — Google. Przy karcie lub krypto na stronie podaj pomocy Account ID i numer zamówienia. Nie wysyłaj numeru karty.",
"home": "Klienci z UE, EOG i Wielkiej Brytanii mają 14 dni na odstąpienie. Dla pozostałych opublikowany zwrot gestu dobrej woli to 30 dni i tylko pierwszy zakup; promocje i zniżki są wyłączone. Karta i krypto na stronie: napisz na support@simnetiq.com i podaj Account ID. Nie wysyłaj numeru karty. Zwroty App Store i Google Play zgłasza się w sklepie. Zobacz politykę zwrotów na tej stronie.",
"guar": "Klienci z UE, EOG i Wielkiej Brytanii mają 14 dni na odstąpienie. Dla pozostałych opublikowany zwrot gestu dobrej woli to 30 dni i tylko pierwszy zakup; promocje i zniżki są wyłączone. Płatność na stronie jest jednorazowa i nie odnawia się sama. Plany App Store i Google Play odnawiają się, dopóki ich nie anulujesz.",
"foot": "Bezpieczna płatność kartą (Revolut) lub krypto (OxaPay). Płatność na stronie jest jednorazowa i nie odnawia się sama.",
"sub": "Jednorazowa płatność kartą (Revolut) lub krypto (OxaPay). Bez automatycznego odnowienia. Klienci z UE, EOG i Wielkiej Brytanii mają 14 dni na odstąpienie. Gdzie indziej opublikowany zwrot gestu dobrej woli to 30 dni i tylko pierwszy zakup.",
"eb": "14 dni na odstąpienie w UE, EOG i Wielkiej Brytanii. Dla pozostałych klientów zwrot gestu dobrej woli 30 dni na pierwszy zakup.",
"er": "Jeśli Doppler VPN ci nie służy, odpowiedz na tego e-maila albo napisz na {email}, podając numer zamówienia i Account ID. Nie wysyłaj numeru karty. Zwrot płatności ze strony dotyczy zapłaconej kwoty.",
"pt": "Kontakt pomocy i usunięcie konta",
"pc": "Powiązanie e-maila lub Telegramu do odzyskania albo pomocy nie jest usunięciem konta. Strona usuwania kasuje konto Doppler. Nie usuwa samego kontaktu pomocy. Zapisy płatności mogą być przechowywane, gdy wymaga tego prawo. Nie ma osobnej publicznej strony do usunięcia tylko kontaktu pomocy.",
}))
print("ok pl")
