#!/usr/bin/env python3
"""Refund/help packs: uk, sk, hu, ro, bg, hr, sl, el, ca."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pack_rows import L, save

UK = {
"u": "Останнє оновлення: 28 вересня 2026",
"rt": "Повернення коштів",
"ri": "Ця політика стосується покупок Doppler VPN у SIMNETIQ LTD (номер 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Доступ на сайті — одноразова оплата. Плани App Store і Google Play продовжуються, доки ви їх не скасуєте в магазині.",
"ai": "Інструкція Apple щодо повернення", "ar": "Повідомити Apple про проблему", "gi": "Правила повернення Google Play",
"e1t": "1. Відмова в ЄС/ЄЕЗ (14 днів)",
"e1": "Якщо ви споживач у Європейському Союзі або ЄЕЗ, можете відмовитися протягом 14 днів без пояснення причин. Напишіть на support@simnetiq.com до закінчення 14 днів. Ми повертаємо сплачену суму і не утримуємо комісію платіжного оператора. Відрахування за вже надану послугу не є автоматичним. Покупки в App Store або Google Play подаються в тому магазині.",
"e2t": "2. Відмова у Сполученому Королівстві (14 днів)",
"e2": "Якщо ви споживач у Сполученому Королівстві, маєте 14 днів на відмову згідно з Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Надішліть чітку заяву на support@simnetiq.com. Ми повертаємо сплачену суму і не утримуємо комісію оператора. Відрахування за вже надану послугу не є автоматичним, а одне підключення саме по собі не є причиною відмови.",
"e3t": "3. Повернення з доброї волі протягом 30 днів",
"e3": "Для клієнтів поза ЄС, ЄЕЗ і Сполученим Королівством опублікована добра воля — 30 днів від першої покупки, один раз на клієнта. Промо та знижкові покупки виключені, якщо закон не вимагає іншого. Якщо повернення надано, воно стосується сплаченої суми. Напишіть на support@simnetiq.com і вкажіть Account ID та номер замовлення.",
"e4t": "4. Оплата карткою на сайті",
"e4": "Оплати карткою на сайті, зокрема Apple Pay і Google Pay на цій сторінці, обробляє Revolut. Це не покупки App Store чи Google Play. Напишіть на support@simnetiq.com, вкажіть Account ID і номер замовлення. Не надсилайте номер картки. Ця політика не утримує комісію оператора. Банк вирішує, коли з’явиться зарахування.",
"e5t": "5. Оплата криптовалютою (OxaPay)",
"e5": "Криптооплати на сайті обробляє OxaPay. Напишіть на support@simnetiq.com і вкажіть Account ID, номер рахунку, монету та мережу. Ми не вгадуємо адресу відправника. Вкажіть адресу гаманця. Перед надсиланням підтверджуємо актив, мережу та суму. Ця політика не утримує мережеві комісії чи зміну ціни.",
"e6t": "6. App Store",
"e6": "Про повернення в App Store вирішує Apple. Ми не обіцяємо схвалення чи кількість днів. Посилання нижче. Допомога з Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Про повернення в Google Play вирішує Google. Це залежить від продукту, часу з моменту оплати, країни та причини. Ми не перетворюємо один опублікований строк на загальну відмову і не обіцяємо схвалення. Посилання нижче.",
"e8t": "8. Продовження",
"e8": "Покупка на сайті охоплює вибраний період. Вона не продовжується сама і немає плати за продовження для повернення. План App Store або Google Play продовжується, доки ви не скасуєте його в магазині щонайменше за 24 години до кінця періоду. Якщо магазин стягнув небажане продовження, напишіть нам протягом 14 днів — допоможемо подати запит у магазині. Рішення приймає магазин.",
"e9t": "9. Виключення",
"e9": "Повернення з доброї волі може бути відхилено, якщо запит запізнілий, обліковий запис закрито за порушення Умов, той самий клієнт просить знову або покупка була промо чи зі знижкою. Це не скасовує законних прав. Комісія платіжного оператора не є причиною відмови чи зменшення повернення.",
"e10t": "10. Як подати запит",
"e10": "Вкажіть Account ID, спосіб оплати (картка на сайті, крипто, App Store або Google Play), номер замовлення чи рахунку та дату. Причина необов’язкова. E-mail: support@simnetiq.com. Не надсилайте номер картки, seed-фразу чи приватний ключ. Запит із сайту намагаємося підтвердити протягом 2 робочих днів.",
"e11t": "11. Контакт",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.com. Споживачі з ЄС також можуть скористатися платформою ODR Європейської комісії: https://ec.europa.eu/consumers/odr.",
"at": "Account ID і відновлення",
"ai2": "Обліковий запис Doppler — це анонімний Account ID. Це не вхід за e-mail, а мова додатка не є країною проживання.",
"w1t": "Що таке Account ID",
"w1": "ID має вигляд VPN-XXXX-XXXX-XXXX. Додаток створює його при першому запуску. Сайт може створити його під час оплати. Він у Профілі або Налаштуваннях, у розділі Обліковий запис. Використовуйте той самий ID на кожному пристрої й тримайте його в таємниці. Підтримка не просить номер картки.",
"w2t": "Якщо ви його втратили",
"w2": "Якщо прив’язано e-mail, відкрийте Допомогу і виберіть відновлення облікового запису. Ми надішлемо ID на цей e-mail. Якщо нічого не прив’язано, подайте звернення. Вставлений ID сам по собі не доводить, що обліковий запис ваш.",
"w3t": "Мова — це не місце проживання",
"w3": "Російська чи будь-яка інша мова не означає, у якій країні ви живете і чи стосується вас санкційне правило.",
"w4t": "Видалення облікового запису",
"w4": "Видалення облікового запису в додатку або на сторінці видалення видаляє весь обліковий запис Doppler. Воно не видаляє лише контакт підтримки. Платний доступ спочатку має закінчитися або бути скасованим. Окремої публічної сторінки лише для видалення контакту підтримки ще немає.",
"bt": "Доступ на сайті та підписки магазинів",
"bi": "Місце оплати визначає, чи доступ продовжується і хто може повернути гроші.",
"b1t": "Одноразовий доступ на сайті",
"b1": "Сайт стягує один раз плату за вибраний період: місяць, 6 місяців або рік. Немає автоматичного продовження й збереженої картки для наступної оплати. Картка йде через Revolut, крипто — через OxaPay. Додаток Windows і APK Android купують на сайті.",
"b2t": "Apple Pay і Google Pay на сайті",
"b2": "Apple Pay і Google Pay на сайті — це гаманці при оплаті карткою. Це не підписки App Store чи Google Play.",
"b3t": "App Store і Google Play",
"b3": "Ці магазини продають підписки з автоматичним продовженням. Нові клієнти магазину мають 3 дні пробного періоду. Скасуйте в магазині щонайменше за 24 години до продовження. Одна підписка магазину призначає Pro одному Account ID.",
"b4t": "Чого ми не продаємо",
"b4": "Немає покупки за Telegram Stars, покупки в Microsoft Store чи поповнення балансу. Додаток Windows — прямий інсталятор.",
"ct": "Відновити, скасувати або повернути",
"ci": "Відновлення, скасування і повернення — різні дії.",
"c1t": "Відновлення",
"c1": "Відновлення розміщує вже оплачений доступ на Account ID. У додатку з App Store або Google Play відкрийте Профіль, Підписку, потім Відновити покупки. Відновлення на іншому Account ID переносить туди Pro. Покупку з сайту видно, коли додаток увійшов із тим Account ID, що використовувався при оплаті. Перезапустіть додаток, якщо його не видно. APK не має кнопки відновлення.",
"c2t": "Скасування",
"c2": "Скасування зупиняє наступне продовження в магазині. Саме по собі воно не повертає гроші. На iPhone: Налаштування, ваше ім’я, Підписки, Doppler VPN, Скасувати. На Android: Play Store, профіль, Платежі та підписки, Підписки, Скасувати. Покупка на сайті не продовжується, тож скасовувати нічого.",
"c3t": "Повернення",
"c3": "Повернення — це прохання повернути гроші. Політика повернень описує кроки для картки на сайті, крипто, App Store і Google Play. Не надсилайте номер картки.",
"gt": "Посібники", "g1": "Account ID і відновлення", "g2": "Доступ на сайті та підписки магазинів", "g3": "Відновити, скасувати або повернути", "g4": "Повернення коштів",
"faq": "Клієнти з ЄС, ЄЕЗ і Сполученого Королівства мають 14 днів на відмову. Для інших опубліковане повернення з доброї волі — 30 днів і лише перша покупка; промо та знижки виключені. Повернення App Store обробляє Apple, а Google Play — Google. Для картки чи крипто на сайті повідомте підтримці Account ID і номер замовлення. Не надсилайте номер картки.",
"home": "Клієнти з ЄС, ЄЕЗ і Сполученого Королівства мають 14 днів на відмову. Для інших опубліковане повернення з доброї волі — 30 днів і лише перша покупка; промо та знижки виключені. Картка і крипто на сайті: напишіть на support@simnetiq.com і вкажіть Account ID. Не надсилайте номер картки. Повернення App Store і Google Play подаються в магазині. Див. політику повернень на цій сторінці.",
"guar": "Клієнти з ЄС, ЄЕЗ і Сполученого Королівства мають 14 днів на відмову. Для інших опубліковане повернення з доброї волі — 30 днів і лише перша покупка; промо та знижки виключені. Оплата на сайті одноразова і не продовжується сама. Плани App Store і Google Play продовжуються, доки їх не скасуєте.",
"foot": "Безпечна оплата карткою (Revolut) або крипто (OxaPay). Оплата на сайті одноразова і не продовжується сама.",
"sub": "Одноразова оплата карткою (Revolut) або крипто (OxaPay). Без автоматичного продовження. Клієнти з ЄС, ЄЕЗ і Сполученого Королівства мають 14 днів на відмову. В інших країнах опубліковане повернення з доброї волі — 30 днів і лише перша покупка.",
"eb": "14 днів на відмову в ЄС, ЄЕЗ і Сполученому Королівстві. Для інших клієнтів повернення з доброї волі 30 днів на першу покупку.",
"er": "Якщо Doppler VPN вам не підходить, відповіть на цей e-mail або напишіть на {email}, вказавши номер замовлення та Account ID. Не надсилайте номер картки. Повернення оплати з сайту стосується сплаченої суми.",
"pt": "Контакт підтримки та видалення облікового запису",
"pc": "Прив’язка e-mail або Telegram для відновлення чи допомоги — це не видалення облікового запису. Сторінка видалення стирає обліковий запис Doppler. Вона не видаляє лише контакт підтримки. Платіжні записи можуть зберігатися, коли цього вимагає закон. Немає окремої публічної сторінки лише для видалення контакту підтримки.",
}

SK = {
"u": "Posledná aktualizácia: 28. septembra 2026",
"rt": "Vrátenia peňazí",
"ri": "Táto politika sa týka nákupov Doppler VPN od SIMNETIQ LTD (číslo 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Prístup na webe je jednorazová platba. Plány App Store a Google Play sa obnovujú, kým ich v obchode nezrušíte.",
"ai": "Pokyny Apple k vráteniu", "ar": "Nahlásiť problém spoločnosti Apple", "gi": "Pravidlá vrátenia Google Play",
"e1t": "1. Odstúpenie v EÚ/EHP (14 dní)",
"e1": "Ak ste spotrebiteľ v Európskej únii alebo EHP, môžete odstúpiť do 14 dní bez uvedenia dôvodu. Napíšte na support@simnetiq.com pred koncom 14 dní. Vrátime zaplatenú sumu a neodrátame poplatok platobného operátora. Odpočet za už poskytnutú službu nie je automatický. Nákupy v App Store alebo Google Play sa uplatňujú v tom obchode.",
"e2t": "2. Odstúpenie v Spojenom kráľovstve (14 dní)",
"e2": "Ak ste spotrebiteľ v Spojenom kráľovstve, máte 14 dní na odstúpenie podľa Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Pošlite jasné vyhlásenie na support@simnetiq.com. Vrátime zaplatenú sumu a neodrátame poplatok operátora. Odpočet za už poskytnutú službu nie je automatický a jedno pripojenie samo osebe nie je dôvodom na odmietnutie.",
"e3t": "3. Dobrovoľné vrátenie do 30 dní",
"e3": "Pre zákazníkov mimo EÚ, EHP a Spojeného kráľovstva je zverejnená dobrá vôľa 30 dní od prvého nákupu, raz na zákazníka. Promo a zľavnené nákupy sú vylúčené, pokiaľ zákon nevyžaduje inak. Ak sa vrátenie schváli, ide o zaplatenú sumu. Napíšte na support@simnetiq.com a uveďte Account ID a číslo objednávky.",
"e4t": "4. Platba kartou na webe",
"e4": "Platby kartou na webe vrátane Apple Pay a Google Pay na tejto stránke spracúva Revolut. Nie sú to nákupy App Store ani Google Play. Napíšte na support@simnetiq.com, uveďte Account ID a číslo objednávky. Neposielajte číslo karty. Táto politika neodrátava poplatok operátora. Banka rozhoduje, kedy sa pripíše dobropis.",
"e5t": "5. Platba kryptom (OxaPay)",
"e5": "Kryptoplatby na webe spracúva OxaPay. Napíšte na support@simnetiq.com a uveďte Account ID, číslo faktúry, mincu a sieť. Nehádame adresu odosielateľa. Uveďte adresu peňaženky. Pred odoslaním potvrdíme aktívum, sieť a sumu. Táto politika nezadržiava sieťové poplatky ani zmenu ceny.",
"e6t": "6. App Store",
"e6": "O vrátení v App Store rozhoduje Apple. Nesľubujeme schválenie ani počet dní. Odkazy sú nižšie. Pomoc s Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "O vrátení v Google Play rozhoduje Google. Závisí to od produktu, času od platby, krajiny a dôvodu. Z jedného zverejneného termínu nerobíme všeobecné odmietnutie a nesľubujeme schválenie. Odkaz je nižšie.",
"e8t": "8. Obnovenia",
"e8": "Nákup na webe pokrýva zvolené obdobie. Neobnovuje sa sám a nie je tu poplatok za obnovenie na vrátenie. Plán App Store alebo Google Play sa obnovuje, kým ho v obchode nezrušíte aspoň 24 hodín pred koncom obdobia. Ak obchod strhol neželané obnovenie, napíšte nám do 14 dní a pomôžeme podať žiadosť v obchode. Rozhoduje obchod.",
"e9t": "9. Vylúčenia",
"e9": "Dobrovoľné vrátenie môže byť odmietnuté, ak je žiadosť oneskorená, účet bol zatvorený za porušenie Podmienok, ten istý zákazník žiada znova alebo nákup bol promo či zľavnený. To neoberá o zákonné práva. Poplatok platobného operátora nie je dôvodom na odmietnutie ani zníženie vrátenia.",
"e10t": "10. Ako podať žiadosť",
"e10": "Uveďte Account ID, spôsob platby (karta na webe, krypto, App Store alebo Google Play), číslo objednávky alebo faktúry a dátum. Dôvod je voliteľný. E-mail: support@simnetiq.com. Neposielajte číslo karty, seed frázu ani súkromný kľúč. Žiadosť z webu sa snažíme potvrdiť do 2 pracovných dní.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.com. Spotrebitelia z EÚ môžu využiť aj platformu ODR Európskej komisie: https://ec.europa.eu/consumers/odr.",
"at": "Account ID a obnovenie",
"ai2": "Účet Doppler je anonymné Account ID. Nie je to prihlásenie e-mailom a jazyk aplikácie nie je krajina, v ktorej bývate.",
"w1t": "Čo je Account ID",
"w1": "ID má tvar VPN-XXXX-XXXX-XXXX. Aplikácia ho vytvorí pri prvom spustení. Web ho môže vytvoriť pri platbe. Je v Profile alebo Nastaveniach, v sekcii Účet. Používajte rovnaké ID na každom zariadení a majte ho v tajnosti. Podpora nežiada číslo karty.",
"w2t": "Ak ho stratíte",
"w2": "Ak ste prepojili e-mail, otvorte Pomoc a vyberte obnovenie účtu. Pošleme ID na tento e-mail. Ak nič nie je prepojené, podajte ticket. Vložené ID samo osebe nedokazuje, že účet je váš.",
"w3t": "Jazyk nie je bydlisko",
"w3": "Ruština ani žiadny iný jazyk nehovorí, v ktorej krajine bývate ani či sa na vás vzťahuje sankčné pravidlo.",
"w4t": "Odstránenie účtu",
"w4": "Odstránenie účtu v aplikácii alebo na stránke odstránenia odstráni celý účet Doppler. Neodstráni len kontakt podpory. Platený prístup musí najprv vypršať alebo byť zrušený. Samostatná verejná stránka len na odstránenie kontaktu podpory zatiaľ nie je.",
"bt": "Prístup na webe a predplatné obchodov",
"bi": "Miesto platby rozhoduje, či sa prístup obnovuje a kto môže vrátiť peniaze.",
"b1t": "Jednorazový prístup na webe",
"b1": "Web strhne raz poplatok za zvolené obdobie: mesiac, 6 mesiacov alebo rok. Nie je automatické obnovenie ani uložená karta na ďalšiu platbu. Karta ide cez Revolut, krypto cez OxaPay. Aplikáciu Windows a APK Androidu kupujete na webe.",
"b2t": "Apple Pay a Google Pay na webe",
"b2": "Apple Pay a Google Pay na webe sú peňaženky pri platbe kartou. Nie sú to predplatné App Store ani Google Play.",
"b3t": "App Store a Google Play",
"b3": "Tieto obchody predávajú predplatné s automatickým obnovením. Noví zákazníci obchodu majú 3 dni skúšky. Zrušte v obchode aspoň 24 hodín pred obnovením. Jedno predplatné obchodu priradí Pro jednému Account ID.",
"b4t": "Čo nepredávame",
"b4": "Nie je nákup za Telegram Stars, nákup v Microsoft Store ani dobitie zostatku. Aplikácia Windows je priamy inštalátor.",
"ct": "Obnoviť, zrušiť alebo vrátiť",
"ci": "Obnovenie, zrušenie a vrátenie sú rôzne úkony.",
"c1t": "Obnovenie",
"c1": "Obnovenie umiestni už zaplatený prístup na Account ID. V aplikácii z App Store alebo Google Play otvorte Profil, Predplatné a potom Obnoviť nákupy. Obnovenie na inom Account ID tam prenesie Pro. Nákup z webu je viditeľný, keď je aplikácia prihlásená s Account ID použitým pri platbe. Ak chýba, spustite aplikáciu znova. APK nemá tlačidlo obnovenia.",
"c2t": "Zrušenie",
"c2": "Zrušenie zastaví ďalšie obnovenie v obchode. Samo osebe nevracia peniaze. Na iPhone: Nastavenia, vaše meno, Predplatné, Doppler VPN, Zrušiť. Na Androide: Obchod Play, profil, Platby a predplatné, Predplatné, Zrušiť. Nákup na webe sa neobnovuje, takže nie je čo zrušiť.",
"c3t": "Vrátenie",
"c3": "Vrátenie je žiadosť o peniaze späť. Politika vrátenia popisuje kroky pre kartu na webe, krypto, App Store a Google Play. Neposielajte číslo karty.",
"gt": "Návody", "g1": "Account ID a obnovenie", "g2": "Prístup na webe a predplatné obchodov", "g3": "Obnoviť, zrušiť alebo vrátiť", "g4": "Vrátenia peňazí",
"faq": "Zákazníci z EÚ, EHP a Spojeného kráľovstva majú 14 dní na odstúpenie. Pre ostatných je zverejnené dobrovoľné vrátenie 30 dní a len prvý nákup; promo a zľavy sú vylúčené. Vrátenia App Store rieši Apple a Google Play Google. Pri karte alebo kryptu na webe uveďte podpore Account ID a číslo objednávky. Neposielajte číslo karty.",
"home": "Zákazníci z EÚ, EHP a Spojeného kráľovstva majú 14 dní na odstúpenie. Pre ostatných je zverejnené dobrovoľné vrátenie 30 dní a len prvý nákup; promo a zľavy sú vylúčené. Karta a krypto na webe: napíšte na support@simnetiq.com a uveďte Account ID. Neposielajte číslo karty. Vrátenia App Store a Google Play sa uplatňujú v obchode. Pozrite politiku vrátenia na tejto stránke.",
"guar": "Zákazníci z EÚ, EHP a Spojeného kráľovstva majú 14 dní na odstúpenie. Pre ostatných je zverejnené dobrovoľné vrátenie 30 dní a len prvý nákup; promo a zľavy sú vylúčené. Platba na webe je jednorazová a neobnovuje sa sama. Plány App Store a Google Play sa obnovujú, kým ich nezrušíte.",
"foot": "Bezpečná platba kartou (Revolut) alebo kryptom (OxaPay). Platba na webe je jednorazová a neobnovuje sa sama.",
"sub": "Jednorazová platba kartou (Revolut) alebo kryptom (OxaPay). Bez automatického obnovenia. Zákazníci z EÚ, EHP a Spojeného kráľovstva majú 14 dní na odstúpenie. Inde je zverejnené dobrovoľné vrátenie 30 dní a len prvý nákup.",
"eb": "14 dní na odstúpenie v EÚ, EHP a Spojenom kráľovstve. Pre ostatných zákazníkov dobrovoľné vrátenie 30 dní na prvý nákup.",
"er": "Ak vám Doppler VPN nevyhovuje, odpovedzte na tento e-mail alebo napíšte na {email} s číslom objednávky a Account ID. Neposielajte číslo karty. Vrátenie platby z webu sa týka zaplatenej sumy.",
"pt": "Kontakt podpory a odstránenie účtu",
"pc": "Prepojenie e-mailu alebo Telegramu na obnovenie alebo pomoc nie je odstránenie účtu. Stránka odstránenia zmaže účet Doppler. Neodstráni len kontakt podpory. Platobné záznamy môžu byť uchované, keď to vyžaduje zákon. Nie je samostatná verejná stránka len na odstránenie kontaktu podpory.",
}

HU = {
"u": "Utolsó frissítés: 2026. szeptember 28.",
"rt": "Visszatérítések",
"ri": "Ez a szabályzat a SIMNETIQ LTD (cégjegyzékszám 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom által értékesített Doppler VPN vásárlásokra vonatkozik. A webhelyes hozzáférés egyszeri fizetés. Az App Store és a Google Play csomagok addig újulnak meg, amíg a boltban le nem mondja őket.",
"ai": "Apple visszatérítési útmutató", "ar": "Probléma bejelentése az Apple-nek", "gi": "Google Play visszatérítési szabályok",
"e1t": "1. Elállás az EU/EGT területén (14 nap)",
"e1": "Ha az Európai Unióban vagy az EGT-ben fogyasztó, 14 napon belül indoklás nélkül elállhat. Írjon a support@simnetiq.com címre a 14 nap lejárta előtt. A befizetett összeget visszatérítjük, és nem vonjuk le a fizetési szolgáltató díját. A már igénybe vett szolgáltatás miatti levonás nem automatikus. Az App Store vagy Google Play vásárlásokat abban a boltban kell kérvényezni.",
"e2t": "2. Elállás az Egyesült Királyságban (14 nap)",
"e2": "Ha az Egyesült Királyságban fogyasztó, 14 napja van elállni a Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 alapján. Küldjön egyértelmű nyilatkozatot a support@simnetiq.com címre. A befizetett összeget visszatérítjük, és nem vonjuk le a szolgáltatói díjat. A már igénybe vett szolgáltatás miatti levonás nem automatikus, és egyetlen csatlakozás önmagában nem elutasítási ok.",
"e3t": "3. 30 napos jóindulatú visszatérítés",
"e3": "Az EU-n, az EGT-n és az Egyesült Királyságon kívüli ügyfeleknek a közzétett jóindulat 30 nap az első vásárlástól, ügyfélenként egyszer. A promóciós és kedvezményes vásárlások ki vannak zárva, kivéve ha a törvény mást ír elő. Ha a visszatérítést megadják, a befizetett összegre vonatkozik. Írjon a support@simnetiq.com címre, és adja meg az Account ID-t és a rendelési számot.",
"e4t": "4. Kártyás fizetés a webhelyen",
"e4": "A webhelyes kártyás fizetéseket, beleértve az Apple Pay-t és a Google Pay-t ezen az oldalon, a Revolut kezeli. Ezek nem App Store vagy Google Play vásárlások. Írjon a support@simnetiq.com címre, adja meg az Account ID-t és a rendelési számot. Ne küldje el a kártyaszámot. Ez a szabályzat nem vonja le a szolgáltatói díjat. A bank dönti el, mikor jelenik meg a jóváírás.",
"e5t": "5. Kriptofizetés (OxaPay)",
"e5": "A webhelyes kriptofizetéseket az OxaPay kezeli. Írjon a support@simnetiq.com címre, és adja meg az Account ID-t, a számla számát, az érmét és a hálózatot. Nem találgatjuk a küldő címet. Adja meg a tárca címét. Küldés előtt megerősítjük az eszközt, a hálózatot és az összeget. Ez a szabályzat nem tartja meg a hálózati díjakat vagy az árváltozást.",
"e6t": "6. App Store",
"e6": "Az App Store visszatérítésről az Apple dönt. Nem ígérünk jóváhagyást vagy napok számát. A linkek lent vannak. Account ID segítség: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "A Google Play visszatérítésről a Google dönt. A terméktől, a fizetés óta eltelt időtől, az országtól és az indoktól függ. Egy közzétett határidőből nem csinálunk általános elutasítást, és nem ígérünk jóváhagyást. A link lent van.",
"e8t": "8. Megújítások",
"e8": "A webhelyes vásárlás a választott időszakra szól. Magától nem újul meg, és nincs megújítási díj, amit vissza kellene téríteni. Az App Store vagy Google Play csomag addig újul meg, amíg a boltban legalább 24 órával az időszak vége előtt le nem mondja. Ha a bolt nem kívánt megújítást vont le, írjon nekünk 14 napon belül, és segítünk a bolti kérelmet benyújtani. A bolt dönt.",
"e9t": "9. Kizárások",
"e9": "A jóindulatú visszatérítés elutasítható, ha a kérelem késő, a fiókot a Feltételek megsértése miatt zárták, ugyanaz az ügyfél újra kér, vagy a vásárlás promóciós vagy kedvezményes volt. Ez nem vonja el a törvényes jogokat. A fizetési szolgáltató díja nem ok a visszatérítés elutasítására vagy csökkentésére.",
"e10t": "10. Hogyan nyújtson be kérelmet",
"e10": "Adja meg az Account ID-t, a fizetési módot (webhelyes kártya, kriptó, App Store vagy Google Play), a rendelési vagy számla számát és a dátumot. Az indok opcionális. E-mail: support@simnetiq.com. Ne küldjön kártyaszámot, seed mondatot vagy privát kulcsot. A webhelyes kérelmet igyekszünk 2 munkanapon belül visszaigazolni.",
"e11t": "11. Kapcsolat",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.com. Az EU fogyasztói az Európai Bizottság ODR platformját is használhatják: https://ec.europa.eu/consumers/odr.",
"at": "Account ID és helyreállítás",
"ai2": "A Doppler-fiók egy névtelen Account ID. Nem e-mailes bejelentkezés, és az alkalmazás nyelve nem a lakóhely országa.",
"w1t": "Mi az Account ID",
"w1": "Az ID formája VPN-XXXX-XXXX-XXXX. Az alkalmazás az első indításkor létrehozza. A webhely a fizetéskor létrehozhatja. A Profilban vagy a Beállításokban, a Fiók részben található. Használja ugyanazt az ID-t minden eszközön, és tartsa titokban. A támogatás nem kér kártyaszámot.",
"w2t": "Ha elveszíti",
"w2": "Ha e-mailt társított, nyissa meg a Súgót, és válassza a fiókhelyreállítást. Az ID-t erre az e-mailre küldjük. Ha semmi nincs társítva, nyisson jegyet. A beillesztett ID önmagában nem bizonyítja, hogy a fiók az Öné.",
"w3t": "A nyelv nem lakóhely",
"w3": "Az orosz vagy bármely más nyelv nem mondja meg, melyik országban él, és hogy szankciós szabály vonatkozik-e Önre.",
"w4t": "Fiók törlése",
"w4": "A fiók törlése az alkalmazásban vagy a törlési oldalon a teljes Doppler-fiókot törli. Nem csak a támogatási kapcsolatot távolítja el. A fizetett hozzáférésnek előbb le kell járnia vagy meg kell szűnnie. Külön nyilvános oldal csak a támogatási kapcsolat eltávolítására még nincs.",
"bt": "Webhelyes hozzáférés és bolti előfizetések",
"bi": "A fizetés helye dönti el, hogy a hozzáférés megújul-e, és ki téríthet vissza pénzt.",
"b1t": "Egyszeri webhelyes hozzáférés",
"b1": "A webhely egyszer vonja le a választott időszakra: egy hónap, 6 hónap vagy egy év. Nincs automatikus megújítás és nincs elmentett kártya a következő terheléshez. A kártya a Revoluton, a kriptó az OxaPayen keresztül megy. A Windows alkalmazást és az Android APK-t a webhelyen vásárolja.",
"b2t": "Apple Pay és Google Pay a webhelyen",
"b2": "Az Apple Pay és a Google Pay a webhelyen kártyás fizetési tárcák. Nem App Store vagy Google Play előfizetések.",
"b3t": "App Store és Google Play",
"b3": "Ezek a boltok automatikusan megújuló előfizetéseket árulnak. Az új bolti ügyfelek 3 napos próbaidőt kapnak. Mondja le a boltban legalább 24 órával a megújítás előtt. Egy bolti előfizetés egy Account ID-hez rendeli a Pro-t.",
"b4t": "Amit nem árulunk",
"b4": "Nincs Telegram Stars vásárlás, Microsoft Store vásárlás és egyenlegfeltöltés. A Windows alkalmazás közvetlen telepítő.",
"ct": "Helyreállítás, lemondás vagy visszatérítés",
"ci": "A helyreállítás, a lemondás és a visszatérítés különböző műveletek.",
"c1t": "Helyreállítás",
"c1": "A helyreállítás a már kifizetett hozzáférést egy Account ID-re helyezi. Az App Store vagy Google Play alkalmazásban nyissa meg a Profil, Előfizetés, majd Vásárlások helyreállítása menüt. Másik Account ID-re történő helyreállítás oda viszi a Pro-t. A webhelyes vásárlás akkor látszik, ha az alkalmazás a fizetéskor használt Account ID-vel van bejelentkezve. Indítsa újra az alkalmazást, ha hiányzik. Az APK-nak nincs helyreállítási gombja.",
"c2t": "Lemondás",
"c2": "A lemondás megállítja a következő bolti megújítást. Önmagában nem ad vissza pénzt. iPhone-on: Beállítások, az Ön neve, Előfizetések, Doppler VPN, Lemondás. Androidon: Play Áruház, profil, Fizetések és előfizetések, Előfizetések, Lemondás. A webhelyes vásárlás nem újul meg, tehát nincs mit lemondani.",
"c3t": "Visszatérítés",
"c3": "A visszatérítés a pénz visszaadásának kérése. A visszatérítési szabályzat leírja a lépéseket webhelyes kártyához, kriptóhoz, App Store-hoz és Google Playhez. Ne küldje el a kártyaszámot.",
"gt": "Útmutatók", "g1": "Account ID és helyreállítás", "g2": "Webhelyes hozzáférés és bolti előfizetések", "g3": "Helyreállítás, lemondás vagy visszatérítés", "g4": "Visszatérítések",
"faq": "Az EU, az EGT és az Egyesült Királyság ügyfeleinek 14 napos elállási joga van. Másoknak a közzétett jóindulatú visszatérítés 30 nap, és csak az első vásárlásra; a promók és kedvezmények ki vannak zárva. Az App Store visszatérítéseket az Apple, a Google Playét a Google kezeli. Webhelyes kártyánál vagy kriptónál adja meg a támogatásnak az Account ID-t és a rendelési számot. Ne küldje el a kártyaszámot.",
"home": "Az EU, az EGT és az Egyesült Királyság ügyfeleinek 14 napos elállási joga van. Másoknak a közzétett jóindulatú visszatérítés 30 nap, és csak az első vásárlásra; a promók és kedvezmények ki vannak zárva. Webhelyes kártya és kriptó: írjon a support@simnetiq.com címre, és adja meg az Account ID-t. Ne küldje el a kártyaszámot. Az App Store és Google Play visszatérítéseket a boltban kell kérvényezni. Lásd a visszatérítési szabályzatot ezen az oldalon.",
"guar": "Az EU, az EGT és az Egyesült Királyság ügyfeleinek 14 napos elállási joga van. Másoknak a közzétett jóindulatú visszatérítés 30 nap, és csak az első vásárlásra; a promók és kedvezmények ki vannak zárva. A webhelyes fizetés egyszeri, és magától nem újul meg. Az App Store és Google Play csomagok addig újulnak meg, amíg le nem mondja őket.",
"foot": "Biztonságos kártyás (Revolut) vagy kriptós (OxaPay) fizetés. A webhelyes fizetés egyszeri, és magától nem újul meg.",
"sub": "Egyszeri fizetés kártyával (Revolut) vagy kriptóval (OxaPay). Nincs automatikus megújítás. Az EU, az EGT és az Egyesült Királyság ügyfeleinek 14 napos elállási joga van. Máshol a közzétett jóindulatú visszatérítés 30 nap, és csak az első vásárlásra.",
"eb": "14 napos elállás az EU-ban, az EGT-ben és az Egyesült Királyságban. Más ügyfeleknél 30 napos jóindulatú visszatérítés az első vásárlásra.",
"er": "Ha a Doppler VPN nem felel meg Önnek, válaszoljon erre az e-mailre, vagy írjon a {email} címre a rendelési számmal és az Account ID-vel. Ne küldje el a kártyaszámot. A webhelyes visszatérítés a befizetett összegre vonatkozik.",
"pt": "Támogatási kapcsolat és fióktörlés",
"pc": "E-mail vagy Telegram társítása helyreállításhoz vagy támogatáshoz nem egyenlő a fiók törlésével. A törlési oldal a Doppler-fiókot törli. Nem csak a támogatási kapcsolatot távolítja el. A fizetési nyilvántartások megőrizhetők, ha a törvény előírja. Nincs külön nyilvános oldal csak a támogatási kapcsolat eltávolítására.",
}

RO = {
"u": "Ultima actualizare: 28 septembrie 2026",
"rt": "Rambursări",
"ri": "Această politică acoperă achizițiile Doppler VPN de la SIMNETIQ LTD (număr 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Accesul pe site este o plată unică. Planurile App Store și Google Play se reînnoiesc până le anulezi în magazin.",
"ai": "Instrucțiuni de rambursare Apple", "ar": "Raportează o problemă către Apple", "gi": "Reguli de rambursare Google Play",
"e1t": "1. Retragere în UE/SEE (14 zile)",
"e1": "Dacă ești consumator în Uniunea Europeană sau SEE, poți renunța în 14 zile fără a da un motiv. Scrie la support@simnetiq.com înainte de sfârșitul celor 14 zile. Restituim suma plătită și nu reținem comisionul procesatorului de plăți. Deducerea pentru serviciul deja prestat nu este automată. Achizițiile App Store sau Google Play se solicită în acel magazin.",
"e2t": "2. Retragere în Regatul Unit (14 zile)",
"e2": "Dacă ești consumator în Regatul Unit, ai 14 zile pentru a renunța conform Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Trimite o declarație clară la support@simnetiq.com. Restituim suma plătită și nu reținem comisionul procesatorului. Deducerea pentru serviciul deja prestat nu este automată, iar o singură conexiune nu este în sine un motiv de refuz.",
"e3t": "3. Rambursare de bunăvoință în 30 de zile",
"e3": "Pentru clienții din afara UE, SEE și Regatului Unit, bunăvoința publicată este de 30 de zile de la prima achiziție, o dată per client. Achizițiile promoționale sau cu reducere sunt excluse, cu excepția cazului în care legea cere altfel. Dacă se acordă rambursarea, aceasta privește suma plătită. Scrie la support@simnetiq.com și indică Account ID și numărul comenzii.",
"e4t": "4. Plată cu cardul pe site",
"e4": "Plățile cu cardul pe site, inclusiv Apple Pay și Google Pay pe această pagină, sunt procesate de Revolut. Nu sunt achiziții App Store sau Google Play. Scrie la support@simnetiq.com, indică Account ID și numărul comenzii. Nu trimite numărul cardului. Această politică nu reține comisionul procesatorului. Banca decide când apare creditarea.",
"e5t": "5. Plată cripto (OxaPay)",
"e5": "Plățile cripto pe site sunt procesate de OxaPay. Scrie la support@simnetiq.com și indică Account ID, numărul facturii, moneda și rețeaua. Nu ghicim adresa expeditorului. Indică adresa portofelului. Înainte de trimitere confirmăm activul, rețeaua și suma. Această politică nu reține comisioanele de rețea sau o schimbare de preț.",
"e6t": "6. App Store",
"e6": "Rambursările App Store le decide Apple. Nu promitem aprobarea și nici un număr de zile. Linkurile sunt mai jos. Ajutor pentru Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Rambursările Google Play le decide Google. Depinde de produs, de timpul de la plată, de țară și de motiv. Nu transformăm un termen publicat într-un refuz general și nu promitem aprobarea. Linkul este mai jos.",
"e8t": "8. Reînnoiri",
"e8": "Achiziția pe site acoperă perioada aleasă. Nu se reînnoiește singură și nu există o taxă de reînnoire de rambursat. Un plan App Store sau Google Play se reînnoiește până îl anulezi în magazin cu cel puțin 24 de ore înainte de sfârșitul perioadei. Dacă magazinul a debitat o reînnoire nedorită, scrie-ne în 14 zile și te ajutăm să depui cererea în magazin. Decide magazinul.",
"e9t": "9. Excluderi",
"e9": "Rambursarea de bunăvoință poate fi refuzată dacă cererea este întârziată, contul a fost închis pentru încălcarea Condițiilor, același client cere din nou sau achiziția a fost promoțională ori cu reducere. Asta nu anulează drepturile legale. Comisionul procesatorului de plăți nu este un motiv de refuz sau de reducere a rambursării.",
"e10t": "10. Cum depui cererea",
"e10": "Indică Account ID, metoda de plată (card pe site, cripto, App Store sau Google Play), numărul comenzii sau al facturii și data. Motivul este opțional. E-mail: support@simnetiq.com. Nu trimite numărul cardului, fraza seed sau cheia privată. Cererea de pe site încercăm să o confirmăm în 2 zile lucrătoare.",
"e11t": "11. Contact",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.com. Consumatorii din UE pot folosi și platforma ODR a Comisiei Europene: https://ec.europa.eu/consumers/odr.",
"at": "Account ID și recuperare",
"ai2": "Contul Doppler este un Account ID anonim. Nu este autentificare prin e-mail, iar limba aplicației nu este țara în care locuiești.",
"w1t": "Ce este Account ID",
"w1": "ID-ul are forma VPN-XXXX-XXXX-XXXX. Aplicația îl creează la prima pornire. Site-ul îl poate crea la plată. Se află în Profil sau Setări, la secțiunea Cont. Folosește același ID pe fiecare dispozitiv și păstrează-l secret. Asistența nu cere numărul cardului.",
"w2t": "Dacă îl pierzi",
"w2": "Dacă ai asociat un e-mail, deschide Ajutor și alege recuperarea contului. Trimitem ID-ul pe acel e-mail. Dacă nu este asociat nimic, deschide o solicitare. Un ID lipit nu dovedește singur că contul este al tău.",
"w3t": "Limba nu este reședința",
"w3": "Rusa sau orice altă limbă nu spune în ce țară locuiești și nici dacă te afectează o regulă de sancțiuni.",
"w4t": "Ștergerea contului",
"w4": "Ștergerea contului în aplicație sau pe pagina de ștergere elimină întregul cont Doppler. Nu elimină doar contactul de asistență. Accesul plătit trebuie mai întâi să expire sau să fie anulat. Nu există încă o pagină publică separată doar pentru eliminarea contactului de asistență.",
"bt": "Acces pe site și abonamente din magazine",
"bi": "Locul plății decide dacă accesul se reînnoiește și cine poate returna banii.",
"b1t": "Acces unic pe site",
"b1": "Site-ul taxează o dată perioada aleasă: o lună, 6 luni sau un an. Nu există reînnoire automată și nici card salvat pentru o plată ulterioară. Cardul trece prin Revolut, cripto prin OxaPay. Aplicația Windows și APK-ul Android se cumpără pe site.",
"b2t": "Apple Pay și Google Pay pe site",
"b2": "Apple Pay și Google Pay pe site sunt portofele la plata cu cardul. Nu sunt abonamente App Store sau Google Play.",
"b3t": "App Store și Google Play",
"b3": "Aceste magazine vând abonamente cu reînnoire automată. Clienții noi din magazin au 3 zile de încercare. Anulează în magazin cu cel puțin 24 de ore înainte de reînnoire. Un abonament din magazin atribuie Pro unui singur Account ID.",
"b4t": "Ce nu vindem",
"b4": "Nu există cumpărare cu Telegram Stars, cumpărare din Microsoft Store și nici încărcare de sold. Aplicația Windows este un instalator direct.",
"ct": "Restaurează, anulează sau rambursează",
"ci": "Restaurarea, anularea și rambursarea sunt acțiuni diferite.",
"c1t": "Restaurare",
"c1": "Restaurarea plasează accesul deja plătit pe un Account ID. În aplicația din App Store sau Google Play deschide Profil, Abonament, apoi Restaurează achizițiile. Restaurarea pe un alt Account ID mută Pro acolo. Achiziția de pe site apare când aplicația este autentificată cu Account ID-ul folosit la plată. Repornește aplicația dacă nu apare. APK-ul nu are buton de restaurare.",
"c2t": "Anulare",
"c2": "Anularea oprește următoarea reînnoire din magazin. Singură nu returnează bani. Pe iPhone: Setări, numele tău, Abonamente, Doppler VPN, Anulează. Pe Android: Magazin Play, profil, Plăți și abonamente, Abonamente, Anulează. Achiziția pe site nu se reînnoiește, deci nu e nimic de anulat.",
"c3t": "Rambursare",
"c3": "Rambursarea este cererea de a primi banii înapoi. Politica de rambursări descrie pașii pentru card pe site, cripto, App Store și Google Play. Nu trimite numărul cardului.",
"gt": "Ghiduri", "g1": "Account ID și recuperare", "g2": "Acces pe site și abonamente din magazine", "g3": "Restaurează, anulează sau rambursează", "g4": "Rambursări",
"faq": "Clienții din UE, SEE și Regatul Unit au 14 zile pentru retragere. Pentru ceilalți, rambursarea de bunăvoință publicată este de 30 de zile și doar prima achiziție; promoțiile și reducerile sunt excluse. Rambursările App Store le gestionează Apple, iar pe cele Google Play — Google. La card sau cripto pe site, indică asistenței Account ID și numărul comenzii. Nu trimite numărul cardului.",
"home": "Clienții din UE, SEE și Regatul Unit au 14 zile pentru retragere. Pentru ceilalți, rambursarea de bunăvoință publicată este de 30 de zile și doar prima achiziție; promoțiile și reducerile sunt excluse. Card și cripto pe site: scrie la support@simnetiq.com și indică Account ID. Nu trimite numărul cardului. Rambursările App Store și Google Play se solicită în magazin. Vezi politica de rambursări pe această pagină.",
"guar": "Clienții din UE, SEE și Regatul Unit au 14 zile pentru retragere. Pentru ceilalți, rambursarea de bunăvoință publicată este de 30 de zile și doar prima achiziție; promoțiile și reducerile sunt excluse. Plata pe site este unică și nu se reînnoiește singură. Planurile App Store și Google Play se reînnoiesc până le anulezi.",
"foot": "Plată sigură cu cardul (Revolut) sau cripto (OxaPay). Plata pe site este unică și nu se reînnoiește singură.",
"sub": "Plată unică cu cardul (Revolut) sau cripto (OxaPay). Fără reînnoire automată. Clienții din UE, SEE și Regatul Unit au 14 zile pentru retragere. În altă parte, rambursarea de bunăvoință publicată este de 30 de zile și doar prima achiziție.",
"eb": "14 zile pentru retragere în UE, SEE și Regatul Unit. Pentru ceilalți clienți, rambursare de bunăvoință 30 de zile la prima achiziție.",
"er": "Dacă Doppler VPN nu ți se potrivește, răspunde la acest e-mail sau scrie la {email} cu numărul comenzii și Account ID. Nu trimite numărul cardului. Rambursarea plății de pe site privește suma plătită.",
"pt": "Contact de asistență și ștergerea contului",
"pc": "Asocierea unui e-mail sau Telegram pentru recuperare ori asistență nu este ștergerea contului. Pagina de ștergere șterge contul Doppler. Nu elimină doar contactul de asistență. Înregistrările de plată pot fi păstrate când legea o cere. Nu există o pagină publică separată doar pentru eliminarea contactului de asistență.",
}

BG = {
"u": "Последна актуализация: 28 септември 2026",
"rt": "Възстановявания",
"ri": "Тази политика обхваща покупки на Doppler VPN от SIMNETIQ LTD (номер 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Достъпът през сайта е еднократно плащане. Плановете в App Store и Google Play се подновяват, докато не ги отмените в магазина.",
"ai": "Указания на Apple за възстановяване", "ar": "Докладвайте проблем на Apple", "gi": "Правила за възстановяване в Google Play",
"e1t": "1. Отказ в ЕС/ЕИП (14 дни)",
"e1": "Ако сте потребител в Европейския съюз или ЕИП, можете да се откажете в рамките на 14 дни без да посочвате причина. Пишете на support@simnetiq.com преди края на 14-те дни. Възстановяваме платената сума и не удържаме таксата на платежния оператор. Удръжка за вече предоставена услуга не е автоматична. Покупки в App Store или Google Play се подават в съответния магазин.",
"e2t": "2. Отказ в Обединеното кралство (14 дни)",
"e2": "Ако сте потребител в Обединеното кралство, имате 14 дни за отказ според Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Изпратете ясно изявление на support@simnetiq.com. Възстановяваме платената сума и не удържаме таксата на оператора. Удръжка за вече предоставена услуга не е автоматична, а едно свързване само по себе си не е основание за отказ.",
"e3t": "3. Възстановяване по добра воля в рамките на 30 дни",
"e3": "За клиенти извън ЕС, ЕИП и Обединеното кралство публикуваната добра воля е 30 дни от първата покупка, веднъж на клиент. Промо и намалени покупки са изключени, освен ако законът не изисква друго. Ако възстановяването бъде одобрено, то е за платената сума. Пишете на support@simnetiq.com и посочете Account ID и номер на поръчка.",
"e4t": "4. Плащане с карта на сайта",
"e4": "Плащанията с карта на сайта, включително Apple Pay и Google Pay на тази страница, се обработват от Revolut. Това не са покупки от App Store или Google Play. Пишете на support@simnetiq.com, посочете Account ID и номер на поръчка. Не изпращайте номера на картата. Тази политика не удържа таксата на оператора. Банката решава кога ще се появи заверяването.",
"e5t": "5. Плащане с крипто (OxaPay)",
"e5": "Крипто плащанията на сайта се обработват от OxaPay. Пишете на support@simnetiq.com и посочете Account ID, номер на фактура, монета и мрежа. Не отгатваме адреса на подателя. Посочете адреса на портфейла. Преди изпращане потвърждаваме актива, мрежата и сумата. Тази политика не задържа мрежови такси или промяна в цената.",
"e6t": "6. App Store",
"e6": "За възстановявания в App Store решава Apple. Не обещаваме одобрение или брой дни. Връзките са по-долу. Помощ за Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "За възстановявания в Google Play решава Google. Зависи от продукта, времето от плащането, държавата и причината. Не превръщаме един публикуван срок в общ отказ и не обещаваме одобрение. Връзката е по-долу.",
"e8t": "8. Подновявания",
"e8": "Покупката на сайта покрива избрания период. Не се подновява сама и няма такса за подновяване за възстановяване. План в App Store или Google Play се подновява, докато не го отмените в магазина поне 24 часа преди края на периода. Ако магазинът е таксувал нежелано подновяване, пишете ни в рамките на 14 дни и ще помогнем да подадете заявка в магазина. Решава магазинът.",
"e9t": "9. Изключения",
"e9": "Възстановяване по добра воля може да бъде отказано, ако заявката е закъсняла, акаунтът е затворен заради нарушение на Условията, същият клиент иска отново или покупката е била промо или с намаление. Това не отнема законовите права. Таксата на платежния оператор не е причина за отказ или намаляване на възстановяването.",
"e10t": "10. Как да подадете заявка",
"e10": "Посочете Account ID, начин на плащане (карта на сайта, крипто, App Store или Google Play), номер на поръчка или фактура и датата. Причината е по избор. Имейл: support@simnetiq.com. Не изпращайте номер на карта, seed фраза или частен ключ. Заявка от сайта се стремим да потвърдим в рамките на 2 работни дни.",
"e11t": "11. Контакт",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Имейл: support@simnetiq.com. Потребители от ЕС могат да ползват и платформата ODR на Европейската комисия: https://ec.europa.eu/consumers/odr.",
"at": "Account ID и възстановяване",
"ai2": "Акаунтът Doppler е анонимен Account ID. Това не е вход с имейл, а езикът на приложението не е държавата, в която живеете.",
"w1t": "Какво е Account ID",
"w1": "ID-то има вида VPN-XXXX-XXXX-XXXX. Приложението го създава при първо стартиране. Сайтът може да го създаде при плащане. Намира се в Профил или Настройки, в секция Акаунт. Използвайте същото ID на всяко устройство и го пазете в тайна. Поддръжката не иска номер на карта.",
"w2t": "Ако го изгубите",
"w2": "Ако сте свързали имейл, отворете Помощ и изберете възстановяване на акаунт. Ще изпратим ID-то на този имейл. Ако нищо не е свързано, подайте заявка. Поставено ID само по себе си не доказва, че акаунтът е ваш.",
"w3t": "Езикът не е местожителство",
"w3": "Руският или който и да е друг език не казва в коя държава живеете и дали ви засяга санкционно правило.",
"w4t": "Изтриване на акаунт",
"w4": "Изтриването на акаунт в приложението или на страницата за изтриване премахва целия акаунт Doppler. Не премахва само контакт за поддръжка. Платеният достъп трябва първо да изтече или да бъде отменен. Все още няма отделна публична страница само за премахване на контакт за поддръжка.",
"bt": "Достъп на сайта и абонаменти от магазини",
"bi": "Мястото на плащане решава дали достъпът се подновява и кой може да върне пари.",
"b1t": "Еднократен достъп на сайта",
"b1": "Сайтът таксува веднъж за избрания период: месец, 6 месеца или година. Няма автоматично подновяване и запазена карта за следващо плащане. Картата минава през Revolut, криптото през OxaPay. Приложението за Windows и Android APK се купуват на сайта.",
"b2t": "Apple Pay и Google Pay на сайта",
"b2": "Apple Pay и Google Pay на сайта са портфейли при плащане с карта. Това не са абонаменти в App Store или Google Play.",
"b3t": "App Store и Google Play",
"b3": "Тези магазини продават абонаменти с автоматично подновяване. Новите клиенти на магазина имат 3 дни пробен период. Отменете в магазина поне 24 часа преди подновяването. Един абонамент от магазина присвоява Pro на едно Account ID.",
"b4t": "Какво не продаваме",
"b4": "Няма покупка с Telegram Stars, покупка от Microsoft Store и зареждане на баланс. Приложението за Windows е директен инсталатор.",
"ct": "Възстанови, отмени или възстанови сума",
"ci": "Възстановяването на покупки, отмяната и възстановяването на сума са различни действия.",
"c1t": "Възстановяване",
"c1": "Възстановяването поставя вече платен достъп върху Account ID. В приложението от App Store или Google Play отворете Профил, Абонамент, после Възстанови покупки. Възстановяване на друго Account ID прехвърля Pro там. Покупката от сайта се вижда, когато приложението е влязло с Account ID, използвано при плащането. Рестартирайте приложението, ако липсва. APK няма бутон за възстановяване.",
"c2t": "Отмяна",
"c2": "Отмяната спира следващото подновяване в магазина. Сама по себе си не връща пари. На iPhone: Настройки, вашето име, Абонаменти, Doppler VPN, Отмени. На Android: Play Store, профил, Плащания и абонаменти, Абонаменти, Отмени. Покупката на сайта не се подновява, така че няма какво да се отменя.",
"c3t": "Възстановяване на сума",
"c3": "Възстановяването на сума е молба за връщане на пари. Политиката за възстановявания описва стъпките за карта на сайта, крипто, App Store и Google Play. Не изпращайте номера на картата.",
"gt": "Ръководства", "g1": "Account ID и възстановяване", "g2": "Достъп на сайта и абонаменти от магазини", "g3": "Възстанови, отмени или възстанови сума", "g4": "Възстановявания",
"faq": "Клиентите от ЕС, ЕИП и Обединеното кралство имат 14 дни за отказ. За останалите публикуваното възстановяване по добра воля е 30 дни и само първата покупка; промоциите и намаленията са изключени. Възстановяванията в App Store обработва Apple, а в Google Play — Google. При карта или крипто на сайта посочете на поддръжката Account ID и номер на поръчка. Не изпращайте номера на картата.",
"home": "Клиентите от ЕС, ЕИП и Обединеното кралство имат 14 дни за отказ. За останалите публикуваното възстановяване по добра воля е 30 дни и само първата покупка; промоциите и намаленията са изключени. Карта и крипто на сайта: пишете на support@simnetiq.com и посочете Account ID. Не изпращайте номера на картата. Възстановяванията в App Store и Google Play се подават в магазина. Вижте политиката за възстановявания на тази страница.",
"guar": "Клиентите от ЕС, ЕИП и Обединеното кралство имат 14 дни за отказ. За останалите публикуваното възстановяване по добра воля е 30 дни и само първата покупка; промоциите и намаленията са изключени. Плащането на сайта е еднократно и не се подновява само. Плановете в App Store и Google Play се подновяват, докато не ги отмените.",
"foot": "Сигурно плащане с карта (Revolut) или крипто (OxaPay). Плащането на сайта е еднократно и не се подновява само.",
"sub": "Еднократно плащане с карта (Revolut) или крипто (OxaPay). Без автоматично подновяване. Клиентите от ЕС, ЕИП и Обединеното кралство имат 14 дни за отказ. Другаде публикуваното възстановяване по добра воля е 30 дни и само първата покупка.",
"eb": "14 дни за отказ в ЕС, ЕИП и Обединеното кралство. За останалите клиенти възстановяване по добра воля 30 дни за първата покупка.",
"er": "Ако Doppler VPN не ви устройва, отговорете на този имейл или пишете на {email} с номер на поръчка и Account ID. Не изпращайте номера на картата. Възстановяването на плащане от сайта е за платената сума.",
"pt": "Контакт за поддръжка и изтриване на акаунт",
"pc": "Свързването на имейл или Telegram за възстановяване или помощ не е изтриване на акаунт. Страницата за изтриване изтрива акаунта Doppler. Не премахва само контакт за поддръжка. Платежните записи могат да се съхраняват, когато законът го изисква. Няма отделна публична страница само за премахване на контакт за поддръжка.",
}

HR = {
"u": "Zadnja aktualizacija: 28. rujna 2026.",
"rt": "Povrati novca",
"ri": "Ova politika pokriva kupnje Doppler VPN od SIMNETIQ LTD (broj 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Pristup na web-stranici je jednokratna uplata. Planovi App Store i Google Play obnavljaju se dok ih ne otkažete u trgovini.",
"ai": "Apple upute za povrat", "ar": "Prijavi problem Appleu", "gi": "Pravila povrata Google Playa",
"e1t": "1. Odustajanje u EU/EEA (14 dana)",
"e1": "Ako ste potrošač u Europskoj uniji ili EEA, možete odustati u roku od 14 dana bez navođenja razloga. Pišite na support@simnetiq.com prije kraja 14 dana. Vraćamo plaćeni iznos i ne odbijamo naknadu procesora plaćanja. Odbitak za već pruženu uslugu nije automatski. Kupnje u App Storeu ili Google Playu prijavljuju se u toj trgovini.",
"e2t": "2. Odustajanje u Ujedinjenoj Kraljevini (14 dana)",
"e2": "Ako ste potrošač u Ujedinjenoj Kraljevini, imate 14 dana za odustajanje prema Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Pošaljite jasnu izjavu na support@simnetiq.com. Vraćamo plaćeni iznos i ne odbijamo naknadu procesora. Odbitak za već pruženu uslugu nije automatski, a jedno povezivanje samo po sebi nije razlog za odbijanje.",
"e3t": "3. Povrat dobre volje unutar 30 dana",
"e3": "Za kupce izvan EU, EEA i Ujedinjene Kraljevine objavljena dobra volja je 30 dana od prve kupnje, jednom po kupcu. Promotivne i snižene kupnje su isključene, osim ako zakon ne zahtijeva drugačije. Ako se povrat odobri, odnosi se na plaćeni iznos. Pišite na support@simnetiq.com i navedite Account ID te broj narudžbe.",
"e4t": "4. Plaćanje karticom na web-stranici",
"e4": "Plaćanja karticom na web-stranici, uključujući Apple Pay i Google Pay na ovoj stranici, obrađuje Revolut. To nisu kupnje App Storea ni Google Playa. Pišite na support@simnetiq.com, navedite Account ID i broj narudžbe. Ne šaljite broj kartice. Ova politika ne odbija naknadu procesora. Banka odlučuje kada će se pojaviti odobrenje.",
"e5t": "5. Kripto plaćanje (OxaPay)",
"e5": "Kripto plaćanja na web-stranici obrađuje OxaPay. Pišite na support@simnetiq.com i navedite Account ID, broj računa, kovanicu i mrežu. Ne pogađamo adresu pošiljatelja. Navedite adresu novčanika. Prije slanja potvrđujemo imovinu, mrežu i iznos. Ova politika ne zadržava mrežne naknade ni promjenu cijene.",
"e6t": "6. App Store",
"e6": "O povratu u App Storeu odlučuje Apple. Ne obećavamo odobrenje ni broj dana. Poveznice su dolje. Pomoć za Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "O povratu u Google Playu odlučuje Google. Ovisi o proizvodu, vremenu od plaćanja, zemlji i razlogu. Jedan objavljeni rok ne pretvaramo u opće odbijanje i ne obećavamo odobrenje. Poveznica je dolje.",
"e8t": "8. Obnove",
"e8": "Kupnja na web-stranici pokriva odabrano razdoblje. Ne obnavlja se sama i nema naknade za obnovu za povrat. Plan App Storea ili Google Playa obnavlja se dok ga ne otkažete u trgovini najmanje 24 sata prije kraja razdoblja. Ako je trgovina naplatila neželjenu obnovu, pišite nam u roku od 14 dana i pomoći ćemo podnijeti zahtjev u trgovini. Odluku donosi trgovina.",
"e9t": "9. Isključenja",
"e9": "Povrat dobre volje može biti odbijen ako je zahtjev kasnio, račun je zatvoren zbog kršenja Uvjeta, isti kupac ponovno traži ili je kupnja bila promotivna ili snižena. To ne ukida zakonska prava. Naknada procesora plaćanja nije razlog za odbijanje ili smanjenje povrata.",
"e10t": "10. Kako podnijeti zahtjev",
"e10": "Navedite Account ID, način plaćanja (kartica na web-stranici, kripto, App Store ili Google Play), broj narudžbe ili računa i datum. Razlog je opcionalan. E-mail: support@simnetiq.com. Ne šaljite broj kartice, seed frazu ni privatni ključ. Zahtjev s web-stranice nastojimo potvrditi u roku od 2 radna dana.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.com. Potrošači iz EU mogu koristiti i ODR platformu Europske komisije: https://ec.europa.eu/consumers/odr.",
"at": "Account ID i oporavak",
"ai2": "Doppler račun je anonimni Account ID. To nije prijava e-mailom, a jezik aplikacije nije zemlja u kojoj živite.",
"w1t": "Što je Account ID",
"w1": "ID ima oblik VPN-XXXX-XXXX-XXXX. Aplikacija ga stvara pri prvom pokretanju. Web-stranica ga može stvoriti pri plaćanju. Nalazi se u Profilu ili Postavkama, u odjeljku Račun. Koristite isti ID na svakom uređaju i držite ga tajnim. Podrška ne traži broj kartice.",
"w2t": "Ako ga izgubite",
"w2": "Ako ste povezali e-mail, otvorite Pomoć i odaberite oporavak računa. Poslat ćemo ID na taj e-mail. Ako ništa nije povezano, otvorite zahtjev. Zalijepljeni ID sam po sebi ne dokazuje da je račun vaš.",
"w3t": "Jezik nije prebivalište",
"w3": "Ruski ili bilo koji drugi jezik ne govori u kojoj zemlji živite niti odnosi li se na vas sankcijsko pravilo.",
"w4t": "Brisanje računa",
"w4": "Brisanje računa u aplikaciji ili na stranici za brisanje briše cijeli Doppler račun. Ne briše samo kontakt podrške. Plaćeni pristup prvo mora istekati ili biti otkazan. Još nema zasebne javne stranice samo za uklanjanje kontakta podrške.",
"bt": "Pristup na web-stranici i pretplate trgovina",
"bi": "Mjesto plaćanja odlučuje obnovljuje li se pristup i tko može vratiti novac.",
"b1t": "Jednokratni pristup na web-stranici",
"b1": "Web-stranica jednom naplaćuje odabrano razdoblje: mjesec, 6 mjeseci ili godinu. Nema automatske obnove ni spremljene kartice za sljedeću naplatu. Kartica ide preko Revoluta, kripto preko OxaPaya. Windows aplikaciju i Android APK kupujete na web-stranici.",
"b2t": "Apple Pay i Google Pay na web-stranici",
"b2": "Apple Pay i Google Pay na web-stranici su novčanici pri plaćanju karticom. To nisu pretplate App Storea ni Google Playa.",
"b3t": "App Store i Google Play",
"b3": "Te trgovine prodaju pretplate s automatskom obnovom. Novi kupci trgovine imaju 3 dana probe. Otkažite u trgovini najmanje 24 sata prije obnove. Jedna pretplata trgovine dodjeljuje Pro jednom Account ID-u.",
"b4t": "Što ne prodajemo",
"b4": "Nema kupnje Telegram Starsima, kupnje u Microsoft Storeu ni dopune salda. Windows aplikacija je izravni instalacijski program.",
"ct": "Vrati, otkaži ili povrati",
"ci": "Vraćanje, otkazivanje i povrat različite su radnje.",
"c1t": "Vraćanje",
"c1": "Vraćanje stavlja već plaćeni pristup na Account ID. U aplikaciji iz App Storea ili Google Playa otvorite Profil, Pretplatu, zatim Vrati kupnje. Vraćanje na drugi Account ID premješta Pro tamo. Kupnja s web-stranice vidljiva je kada je aplikacija prijavljena s Account ID-om korištenim pri plaćanju. Ponovno pokrenite aplikaciju ako je nema. APK nema gumb za vraćanje.",
"c2t": "Otkazivanje",
"c2": "Otkazivanje zaustavlja sljedeću obnovu u trgovini. Samo po sebi ne vraća novac. Na iPhoneu: Postavke, vaše ime, Pretplate, Doppler VPN, Otkaži. Na Androidu: Play trgovina, profil, Plaćanja i pretplate, Pretplate, Otkaži. Kupnja na web-stranici se ne obnavlja, pa nema što otkazati.",
"c3t": "Povrat",
"c3": "Povrat je zahtjev za povrat novca. Politika povrata opisuje korake za karticu na web-stranici, kripto, App Store i Google Play. Ne šaljite broj kartice.",
"gt": "Vodiči", "g1": "Account ID i oporavak", "g2": "Pristup na web-stranici i pretplate trgovina", "g3": "Vrati, otkaži ili povrati", "g4": "Povrati novca",
"faq": "Kupci iz EU, EEA i Ujedinjene Kraljevine imaju 14 dana za odustajanje. Za ostale je objavljeni povrat dobre volje 30 dana i samo prva kupnja; promocije i popusti su isključeni. Povrati App Storea obrađuje Apple, a Google Playa Google. Za karticu ili kripto na web-stranici podršci navedite Account ID i broj narudžbe. Ne šaljite broj kartice.",
"home": "Kupci iz EU, EEA i Ujedinjene Kraljevine imaju 14 dana za odustajanje. Za ostale je objavljeni povrat dobre volje 30 dana i samo prva kupnja; promocije i popusti su isključeni. Kartica i kripto na web-stranici: pišite na support@simnetiq.com i navedite Account ID. Ne šaljite broj kartice. Povrati App Storea i Google Playa prijavljuju se u trgovini. Pogledajte politiku povrata na ovoj stranici.",
"guar": "Kupci iz EU, EEA i Ujedinjene Kraljevine imaju 14 dana za odustajanje. Za ostale je objavljeni povrat dobre volje 30 dana i samo prva kupnja; promocije i popusti su isključeni. Plaćanje na web-stranici je jednokratno i ne obnavlja se samo. Planovi App Storea i Google Playa obnavljaju se dok ih ne otkažete.",
"foot": "Sigurno plaćanje karticom (Revolut) ili kriptom (OxaPay). Plaćanje na web-stranici je jednokratno i ne obnavlja se samo.",
"sub": "Jednokratno plaćanje karticom (Revolut) ili kriptom (OxaPay). Bez automatske obnove. Kupci iz EU, EEA i Ujedinjene Kraljevine imaju 14 dana za odustajanje. Drugdje je objavljeni povrat dobre volje 30 dana i samo prva kupnja.",
"eb": "14 dana za odustajanje u EU, EEA i Ujedinjenoj Kraljevini. Za ostale kupce povrat dobre volje 30 dana na prvu kupnju.",
"er": "Ako vam Doppler VPN ne odgovara, odgovorite na ovaj e-mail ili pišite na {email} s brojem narudžbe i Account ID. Ne šaljite broj kartice. Povrat plaćanja s web-stranice odnosi se na plaćeni iznos.",
"pt": "Kontakt podrške i brisanje računa",
"pc": "Povezivanje e-maila ili Telegrama za oporavak ili pomoć nije brisanje računa. Stranica za brisanje briše Doppler račun. Ne uklanja samo kontakt podrške. Evidencije plaćanja mogu se čuvati kad to zakon zahtijeva. Nema zasebne javne stranice samo za uklanjanje kontakta podrške.",
}

SL = {
"u": "Zadnja posodobitev: 28. september 2026",
"rt": "Vračila",
"ri": "Ta politika zajema nakupe Doppler VPN pri SIMNETIQ LTD (številka 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Dostop na spletnem mestu je enkratno plačilo. Načrti App Store in Google Play se podaljšujejo, dokler jih v trgovini ne prekličete.",
"ai": "Apple navodila za vračilo", "ar": "Prijavi težavo Applu", "gi": "Pravila vračil Google Play",
"e1t": "1. Odstop v EU/EGP (14 dni)",
"e1": "Če ste potrošnik v Evropski uniji ali EGP, lahko odstopite v 14 dneh brez navedbe razloga. Pišite na support@simnetiq.com pred koncem 14 dni. Vrnimo plačani znesek in ne odštejemo provizije plačilnega procesorja. Odbitje za že opravljeno storitev ni samodejno. Nakupe v App Store ali Google Play uveljavljate v tej trgovini.",
"e2t": "2. Odstop v Združenem kraljestvu (14 dni)",
"e2": "Če ste potrošnik v Združenem kraljestvu, imate 14 dni za odstop po Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Pošljite jasno izjavo na support@simnetiq.com. Vrnimo plačani znesek in ne odštejemo provizije procesorja. Odbitje za že opravljeno storitev ni samodejno, ena povezava pa sama po sebi ni razlog za zavrnitev.",
"e3t": "3. Vračilo dobre volje v 30 dneh",
"e3": "Za stranke zunaj EU, EGP in Združenega kraljestva je objavljena dobra volja 30 dni od prvega nakupa, enkrat na stranko. Promo in znižani nakupi so izključeni, razen če zakon zahteva drugače. Če je vračilo odobreno, zadeva plačani znesek. Pišite na support@simnetiq.com in navedite Account ID ter številko naročila.",
"e4t": "4. Plačilo s kartico na spletnem mestu",
"e4": "Plačila s kartico na spletnem mestu, vključno z Apple Pay in Google Pay na tej strani, obdela Revolut. To niso nakupi App Store ali Google Play. Pišite na support@simnetiq.com, navedite Account ID in številko naročila. Ne pošiljajte številke kartice. Ta politika ne odšteje provizije procesorja. Banka odloči, kdaj se pojavi dobropis.",
"e5t": "5. Kripto plačilo (OxaPay)",
"e5": "Kripto plačila na spletnem mestu obdela OxaPay. Pišite na support@simnetiq.com in navedite Account ID, številko računa, kovanec in omrežje. Ne ugibamo naslova pošiljatelja. Navedite naslov denarnice. Pred pošiljanjem potrdimo sredstvo, omrežje in znesek. Ta politika ne zadrži omrežnih provizij ali spremembe cene.",
"e6t": "6. App Store",
"e6": "O vračilu v App Store odloča Apple. Ne obljubljamo odobritve niti števila dni. Povezave so spodaj. Pomoč za Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "O vračilu v Google Play odloča Google. Odvisno je od izdelka, časa od plačila, države in razloga. En objavljeni rok ne spremenimo v splošno zavrnitev in ne obljubljamo odobritve. Povezava je spodaj.",
"e8t": "8. Podaljšanja",
"e8": "Nakup na spletnem mestu pokriva izbrano obdobje. Ne podaljša se sam in ni pristojbine za podaljšanje za vračilo. Načrt App Store ali Google Play se podaljšuje, dokler ga v trgovini ne prekličete vsaj 24 ur pred koncem obdobja. Če je trgovina zaračunala neželeno podaljšanje, nam pišite v 14 dneh in pomagamo vložiti zahtevo v trgovini. Odloča trgovina.",
"e9t": "9. Izključitve",
"e9": "Vračilo dobre volje se lahko zavrne, če je zahteva zamujena, račun zaprt zaradi kršitve Pogojev, ista stranka znova prosi ali je bil nakup promo ali znižan. To ne odvzame zakonitih pravic. Provizija plačilnega procesorja ni razlog za zavrnitev ali zmanjšanje vračila.",
"e10t": "10. Kako vložiti zahtevo",
"e10": "Navedite Account ID, način plačila (kartica na spletnem mestu, kripto, App Store ali Google Play), številko naročila ali računa in datum. Razlog je neobvezen. E-pošta: support@simnetiq.com. Ne pošiljajte številke kartice, seed fraze ali zasebnega ključa. Zahtevo s spletnega mesta skušamo potrditi v 2 delovnih dneh.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-pošta: support@simnetiq.com. Potrošniki iz EU lahko uporabijo tudi platformo ODR Evropske komisije: https://ec.europa.eu/consumers/odr.",
"at": "Account ID in obnovitev",
"ai2": "Doppler račun je anonimni Account ID. To ni prijava z e-pošto, jezik aplikacije pa ni država, v kateri živite.",
"w1t": "Kaj je Account ID",
"w1": "ID ima obliko VPN-XXXX-XXXX-XXXX. Aplikacija ga ustvari ob prvem zagonu. Spletno mesto ga lahko ustvari pri plačilu. Je v Profilu ali Nastavitvah, v razdelku Račun. Uporabljajte isti ID na vsaki napravi in ga hranite v tajnosti. Podpora ne zahteva številke kartice.",
"w2t": "Če ga izgubite",
"w2": "Če ste povezali e-pošto, odprite Pomoč in izberite obnovitev računa. ID pošljemo na to e-pošto. Če nič ni povezano, odprite zahtevo. Prilepljeni ID sam po sebi ne dokazuje, da je račun vaš.",
"w3t": "Jezik ni prebivališče",
"w3": "Ruščina ali kateri koli drug jezik ne pove, v kateri državi živite niti ali vas zadeva sankcijsko pravilo.",
"w4t": "Brisanje računa",
"w4": "Brisanje računa v aplikaciji ali na strani za brisanje izbriše celoten Doppler račun. Ne odstrani le stika podpore. Plačani dostop mora najprej potekati ali biti preklican. Ločene javne strani samo za odstranitev stika podpore še ni.",
"bt": "Dostop na spletnem mestu in naročnine trgovin",
"bi": "Kraj plačila odloča, ali se dostop podaljša in kdo lahko vrne denar.",
"b1t": "Enkratni dostop na spletnem mestu",
"b1": "Spletno mesto enkrat zaračuna izbrano obdobje: mesec, 6 mesecev ali leto. Ni samodejnega podaljšanja in shranjene kartice za naslednje plačilo. Kartica gre prek Revoluta, kripto prek OxaPaya. Aplikacijo Windows in Android APK kupite na spletnem mestu.",
"b2t": "Apple Pay in Google Pay na spletnem mestu",
"b2": "Apple Pay in Google Pay na spletnem mestu sta denarnici pri plačilu s kartico. Nista naročnini App Store ali Google Play.",
"b3t": "App Store in Google Play",
"b3": "Te trgovine prodajajo naročnine s samodejnim podaljšanjem. Novi kupci trgovine imajo 3 dni preizkusa. Prekličite v trgovini vsaj 24 ur pred podaljšanjem. Ena naročnina trgovine dodeli Pro enemu Account ID.",
"b4t": "Česa ne prodajamo",
"b4": "Ni nakupa s Telegram Stars, nakupa v Microsoft Store niti polnjenja stanja. Aplikacija Windows je neposredni namestitveni program.",
"ct": "Obnovi, prekliči ali vrni",
"ci": "Obnovitev, preklic in vračilo so različna dejanja.",
"c1t": "Obnovitev",
"c1": "Obnovitev postavi že plačani dostop na Account ID. V aplikaciji iz App Store ali Google Play odprite Profil, Naročnino, nato Obnovi nakupe. Obnovitev na drugem Account ID prenese Pro tja. Nakup s spletnega mesta je viden, ko je aplikacija prijavljena z Account ID, uporabljenim pri plačilu. Znova zaženite aplikacijo, če ga ni. APK nima gumba za obnovitev.",
"c2t": "Preklic",
"c2": "Preklic ustavi naslednje podaljšanje v trgovini. Sam po sebi ne vrača denarja. Na iPhonu: Nastavitve, vaše ime, Naročnine, Doppler VPN, Prekliči. Na Androidu: Trgovina Play, profil, Plačila in naročnine, Naročnine, Prekliči. Nakup na spletnem mestu se ne podaljša, zato ni česa preklicati.",
"c3t": "Vračilo",
"c3": "Vračilo je prošnja za denar nazaj. Politika vračil opisuje korake za kartico na spletnem mestu, kripto, App Store in Google Play. Ne pošiljajte številke kartice.",
"gt": "Vodniki", "g1": "Account ID in obnovitev", "g2": "Dostop na spletnem mestu in naročnine trgovin", "g3": "Obnovi, prekliči ali vrni", "g4": "Vračila",
"faq": "Stranke iz EU, EGP in Združenega kraljestva imajo 14 dni za odstop. Za druge je objavljeno vračilo dobre volje 30 dni in samo prvi nakup; promocije in popusti so izključeni. Vračila App Store ureja Apple, Google Play pa Google. Pri kartici ali kriptu na spletnem mestu podpori navedite Account ID in številko naročila. Ne pošiljajte številke kartice.",
"home": "Stranke iz EU, EGP in Združenega kraljestva imajo 14 dni za odstop. Za druge je objavljeno vračilo dobre volje 30 dni in samo prvi nakup; promocije in popusti so izključeni. Kartica in kripto na spletnem mestu: pišite na support@simnetiq.com in navedite Account ID. Ne pošiljajte številke kartice. Vračila App Store in Google Play uveljavljate v trgovini. Glejte politiko vračil na tej strani.",
"guar": "Stranke iz EU, EGP in Združenega kraljestva imajo 14 dni za odstop. Za druge je objavljeno vračilo dobre volje 30 dni in samo prvi nakup; promocije in popusti so izključeni. Plačilo na spletnem mestu je enkratno in se ne podaljša samo. Načrti App Store in Google Play se podaljšujejo, dokler jih ne prekličete.",
"foot": "Varno plačilo s kartico (Revolut) ali kriptom (OxaPay). Plačilo na spletnem mestu je enkratno in se ne podaljša samo.",
"sub": "Enkratno plačilo s kartico (Revolut) ali kriptom (OxaPay). Brez samodejnega podaljšanja. Stranke iz EU, EGP in Združenega kraljestva imajo 14 dni za odstop. Drugod je objavljeno vračilo dobre volje 30 dni in samo prvi nakup.",
"eb": "14 dni za odstop v EU, EGP in Združenem kraljestvu. Za druge stranke vračilo dobre volje 30 dni za prvi nakup.",
"er": "Če vam Doppler VPN ne ustreza, odgovorite na to e-pošto ali pišite na {email} s številko naročila in Account ID. Ne pošiljajte številke kartice. Vračilo plačila s spletnega mesta zadeva plačani znesek.",
"pt": "Stik podpore in brisanje računa",
"pc": "Povezava e-pošte ali Telegrama za obnovitev ali pomoč ni brisanje računa. Stran za brisanje izbriše Doppler račun. Ne odstrani le stika podpore. Evidence plačil se lahko hranijo, ko to zahteva zakon. Ni ločene javne strani samo za odstranitev stika podpore.",
}

EL = {
"u": "Τελευταία ενημέρωση: 28 Σεπτεμβρίου 2026",
"rt": "Επιστροφές χρημάτων",
"ri": "Αυτή η πολιτική καλύπτει αγορές Doppler VPN από τη SIMNETIQ LTD (αριθμός 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Η πρόσβαση στον ιστότοπο είναι εφάπαξ πληρωμή. Τα πακέτα App Store και Google Play ανανεώνονται μέχρι να τα ακυρώσετε στο κατάστημα.",
"ai": "Οδηγίες επιστροφής Apple", "ar": "Αναφορά προβλήματος στην Apple", "gi": "Κανόνες επιστροφών Google Play",
"e1t": "1. Υπαναχώρηση στην ΕΕ/ΕΟΧ (14 ημέρες)",
"e1": "Αν είστε καταναλωτής στην Ευρωπαϊκή Ένωση ή τον ΕΟΧ, μπορείτε να υπαναχωρήσετε εντός 14 ημερών χωρίς αιτιολογία. Γράψτε στο support@simnetiq.com πριν λήξουν οι 14 ημέρες. Επιστρέφουμε το καταβληθέν ποσό και δεν αφαιρούμε την προμήθεια του επεξεργαστή πληρωμών. Η αφαίρεση για ήδη παρεχόμενη υπηρεσία δεν είναι αυτόματη. Οι αγορές App Store ή Google Play υποβάλλονται σε εκείνο το κατάστημα.",
"e2t": "2. Υπαναχώρηση στο Ηνωμένο Βασίλειο (14 ημέρες)",
"e2": "Αν είστε καταναλωτής στο Ηνωμένο Βασίλειο, έχετε 14 ημέρες για υπαναχώρηση βάσει των Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Στείλτε σαφή δήλωση στο support@simnetiq.com. Επιστρέφουμε το καταβληθέν ποσό και δεν αφαιρούμε την προμήθεια του επεξεργαστή. Η αφαίρεση για ήδη παρεχόμενη υπηρεσία δεν είναι αυτόματη και μία σύνδεση από μόνη της δεν αποτελεί λόγο απόρριψης.",
"e3t": "3. Επιστροφή καλής θέλησης εντός 30 ημερών",
"e3": "Για πελάτες εκτός ΕΕ, ΕΟΧ και Ηνωμένου Βασιλείου, η δημοσιευμένη καλή θέληση είναι 30 ημέρες από την πρώτη αγορά, μία φορά ανά πελάτη. Οι προωθητικές και μειωμένες αγορές εξαιρούνται, εκτός αν ο νόμος ορίζει διαφορετικά. Αν εγκριθεί η επιστροφή, αφορά το καταβληθέν ποσό. Γράψτε στο support@simnetiq.com και δώστε Account ID και αριθμό παραγγελίας.",
"e4t": "4. Πληρωμή με κάρτα στον ιστότοπο",
"e4": "Οι πληρωμές με κάρτα στον ιστότοπο, συμπεριλαμβανομένων Apple Pay και Google Pay σε αυτή τη σελίδα, διεκπεραιώνονται από τη Revolut. Δεν είναι αγορές App Store ή Google Play. Γράψτε στο support@simnetiq.com, δώστε Account ID και αριθμό παραγγελίας. Μην στείλετε τον αριθμό κάρτας. Αυτή η πολιτική δεν αφαιρεί την προμήθεια του επεξεργαστή. Η τράπεζα αποφασίζει πότε εμφανίζεται η πίστωση.",
"e5t": "5. Πληρωμή κρυπτο (OxaPay)",
"e5": "Οι πληρωμές κρυπτο στον ιστότοπο διεκπεραιώνονται από την OxaPay. Γράψτε στο support@simnetiq.com και δώστε Account ID, αριθμό τιμολογίου, νόμισμα και δίκτυο. Δεν μαντεύουμε τη διεύθυνση αποστολέα. Δηλώστε τη διεύθυνση πορτοφολιού. Πριν την αποστολή επιβεβαιώνουμε περιουσιακό στοιχείο, δίκτυο και ποσό. Αυτή η πολιτική δεν κρατά τέλη δικτύου ή αλλαγή τιμής.",
"e6t": "6. App Store",
"e6": "Για επιστροφές στο App Store αποφασίζει η Apple. Δεν υποσχόμαστε έγκριση ούτε αριθμό ημερών. Οι σύνδεσμοι είναι παρακάτω. Βοήθεια για Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Για επιστροφές στο Google Play αποφασίζει η Google. Εξαρτάται από το προϊόν, τον χρόνο από την πληρωμή, τη χώρα και τον λόγο. Δεν μετατρέπουμε μία δημοσιευμένη προθεσμία σε γενική απόρριψη και δεν υποσχόμαστε έγκριση. Ο σύνδεσμος είναι παρακάτω.",
"e8t": "8. Ανανεώσεις",
"e8": "Η αγορά στον ιστότοπο καλύπτει την επιλεγμένη περίοδο. Δεν ανανεώνεται μόνη της και δεν υπάρχει χρέωση ανανέωσης προς επιστροφή. Ένα πακέτο App Store ή Google Play ανανεώνεται μέχρι να το ακυρώσετε στο κατάστημα τουλάχιστον 24 ώρες πριν το τέλος της περιόδου. Αν το κατάστημα χρέωσε ανεπιθύμητη ανανέωση, γράψτε μας εντός 14 ημερών και θα βοηθήσουμε να υποβάλετε αίτημα στο κατάστημα. Αποφασίζει το κατάστημα.",
"e9t": "9. Εξαιρέσεις",
"e9": "Η επιστροφή καλής θέλησης μπορεί να απορριφθεί αν το αίτημα είναι καθυστερημένο, ο λογαριασμός έκλεισε λόγω παραβίασης των Όρων, ο ίδιος πελάτης ζητά ξανά ή η αγορά ήταν προωθητική ή με έκπτωση. Αυτό δεν αφαιρεί νόμιμα δικαιώματα. Η προμήθεια του επεξεργαστή πληρωμών δεν είναι λόγος απόρριψης ή μείωσης της επιστροφής.",
"e10t": "10. Πώς να υποβάλετε αίτημα",
"e10": "Δώστε Account ID, τρόπο πληρωμής (κάρτα στον ιστότοπο, κρυπτο, App Store ή Google Play), αριθμό παραγγελίας ή τιμολογίου και ημερομηνία. Ο λόγος είναι προαιρετικός. E-mail: support@simnetiq.com. Μην στείλετε αριθμό κάρτας, seed φράση ή ιδιωτικό κλειδί. Αίτημα από τον ιστότοπο προσπαθούμε να επιβεβαιώσουμε εντός 2 εργάσιμων ημερών.",
"e11t": "11. Επικοινωνία",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.com. Οι καταναλωτές στην ΕΕ μπορούν επίσης να χρησιμοποιήσουν την πλατφόρμα ODR της Ευρωπαϊκής Επιτροπής: https://ec.europa.eu/consumers/odr.",
"at": "Account ID και ανάκτηση",
"ai2": "Ο λογαριασμός Doppler είναι ανώνυμο Account ID. Δεν είναι σύνδεση με e-mail και η γλώσσα της εφαρμογής δεν είναι η χώρα διαμονής σας.",
"w1t": "Τι είναι το Account ID",
"w1": "Το ID έχει μορφή VPN-XXXX-XXXX-XXXX. Η εφαρμογή το δημιουργεί στην πρώτη εκκίνηση. Ο ιστότοπος μπορεί να το δημιουργήσει στην πληρωμή. Βρίσκεται στο Προφίλ ή στις Ρυθμίσεις, στην ενότητα Λογαριασμός. Χρησιμοποιήστε το ίδιο ID σε κάθε συσκευή και κρατήστε το μυστικό. Η υποστήριξη δεν ζητά αριθμό κάρτας.",
"w2t": "Αν το χάσετε",
"w2": "Αν έχετε συνδέσει e-mail, ανοίξτε τη Βοήθεια και επιλέξτε ανάκτηση λογαριασμού. Θα στείλουμε το ID σε αυτό το e-mail. Αν τίποτα δεν είναι συνδεδεμένο, ανοίξτε αίτημα. Ένα επικολλημένο ID από μόνο του δεν αποδεικνύει ότι ο λογαριασμός είναι δικός σας.",
"w3t": "Η γλώσσα δεν είναι κατοικία",
"w3": "Τα ρωσικά ή οποιαδήποτε άλλη γλώσσα δεν λέει σε ποια χώρα ζείτε ούτε αν σας αφορά κανόνας κυρώσεων.",
"w4t": "Διαγραφή λογαριασμού",
"w4": "Η διαγραφή λογαριασμού στην εφαρμογή ή στη σελίδα διαγραφής διαγράφει ολόκληρο τον λογαριασμό Doppler. Δεν αφαιρεί μόνο μια επαφή υποστήριξης. Η επί πληρωμή πρόσβαση πρέπει πρώτα να λήξει ή να ακυρωθεί. Δεν υπάρχει ακόμη ξεχωριστή δημόσια σελίδα μόνο για αφαίρεση επαφής υποστήριξης.",
"bt": "Πρόσβαση στον ιστότοπο και συνδρομές καταστημάτων",
"bi": "Το μέρος πληρωμής αποφασίζει αν η πρόσβαση ανανεώνεται και ποιος μπορεί να επιστρέψει χρήματα.",
"b1t": "Εφάπαξ πρόσβαση στον ιστότοπο",
"b1": "Ο ιστότοπος χρεώνει μία φορά την επιλεγμένη περίοδο: μήνα, 6 μήνες ή έτος. Δεν υπάρχει αυτόματη ανανέωση ούτε αποθηκευμένη κάρτα για επόμενη χρέωση. Η κάρτα περνά από Revolut, το κρυπτο από OxaPay. Η εφαρμογή Windows και το Android APK αγοράζονται στον ιστότοπο.",
"b2t": "Apple Pay και Google Pay στον ιστότοπο",
"b2": "Τα Apple Pay και Google Pay στον ιστότοπο είναι πορτοφόλια στην πληρωμή με κάρτα. Δεν είναι συνδρομές App Store ή Google Play.",
"b3t": "App Store και Google Play",
"b3": "Αυτά τα καταστήματα πωλούν συνδρομές με αυτόματη ανανέωση. Οι νέοι πελάτες καταστήματος έχουν 3 ημέρες δοκιμής. Ακυρώστε στο κατάστημα τουλάχιστον 24 ώρες πριν την ανανέωση. Μία συνδρομή καταστήματος αντιστοιχεί Pro σε ένα Account ID.",
"b4t": "Τι δεν πουλάμε",
"b4": "Δεν υπάρχει αγορά με Telegram Stars, αγορά στο Microsoft Store ούτε αναπλήρωση υπολοίπου. Η εφαρμογή Windows είναι άμεσο πρόγραμμα εγκατάστασης.",
"ct": "Επαναφορά, ακύρωση ή επιστροφή",
"ci": "Η επαναφορά, η ακύρωση και η επιστροφή είναι διαφορετικές ενέργειες.",
"c1t": "Επαναφορά",
"c1": "Η επαναφορά τοποθετεί ήδη πληρωμένη πρόσβαση σε Account ID. Στην εφαρμογή από App Store ή Google Play ανοίξτε Προφίλ, Συνδρομή και μετά Επαναφορά αγορών. Η επαναφορά σε άλλο Account ID μεταφέρει εκεί το Pro. Η αγορά από τον ιστότοπο φαίνεται όταν η εφαρμογή είναι συνδεδεμένη με το Account ID που χρησιμοποιήθηκε στην πληρωμή. Επανεκκινήστε την εφαρμογή αν λείπει. Το APK δεν έχει κουμπί επαναφοράς.",
"c2t": "Ακύρωση",
"c2": "Η ακύρωση σταματά την επόμενη ανανέωση στο κατάστημα. Από μόνη της δεν επιστρέφει χρήματα. Στο iPhone: Ρυθμίσεις, το όνομά σας, Συνδρομές, Doppler VPN, Ακύρωση. Σε Android: Play Store, προφίλ, Πληρωμές και συνδρομές, Συνδρομές, Ακύρωση. Η αγορά στον ιστότοπο δεν ανανεώνεται, οπότε δεν υπάρχει κάτι για ακύρωση.",
"c3t": "Επιστροφή",
"c3": "Η επιστροφή είναι αίτημα για επιστροφή χρημάτων. Η πολιτική επιστροφών περιγράφει τα βήματα για κάρτα στον ιστότοπο, κρυπτο, App Store και Google Play. Μην στείλετε τον αριθμό κάρτας.",
"gt": "Οδηγοί", "g1": "Account ID και ανάκτηση", "g2": "Πρόσβαση στον ιστότοπο και συνδρομές καταστημάτων", "g3": "Επαναφορά, ακύρωση ή επιστροφή", "g4": "Επιστροφές χρημάτων",
"faq": "Οι πελάτες σε ΕΕ, ΕΟΧ και Ηνωμένο Βασίλειο έχουν 14 ημέρες για υπαναχώρηση. Για τους υπόλοιπους η δημοσιευμένη επιστροφή καλής θέλησης είναι 30 ημέρες και μόνο η πρώτη αγορά· προωθήσεις και εκπτώσεις εξαιρούνται. Τις επιστροφές App Store χειρίζεται η Apple και του Google Play η Google. Για κάρτα ή κρυπτο στον ιστότοπο δώστε στην υποστήριξη Account ID και αριθμό παραγγελίας. Μην στείλετε τον αριθμό κάρτας.",
"home": "Οι πελάτες σε ΕΕ, ΕΟΧ και Ηνωμένο Βασίλειο έχουν 14 ημέρες για υπαναχώρηση. Για τους υπόλοιπους η δημοσιευμένη επιστροφή καλής θέλησης είναι 30 ημέρες και μόνο η πρώτη αγορά· προωθήσεις και εκπτώσεις εξαιρούνται. Κάρτα και κρυπτο στον ιστότοπο: γράψτε στο support@simnetiq.com και δώστε Account ID. Μην στείλετε τον αριθμό κάρτας. Οι επιστροφές App Store και Google Play υποβάλλονται στο κατάστημα. Δείτε την πολιτική επιστροφών σε αυτή τη σελίδα.",
"guar": "Οι πελάτες σε ΕΕ, ΕΟΧ και Ηνωμένο Βασίλειο έχουν 14 ημέρες για υπαναχώρηση. Για τους υπόλοιπους η δημοσιευμένη επιστροφή καλής θέλησης είναι 30 ημέρες και μόνο η πρώτη αγορά· προωθήσεις και εκπτώσεις εξαιρούνται. Η πληρωμή στον ιστότοπο είναι εφάπαξ και δεν ανανεώνεται μόνη της. Τα πακέτα App Store και Google Play ανανεώνονται μέχρι να τα ακυρώσετε.",
"foot": "Ασφαλής πληρωμή με κάρτα (Revolut) ή κρυπτο (OxaPay). Η πληρωμή στον ιστότοπο είναι εφάπαξ και δεν ανανεώνεται μόνη της.",
"sub": "Εφάπαξ πληρωμή με κάρτα (Revolut) ή κρυπτο (OxaPay). Χωρίς αυτόματη ανανέωση. Οι πελάτες σε ΕΕ, ΕΟΧ και Ηνωμένο Βασίλειο έχουν 14 ημέρες για υπαναχώρηση. Αλλού η δημοσιευμένη επιστροφή καλής θέλησης είναι 30 ημέρες και μόνο η πρώτη αγορά.",
"eb": "14 ημέρες για υπαναχώρηση σε ΕΕ, ΕΟΧ και Ηνωμένο Βασίλειο. Για τους άλλους πελάτες επιστροφή καλής θέλησης 30 ημερών στην πρώτη αγορά.",
"er": "Αν το Doppler VPN δεν σας εξυπηρετεί, απαντήστε σε αυτό το e-mail ή γράψτε στο {email} με αριθμό παραγγελίας και Account ID. Μην στείλετε τον αριθμό κάρτας. Η επιστροφή πληρωμής από τον ιστότοπο αφορά το καταβληθέν ποσό.",
"pt": "Επαφή υποστήριξης και διαγραφή λογαριασμού",
"pc": "Η σύνδεση e-mail ή Telegram για ανάκτηση ή βοήθεια δεν είναι διαγραφή λογαριασμού. Η σελίδα διαγραφής διαγράφει τον λογαριασμό Doppler. Δεν αφαιρεί μόνο μια επαφή υποστήριξης. Τα αρχεία πληρωμών μπορεί να διατηρούνται όταν το απαιτεί ο νόμος. Δεν υπάρχει ξεχωριστή δημόσια σελίδα μόνο για αφαίρεση επαφής υποστήριξης.",
}

CA = {
"u": "Darrera actualització: 28 de setembre de 2026",
"rt": "Reemborsaments",
"ri": "Aquesta política cobreix les compres de Doppler VPN a SIMNETIQ LTD (número 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. L'accés al lloc web és un pagament únic. Els plans d'App Store i Google Play es renoven fins que els cancel·leu a la botiga.",
"ai": "Instruccions de reemborsament d'Apple", "ar": "Informa d'un problema a Apple", "gi": "Normes de reemborsament de Google Play",
"e1t": "1. Desistiment a la UE/EEE (14 dies)",
"e1": "Si sou consumidor a la Unió Europea o a l'EEE, podeu desistir en 14 dies sense donar cap motiu. Escriviu a support@simnetiq.com abans que acabin els 14 dies. Reemborsem l'import pagat i no deduïm la comissió del processador de pagaments. La deducció pel servei ja prestat no és automàtica. Les compres d'App Store o Google Play es sol·liciten en aquella botiga.",
"e2t": "2. Desistiment al Regne Unit (14 dies)",
"e2": "Si sou consumidor al Regne Unit, teniu 14 dies per desistir segons les Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Envieu una declaració clara a support@simnetiq.com. Reemborsem l'import pagat i no deduïm la comissió del processador. La deducció pel servei ja prestat no és automàtica, i connectar-se una vegada no és per si sol un motiu de denegació.",
"e3t": "3. Reemborsament de bona voluntat en 30 dies",
"e3": "Per a clients fora de la UE, l'EEE i el Regne Unit, la bona voluntat publicada és de 30 dies des de la primera compra, una vegada per client. Les compres promocionals o amb descompte queden excloses, llevat que la llei exigeixi una altra cosa. Si s'atorga, el reemborsament és l'import pagat. Escriviu a support@simnetiq.com i indiqueu l'Account ID i el número de comanda.",
"e4t": "4. Pagament amb targeta al lloc web",
"e4": "Els pagaments amb targeta al lloc, inclosos Apple Pay i Google Pay en aquesta pàgina, els processa Revolut. No són compres d'App Store ni de Google Play. Escriviu a support@simnetiq.com, indiqueu l'Account ID i el número de comanda. No envieu el número de targeta. Aquesta política no dedueix la comissió del processador. El banc decideix quan apareix l'abonament.",
"e5t": "5. Pagament amb cripto (OxaPay)",
"e5": "Els pagaments amb cripto al lloc els processa OxaPay. Escriviu a support@simnetiq.com i indiqueu l'Account ID, el número de factura, la moneda i la xarxa. No endevinem l'adreça del remitent. Indiqueu l'adreça de la cartera. Abans d'enviar confirmem l'actiu, la xarxa i l'import. Aquesta política no reté comissions de xarxa ni un canvi de preu.",
"e6t": "6. App Store",
"e6": "Els reemborsaments d'App Store els decideix Apple. No prometem l'aprovació ni un nombre de dies. Els enllaços són a sota. Ajuda amb l'Account ID: support@simnetiq.com.",
"e7t": "7. Google Play",
"e7": "Els reemborsaments de Google Play els decideix Google. Depèn del producte, del temps des del pagament, del país i del motiu. No convertim un termini publicat en una denegació general i no prometem l'aprovació. L'enllaç és a sota.",
"e8t": "8. Renovacions",
"e8": "La compra al lloc cobreix el període triat. No es renova sola i no hi ha cap càrrec de renovació a reemborsar. Un pla d'App Store o Google Play es renova fins que el cancel·leu a la botiga almenys 24 hores abans del final del període. Si la botiga ha cobrat una renovació no desitjada, escriviu-nos en 14 dies i us ajudarem a presentar la sol·licitud a la botiga. Decideix la botiga.",
"e9t": "9. Exclusions",
"e9": "El reemborsament de bona voluntat es pot denegar si la sol·licitud arriba tard, el compte s'ha tancat per incompliment de les Condicions, el mateix client demana una altra vegada o la compra era promocional o amb descompte. Això no elimina drets legals. La comissió del processador de pagaments no és un motiu per denegar o reduir el reemborsament.",
"e10t": "10. Com presentar la sol·licitud",
"e10": "Indiqueu l'Account ID, el mètode de pagament (targeta al lloc, cripto, App Store o Google Play), el número de comanda o factura i la data. El motiu és opcional. E-mail: support@simnetiq.com. No envieu el número de targeta, la frase seed ni la clau privada. Una sol·licitud del lloc intentem confirmar-la en 2 dies laborables.",
"e11t": "11. Contacte",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.com. Els consumidors de la UE també poden fer servir la plataforma ODR de la Comissió Europea: https://ec.europa.eu/consumers/odr.",
"at": "Account ID i recuperació",
"ai2": "El compte Doppler és un Account ID anònim. No és un inici de sessió per e-mail, i l'idioma de l'aplicació no és el país on residiu.",
"w1t": "Què és l'Account ID",
"w1": "L'ID té la forma VPN-XXXX-XXXX-XXXX. L'aplicació el crea al primer inici. El lloc el pot crear al pagament. És a Perfil o Configuració, a la secció Compte. Feu servir el mateix ID a cada dispositiu i guardeu-lo en secret. El suport no demana el número de targeta.",
"w2t": "Si el perdeu",
"w2": "Si heu vinculat un e-mail, obriu Ajuda i trieu la recuperació del compte. Enviarem l'ID a aquest e-mail. Si no hi ha res vinculat, obriu una sol·licitud. Un ID enganxat per si sol no prova que el compte sigui vostre.",
"w3t": "L'idioma no és la residència",
"w3": "El rus o qualsevol altre idioma no diu en quin país residiu ni si us afecta una norma de sancions.",
"w4t": "Supressió del compte",
"w4": "Suprimir el compte a l'aplicació o a la pàgina de supressió elimina tot el compte Doppler. No elimina només un contacte de suport. L'accés de pagament ha d'acabar o cancel·lar-se primer. Encara no hi ha una pàgina pública separada només per eliminar un contacte de suport.",
"bt": "Accés al lloc i subscripcions de botigues",
"bi": "El lloc del pagament decideix si l'accés es renova i qui pot tornar els diners.",
"b1t": "Accés únic al lloc web",
"b1": "El lloc cobra una vegada el període triat: un mes, 6 mesos o un any. No hi ha renovació automàtica ni targeta desada per a un càrrec posterior. La targeta va per Revolut, la cripto per OxaPay. L'aplicació Windows i l'APK d'Android es compren al lloc.",
"b2t": "Apple Pay i Google Pay al lloc web",
"b2": "Apple Pay i Google Pay al lloc són carteres en el pagament amb targeta. No són subscripcions d'App Store ni de Google Play.",
"b3t": "App Store i Google Play",
"b3": "Aquestes botigues venen subscripcions amb renovació automàtica. Els clients nous de la botiga tenen 3 dies de prova. Cancel·leu a la botiga almenys 24 hores abans de la renovació. Una subscripció de botiga assigna Pro a un Account ID.",
"b4t": "El que no venem",
"b4": "No hi ha compra amb Telegram Stars, compra a Microsoft Store ni recàrrega de saldo. L'aplicació Windows és un instal·lador directe.",
"ct": "Restaura, cancel·la o reembolsa",
"ci": "Restaurar, cancel·lar i reemborsar són accions diferents.",
"c1t": "Restauració",
"c1": "La restauració col·loca l'accés ja pagat en un Account ID. A l'aplicació d'App Store o Google Play obriu Perfil, Subscripció i després Restaura compres. Restaurar en un altre Account ID hi trasllada Pro. La compra del lloc es veu quan l'aplicació està iniciada amb l'Account ID usat al pagament. Reinicieu l'aplicació si no es veu. L'APK no té botó de restauració.",
"c2t": "Cancel·lació",
"c2": "La cancel·lació atura la propera renovació a la botiga. Per si sola no torna diners. A l'iPhone: Configuració, el vostre nom, Subscripcions, Doppler VPN, Cancel·la. A Android: Play Store, perfil, Pagaments i subscripcions, Subscripcions, Cancel·la. La compra al lloc no es renova, així que no hi ha res a cancel·lar.",
"c3t": "Reemborsament",
"c3": "El reemborsament és la petició de recuperar els diners. La política de reemborsaments descriu els passos per a targeta al lloc, cripto, App Store i Google Play. No envieu el número de targeta.",
"gt": "Guies", "g1": "Account ID i recuperació", "g2": "Accés al lloc i subscripcions de botigues", "g3": "Restaura, cancel·la o reembolsa", "g4": "Reemborsaments",
"faq": "Els clients de la UE, l'EEE i el Regne Unit tenen 14 dies per desistir. Per a la resta, el reemborsament de bona voluntat publicat és de 30 dies i només la primera compra; promocions i descomptes queden exclosos. Els reemborsaments d'App Store els gestiona Apple, i els de Google Play Google. Amb targeta o cripto al lloc, indiqueu al suport l'Account ID i el número de comanda. No envieu el número de targeta.",
"home": "Els clients de la UE, l'EEE i el Regne Unit tenen 14 dies per desistir. Per a la resta, el reemborsament de bona voluntat publicat és de 30 dies i només la primera compra; promocions i descomptes queden exclosos. Targeta i cripto al lloc: escriviu a support@simnetiq.com i indiqueu l'Account ID. No envieu el número de targeta. Els reemborsaments d'App Store i Google Play es sol·liciten a la botiga. Vegeu la política de reemborsaments en aquesta pàgina.",
"guar": "Els clients de la UE, l'EEE i el Regne Unit tenen 14 dies per desistir. Per a la resta, el reemborsament de bona voluntat publicat és de 30 dies i només la primera compra; promocions i descomptes queden exclosos. El pagament al lloc és únic i no es renova sol. Els plans d'App Store i Google Play es renoven fins que els cancel·leu.",
"foot": "Pagament segur amb targeta (Revolut) o cripto (OxaPay). El pagament al lloc és únic i no es renova sol.",
"sub": "Pagament únic amb targeta (Revolut) o cripto (OxaPay). Sense renovació automàtica. Els clients de la UE, l'EEE i el Regne Unit tenen 14 dies per desistir. En altres llocs, el reemborsament de bona voluntat publicat és de 30 dies i només la primera compra.",
"eb": "14 dies per desistir a la UE, l'EEE i el Regne Unit. Per a la resta de clients, reemborsament de bona voluntat de 30 dies a la primera compra.",
"er": "Si Doppler VPN no us serveix, responeu a aquest e-mail o escriviu a {email} amb el número de comanda i l'Account ID. No envieu el número de targeta. El reemborsament del pagament del lloc és l'import pagat.",
"pt": "Contacte de suport i supressió del compte",
"pc": "Vincular un e-mail o Telegram per a recuperació o ajuda no és suprimir el compte. La pàgina de supressió esborra el compte Doppler. No elimina només un contacte de suport. Els registres de pagament es poden conservar quan ho exigeix la llei. No hi ha una pàgina pública separada només per eliminar un contacte de suport.",
}

for locale, pack in (
    ("uk", UK),
    ("sk", SK),
    ("hu", HU),
    ("ro", RO),
    ("bg", BG),
    ("hr", HR),
    ("sl", SL),
    ("el", EL),
    ("ca", CA),
):
    save(locale, L(pack))
print("ok", "uk sk hu ro bg hr sl el ca")
