#!/usr/bin/env python3
"""Nordic/Baltic/Czech refund+help packs: nl, sv, da, nb, fi, et, lv, lt, cs."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pack_rows import L, save

save("nl", L({
"u": "Laatst bijgewerkt: 28 september 2026",
"rt": "Restitutie",
"ri": "Dit beleid geldt voor aankopen van Doppler VPN bij SIMNETIQ LTD (nummer 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Toegang via de website is een eenmalige betaling. Abonnementen in de App Store en Google Play verlengen zich tot u ze in de store annuleert.",
"ai": "Restitutie-instructies van Apple", "ar": "Een probleem melden bij Apple", "gi": "Restitutiebeleid van Google Play",
"e1t": "1. Herroeping in de EU/EER (14 dagen)",
"e1": "Als u consument bent in de Europese Unie of de EER, kunt u binnen 14 dagen zonder opgave van reden herroepen. Mail support@simnetiq.store vóór het einde van die 14 dagen. Wij restitueren het betaalde bedrag en trekken de vergoeding van de betaalprovider niet af. Een aftrek voor reeds gebruikte dienst is niet automatisch. Aankopen in de App Store of Google Play vraagt u bij die store aan.",
"e2t": "2. Herroeping in het Verenigd Koninkrijk (14 dagen)",
"e2": "Als u consument bent in het Verenigd Koninkrijk, heeft u 14 dagen herroepingsrecht op grond van de Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Stuur een duidelijke verklaring naar support@simnetiq.store. Wij restitueren het betaalde bedrag en trekken de vergoeding van de betaalprovider niet af. Een aftrek voor reeds gebruikte dienst is niet automatisch, en één verbinding is op zich geen weigeringsgrond.",
"e3t": "3. Coulancerestitutie binnen 30 dagen",
"e3": "Voor klanten buiten de EU, de EER en het Verenigd Koninkrijk geldt de gepubliceerde coulante: 30 dagen vanaf de eerste aankoop, één keer per klant. Promotionele of kortingsaankopen zijn uitgesloten, tenzij de wet anders vereist. Als de restitutie wordt toegekend, betreft die het betaalde bedrag. Mail support@simnetiq.store met uw Account ID en orderreferentie.",
"e4t": "4. Kaartbetaling op de website",
"e4": "Kaartbetalingen op de website, inclusief Apple Pay en Google Pay op die pagina, lopen via Revolut. Dat zijn geen aankopen in de App Store of Google Play. Mail support@simnetiq.store met Account ID en orderreferentie. Stuur geen kaartnummer. Dit beleid trekt de providervergoeding niet af. Uw bank bepaalt wanneer het tegoed zichtbaar is.",
"e5t": "5. Cryptobetaling (OxaPay)",
"e5": "Cryptobetalingen op de website lopen via OxaPay. Mail support@simnetiq.store met Account ID, factuurreferentie, coin en netwerk. Wij raden het afzenderadres niet. Geef het walletadres. Voor verzending bevestigen wij asset, netwerk en bedrag. Dit beleid houdt netwerkkosten of een prijswijziging niet in.",
"e6t": "6. App Store",
"e6": "Apple beslist over restituties in de App Store. Wij beloven geen goedkeuring en geen aantal dagen. Gebruik de links hieronder. Hulp bij Account ID: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "Google beslist over restituties in Google Play. Dat hangt af van product, tijd sinds betaling, land en reden. Wij maken van één gepubliceerd tijdvenster geen algemene weigering en beloven geen goedkeuring. De link staat hieronder.",
"e8t": "8. Verlengingen",
"e8": "Een websiteaankoop geldt voor de gekozen periode. Die verlengt niet automatisch en er is geen verlengingskosten om te restitueren. Een abonnement in de App Store of Google Play verlengt tot u het in die store annuleert, minstens 24 uur voor het einde van de periode. Als de store een ongewenste verlenging heeft berekend, neem binnen 14 dagen contact op; wij helpen om de store te vragen. De store beslist.",
"e9t": "9. Uitsluitingen",
"e9": "Een coulancerestitutie kan worden geweigerd als het verzoek te laat is, het account is gesloten wegens schending van de Voorwaarden, dezelfde klant opnieuw vraagt, of de aankoop promotioneel of met korting was. Dit neemt geen wettelijk recht weg. De vergoeding van de betaalprovider is geen reden om te weigeren of te verlagen.",
"e10t": "10. Hoe u een verzoek indient",
"e10": "Stuur Account ID, betaalmethode (websitekaart, crypto, App Store of Google Play), order- of factuurreferentie en de datum. Een reden is optioneel. E-mail: support@simnetiq.store. Stuur geen kaartnummer, seed phrase of privésleutel. Een websiteverzoek proberen we binnen 2 werkdagen te bevestigen.",
"e11t": "11. Contact",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.store. Consumenten in de EU kunnen ook het ODR-platform van de Europese Commissie gebruiken: https://ec.europa.eu/consumers/odr.",
"at": "Account ID en herstel",
"ai2": "Een Doppler-account is een anoniem Account ID. Het is geen e-maillogin, en de taal van de app is niet het land waar u woont.",
"w1t": "Wat het Account ID is",
"w1": "Het ID heeft de vorm VPN-XXXX-XXXX-XXXX. De app maakt het bij de eerste start. De website kan het bij betaling aanmaken. Het staat onder Profiel of Instellingen, bij Account. Gebruik hetzelfde ID op elk apparaat en houd het geheim. Support vraagt niet om uw kaartnummer.",
"w2t": "Als u het kwijt bent",
"w2": "Als u een e-mail heeft gekoppeld, open Support en kies account herstellen. Wij sturen het ID naar die e-mail. Als er niets is gekoppeld, dien een supportverzoek in. Een geplakt ID bewijst op zich niet dat het account van u is.",
"w3t": "Taal is geen woonplaats",
"w3": "Russisch of enige andere taal zegt niet in welk land u woont of of een sanctieregel op u van toepassing is.",
"w4t": "Account verwijderen",
"w4": "Account verwijderen in de app of op de verwijderpagina verwijdert het hele Doppler-account. Het verwijdert niet alleen een supportcontact. Betaalde toegang moet eerst aflopen of worden geannuleerd. Er is nog geen aparte openbare pagina om alleen een supportcontact te verwijderen.",
"bt": "Websitetoegang en store-abonnementen",
"bi": "Waar u betaalde, bepaalt of toegang verlengt en wie kan restitueren.",
"b1t": "Eenmalige websitetoegang",
"b1": "De website rekent één keer af voor de gekozen periode: een maand, 6 maanden of een jaar. Er is geen automatische verlenging en geen bewaarde kaart voor een latere afschrijving. Kaart loopt via Revolut, crypto via OxaPay. De Windows-app en de Android-APK koopt u op de website.",
"b2t": "Apple Pay en Google Pay op de website",
"b2": "Apple Pay en Google Pay op de website zijn wallets bij de kaartcheckout. Het zijn geen abonnementen van de App Store of Google Play.",
"b3t": "App Store en Google Play",
"b3": "Die stores verkopen automatisch verlengende abonnementen. Nieuwe storeklanten krijgen 3 dagen proef. Annuleer in de store minstens 24 uur voor verlenging. Eén store-abonnement koppelt Pro aan één Account ID tegelijk.",
"b4t": "Wat wij niet verkopen",
"b4": "Er is geen aankoop met Telegram Stars, geen aankoop in de Microsoft Store en geen saldostorting. De Windows-app is een directe installer.",
"ct": "Herstellen, annuleren of restitueren",
"ci": "Herstellen, annuleren en restitueren zijn verschillende handelingen.",
"c1t": "Herstellen",
"c1": "Herstellen zet reeds betaalde toegang op een Account ID. In de App Store- of Google Play-app: open Profiel, Abonnement, daarna Aankopen herstellen. Herstellen op een ander Account ID verplaatst Pro daarheen. Een websiteaankoop verschijnt als de app is ingelogd met het Account ID van de betaling. Start de app opnieuw als die nog niet zichtbaar is. De APK heeft geen knop Aankopen herstellen.",
"c2t": "Annuleren",
"c2": "Annuleren stopt de volgende storeverlenging. Het geeft op zich geen geld terug. Op iPhone: Instellingen, uw naam, Abonnementen, Doppler VPN, Annuleren. Op Android: Play Store, profiel, Betalingen en abonnementen, Abonnementen, Annuleren. Een websiteaankoop verlengt niet, dus er is niets te annuleren.",
"c3t": "Restitueren",
"c3": "Restitueren is een verzoek om geld terug. Het restitutiebeleid beschrijft de stappen voor websitekaart, crypto, App Store en Google Play. Stuur geen kaartnummer.",
"gt": "Gidsen", "g1": "Account ID en herstel", "g2": "Websitetoegang en store-abonnementen", "g3": "Herstellen, annuleren of restitueren", "g4": "Restitutie",
"faq": "Klanten in de EU, EER en het Verenigd Koninkrijk hebben 14 dagen herroepingsrecht. Voor anderen is de gepubliceerde coulante 30 dagen en alleen de eerste aankoop; promoties en kortingen zijn uitgesloten. App Store-restituties via Apple, Google Play via Google. Bij websitekaart of crypto: geef support Account ID en orderreferentie. Stuur geen kaartnummer.",
"home": "Klanten in de EU, EER en het Verenigd Koninkrijk hebben 14 dagen herroepingsrecht. Voor anderen is de gepubliceerde coulante 30 dagen en alleen de eerste aankoop; promoties en kortingen zijn uitgesloten. Websitekaart en crypto: mail support@simnetiq.store met Account ID. Stuur geen kaartnummer. App Store- en Google Play-restituties vraagt u bij die store aan. Zie het restitutiebeleid op deze website.",
"guar": "Klanten in de EU, EER en het Verenigd Koninkrijk hebben 14 dagen herroepingsrecht. Voor anderen is de gepubliceerde coulante 30 dagen en alleen de eerste aankoop; promoties en kortingen zijn uitgesloten. Webcheckout is een eenmalige betaling en verlengt niet automatisch. Abonnementen in de App Store en Google Play verlengen tot u ze annuleert.",
"foot": "Veilige betaling met kaart (Revolut) of crypto (OxaPay). Webcheckout is een eenmalige betaling en verlengt niet automatisch.",
"sub": "Eenmalige betaling met kaart (Revolut) of crypto (OxaPay). Geen automatische verlenging. Klanten in de EU, EER en het Verenigd Koninkrijk hebben 14 dagen herroepingsrecht. Elders is de gepubliceerde coulante 30 dagen en alleen de eerste aankoop.",
"eb": "14 dagen herroepingsrecht in de EU, EER en het Verenigd Koninkrijk. Voor andere klanten 30 dagen coulante op de eerste aankoop.",
"er": "Als Doppler VPN niet voor u werkt, beantwoord deze e-mail of mail {email} met ordernummer en Account ID. Stuur geen kaartnummer. Een websiterestitutie betreft het betaalde bedrag.",
"pt": "Supportcontact en accountverwijdering",
"pc": "Een e-mail of Telegram koppelen voor herstel of support is geen accountverwijdering. De verwijderpagina verwijdert het Doppler-account. Die verwijdert niet alleen een supportcontact. Betaalgegevens kunnen worden bewaard waar de wet dat vereist. Er is geen aparte openbare pagina om alleen een supportcontact te verwijderen.",
}))

save("sv", L({
"u": "Senast uppdaterad: 28 september 2026",
"rt": "Återbetalning",
"ri": "Denna policy gäller köp av Doppler VPN från SIMNETIQ LTD (nummer 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Webbplatsåtkomst är en engångsbetalning. Abonnemang i App Store och Google Play förnyas tills du avslutar dem i butiken.",
"ai": "Apples instruktioner för återbetalning", "ar": "Rapportera ett problem till Apple", "gi": "Google Plays återbetalningspolicy",
"e1t": "1. Ångerrätt i EU/EES (14 dagar)",
"e1": "Om du är konsument i Europeiska unionen eller EES kan du ångra dig inom 14 dagar utan att ange skäl. Mejla support@simnetiq.store innan de 14 dagarna går ut. Vi återbetalar det belopp du betalade och drar inte av betalningsförmedlarens avgift. Avdrag för redan använd tjänst är inte automatiskt. Köp i App Store eller Google Play begärs i den butiken.",
"e2t": "2. Ångerrätt i Storbritannien (14 dagar)",
"e2": "Om du är konsument i Storbritannien har du 14 dagars ångerrätt enligt Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Skicka ett tydligt meddelande till support@simnetiq.store. Vi återbetalar det belopp du betalade och drar inte av förmedlarens avgift. Avdrag för redan använd tjänst är inte automatiskt, och en enda anslutning är i sig ingen grund för avslag.",
"e3t": "3. Godvillig återbetalning inom 30 dagar",
"e3": "För kunder utanför EU, EES och Storbritannien gäller den publicerade godvilligheten: 30 dagar från det första köpet, en gång per kund. Kampanj- eller rabatterade köp undantas om inte lagen kräver annat. Om återbetalning beviljas gäller den det betalade beloppet. Mejla support@simnetiq.store med Account ID och orderreferens.",
"e4t": "4. Kortbetalning på webbplatsen",
"e4": "Kortbetalningar på webbplatsen, inklusive Apple Pay och Google Pay på den sidan, hanteras av Revolut. Det är inte köp i App Store eller Google Play. Mejla support@simnetiq.store med Account ID och orderreferens. Skicka inte kortnumret. Denna policy drar inte av förmedlarens avgift. Din bank avgör när krediten syns.",
"e5t": "5. Kryptobetalning (OxaPay)",
"e5": "Kryptobetalningar på webbplatsen hanteras av OxaPay. Mejla support@simnetiq.store med Account ID, fakturareferens, coin och nätverk. Vi gissar inte avsändaradressen. Ange plånboksadressen. Innan vi skickar bekräftar vi tillgång, nätverk och belopp. Denna policy behåller inte nätverksavgifter eller en prisändring.",
"e6t": "6. App Store",
"e6": "Apple beslutar om återbetalningar i App Store. Vi lovar varken godkännande eller antal dagar. Använd länkarna nedan. Hjälp med Account ID: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "Google beslutar om återbetalningar i Google Play. Det beror på produkt, tid sedan betalning, land och skäl. Vi gör inte ett publicerat tidsfönster till ett generellt avslag och lovar inte godkännande. Länken finns nedan.",
"e8t": "8. Förnyelser",
"e8": "Ett webbköp gäller den period du valde. Det förnyas inte automatiskt och det finns ingen förnyelseavgift att återbetala. Ett abonnemang i App Store eller Google Play förnyas tills du avslutar det i butiken, minst 24 timmar före periodens slut. Om butiken debiterade en oönskad förnyelse, kontakta oss inom 14 dagar så hjälper vi dig att fråga butiken. Butiken beslutar.",
"e9t": "9. Undantag",
"e9": "En godvillig återbetalning kan avslås om begäran är sen, kontot stängdes för brott mot Villkoren, samma kund frågar igen, eller köpet var kampanj eller rabatterat. Detta tar inte bort en lagstadgad rättighet. Betalningsförmedlarens avgift är ingen grund att avslå eller sänka.",
"e10t": "10. Så begär du",
"e10": "Skicka Account ID, betalningssätt (webbkort, krypto, App Store eller Google Play), order- eller fakturareferens och datum. Skäl är valfritt. E-post: support@simnetiq.store. Skicka inte kortnummer, seed phrase eller privat nyckel. En webbegäran försöker vi bekräfta inom 2 arbetsdagar.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-post: support@simnetiq.store. Konsumenter i EU kan också använda Europeiska kommissionens ODR-plattform: https://ec.europa.eu/consumers/odr.",
"at": "Account ID och återställning",
"ai2": "Ett Doppler-konto är ett anonymt Account ID. Det är inte en e-postinloggning, och appens språk är inte det land där du bor.",
"w1t": "Vad Account ID är",
"w1": "ID:t har formen VPN-XXXX-XXXX-XXXX. Appen skapar det vid första start. Webbplatsen kan skapa det vid betalning. Det finns under Profil eller Inställningar, sedan Konto. Använd samma ID på varje enhet och håll det privat. Support ber inte om kortnummer.",
"w2t": "Om du tappar bort det",
"w2": "Om du kopplat e-post, öppna Support och välj återställ konto. Vi skickar ID:t till den e-posten. Om inget är kopplat, öppna ett supportärende. Ett inklistrat ID bevisar i sig inte att du äger kontot.",
"w3t": "Språk är inte hemvist",
"w3": "Ryska eller något annat språk säger inte vilket land du bor i eller om en sanktionsregel gäller dig.",
"w4t": "Radera konto",
"w4": "Radera konto i appen eller på raderingssidan tar bort hela Doppler-kontot. Det tar inte bort bara en supportkontakt. Betald åtkomst måste först löpa ut eller avslutas. Det finns ännu ingen separat offentlig sida för att ta bort bara en supportkontakt.",
"bt": "Webbåtkomst och butiksabonnemang",
"bi": "Var du betalade avgör om åtkomst förnyas och vem som kan återbetala.",
"b1t": "Engångs webbåtkomst",
"b1": "Webbplatsen debiterar en gång för den period du väljer: en månad, 6 månader eller ett år. Ingen automatisk förnyelse och inget sparat kort för senare debitering. Kort går via Revolut, krypto via OxaPay. Windows-appen och Android-APK köps på webbplatsen.",
"b2t": "Apple Pay och Google Pay på webbplatsen",
"b2": "Apple Pay och Google Pay på webbplatsen är plånböcker vid kortkassan. Det är inte App Store- eller Google Play-abonnemang.",
"b3t": "App Store och Google Play",
"b3": "De butikerna säljer abonnemang med automatisk förnyelse. Nya butikskunder får 3 dagars provperiod. Avsluta i butiken minst 24 timmar före förnyelse. Ett butiksabonnemang kopplar Pro till ett Account ID åt gången.",
"b4t": "Vad vi inte säljer",
"b4": "Det finns inget köp med Telegram Stars, inget köp i Microsoft Store och ingen saldotankning. Windows-appen är en direkt installerare.",
"ct": "Återställ, avsluta eller återbetala",
"ci": "Återställning, avslut och återbetalning är olika saker.",
"c1t": "Återställ",
"c1": "Återställ lägger redan betald åtkomst på ett Account ID. I App Store- eller Google Play-appen: öppna Profil, Prenumeration, sedan Återställ köp. Återställning på ett annat Account ID flyttar Pro dit. Ett webbköp syns när appen är inloggad med det Account ID som användes vid betalning. Starta om appen om det inte syns än. APK:n har ingen knappen Återställ köp.",
"c2t": "Avsluta",
"c2": "Avsluta stoppar nästa butiksförnyelse. Det ger i sig inte pengar tillbaka. På iPhone: Inställningar, ditt namn, Prenumerationer, Doppler VPN, Avsluta. På Android: Play Butik, profil, Betalningar och prenumerationer, Prenumerationer, Avsluta. Ett webbköp förnyas inte, så det finns inget att avsluta.",
"c3t": "Återbetala",
"c3": "Återbetalning är en begäran om pengarna tillbaka. Återbetalningspolicyn beskriver stegen för webbkort, krypto, App Store och Google Play. Skicka inte kortnummer.",
"gt": "Guider", "g1": "Account ID och återställning", "g2": "Webbåtkomst och butiksabonnemang", "g3": "Återställ, avsluta eller återbetala", "g4": "Återbetalning",
"faq": "Kunder i EU, EES och Storbritannien har 14 dagars ångerrätt. För övriga är den publicerade godvilligheten 30 dagar och endast första köpet; kampanjer och rabatter undantas. App Store-återbetalningar via Apple, Google Play via Google. Vid webbkort eller krypto: ge support Account ID och orderreferens. Skicka inte kortnummer.",
"home": "Kunder i EU, EES och Storbritannien har 14 dagars ångerrätt. För övriga är den publicerade godvilligheten 30 dagar och endast första köpet; kampanjer och rabatter undantas. Webbkort och krypto: mejla support@simnetiq.store med Account ID. Skicka inte kortnummer. App Store- och Google Play-återbetalningar begärs i butiken. Se återbetalningspolicyn på denna webbplats.",
"guar": "Kunder i EU, EES och Storbritannien har 14 dagars ångerrätt. För övriga är den publicerade godvilligheten 30 dagar och endast första köpet; kampanjer och rabatter undantas. Webbcheckout är en engångsbetalning och förnyas inte automatiskt. Abonnemang i App Store och Google Play förnyas tills du avslutar dem.",
"foot": "Säker betalning med kort (Revolut) eller krypto (OxaPay). Webbcheckout är en engångsbetalning och förnyas inte automatiskt.",
"sub": "Engångsbetalning med kort (Revolut) eller krypto (OxaPay). Ingen automatisk förnyelse. Kunder i EU, EES och Storbritannien har 14 dagars ångerrätt. På andra ställen är den publicerade godvilligheten 30 dagar och endast första köpet.",
"eb": "14 dagars ångerrätt i EU, EES och Storbritannien. För övriga kunder 30 dagars godvillig återbetalning på första köpet.",
"er": "Om Doppler VPN inte fungerar för dig, svara på detta mejl eller kontakta {email} med order-ID och Account ID. Skicka inte kortnummer. En webåterbetalning gäller det belopp du betalade.",
"pt": "Supportkontakt och kontoradering",
"pc": "Att koppla e-post eller Telegram för återställning eller support är inte detsamma som att radera kontot. Raderingssidan raderar Doppler-kontot. Den tar inte bort bara en supportkontakt. Betalningsuppgifter kan sparas där lagen kräver det. Det finns ingen separat offentlig sida för att ta bort bara en supportkontakt.",
}))

save("da", L({
"u": "Senest opdateret: 28. september 2026",
"rt": "Refusion",
"ri": "Denne politik gælder køb af Doppler VPN fra SIMNETIQ LTD (nummer 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Adgang via hjemmesiden er en engangsbetaling. Abonnementer i App Store og Google Play fornyes, indtil du opsiger dem i butikken.",
"ai": "Apples vejledning til refusion", "ar": "Rapportér et problem til Apple", "gi": "Google Plays refusionspolitik",
"e1t": "1. Fortrydelse i EU/EØS (14 dage)",
"e1": "Hvis du er forbruger i Den Europæiske Union eller EØS, kan du fortryde inden for 14 dage uden at angive grund. Skriv til support@simnetiq.store før de 14 dage udløber. Vi refunderer det beløb, du betalte, og trækker ikke betalingsformidlerens gebyr fra. Fradrag for allerede brugt tjeneste er ikke automatisk. Køb i App Store eller Google Play anmodes i den butik.",
"e2t": "2. Fortrydelse i Storbritannien (14 dage)",
"e2": "Hvis du er forbruger i Storbritannien, har du 14 dages fortrydelsesret efter Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Send en klar erklæring til support@simnetiq.store. Vi refunderer det beløb, du betalte, og trækker ikke formidlerens gebyr fra. Fradrag for allerede brugt tjeneste er ikke automatisk, og én forbindelse er i sig selv ikke et afslagsgrundlag.",
"e3t": "3. Goodwill-refusion inden for 30 dage",
"e3": "For kunder uden for EU, EØS og Storbritannien gælder den offentliggjorte goodwill: 30 dage fra det første køb, én gang pr. kunde. Kampagne- eller rabatterede køb er undtaget, medmindre loven kræver andet. Hvis refusionen bevilges, gælder den det betalte beløb. Skriv til support@simnetiq.store med Account ID og ordrenummer.",
"e4t": "4. Kortbetaling på hjemmesiden",
"e4": "Kortbetalinger på hjemmesiden, herunder Apple Pay og Google Pay på den side, behandles af Revolut. Det er ikke køb i App Store eller Google Play. Skriv til support@simnetiq.store med Account ID og ordrenummer. Send ikke kortnummeret. Denne politik trækker ikke formidlerens gebyr fra. Din bank afgør, hvornår krediteringen vises.",
"e5t": "5. Kryptobetaling (OxaPay)",
"e5": "Kryptobetalinger på hjemmesiden behandles af OxaPay. Skriv til support@simnetiq.store med Account ID, fakturanummer, coin og netværk. Vi gætter ikke afsenderadressen. Opgiv wallet-adressen. Før vi sender, bekræfter vi aktiv, netværk og beløb. Denne politik beholder ikke netværksgebyrer eller en prisændring.",
"e6t": "6. App Store",
"e6": "Apple afgør refusioner i App Store. Vi lover hverken godkendelse eller et antal dage. Brug linkene nedenfor. Hjælp til Account ID: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "Google afgør refusioner i Google Play. Det afhænger af produkt, tid siden betaling, land og årsag. Vi gør ikke ét offentliggjort tidsvindue til et generelt afslag og lover ikke godkendelse. Linket er nedenfor.",
"e8t": "8. Fornyelser",
"e8": "Et hjemmesidekøb dækker den periode, du valgte. Det fornyes ikke automatisk, og der er intet fornyelsesgebyr at refundere. Et abonnement i App Store eller Google Play fornyes, indtil du opsiger det i butikken, mindst 24 timer før periodens slutning. Hvis butikken opkrævede en uønsket fornyelse, kontakt os inden for 14 dage, så hjælper vi dig med at spørge butikken. Butikken afgør.",
"e9t": "9. Undtagelser",
"e9": "En goodwill-refusion kan afslås, hvis anmodningen er for sent, kontoen blev lukket for brud på Vilkårene, samme kunde spørger igen, eller købet var kampagne eller rabatteret. Dette fjerner ikke en lovbestemt rettighed. Betalingsformidlerens gebyr er ikke grund til at afslå eller nedsætte.",
"e10t": "10. Sådan anmoder du",
"e10": "Send Account ID, betalingsmåde (hjemmesidekort, krypto, App Store eller Google Play), ordre- eller fakturanummer og dato. En årsag er valgfri. E-mail: support@simnetiq.store. Send ikke kortnummer, seed phrase eller privat nøgle. En anmodning fra hjemmesiden forsøger vi at bekræfte inden for 2 hverdage.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.store. Forbrugere i EU kan også bruge Europa-Kommissionens ODR-platform: https://ec.europa.eu/consumers/odr.",
"at": "Account ID og gendannelse",
"ai2": "En Doppler-konto er et anonymt Account ID. Det er ikke et e-mail-login, og appens sprog er ikke det land, du bor i.",
"w1t": "Hvad Account ID er",
"w1": "ID'et har formen VPN-XXXX-XXXX-XXXX. Appen opretter det ved første start. Hjemmesiden kan oprette det ved betaling. Find det under Profil eller Indstillinger, derefter Konto. Brug samme ID på alle enheder, og hold det privat. Support beder ikke om kortnummer.",
"w2t": "Hvis du mister det",
"w2": "Hvis du har knyttet e-mail, åbn Support og vælg gendan konto. Vi sender ID'et til den e-mail. Hvis intet er knyttet, opret en supportanmodning. Et indsat ID beviser i sig selv ikke, at du ejer kontoen.",
"w3t": "Sprog er ikke bopæl",
"w3": "Russisk eller ethvert andet sprog fortæller ikke, hvilket land du bor i, eller om en sanktionsregel gælder dig.",
"w4t": "Slet konto",
"w4": "Slet konto i appen eller på sletningssiden fjerner hele Doppler-kontoen. Det fjerner ikke kun en supportkontakt. Betalt adgang skal først udløbe eller opsiges. Der er endnu ingen separat offentlig side til kun at fjerne en supportkontakt.",
"bt": "Hjemmesideadgang og butiksabonnementer",
"bi": "Hvor du betalte, afgør om adgang fornyes, og hvem der kan refundere.",
"b1t": "Engangs hjemmesideadgang",
"b1": "Hjemmesiden opkræver én gang for den periode, du vælger: en måned, 6 måneder eller et år. Ingen automatisk fornyelse og intet gemt kort til senere opkrævning. Kort går via Revolut, krypto via OxaPay. Windows-appen og Android-APK købes på hjemmesiden.",
"b2t": "Apple Pay og Google Pay på hjemmesiden",
"b2": "Apple Pay og Google Pay på hjemmesiden er wallets ved kortbetaling. Det er ikke App Store- eller Google Play-abonnementer.",
"b3t": "App Store og Google Play",
"b3": "De butikker sælger abonnementer med automatisk fornyelse. Nye butikskunder får 3 dages prøve. Opsig i butikken mindst 24 timer før fornyelse. Ét butiksabonnement knytter Pro til ét Account ID ad gangen.",
"b4t": "Hvad vi ikke sælger",
"b4": "Der er intet køb med Telegram Stars, intet køb i Microsoft Store og ingen saldoopfyldning. Windows-appen er en direkte installer.",
"ct": "Gendan, opsig eller refundér",
"ci": "Gendannelse, opsigelse og refusion er forskellige handlinger.",
"c1t": "Gendan",
"c1": "Gendan lægger allerede betalt adgang på et Account ID. I App Store- eller Google Play-appen: åbn Profil, Abonnement, derefter Gendan køb. Gendannelse på et andet Account ID flytter Pro dertil. Et hjemmesidekøb vises, når appen er logget ind med det Account ID, der blev brugt ved betaling. Genstart appen, hvis det ikke vises endnu. APK'en har ingen knap til Gendan køb.",
"c2t": "Opsig",
"c2": "Opsig stopper den næste butiksfornyelse. Det giver i sig selv ikke penge tilbage. På iPhone: Indstillinger, dit navn, Abonnementer, Doppler VPN, Opsig. På Android: Play Butik, profil, Betalinger og abonnementer, Abonnementer, Opsig. Et hjemmesidekøb fornyes ikke, så der er intet at opsige.",
"c3t": "Refundér",
"c3": "Refusion er en anmodning om pengene tilbage. Refusionspolitikken beskriver trinnene for hjemmesidekort, krypto, App Store og Google Play. Send ikke kortnummer.",
"gt": "Vejledninger", "g1": "Account ID og gendannelse", "g2": "Hjemmesideadgang og butiksabonnementer", "g3": "Gendan, opsig eller refundér", "g4": "Refusion",
"faq": "Kunder i EU, EØS og Storbritannien har 14 dages fortrydelsesret. For andre er den offentliggjorte goodwill 30 dage og kun første køb; kampagner og rabatter er undtaget. App Store-refusioner via Apple, Google Play via Google. Ved hjemmesidekort eller krypto: giv support Account ID og ordrenummer. Send ikke kortnummer.",
"home": "Kunder i EU, EØS og Storbritannien har 14 dages fortrydelsesret. For andre er den offentliggjorte goodwill 30 dage og kun første køb; kampagner og rabatter er undtaget. Hjemmesidekort og krypto: skriv til support@simnetiq.store med Account ID. Send ikke kortnummer. App Store- og Google Play-refusioner anmodes i butikken. Se refusionspolitikken på denne hjemmeside.",
"guar": "Kunder i EU, EØS og Storbritannien har 14 dages fortrydelsesret. For andre er den offentliggjorte goodwill 30 dage og kun første køb; kampagner og rabatter er undtaget. Webcheckout er en engangsbetaling og fornyes ikke automatisk. Abonnementer i App Store og Google Play fornyes, indtil du opsiger dem.",
"foot": "Sikker betaling med kort (Revolut) eller krypto (OxaPay). Webcheckout er en engangsbetaling og fornyes ikke automatisk.",
"sub": "Engangsbetaling med kort (Revolut) eller krypto (OxaPay). Ingen automatisk fornyelse. Kunder i EU, EØS og Storbritannien har 14 dages fortrydelsesret. Andre steder er den offentliggjorte goodwill 30 dage og kun første køb.",
"eb": "14 dages fortrydelsesret i EU, EØS og Storbritannien. For andre kunder 30 dages goodwill-refusion på første køb.",
"er": "Hvis Doppler VPN ikke virker for dig, besvar denne e-mail eller skriv til {email} med ordre-ID og Account ID. Send ikke kortnummer. En hjemmesiderefusion gælder det beløb, du betalte.",
"pt": "Supportkontakt og kontosletning",
"pc": "At knytte e-mail eller Telegram til gendannelse eller support er ikke det samme som at slette kontoen. Sletningssiden sletter Doppler-kontoen. Den fjerner ikke kun en supportkontakt. Betalingsoplysninger kan opbevares, hvor loven kræver det. Der er ingen separat offentlig side til kun at fjerne en supportkontakt.",
}))

save("nb", L({
"u": "Sist oppdatert: 28. september 2026",
"rt": "Refusjon",
"ri": "Denne policyen gjelder kjøp av Doppler VPN fra SIMNETIQ LTD (nummer 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Tilgang via nettstedet er en engangsbetaling. Abonnementer i App Store og Google Play fornyes til du avslutter dem i butikken.",
"ai": "Apples veiledning for refusjon", "ar": "Rapporter et problem til Apple", "gi": "Google Plays refusjonspolicy",
"e1t": "1. Angrerett i EU/EØS (14 dager)",
"e1": "Hvis du er forbruker i Den europeiske union eller EØS, kan du angre innen 14 dager uten å oppgi grunn. Send e-post til support@simnetiq.store før de 14 dagene utløper. Vi refunderer beløpet du betalte og trekker ikke betalingsformidlerens gebyr. Fradrag for allerede brukt tjeneste er ikke automatisk. Kjøp i App Store eller Google Play forespørres i den butikken.",
"e2t": "2. Angrerett i Storbritannia (14 dager)",
"e2": "Hvis du er forbruker i Storbritannia, har du 14 dagers angrerett etter Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Send en klar erklæring til support@simnetiq.store. Vi refunderer beløpet du betalte og trekker ikke formidlerens gebyr. Fradrag for allerede brukt tjeneste er ikke automatisk, og én tilkobling er i seg selv ikke grunn til avslag.",
"e3t": "3. Goodwill-refusjon innen 30 dager",
"e3": "For kunder utenfor EU, EØS og Storbritannia gjelder den publiserte goodwillen: 30 dager fra første kjøp, én gang per kunde. Kampanje- eller rabatterte kjøp er unntatt med mindre loven krever noe annet. Hvis refusjonen innvilges, gjelder den det betalte beløpet. Send e-post til support@simnetiq.store med Account ID og ordrenummer.",
"e4t": "4. Kortbetaling på nettstedet",
"e4": "Kortbetalinger på nettstedet, inkludert Apple Pay og Google Pay på den siden, behandles av Revolut. Det er ikke kjøp i App Store eller Google Play. Send e-post til support@simnetiq.store med Account ID og ordrenummer. Ikke send kortnummeret. Denne policyen trekker ikke formidlerens gebyr. Banken din avgjør når kreditten vises.",
"e5t": "5. Kryptobetaling (OxaPay)",
"e5": "Kryptobetalinger på nettstedet behandles av OxaPay. Send e-post til support@simnetiq.store med Account ID, fakturanummer, coin og nettverk. Vi gjetter ikke avsenderadressen. Oppgi lommebokadressen. Før vi sender, bekrefter vi aktivum, nettverk og beløp. Denne policyen beholder ikke nettverksgebyrer eller en prisendring.",
"e6t": "6. App Store",
"e6": "Apple avgjør refusjoner i App Store. Vi lover verken godkjenning eller et antall dager. Bruk lenkene nedenfor. Hjelp med Account ID: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "Google avgjør refusjoner i Google Play. Det avhenger av produkt, tid siden betaling, land og årsak. Vi gjør ikke ett publisert tidsvindu til et generelt avslag og lover ikke godkjenning. Lenken er nedenfor.",
"e8t": "8. Fornyelser",
"e8": "Et nettkjøp dekker perioden du valgte. Det fornyes ikke automatisk, og det finnes ingen fornyelsesavgift å refundere. Et abonnement i App Store eller Google Play fornyes til du avslutter det i butikken, minst 24 timer før periodens slutt. Hvis butikken belastet en uønsket fornyelse, kontakt oss innen 14 dager, så hjelper vi deg med å spørre butikken. Butikken avgjør.",
"e9t": "9. Unntak",
"e9": "En goodwill-refusjon kan avslås hvis forespørselen er for sen, kontoen ble stengt for brudd på Vilkårene, samme kunde spør igjen, eller kjøpet var kampanje eller rabattert. Dette fjerner ikke en lovfestet rettighet. Betalingsformidlerens gebyr er ikke grunn til å avslå eller redusere.",
"e10t": "10. Slik ber du",
"e10": "Send Account ID, betalingsmåte (nettkort, krypto, App Store eller Google Play), ordre- eller fakturanummer og dato. En årsak er valgfri. E-post: support@simnetiq.store. Ikke send kortnummer, seed phrase eller privat nøkkel. En forespørsel fra nettstedet prøver vi å bekrefte innen 2 virkedager.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-post: support@simnetiq.store. Forbrukere i EU kan også bruke Europakommisjonens ODR-plattform: https://ec.europa.eu/consumers/odr.",
"at": "Account ID og gjenoppretting",
"ai2": "En Doppler-konto er et anonymt Account ID. Det er ikke e-postinnlogging, og appens språk er ikke landet du bor i.",
"w1t": "Hva Account ID er",
"w1": "ID-en har formen VPN-XXXX-XXXX-XXXX. Appen oppretter den ved første start. Nettstedet kan opprette den ved betaling. Finn den under Profil eller Innstillinger, deretter Konto. Bruk samme ID på alle enheter, og hold den privat. Support ber ikke om kortnummer.",
"w2t": "Hvis du mister den",
"w2": "Hvis du har knyttet e-post, åpne Support og velg gjenopprett konto. Vi sender ID-en til den e-posten. Hvis ingenting er knyttet, opprett en supportforespørsel. En innlimt ID beviser i seg selv ikke at du eier kontoen.",
"w3t": "Språk er ikke bosted",
"w3": "Russisk eller ethvert annet språk forteller ikke hvilket land du bor i, eller om en sanksjonsregel gjelder deg.",
"w4t": "Slett konto",
"w4": "Slett konto i appen eller på slettesiden fjerner hele Doppler-kontoen. Det fjerner ikke bare en supportkontakt. Betalt tilgang må først utløpe eller avsluttes. Det finnes ennå ingen egen offentlig side for å fjerne bare en supportkontakt.",
"bt": "Nettstedstilgang og butikkabonnementer",
"bi": "Hvor du betalte, avgjør om tilgang fornyes og hvem som kan refundere.",
"b1t": "Engangs nettstedstilgang",
"b1": "Nettstedet belaster én gang for perioden du velger: en måned, 6 måneder eller et år. Ingen automatisk fornyelse og ingen lagret kort for senere belastning. Kort går via Revolut, krypto via OxaPay. Windows-appen og Android-APK kjøpes på nettstedet.",
"b2t": "Apple Pay og Google Pay på nettstedet",
"b2": "Apple Pay og Google Pay på nettstedet er lommebøker ved kortkassen. Det er ikke App Store- eller Google Play-abonnementer.",
"b3t": "App Store og Google Play",
"b3": "De butikkene selger abonnementer med automatisk fornyelse. Nye butikkunder får 3 dagers prøveperiode. Avslutt i butikken minst 24 timer før fornyelse. Ett butikkabonnement knytter Pro til ett Account ID om gangen.",
"b4t": "Hva vi ikke selger",
"b4": "Det finnes ikke kjøp med Telegram Stars, ikke kjøp i Microsoft Store og ingen saldooppfylling. Windows-appen er en direkte installasjonsfil.",
"ct": "Gjenopprett, avslutt eller refunder",
"ci": "Gjenoppretting, avslutning og refusjon er ulike handlinger.",
"c1t": "Gjenopprett",
"c1": "Gjenopprett legger allerede betalt tilgang på et Account ID. I App Store- eller Google Play-appen: åpne Profil, Abonnement, deretter Gjenopprett kjøp. Gjenoppretting på et annet Account ID flytter Pro dit. Et nettkjøp vises når appen er logget inn med Account ID-en som ble brukt ved betaling. Start appen på nytt hvis den ikke vises ennå. APK-en har ingen knappen Gjenopprett kjøp.",
"c2t": "Avslutt",
"c2": "Avslutt stopper neste butikkfornyelse. Det gir i seg selv ikke penger tilbake. På iPhone: Innstillinger, navnet ditt, Abonnementer, Doppler VPN, Avslutt. På Android: Play Butikk, profil, Betalinger og abonnementer, Abonnementer, Avslutt. Et nettkjøp fornyes ikke, så det er ingenting å avslutte.",
"c3t": "Refunder",
"c3": "Refusjon er en forespørsel om pengene tilbake. Refusjonspolicyen beskriver stegene for nettkort, krypto, App Store og Google Play. Ikke send kortnummer.",
"gt": "Veiledninger", "g1": "Account ID og gjenoppretting", "g2": "Nettstedstilgang og butikkabonnementer", "g3": "Gjenopprett, avslutt eller refunder", "g4": "Refusjon",
"faq": "Kunder i EU, EØS og Storbritannia har 14 dagers angrerett. For andre er den publiserte goodwillen 30 dager og kun første kjøp; kampanjer og rabatter er unntatt. App Store-refusjoner via Apple, Google Play via Google. Ved nettkort eller krypto: gi support Account ID og ordrenummer. Ikke send kortnummer.",
"home": "Kunder i EU, EØS og Storbritannia har 14 dagers angrerett. For andre er den publiserte goodwillen 30 dager og kun første kjøp; kampanjer og rabatter er unntatt. Nettkort og krypto: send e-post til support@simnetiq.store med Account ID. Ikke send kortnummer. App Store- og Google Play-refusjoner forespørres i butikken. Se refusjonspolicyen på dette nettstedet.",
"guar": "Kunder i EU, EØS og Storbritannia har 14 dagers angrerett. For andre er den publiserte goodwillen 30 dager og kun første kjøp; kampanjer og rabatter er unntatt. Webcheckout er en engangsbetaling og fornyes ikke automatisk. Abonnementer i App Store og Google Play fornyes til du avslutter dem.",
"foot": "Sikker betaling med kort (Revolut) eller krypto (OxaPay). Webcheckout er en engangsbetaling og fornyes ikke automatisk.",
"sub": "Engangsbetaling med kort (Revolut) eller krypto (OxaPay). Ingen automatisk fornyelse. Kunder i EU, EØS og Storbritannia har 14 dagers angrerett. Andre steder er den publiserte goodwillen 30 dager og kun første kjøp.",
"eb": "14 dagers angrerett i EU, EØS og Storbritannia. For andre kunder 30 dagers goodwill-refusjon på første kjøp.",
"er": "Hvis Doppler VPN ikke fungerer for deg, svar på denne e-posten eller kontakt {email} med ordre-ID og Account ID. Ikke send kortnummer. En nettrefusjon gjelder beløpet du betalte.",
"pt": "Supportkontakt og kontosletting",
"pc": "Å knytte e-post eller Telegram for gjenoppretting eller support er ikke det samme som å slette kontoen. Slettesiden sletter Doppler-kontoen. Den fjerner ikke bare en supportkontakt. Betalingsopplysninger kan lagres der loven krever det. Det finnes ingen egen offentlig side for å fjerne bare en supportkontakt.",
}))

save("fi", L({
"u": "Viimeksi päivitetty: 28. syyskuuta 2026",
"rt": "Hyvitys",
"ri": "Tämä käytäntö koskee Doppler VPN -ostoja SIMNETIQ LTD:ltä (numero 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Verkkosivuston käyttöoikeus on kertamaksu. App Storen ja Google Playn tilaukset uusiutuvat, kunnes peruutat ne kaupassa.",
"ai": "Applen hyvitysohjeet", "ar": "Ilmoita ongelma Applelle", "gi": "Google Playn hyvityskäytäntö",
"e1t": "1. Peruutusoikeus EU:ssa/ETA:ssa (14 päivää)",
"e1": "Jos olet kuluttaja Euroopan unionissa tai ETA-alueella, voit peruuttaa 14 päivän kuluessa ilman syytä. Lähetä sähköpostia osoitteeseen support@simnetiq.store ennen 14 päivän päättymistä. Hyvitämme maksetun summan emmekä vähennä maksupalvelun palkkiota. Vähennyksiä jo käytetystä palvelusta ei tehdä automaattisesti. App Storen tai Google Playn ostot pyydetään kyseisestä kaupasta.",
"e2t": "2. Peruutusoikeus Yhdistyneessä kuningaskunnassa (14 päivää)",
"e2": "Jos olet kuluttaja Yhdistyneessä kuningaskunnassa, sinulla on 14 päivän peruutusoikeus Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 -säännösten nojalla. Lähetä selkeä ilmoitus osoitteeseen support@simnetiq.store. Hyvitämme maksetun summan emmekä vähennä maksupalvelun palkkiota. Vähennyksiä jo käytetystä palvelusta ei tehdä automaattisesti, eikä yksi yhteys ole yksinään hylkäysperuste.",
"e3t": "3. Hyvän tahdon hyvitys 30 päivän kuluessa",
"e3": "Asiakkaille EU:n, ETA:n ja Yhdistyneen kuningaskunnan ulkopuolella julkaistu hyvän tahdon hyvitys on 30 päivää ensimmäisestä ostosta, kerran asiakasta kohden. Kampanja- tai alennusostot on suljettu pois, ellei laki toisin vaadi. Jos hyvitys myönnetään, se koskee maksettua summaa. Lähetä sähköpostia osoitteeseen support@simnetiq.store ja ilmoita Account ID sekä tilausviite.",
"e4t": "4. Korttimaksu verkkosivustolla",
"e4": "Verkkosivuston korttimaksut, mukaan lukien Apple Pay ja Google Pay kyseisellä sivulla, käsittelee Revolut. Ne eivät ole App Storen tai Google Playn ostoja. Lähetä sähköpostia osoitteeseen support@simnetiq.store Account ID:llä ja tilausviitteellä. Älä lähetä kortin numeroa. Tämä käytäntö ei vähennä maksupalvelun palkkiota. Pankkisi päättää, milloin hyvitys näkyy.",
"e5t": "5. Kryptomaksu (OxaPay)",
"e5": "Verkkosivuston kryptomaksut käsittelee OxaPay. Lähetä sähköpostia osoitteeseen support@simnetiq.store Account ID:llä, laskuviitteellä, kolikolla ja verkolla. Emme arvaa lähettäjän osoitetta. Anna lompakko-osoite. Ennen lähettämistä vahvistamme omaisuuden, verkon ja summan. Tämä käytäntö ei pidätä verkkomaksuja eikä hinnanmuutosta.",
"e6t": "6. App Store",
"e6": "Apple päättää App Storen hyvityksistä. Emme lupaa hyväksyntää emmekä päivien määrää. Käytä alla olevia linkkejä. Apua Account ID:hen: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "Google päättää Google Playn hyvityksistä. Se riippuu tuotteesta, maksusta kuluneesta ajasta, maasta ja syystä. Emme muuta yhtä julkaistua aikaikkunaa yleiseksi hylkäykseksi emmekä lupaa hyväksyntää. Linkki on alla.",
"e8t": "8. Uusinnat",
"e8": "Verkkosivusto-osto kattaa valitsemasi jakson. Se ei uusiudu automaattisesti, eikä ole uusintamaksua hyvitettäväksi. App Storen tai Google Playn tilaus uusiutuu, kunnes peruutat sen kaupassa, vähintään 24 tuntia ennen jakson päättymistä. Jos kauppa veloitti ei-toivotun uusinnan, ota yhteyttä 14 päivän kuluessa; autamme pyytämään kauppaa. Kauppa päättää.",
"e9t": "9. Poikkeukset",
"e9": "Hyvän tahdon hyvitys voidaan hylätä, jos pyyntö on myöhässä, tili suljettiin ehtojen rikkomisen vuoksi, sama asiakas pyytää uudelleen tai osto oli kampanja tai alennettu. Tämä ei poista lakisääteistä oikeutta. Maksupalvelun palkkio ei ole peruste hylätä tai alentaa hyvitystä.",
"e10t": "10. Miten pyydät",
"e10": "Lähetä Account ID, maksutapa (verkkosivuston kortti, krypto, App Store tai Google Play), tilaus- tai laskuviite ja päivämäärä. Syy on valinnainen. Sähköposti: support@simnetiq.store. Älä lähetä kortin numeroa, seed phrasea tai yksityistä avainta. Verkkosivustopyynnön pyrimme kuittaamaan 2 arkipäivän kuluessa.",
"e11t": "11. Yhteystiedot",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Sähköposti: support@simnetiq.store. EU:n kuluttajat voivat käyttää myös Euroopan komission ODR-alustaa: https://ec.europa.eu/consumers/odr.",
"at": "Account ID ja palautus",
"ai2": "Doppler-tili on anonyymi Account ID. Se ei ole sähköpostikirjautuminen, eikä sovelluksen kieli ole asuinmaasi.",
"w1t": "Mikä Account ID on",
"w1": "ID on muodossa VPN-XXXX-XXXX-XXXX. Sovellus luo sen ensimmäisellä käynnistyksellä. Verkkosivusto voi luoda sen maksussa. Se on Profiilissa tai Asetuksissa kohdassa Tili. Käytä samaa ID:tä jokaisella laitteella ja pidä se yksityisenä. Tuki ei pyydä kortin numeroa.",
"w2t": "Jos kadotat sen",
"w2": "Jos linkitit sähköpostin, avaa Tuki ja valitse tilin palautus. Lähetämme ID:n siihen sähköpostiin. Jos mitään ei ole linkitetty, tee tukipyyntö. Liitetty ID ei yksin todista, että tili on sinun.",
"w3t": "Kieli ei ole asuinpaikka",
"w3": "Venäjä tai mikään muu kieli ei kerro, missä maassa asut tai koskeeko sinua sanktiosääntö.",
"w4t": "Tilin poistaminen",
"w4": "Tilin poistaminen sovelluksessa tai poistosivulla poistaa koko Doppler-tilin. Se ei poista vain tukiyhteystietoa. Maksetun käyttöoikeuden on ensin päätyttävä tai peruututtava. Erillistä julkista sivua vain tukiyhteystiedon poistamiseen ei vielä ole.",
"bt": "Verkkosivuston käyttöoikeus ja kauppatilaukset",
"bi": "Missä maksoit, ratkaisee uusiutuuko käyttöoikeus ja kuka voi hyvittää.",
"b1t": "Kertaluonteinen verkkosivuston käyttöoikeus",
"b1": "Verkkosivusto veloittaa kerran valitsemastasi jaksosta: kuukausi, 6 kuukautta tai vuosi. Ei automaattista uusintaa eikä tallennettua korttia myöhempää veloitusta varten. Kortti kulkee Revolutin kautta, krypto OxaPayn kautta. Windows-sovellus ja Android-APK ostetaan verkkosivustolta.",
"b2t": "Apple Pay ja Google Pay verkkosivustolla",
"b2": "Apple Pay ja Google Pay verkkosivustolla ovat lompakoita korttimaksussa. Ne eivät ole App Storen tai Google Playn tilauksia.",
"b3t": "App Store ja Google Play",
"b3": "Nuo kaupat myyvät automaattisesti uusiutuvia tilauksia. Uudet kauppa-asiakkaat saavat 3 päivän kokeilun. Peruuta kaupassa vähintään 24 tuntia ennen uusintaa. Yksi kauppatilaus liittää Pron yhteen Account ID:hen kerrallaan.",
"b4t": "Mitä emme myy",
"b4": "Ei Telegram Stars -ostoa, ei Microsoft Store -ostoa eikä saldon latausta. Windows-sovellus on suora asennusohjelma.",
"ct": "Palauta, peruuta tai hyvitä",
"ci": "Palautus, peruutus ja hyvitys ovat eri toimia.",
"c1t": "Palauta",
"c1": "Palautus asettaa jo maksetun käyttöoikeuden Account ID:lle. App Store- tai Google Play -sovelluksessa: avaa Profiili, Tilaus, sitten Palauta ostokset. Palautus toiselle Account ID:lle siirtää Pron sinne. Verkkosivusto-osto näkyy, kun sovellus on kirjautunut maksussa käytetyllä Account ID:llä. Käynnistä sovellus uudelleen, jos se ei vielä näy. APK:ssa ei ole Palauta ostokset -painiketta.",
"c2t": "Peruuta",
"c2": "Peruutus estää seuraavan kaupan uusinnan. Se ei itsessään palauta rahaa. iPhonessa: Asetukset, nimesi, Tilaukset, Doppler VPN, Peruuta. Androidilla: Play Kauppa, profiili, Maksut ja tilaukset, Tilaukset, Peruuta. Verkkosivusto-osto ei uusiudu, joten peruutettavaa ei ole.",
"c3t": "Hyvitä",
"c3": "Hyvitys on pyyntö saada rahat takaisin. Hyvityskäytäntö kuvaa vaiheet verkkosivuston kortille, kryptolle, App Storelle ja Google Playlle. Älä lähetä kortin numeroa.",
"gt": "Oppaat", "g1": "Account ID ja palautus", "g2": "Verkkosivuston käyttöoikeus ja kauppatilaukset", "g3": "Palauta, peruuta tai hyvitä", "g4": "Hyvitys",
"faq": "EU:n, ETA:n ja Yhdistyneen kuningaskunnan asiakkailla on 14 päivän peruutusoikeus. Muille julkaistu hyvän tahdon hyvitys on 30 päivää ja vain ensimmäinen osto; kampanjat ja alennukset on suljettu pois. App Store -hyvitykset Applen, Google Play Googlen kautta. Verkkosivuston kortti tai krypto: anna tuelle Account ID ja tilausviite. Älä lähetä kortin numeroa.",
"home": "EU:n, ETA:n ja Yhdistyneen kuningaskunnan asiakkailla on 14 päivän peruutusoikeus. Muille julkaistu hyvän tahdon hyvitys on 30 päivää ja vain ensimmäinen osto; kampanjat ja alennukset on suljettu pois. Verkkosivuston kortti ja krypto: lähetä sähköpostia osoitteeseen support@simnetiq.store Account ID:llä. Älä lähetä kortin numeroa. App Store- ja Google Play -hyvitykset pyydetään kaupasta. Katso hyvityskäytäntö tältä verkkosivustolta.",
"guar": "EU:n, ETA:n ja Yhdistyneen kuningaskunnan asiakkailla on 14 päivän peruutusoikeus. Muille julkaistu hyvän tahdon hyvitys on 30 päivää ja vain ensimmäinen osto; kampanjat ja alennukset on suljettu pois. Webcheckout on kertamaksu eikä uusiudu automaattisesti. App Storen ja Google Playn tilaukset uusiutuvat, kunnes peruutat ne.",
"foot": "Turvallinen maksu kortilla (Revolut) tai kryptolla (OxaPay). Webcheckout on kertamaksu eikä uusiudu automaattisesti.",
"sub": "Kertamaksu kortilla (Revolut) tai kryptolla (OxaPay). Ei automaattista uusintaa. EU:n, ETA:n ja Yhdistyneen kuningaskunnan asiakkailla on 14 päivän peruutusoikeus. Mualla julkaistu hyvän tahdon hyvitys on 30 päivää ja vain ensimmäinen osto.",
"eb": "14 päivän peruutusoikeus EU:ssa, ETA:ssa ja Yhdistyneessä kuningaskunnassa. Muille asiakkaille 30 päivän hyvän tahdon hyvitys ensimmäiseen ostoon.",
"er": "Jos Doppler VPN ei toimi sinulle, vastaa tähän sähköpostiin tai ota yhteyttä osoitteeseen {email} tilaus-ID:llä ja Account ID:llä. Älä lähetä kortin numeroa. Verkkosivuston hyvitys koskee maksettua summaa.",
"pt": "Tukiyhteystieto ja tilin poisto",
"pc": "Sähköpostin tai Telegramin linkittäminen palautukseen tai tukeen ei ole tilin poisto. Poistosivu poistaa Doppler-tilin. Se ei poista vain tukiyhteystietoa. Maksutietoja voidaan säilyttää lain vaatiessa. Erillistä julkista sivua vain tukiyhteystiedon poistamiseen ei ole.",
}))

save("et", L({
"u": "Viimati uuendatud: 28. september 2026",
"rt": "Tagasimakse",
"ri": "See poliitika hõlmab Doppler VPN ostusid SIMNETIQ LTD-lt (number 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Veebisaidi juurdepääs on ühekordne makse. App Store’i ja Google Play plaanid uuenevad, kuni tühistate need poes.",
"ai": "Apple’i tagasimaksejuhised", "ar": "Teata probleemist Apple’ile", "gi": "Google Play tagasimaksepoliitika",
"e1t": "1. Taganemine EL-is/EMP-is (14 päeva)",
"e1": "Kui olete tarbija Euroopa Liidus või EMP-is, saate 14 päeva jooksul ilma põhjuseta taganeda. Kirjutage aadressile support@simnetiq.store enne 14 päeva lõppu. Tagastame makstud summa ega arvesta maha maksetöötleja tasu. Juba kasutatud teenuse mahaarvamine ei ole automaatne. App Store’i või Google Play ostud esitatakse selles poes.",
"e2t": "2. Taganemine Ühendkuningriigis (14 päeva)",
"e2": "Kui olete tarbija Ühendkuningriigis, on teil 14-päevane taganemisõigus vastavalt Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Saatke selge avaldus aadressile support@simnetiq.store. Tagastame makstud summa ega arvesta maha töötleja tasu. Juba kasutatud teenuse mahaarvamine ei ole automaatne ning ühekordne ühendus ei ole iseenesest keeldumise alus.",
"e3t": "3. Hea tahte tagasimakse 30 päeva jooksul",
"e3": "Klientidele väljaspool EL-i, EMP-i ja Ühendkuningriiki kehtib avaldatud hea tahe: 30 päeva esimesest ostust, üks kord kliendi kohta. Kampaania- või soodusostud on välistatud, kui seadus ei nõua teisiti. Kui tagasimakse antakse, kehtib see makstud summale. Kirjutage aadressile support@simnetiq.store koos Account ID ja tellimuse viitega.",
"e4t": "4. Kaardimakse veebisaidil",
"e4": "Veebisaidi kaardimaksed, sealhulgas Apple Pay ja Google Pay sellel lehel, töötleb Revolut. Need ei ole App Store’i ega Google Play ostud. Kirjutage aadressile support@simnetiq.store koos Account ID ja tellimuse viitega. Ärge saatke kaardi numbrit. See poliitika ei arvesta maha töötleja tasu. Pank otsustab, millal krediit ilmub.",
"e5t": "5. Krüptomakse (OxaPay)",
"e5": "Veebisaidi krüptomaksed töötleb OxaPay. Kirjutage aadressile support@simnetiq.store koos Account ID, arve viite, mündi ja võrguga. Me ei arva saatja aadressi. Esitage rahakoti aadress. Enne saatmist kinnitame vara, võrgu ja summa. See poliitika ei pea kinni võrgutasusid ega hinnamuutust.",
"e6t": "6. App Store",
"e6": "App Store’i tagasimaksete üle otsustab Apple. Me ei luba heakskiitu ega päevade arvu. Kasutage allolevaid linke. Abi Account ID-ga: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "Google Play tagasimaksete üle otsustab Google. See sõltub tootest, maksmisest möödunud ajast, riigist ja põhjusest. Me ei muuda ühte avaldatud ajavahemikku üldiseks keeldumiseks ega luba heakskiitu. Link on allpool.",
"e8t": "8. Uuendused",
"e8": "Veebisaidi ost katab valitud perioodi. See ei uuene automaatselt ja uuendustasu tagastamiseks ei ole. App Store’i või Google Play plaan uueneb, kuni tühistate selle poes, vähemalt 24 tundi enne perioodi lõppu. Kui pood võttis soovimatu uuenduse, võtke meiega ühendust 14 päeva jooksul; aitame poodi küsida. Pood otsustab.",
"e9t": "9. Erandid",
"e9": "Hea tahte tagasimakset võidakse keelduda, kui taotlus on hilinenud, konto suleti Tingimuste rikkumise tõttu, sama klient küsib uuesti või ost oli kampaania või soodustus. See ei võta ära seaduslikku õigust. Maksetöötleja tasu ei ole keeldumise ega vähendamise põhjus.",
"e10t": "10. Kuidas taotleda",
"e10": "Saatke Account ID, makseviis (veebisaidi kaart, krüpto, App Store või Google Play), tellimuse või arve viide ja kuupäev. Põhjus on valikuline. E-post: support@simnetiq.store. Ärge saatke kaardi numbrit, seed phrase’i ega privaatvõtit. Veebisaidi taotlust püüame kinnitada 2 tööpäeva jooksul.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-post: support@simnetiq.store. EL-i tarbijad saavad kasutada ka Euroopa Komisjoni ODR-platvormi: https://ec.europa.eu/consumers/odr.",
"at": "Account ID ja taastamine",
"ai2": "Doppleri konto on anonüümne Account ID. See ei ole e-posti sisselogimine ning rakenduse keel ei ole teie elukohariik.",
"w1t": "Mis on Account ID",
"w1": "ID on kujul VPN-XXXX-XXXX-XXXX. Rakendus loob selle esimesel käivitamisel. Veebisait võib selle luua maksmisel. See on Profiilis või Seadetes jaotises Konto. Kasutage sama ID-d igal seadmel ja hoidke seda salajas. Tugi ei küsi kaardi numbrit.",
"w2t": "Kui kaotate selle",
"w2": "Kui sidusite e-posti, avage Tugi ja valige konto taastamine. Saadame ID sellele e-postile. Kui midagi pole seotud, esitage toe taotlus. Kleebitud ID ei tõenda iseenesest, et konto on teie oma.",
"w3t": "Keel ei ole elukoht",
"w3": "Vene või ükski teine keel ei ütle, millises riigis elate või kas teile kehtib sanktsioonireegel.",
"w4t": "Konto kustutamine",
"w4": "Konto kustutamine rakenduses või kustutuslehel eemaldab kogu Doppleri konto. See ei eemalda ainult toe kontakti. Tasuline juurdepääs peab esmalt lõppema või tühistama. Ainult toe kontakti eemaldamiseks eraldi avalikku lehte veel ei ole.",
"bt": "Veebisaidi juurdepääs ja poe tellimused",
"bi": "Kus maksite, määrab, kas juurdepääs uueneb ja kes saab tagasi maksta.",
"b1t": "Ühekordne veebisaidi juurdepääs",
"b1": "Veebisait võtab ühe korra tasu valitud perioodi eest: kuu, 6 kuud või aasta. Automaatset uuendust ega hilisemaks debiteerimiseks salvestatud kaarti ei ole. Kaart läheb Revoluti kaudu, krüpto OxaPay kaudu. Windows-rakendus ja Androidi APK ostetakse veebisaidilt.",
"b2t": "Apple Pay ja Google Pay veebisaidil",
"b2": "Apple Pay ja Google Pay veebisaidil on rahakotid kaardimakse juures. Need ei ole App Store’i ega Google Play tellimused.",
"b3t": "App Store ja Google Play",
"b3": "Need poed müüvad automaatselt uuenevaid tellimusi. Uued poekliendid saavad 3-päevase proovi. Tühistage poes vähemalt 24 tundi enne uuendust. Üks poe tellimus seob Pro ühe Account ID-ga korraga.",
"b4t": "Mida me ei müü",
"b4": "Telegram Starsi ostu, Microsoft Store’i ostu ega saldo täiendamist ei ole. Windowsi rakendus on otsene installer.",
"ct": "Taasta, tühista või tagasta",
"ci": "Taastamine, tühistamine ja tagasimakse on erinevad toimingud.",
"c1t": "Taasta",
"c1": "Taastamine paneb juba makstud juurdepääsu Account ID-le. App Store’i või Google Play rakenduses: avage Profiil, Tellimus, seejärel Taasta ostud. Taastamine teisel Account ID-l liigutab Pro sinna. Veebisaidi ost ilmub, kui rakendus on sisse logitud maksmisel kasutatud Account ID-ga. Käivitage rakendus uuesti, kui see veel ei ilmu. APK-l ei ole nuppu Taasta ostud.",
"c2t": "Tühista",
"c2": "Tühistamine peatab järgmise poe uuenduse. See iseenesest raha ei tagasta. iPhone’is: Seaded, teie nimi, Tellimused, Doppler VPN, Tühista. Androidis: Play pood, profiil, Maksed ja tellimused, Tellimused, Tühista. Veebisaidi ost ei uuene, seega midagi tühistada ei ole.",
"c3t": "Tagasta",
"c3": "Tagasimakse on taotlus raha tagasi saada. Tagasimaksepoliitika kirjeldab samme veebisaidi kaardi, krüpto, App Store’i ja Google Play jaoks. Ärge saatke kaardi numbrit.",
"gt": "Juhendid", "g1": "Account ID ja taastamine", "g2": "Veebisaidi juurdepääs ja poe tellimused", "g3": "Taasta, tühista või tagasta", "g4": "Tagasimakse",
"faq": "EL-i, EMP-i ja Ühendkuningriigi klientidel on 14-päevane taganemisõigus. Teistele on avaldatud hea tahe 30 päeva ja ainult esimene ost; kampaaniad ja soodustused on välistatud. App Store’i tagasimaksed Apple’i, Google Play Google’i kaudu. Veebisaidi kaardi või krüpto puhul andke toele Account ID ja tellimuse viide. Ärge saatke kaardi numbrit.",
"home": "EL-i, EMP-i ja Ühendkuningriigi klientidel on 14-päevane taganemisõigus. Teistele on avaldatud hea tahe 30 päeva ja ainult esimene ost; kampaaniad ja soodustused on välistatud. Veebisaidi kaart ja krüpto: kirjutage aadressile support@simnetiq.store koos Account ID-ga. Ärge saatke kaardi numbrit. App Store’i ja Google Play tagasimaksed esitatakse poes. Vt tagasimaksepoliitikat sellel veebisaidil.",
"guar": "EL-i, EMP-i ja Ühendkuningriigi klientidel on 14-päevane taganemisõigus. Teistele on avaldatud hea tahe 30 päeva ja ainult esimene ost; kampaaniad ja soodustused on välistatud. Webcheckout on ühekordne makse ega uuene automaatselt. App Store’i ja Google Play plaanid uuenevad, kuni need tühistate.",
"foot": "Turvaline makse kaardiga (Revolut) või krüptoga (OxaPay). Webcheckout on ühekordne makse ega uuene automaatselt.",
"sub": "Ühekordne makse kaardiga (Revolut) või krüptoga (OxaPay). Automaatset uuendust ei ole. EL-i, EMP-i ja Ühendkuningriigi klientidel on 14-päevane taganemisõigus. Mujal on avaldatud hea tahe 30 päeva ja ainult esimene ost.",
"eb": "14-päevane taganemisõigus EL-is, EMP-is ja Ühendkuningriigis. Teistele klientidele 30-päevane hea tahte tagasimakse esimesel ostul.",
"er": "Kui Doppler VPN teile ei sobi, vastake sellele e-kirjale või kirjutage aadressile {email} tellimuse ID ja Account ID-ga. Ärge saatke kaardi numbrit. Veebisaidi tagasimakse kehtib makstud summale.",
"pt": "Toe kontakt ja konto kustutamine",
"pc": "E-posti või Telegrami sidumine taastamiseks või toeks ei ole konto kustutamine. Kustutusleht kustutab Doppleri konto. See ei eemalda ainult toe kontakti. Makseandmeid võidakse säilitada, kui seadus seda nõuab. Ainult toe kontakti eemaldamiseks eraldi avalikku lehte ei ole.",
}))

save("lv", L({
"u": "Pēdējoreiz atjaunināts: 2026. gada 28. septembrī",
"rt": "Atmaksas",
"ri": "Šī politika attiecas uz Doppler VPN pirkumiem no SIMNETIQ LTD (numurs 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Piekļuve vietnē ir vienreizējs maksājums. App Store un Google Play plāni atjaunojas, līdz tos atceļat veikalā.",
"ai": "Apple atmaksas norādījumi", "ar": "Ziņot par problēmu Apple", "gi": "Google Play atmaksas politika",
"e1t": "1. Atcelšana ES/EEZ (14 dienas)",
"e1": "Ja esat patērētājs Eiropas Savienībā vai EEZ, varat atcelt 14 dienu laikā bez iemesla. Rakstiet uz support@simnetiq.store pirms 14 dienu beigām. Atmaksājam samaksāto summu un neatskaitām maksājumu apstrādātāja komisiju. Atskaitījums par jau izmantoto pakalpojumu nav automātisks. App Store vai Google Play pirkumus pieprasa tajā veikalā.",
"e2t": "2. Atcelšana Apvienotajā Karalistē (14 dienas)",
"e2": "Ja esat patērētājs Apvienotajā Karalistē, jums ir 14 dienu atcelšanas tiesības saskaņā ar Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Nosūtiet skaidru paziņojumu uz support@simnetiq.store. Atmaksājam samaksāto summu un neatskaitām apstrādātāja komisiju. Atskaitījums par jau izmantoto pakalpojumu nav automātisks, un viena savienojuma izveide pati par sevi nav atteikuma iemesls.",
"e3t": "3. Labvēlības atmaksa 30 dienu laikā",
"e3": "Klientiem ārpus ES, EEZ un Apvienotās Karalistes publicētā labvēlība ir 30 dienas no pirmā pirkuma, vienreiz uz klientu. Akcijas vai atlaides pirkumi ir izslēgti, ja vien likums neprasa citādi. Ja atmaksa tiek piešķirta, tā attiecas uz samaksāto summu. Rakstiet uz support@simnetiq.store ar Account ID un pasūtījuma atsauci.",
"e4t": "4. Kartes maksājums vietnē",
"e4": "Kartes maksājumus vietnē, tostarp Apple Pay un Google Pay tajā lapā, apstrādā Revolut. Tie nav App Store vai Google Play pirkumi. Rakstiet uz support@simnetiq.store ar Account ID un pasūtījuma atsauci. Nesūtiet kartes numuru. Šī politika neatskaita apstrādātāja komisiju. Banka izlemj, kad kredīts parādās.",
"e5t": "5. Kripto maksājums (OxaPay)",
"e5": "Kripto maksājumus vietnē apstrādā OxaPay. Rakstiet uz support@simnetiq.store ar Account ID, rēķina atsauci, monētu un tīklu. Mēs neuzminam sūtītāja adresi. Norādiet maka adresi. Pirms sūtīšanas apstiprinām aktīvu, tīklu un summu. Šī politika nepatur tīkla maksas vai cenas izmaiņu.",
"e6t": "6. App Store",
"e6": "Par App Store atmaksām lemj Apple. Mēs nesolām apstiprinājumu un dienu skaitu. Izmantojiet zemāk esošās saites. Palīdzība ar Account ID: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "Par Google Play atmaksām lemj Google. Tas atkarīgs no produkta, laika kopš maksājuma, valsts un iemesla. Mēs nepārvēršam vienu publicētu termiņu par vispārēju atteikumu un nesolām apstiprinājumu. Saite ir zemāk.",
"e8t": "8. Atjaunošanas",
"e8": "Vietnes pirkums attiecas uz izvēlēto periodu. Tas neatjaunojas automātiski, un nav atjaunošanas maksas, ko atmaksāt. App Store vai Google Play plāns atjaunojas, līdz to atceļat veikalā, vismaz 24 stundas pirms perioda beigām. Ja veikals iekasēja nevēlamu atjaunošanu, sazinieties 14 dienu laikā; palīdzēsim lūgt veikalu. Veikals lemj.",
"e9t": "9. Izņēmumi",
"e9": "Labvēlības atmaksu var atteikt, ja pieprasījums ir novēlots, konts tika slēgts par Noteikumu pārkāpumu, tas pats klients prasa atkārtoti vai pirkums bija akcija vai ar atlaidi. Tas neatņem likumīgas tiesības. Maksājumu apstrādātāja komisija nav iemesls atteikt vai samazināt.",
"e10t": "10. Kā pieprasīt",
"e10": "Nosūtiet Account ID, maksājuma veidu (vietnes karte, kripto, App Store vai Google Play), pasūtījuma vai rēķina atsauci un datumu. Iemesls ir izvēles. E-pasts: support@simnetiq.store. Nesūtiet kartes numuru, seed phrase vai privāto atslēgu. Vietnes pieprasījumu cenšamies apstiprināt 2 darba dienu laikā.",
"e11t": "11. Kontakti",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-pasts: support@simnetiq.store. ES patērētāji var izmantot arī Eiropas Komisijas ODR platformu: https://ec.europa.eu/consumers/odr.",
"at": "Account ID un atjaunošana",
"ai2": "Doppler konts ir anonīms Account ID. Tas nav e-pasta pieteikšanās, un lietotnes valoda nav jūsu dzīvesvietas valsts.",
"w1t": "Kas ir Account ID",
"w1": "ID ir formā VPN-XXXX-XXXX-XXXX. Lietotne to izveido pirmajā palaišanā. Vietne var to izveidot maksājuma laikā. Tas ir sadaļā Profils vai Iestatījumi, tad Konts. Izmantojiet to pašu ID katrā ierīcē un turiet to privātu. Atbalsts neprasa kartes numuru.",
"w2t": "Ja to pazaudējat",
"w2": "Ja saistījāt e-pastu, atveriet Atbalstu un izvēlieties konta atjaunošanu. Mēs nosūtīsim ID uz to e-pastu. Ja nekas nav saistīts, iesniedziet atbalsta pieprasījumu. Ielīmēts ID pats par sevi nepierāda, ka konts ir jūsu.",
"w3t": "Valoda nav dzīvesvieta",
"w3": "Krievu vai jebkura cita valoda nepasaka, kurā valstī dzīvojat vai vai uz jums attiecas sankciju noteikums.",
"w4t": "Konta dzēšana",
"w4": "Konta dzēšana lietotnē vai dzēšanas lapā noņem visu Doppler kontu. Tā nenoņem tikai atbalsta kontaktu. Apmaksātai piekļuvei vispirms jābeidzas vai jābūt atceltai. Atsevišķas publiskas lapas tikai atbalsta kontakta noņemšanai vēl nav.",
"bt": "Vietnes piekļuve un veikala abonementi",
"bi": "Kur maksājāt, nosaka, vai piekļuve atjaunojas un kurš var atmaksāt.",
"b1t": "Vienreizēja vietnes piekļuve",
"b1": "Vietne iekasē vienreiz par izvēlēto periodu: mēnesi, 6 mēnešus vai gadu. Nav automātiskas atjaunošanas un nav saglabātas kartes vēlākai norakstīšanai. Karte iet caur Revolut, kripto caur OxaPay. Windows lietotni un Android APK iegādājas vietnē.",
"b2t": "Apple Pay un Google Pay vietnē",
"b2": "Apple Pay un Google Pay vietnē ir maki pie kartes kases. Tie nav App Store vai Google Play abonementi.",
"b3t": "App Store un Google Play",
"b3": "Šie veikali pārdod automātiski atjaunojamus abonementus. Jauni veikala klienti saņem 3 dienu izmēģinājumu. Atceliet veikalā vismaz 24 stundas pirms atjaunošanas. Viens veikala abonements piesaista Pro vienam Account ID vienlaikus.",
"b4t": "Ko mēs nepārdodam",
"b4": "Nav pirkuma ar Telegram Stars, nav pirkuma Microsoft Store un nav bilances papildināšanas. Windows lietotne ir tiešs instalētājs.",
"ct": "Atjaunot, atcelt vai atmaksāt",
"ci": "Atjaunošana, atcelšana un atmaksa ir dažādas darbības.",
"c1t": "Atjaunot",
"c1": "Atjaunošana ievieto jau apmaksātu piekļuvi Account ID. App Store vai Google Play lietotnē: atveriet Profils, Abonements, tad Atjaunot pirkumus. Atjaunošana citā Account ID pārvieto Pro tur. Vietnes pirkums parādās, kad lietotne ir pieteikusies ar maksājumā izmantoto Account ID. Restartējiet lietotni, ja tas vēl nerādās. APK nav pogas Atjaunot pirkumus.",
"c2t": "Atcelt",
"c2": "Atcelšana aptur nākamo veikala atjaunošanu. Tā pati par sevi neatdod naudu. iPhone: Iestatījumi, jūsu vārds, Abonementi, Doppler VPN, Atcelt. Android: Play veikals, profils, Maksājumi un abonementi, Abonementi, Atcelt. Vietnes pirkums neatjaunojas, tāpēc nav ko atcelt.",
"c3t": "Atmaksāt",
"c3": "Atmaksa ir lūgums saņemt naudu atpakaļ. Atmaksas politika apraksta soļus vietnes kartei, kripto, App Store un Google Play. Nesūtiet kartes numuru.",
"gt": "Ceļveži", "g1": "Account ID un atjaunošana", "g2": "Vietnes piekļuve un veikala abonementi", "g3": "Atjaunot, atcelt vai atmaksāt", "g4": "Atmaksas",
"faq": "ES, EEZ un Apvienotās Karalistes klientiem ir 14 dienu atcelšanas tiesības. Pārējiem publicētā labvēlība ir 30 dienas un tikai pirmais pirkums; akcijas un atlaides ir izslēgtas. App Store atmaksas caur Apple, Google Play caur Google. Vietnes kartei vai kripto: dodiet atbalstam Account ID un pasūtījuma atsauci. Nesūtiet kartes numuru.",
"home": "ES, EEZ un Apvienotās Karalistes klientiem ir 14 dienu atcelšanas tiesības. Pārējiem publicētā labvēlība ir 30 dienas un tikai pirmais pirkums; akcijas un atlaides ir izslēgtas. Vietnes karte un kripto: rakstiet uz support@simnetiq.store ar Account ID. Nesūtiet kartes numuru. App Store un Google Play atmaksas pieprasa veikalā. Skatiet atmaksas politiku šajā vietnē.",
"guar": "ES, EEZ un Apvienotās Karalistes klientiem ir 14 dienu atcelšanas tiesības. Pārējiem publicētā labvēlība ir 30 dienas un tikai pirmais pirkums; akcijas un atlaides ir izslēgtas. Webcheckout ir vienreizējs maksājums un neatjaunojas automātiski. App Store un Google Play plāni atjaunojas, līdz tos atceļat.",
"foot": "Drošs maksājums ar karti (Revolut) vai kripto (OxaPay). Webcheckout ir vienreizējs maksājums un neatjaunojas automātiski.",
"sub": "Vienreizējs maksājums ar karti (Revolut) vai kripto (OxaPay). Bez automātiskas atjaunošanas. ES, EEZ un Apvienotās Karalistes klientiem ir 14 dienu atcelšanas tiesības. Citur publicētā labvēlība ir 30 dienas un tikai pirmais pirkums.",
"eb": "14 dienu atcelšanas tiesības ES, EEZ un Apvienotajā Karalistē. Pārējiem klientiem 30 dienu labvēlības atmaksa pirmajam pirkumam.",
"er": "Ja Doppler VPN jums neder, atbildiet uz šo e-pastu vai rakstiet uz {email} ar pasūtījuma ID un Account ID. Nesūtiet kartes numuru. Vietnes atmaksa attiecas uz samaksāto summu.",
"pt": "Atbalsta kontakts un konta dzēšana",
"pc": "E-pasta vai Telegram saistīšana atjaunošanai vai atbalstam nav konta dzēšana. Dzēšanas lapa dzēš Doppler kontu. Tā nenoņem tikai atbalsta kontaktu. Maksājumu ierakstus var glabāt, kur to prasa likums. Atsevišķas publiskas lapas tikai atbalsta kontakta noņemšanai nav.",
}))

save("lt", L({
"u": "Paskutinį kartą atnaujinta: 2026 m. rugsėjo 28 d.",
"rt": "Grąžinimai",
"ri": "Ši politika taikoma Doppler VPN pirkimams iš SIMNETIQ LTD (numeris 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Prieiga svetainėje yra vienkartinis mokėjimas. App Store ir Google Play planai atnaujinami, kol juos atšaukiate parduotuvėje.",
"ai": "Apple grąžinimo instrukcijos", "ar": "Pranešti apie problemą Apple", "gi": "Google Play grąžinimo politika",
"e1t": "1. Atsisakymas ES/EEE (14 dienų)",
"e1": "Jei esate vartotojas Europos Sąjungoje arba EEE, galite atsisakyti per 14 dienų nenurodydami priežasties. Rašykite support@simnetiq.store prieš 14 dienų pabaigą. Grąžiname sumokėtą sumą ir neatskaitome mokėjimo tvarkytojo mokesčio. Atskaita už jau naudotą paslaugą nėra automatinė. App Store arba Google Play pirkimai prašomi toje parduotuvėje.",
"e2t": "2. Atsisakymas Jungtinėje Karalystėje (14 dienų)",
"e2": "Jei esate vartotojas Jungtinėje Karalystėje, turite 14 dienų atsisakymo teisę pagal Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Siųskite aiškų pareiškimą į support@simnetiq.store. Grąžiname sumokėtą sumą ir neatskaitome tvarkytojo mokesčio. Atskaita už jau naudotą paslaugą nėra automatinė, o vienas ryšys pats savaime nėra atsisakymo pagrindas.",
"e3t": "3. Geranoriškas grąžinimas per 30 dienų",
"e3": "Klientams už ES, EEE ir Jungtinės Karalystės ribų paskelbtas geranoriškumas yra 30 dienų nuo pirmo pirkimo, kartą vienam klientui. Akcijiniai ar nuolaidiniai pirkimai neįtraukiami, nebent įstatymas reikalauja kitaip. Jei grąžinimas suteikiamas, jis taikomas sumokėtai sumai. Rašykite support@simnetiq.store su Account ID ir užsakymo nuoroda.",
"e4t": "4. Kortelės mokėjimas svetainėje",
"e4": "Kortelių mokėjimus svetainėje, įskaitant Apple Pay ir Google Pay tame puslapyje, apdoroja Revolut. Tai nėra App Store ar Google Play pirkimai. Rašykite support@simnetiq.store su Account ID ir užsakymo nuoroda. Nesiųskite kortelės numerio. Ši politika neatskaito tvarkytojo mokesčio. Bankas nusprendžia, kada atsiranda kreditas.",
"e5t": "5. Kriptovaliutos mokėjimas (OxaPay)",
"e5": "Kriptovaliutos mokėjimus svetainėje apdoroja OxaPay. Rašykite support@simnetiq.store su Account ID, sąskaitos nuoroda, moneta ir tinklu. Mes neatspėjame siuntėjo adreso. Pateikite piniginės adresą. Prieš siųsdami patvirtiname turtą, tinklą ir sumą. Ši politika nelaiko tinklo mokesčių ar kainos pokyčio.",
"e6t": "6. App Store",
"e6": "App Store grąžinimus sprendžia Apple. Negalime pažadėti patvirtinimo ar dienų skaičiaus. Naudokite toliau esančias nuorodas. Pagalba dėl Account ID: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "Google Play grąžinimus sprendžia Google. Tai priklauso nuo produkto, laiko nuo mokėjimo, šalies ir priežasties. Vieno paskelbto termino nepavirstame bendru atsisakymu ir nežadame patvirtinimo. Nuoroda žemiau.",
"e8t": "8. Atnaujinimai",
"e8": "Svetainės pirkimas apima pasirinktą laikotarpį. Jis neatnaujinamas automatiškai ir nėra atnaujinimo mokesčio, kurį grąžinti. App Store ar Google Play planas atnaujinamas, kol jį atšaukiate parduotuvėje, ne vėliau kaip 24 valandas prieš laikotarpio pabaigą. Jei parduotuvė nuskaičiavo nepageidaujamą atnaujinimą, susisiekite per 14 dienų; padėsime kreiptis į parduotuvę. Sprendžia parduotuvė.",
"e9t": "9. Išimtys",
"e9": "Geranoriškas grąžinimas gali būti atmestas, jei prašymas pavėluotas, paskyra uždaryta už Sąlygų pažeidimą, tas pats klientas prašo dar kartą arba pirkimas buvo akcijinis ar su nuolaida. Tai neatima įstatyminės teisės. Mokėjimo tvarkytojo mokestis nėra pagrindas atmesti ar sumažinti.",
"e10t": "10. Kaip prašyti",
"e10": "Siųskite Account ID, mokėjimo būdą (svetainės kortelė, kriptovaliuta, App Store ar Google Play), užsakymo ar sąskaitos nuorodą ir datą. Priežastis neprivaloma. El. paštas: support@simnetiq.store. Nesiųskite kortelės numerio, seed phrase ar privataus rakto. Svetainės prašymą stengiamės patvirtinti per 2 darbo dienas.",
"e11t": "11. Kontaktai",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. El. paštas: support@simnetiq.store. ES vartotojai taip pat gali naudoti Europos Komisijos ODR platformą: https://ec.europa.eu/consumers/odr.",
"at": "Account ID ir atkūrimas",
"ai2": "Doppler paskyra yra anoniminis Account ID. Tai nėra el. pašto prisijungimas, o programėlės kalba nėra jūsų gyvenamosios šalies.",
"w1t": "Kas yra Account ID",
"w1": "ID yra formos VPN-XXXX-XXXX-XXXX. Programėlė jį sukuria pirmą kartą paleidus. Svetainė gali jį sukurti mokėjimo metu. Jį rasite Profile arba Nustatymuose, skiltyje Paskyra. Naudokite tą patį ID kiekviename įrenginyje ir saugokite. Pagalba neprašo kortelės numerio.",
"w2t": "Jei jį prarandate",
"w2": "Jei susiejote el. paštą, atidarykite Pagalbą ir pasirinkite paskyros atkūrimą. Išsiųsime ID tuo el. paštu. Jei niekas nesusieta, pateikite pagalbos prašymą. Įklijuotas ID pats savaime neįrodo, kad paskyra jūsų.",
"w3t": "Kalba nėra gyvenamoji vieta",
"w3": "Rusų ar bet kuri kita kalba nesako, kurioje šalyje gyvenate ar ar jums taikoma sankcijų taisyklė.",
"w4t": "Paskyros ištrynimas",
"w4": "Paskyros ištrynimas programėlėje ar ištrynimo puslapyje pašalina visą Doppler paskyrą. Tai nepašalina tik pagalbos kontakto. Mokama prieiga pirmiausia turi baigtis arba būti atšaukta. Atskiro viešo puslapio tik pagalbos kontaktui pašalinti dar nėra.",
"bt": "Svetainės prieiga ir parduotuvės prenumeratos",
"bi": "Kur mokėjote, lemia, ar prieiga atnaujinama ir kas gali grąžinti.",
"b1t": "Vienkartinė svetainės prieiga",
"b1": "Svetainė nuskaito vieną kartą už pasirinktą laikotarpį: mėnesį, 6 mėnesius arba metus. Nėra automatinio atnaujinimo ir nėra išsaugotos kortelės vėlesniam nuskaitimui. Kortelė eina per Revolut, kriptovaliuta per OxaPay. Windows programėlė ir Android APK perkamos svetainėje.",
"b2t": "Apple Pay ir Google Pay svetainėje",
"b2": "Apple Pay ir Google Pay svetainėje yra piniginės prie kortelės atsiskaitymo. Tai nėra App Store ar Google Play prenumeratos.",
"b3t": "App Store ir Google Play",
"b3": "Tos parduotuvės parduoda automatiškai atnaujinamas prenumeratas. Nauji parduotuvės klientai gauna 3 dienų bandomąjį laikotarpį. Atšaukite parduotuvėje ne vėliau kaip 24 valandas prieš atnaujinimą. Viena parduotuvės prenumerata priskiria Pro vienam Account ID vienu metu.",
"b4t": "Ko neparduodame",
"b4": "Nėra pirkimo Telegram Stars, nėra pirkimo Microsoft Store ir nėra balanso papildymo. Windows programėlė yra tiesioginis diegiklis.",
"ct": "Atkurti, atšaukti ar grąžinti",
"ci": "Atkūrimas, atšaukimas ir grąžinimas yra skirtingi veiksmai.",
"c1t": "Atkurti",
"c1": "Atkūrimas įdeda jau apmokėtą prieigą į Account ID. App Store ar Google Play programėlėje: atidarykite Profilį, Prenumeratą, tada Atkurti pirkimus. Atkūrimas kitame Account ID perkelia Pro ten. Svetainės pirkimas matomas, kai programėlė prisijungusi su mokėjime naudotu Account ID. Paleiskite programėlę iš naujo, jei dar nematote. APK neturi mygtuko Atkurti pirkimus.",
"c2t": "Atšaukti",
"c2": "Atšaukimas sustabdo kitą parduotuvės atnaujinimą. Pats savaime pinigų negrąžina. iPhone: Nustatymai, jūsų vardas, Prenumeratos, Doppler VPN, Atšaukti. Android: Play parduotuvė, profilis, Mokėjimai ir prenumeratos, Prenumeratos, Atšaukti. Svetainės pirkimas neatnaujinamas, todėl nėra ko atšaukti.",
"c3t": "Grąžinti",
"c3": "Grąžinimas yra prašymas gauti pinigus atgal. Grąžinimo politika aprašo žingsnius svetainės kortelei, kriptovaliutai, App Store ir Google Play. Nesiųskite kortelės numerio.",
"gt": "Vadovai", "g1": "Account ID ir atkūrimas", "g2": "Svetainės prieiga ir parduotuvės prenumeratos", "g3": "Atkurti, atšaukti ar grąžinti", "g4": "Grąžinimai",
"faq": "ES, EEE ir Jungtinės Karalystės klientai turi 14 dienų atsisakymo teisę. Kitiems paskelbtas geranoriškumas yra 30 dienų ir tik pirmas pirkimas; akcijos ir nuolaidos neįtraukiamos. App Store grąžinimai per Apple, Google Play per Google. Svetainės kortelei ar kriptovaliutai: pateikite pagalbai Account ID ir užsakymo nuorodą. Nesiųskite kortelės numerio.",
"home": "ES, EEE ir Jungtinės Karalystės klientai turi 14 dienų atsisakymo teisę. Kitiems paskelbtas geranoriškumas yra 30 dienų ir tik pirmas pirkimas; akcijos ir nuolaidos neįtraukiamos. Svetainės kortelė ir kriptovaliuta: rašykite support@simnetiq.store su Account ID. Nesiųskite kortelės numerio. App Store ir Google Play grąžinimai prašomi parduotuvėje. Žr. grąžinimo politiką šioje svetainėje.",
"guar": "ES, EEE ir Jungtinės Karalystės klientai turi 14 dienų atsisakymo teisę. Kitiems paskelbtas geranoriškumas yra 30 dienų ir tik pirmas pirkimas; akcijos ir nuolaidos neįtraukiamos. Webcheckout yra vienkartinis mokėjimas ir neatnaujinamas automatiškai. App Store ir Google Play planai atnaujinami, kol juos atšaukiate.",
"foot": "Saugus mokėjimas kortele (Revolut) arba kriptovaliuta (OxaPay). Webcheckout yra vienkartinis mokėjimas ir neatnaujinamas automatiškai.",
"sub": "Vienkartinis mokėjimas kortele (Revolut) arba kriptovaliuta (OxaPay). Be automatinio atnaujinimo. ES, EEE ir Jungtinės Karalystės klientai turi 14 dienų atsisakymo teisę. Kitur paskelbtas geranoriškumas yra 30 dienų ir tik pirmas pirkimas.",
"eb": "14 dienų atsisakymo teisė ES, EEE ir Jungtinėje Karalystėje. Kitiems klientams 30 dienų geranoriškas grąžinimas pirmam pirkimui.",
"er": "Jei Doppler VPN jums netinka, atsakykite į šį el. laišką arba rašykite {email} su užsakymo ID ir Account ID. Nesiųskite kortelės numerio. Svetainės grąžinimas taikomas sumokėtai sumai.",
"pt": "Pagalbos kontaktas ir paskyros ištrynimas",
"pc": "El. pašto ar Telegram susiejimas atkūrimui ar pagalbai nėra paskyros ištrynimas. Ištrynimo puslapis ištrina Doppler paskyrą. Tai nepašalina tik pagalbos kontakto. Mokėjimo įrašai gali būti saugomi, kai to reikalauja įstatymas. Atskiro viešo puslapio tik pagalbos kontaktui pašalinti nėra.",
}))

save("cs", L({
"u": "Naposledy aktualizováno: 28. září 2026",
"rt": "Vrácení peněz",
"ri": "Tato politika se vztahuje na nákupy Doppler VPN od SIMNETIQ LTD (číslo 16861177), 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. Přístup na webu je jednorázová platba. Plány v App Store a Google Play se obnovují, dokud je v obchodě nezrušíte.",
"ai": "Pokyny Apple k vrácení peněz", "ar": "Nahlásit problém společnosti Apple", "gi": "Zásady vrácení peněz Google Play",
"e1t": "1. Odstoupení v EU/EHP (14 dní)",
"e1": "Pokud jste spotřebitel v Evropské unii nebo EHP, můžete do 14 dnů odstoupit bez udání důvodu. Napište na support@simnetiq.store před koncem 14 dnů. Vrátíme zaplacenou částku a nesrážíme poplatek platebního zpracovatele. Srážka za již využitou službu není automatická. Nákupy v App Store nebo Google Play se žádají v daném obchodě.",
"e2t": "2. Odstoupení ve Spojeném království (14 dní)",
"e2": "Pokud jste spotřebitel ve Spojeném království, máte 14denní právo na odstoupení podle Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013. Pošlete jasné prohlášení na support@simnetiq.store. Vrátíme zaplacenou částku a nesrážíme poplatek zpracovatele. Srážka za již využitou službu není automatická a jedno připojení samo o sobě není důvodem k odmítnutí.",
"e3t": "3. Dobrovolné vrácení do 30 dnů",
"e3": "Pro zákazníky mimo EU, EHP a Spojené království platí zveřejněná dobrá vůle: 30 dnů od prvního nákupu, jednou na zákazníka. Propagační nebo zlevněné nákupy jsou vyloučeny, pokud zákon nevyžaduje jinak. Pokud je vrácení schváleno, týká se zaplacené částky. Napište na support@simnetiq.store s Account ID a referencí objednávky.",
"e4t": "4. Platba kartou na webu",
"e4": "Platby kartou na webu, včetně Apple Pay a Google Pay na této stránce, zpracovává Revolut. Nejde o nákupy v App Store ani Google Play. Napište na support@simnetiq.store s Account ID a referencí objednávky. Neposílejte číslo karty. Tato politika nesráží poplatek zpracovatele. Banka rozhoduje, kdy se kredit objeví.",
"e5t": "5. Krypto platba (OxaPay)",
"e5": "Krypto platby na webu zpracovává OxaPay. Napište na support@simnetiq.store s Account ID, referencí faktury, coin a sítí. Nehádejme adresu odesílatele. Uveďte adresu peněženky. Před odesláním potvrdíme aktivum, síť a částku. Tato politika nezadržuje poplatky sítě ani změnu ceny.",
"e6t": "6. App Store",
"e6": "O vrácení peněz v App Store rozhoduje Apple. Neslibujeme schválení ani počet dní. Použijte odkazy níže. Pomoc s Account ID: support@simnetiq.store.",
"e7t": "7. Google Play",
"e7": "O vrácení peněz v Google Play rozhoduje Google. Záleží na produktu, době od platby, zemi a důvodu. Z jednoho zveřejněného časového okna neděláme obecné odmítnutí a neslibujeme schválení. Odkaz je níže.",
"e8t": "8. Obnovení",
"e8": "Nákup na webu pokrývá zvolené období. Neobnovuje se automaticky a není žádný poplatek za obnovení k vrácení. Plán App Store nebo Google Play se obnovuje, dokud jej v obchodě nezrušíte, nejméně 24 hodin před koncem období. Pokud obchod naúčtoval nechtěné obnovení, kontaktujte nás do 14 dnů a pomůžeme požádat obchod. Rozhoduje obchod.",
"e9t": "9. Výjimky",
"e9": "Dobrovolné vrácení může být odmítnuto, pokud je žádost pozdě, účet byl uzavřen za porušení Podmínek, stejný zákazník žádá znovu nebo nákup byl propagační či zlevněný. To neodebírá zákonné právo. Poplatek platebního zpracovatele není důvodem k odmítnutí nebo snížení.",
"e10t": "10. Jak požádat",
"e10": "Pošlete Account ID, způsob platby (karta na webu, krypto, App Store nebo Google Play), referenci objednávky nebo faktury a datum. Důvod je volitelný. E-mail: support@simnetiq.store. Neposílejte číslo karty, seed phrase ani soukromý klíč. Žádost z webu se snažíme potvrdit do 2 pracovních dnů.",
"e11t": "11. Kontakt",
"e11": "SIMNETIQ LTD, 2 Frederick Street, Kings Cross, London, WC1X 0ND, United Kingdom. E-mail: support@simnetiq.store. Spotřebitelé v EU mohou také použít platformu ODR Evropské komise: https://ec.europa.eu/consumers/odr.",
"at": "Account ID a obnovení",
"ai2": "Účet Doppler je anonymní Account ID. Není to přihlášení e-mailem a jazyk aplikace není země, kde žijete.",
"w1t": "Co je Account ID",
"w1": "ID má tvar VPN-XXXX-XXXX-XXXX. Aplikace jej vytvoří při prvním spuštění. Web jej může vytvořit při platbě. Najdete jej v Profilu nebo Nastavení, sekce Účet. Používejte stejné ID na každém zařízení a uchovávejte je v tajnosti. Podpora nepožaduje číslo karty.",
"w2t": "Pokud jej ztratíte",
"w2": "Pokud jste propojili e-mail, otevřete Podporu a zvolte obnovení účtu. ID pošleme na tento e-mail. Pokud nic není propojeno, podejte žádost o podporu. Vložené ID samo o sobě neprokazuje, že účet je váš.",
"w3t": "Jazyk není bydliště",
"w3": "Ruština ani žádný jiný jazyk neříká, ve které zemi žijete ani zda se na vás vztahuje sankční pravidlo.",
"w4t": "Smazání účtu",
"w4": "Smazání účtu v aplikaci nebo na stránce smazání odstraní celý účet Doppler. Neodstraní jen kontakt podpory. Placený přístup musí nejprve skončit nebo být zrušen. Samostatná veřejná stránka jen pro odstranění kontaktu podpory zatím není.",
"bt": "Přístup na webu a předplatná obchodů",
"bi": "Kde jste zaplatili, rozhoduje, zda se přístup obnovuje a kdo může vrátit peníze.",
"b1t": "Jednorázový přístup na webu",
"b1": "Web účtuje jednou za zvolené období: měsíc, 6 měsíců nebo rok. Není automatické obnovení ani uložená karta pro pozdější účtování. Karta jde přes Revolut, krypto přes OxaPay. Aplikaci Windows a Android APK koupíte na webu.",
"b2t": "Apple Pay a Google Pay na webu",
"b2": "Apple Pay a Google Pay na webu jsou peněženky u platby kartou. Nejde o předplatná App Store ani Google Play.",
"b3t": "App Store a Google Play",
"b3": "Tyto obchody prodávají předplatná s automatickým obnovením. Noví zákazníci obchodu mají 3denní zkušební období. Zrušte v obchodě nejméně 24 hodin před obnovením. Jedno předplatné obchodu přiřadí Pro k jednomu Account ID najednou.",
"b4t": "Co neprodáváme",
"b4": "Není nákup přes Telegram Stars, není nákup v Microsoft Store ani dobití zůstatku. Aplikace Windows je přímý instalátor.",
"ct": "Obnovit, zrušit nebo vrátit",
"ci": "Obnovení, zrušení a vrácení peněz jsou různé úkony.",
"c1t": "Obnovit",
"c1": "Obnovení umístí již zaplacený přístup na Account ID. V aplikaci App Store nebo Google Play: otevřete Profil, Předplatné, pak Obnovit nákupy. Obnovení na jiném Account ID přesune Pro tam. Nákup na webu se zobrazí, když je aplikace přihlášena s Account ID použitým při platbě. Restartujte aplikaci, pokud se ještě nezobrazí. APK nemá tlačítko Obnovit nákupy.",
"c2t": "Zrušit",
"c2": "Zrušení zastaví další obnovení v obchodě. Samo o sobě nevrací peníze. Na iPhonu: Nastavení, vaše jméno, Předplatná, Doppler VPN, Zrušit. Na Androidu: Obchod Play, profil, Platby a předplatná, Předplatná, Zrušit. Nákup na webu se neobnovuje, takže není co zrušit.",
"c3t": "Vrátit",
"c3": "Vrácení peněz je žádost o vrácení peněz. Politika vrácení popisuje kroky pro kartu na webu, krypto, App Store a Google Play. Neposílejte číslo karty.",
"gt": "Průvodci", "g1": "Account ID a obnovení", "g2": "Přístup na webu a předplatná obchodů", "g3": "Obnovit, zrušit nebo vrátit", "g4": "Vrácení peněz",
"faq": "Zákazníci v EU, EHP a Spojeném království mají 14denní právo na odstoupení. Pro ostatní je zveřejněná dobrá vůle 30 dnů a pouze první nákup; akce a slevy jsou vyloučeny. Vrácení App Store přes Apple, Google Play přes Google. U karty nebo krypto na webu uveďte podpoře Account ID a referenci objednávky. Neposílejte číslo karty.",
"home": "Zákazníci v EU, EHP a Spojeném království mají 14denní právo na odstoupení. Pro ostatní je zveřejněná dobrá vůle 30 dnů a pouze první nákup; akce a slevy jsou vyloučeny. Karta a krypto na webu: napište na support@simnetiq.store s Account ID. Neposílejte číslo karty. Vrácení App Store a Google Play se žádají v obchodě. Viz politiku vrácení na tomto webu.",
"guar": "Zákazníci v EU, EHP a Spojeném království mají 14denní právo na odstoupení. Pro ostatní je zveřejněná dobrá vůle 30 dnů a pouze první nákup; akce a slevy jsou vyloučeny. Webcheckout je jednorázová platba a neobnovuje se automaticky. Plány App Store a Google Play se obnovují, dokud je nezrušíte.",
"foot": "Bezpečná platba kartou (Revolut) nebo kryptem (OxaPay). Webcheckout je jednorázová platba a neobnovuje se automaticky.",
"sub": "Jednorázová platba kartou (Revolut) nebo kryptem (OxaPay). Bez automatického obnovení. Zákazníci v EU, EHP a Spojeném království mají 14denní právo na odstoupení. Jinde je zveřejněná dobrá vůle 30 dnů a pouze první nákup.",
"eb": "14denní právo na odstoupení v EU, EHP a Spojeném království. Pro ostatní zákazníky 30denní dobrovolné vrácení u prvního nákupu.",
"er": "Pokud vám Doppler VPN nevyhovuje, odpovězte na tento e-mail nebo napište na {email} s ID objednávky a Account ID. Neposílejte číslo karty. Vrácení z webu se týká zaplacené částky.",
"pt": "Kontakt podpory a smazání účtu",
"pc": "Propojení e-mailu nebo Telegramu pro obnovení nebo podporu není smazání účtu. Stránka smazání smaže účet Doppler. Neodstraní jen kontakt podpory. Platební záznamy mohou být uchovány, kde to vyžaduje zákon. Samostatná veřejná stránka jen pro odstranění kontaktu podpory není.",
}))

print("ok nl sv da nb fi et lv lt cs")
